import { GenesisBackupStore, GenesisCommand, GenesisFixtureAuthority, GenesisNode, GenesisNodeError } from "./index";
declare const process:{stdout:{write(v:string):void};stderr:{write(v:string):void};exitCode?:number};
let assertions=0;
function assert(v:unknown,m:string):asserts v{assertions++;if(!v)throw new Error(m)}
async function expectCode(fn:()=>unknown|Promise<unknown>,code:string){assertions++;try{await fn();throw new Error(`expected ${code}`)}catch(e){if(!(e instanceof GenesisNodeError)||e.code!==code)throw e}}
const H1="11".repeat(32),H2="22".repeat(32),H3="33".repeat(32),KEY="ab".repeat(32),NODE="NODE:GENESIS:LOCAL_A16",NOW="2026-08-09T20:00:00Z";
const authority=new GenesisFixtureAuthority("NODE-AUTHORITY:LOCAL_A16",KEY);
const manifest={schemaVersion:1 as const,nodeId:NODE,mode:"D0_GENESIS" as const,protocol:"/nexus/shards/1.0" as const,reducerVersion:"genesis-reducer/1.0.0" as const,replicationFactor:1 as const,roles:["GATEWAY","EVENT_LOG","REPLICA","STORAGE","INDEX","JOBS"] as const,authorityKeyId:authority.keyId,syntheticLabel:"SYSTEM_TEST" as const};
async function issue(eventId:string,objectCommitment:string,valueCommitment:string,action:"UPSERT"|"TOMBSTONE"="UPSERT"):Promise<Readonly<GenesisCommand>>{return authority.issueCommand({schemaVersion:1,eventId,objectCommitment,valueCommitment,action,occurredAt:NOW,actorClass:"SYSTEM_TEST"})}
async function main(){
  const node=new GenesisNode(manifest,authority);
  const c1=await issue("EVENT:0001",H1,H2),c2=await issue("EVENT:0002",H2,H3),c3=await issue("EVENT:0003",H1,H3,"TOMBSTONE");
  const e1=await node.append(c1),e2=await node.append(c2),e3=await node.append(c3);
  assert(e1.ordinal===1&&e1.previousEventHash==="0".repeat(64),"genesis event starts canonical chain");
  assert(e2.ordinal===2&&e2.previousEventHash===e1.eventHash&&e3.previousEventHash===e2.eventHash,"event lineage is append-only");
  const before=await node.projection();
  assert(before.eventCount===3&&before.rangeStart===1&&before.rangeEnd===3,"projection binds full range");
  assert(before.state.length===2&&before.state.find(v=>v.objectCommitment===H1)?.kind==="TOMBSTONE","tombstone wins reducer order");
  assert(/^[a-f0-9]{64}$/.test(before.stateRoot)&&before.eventHead===e3.eventHash,"projection has verified roots");
  const checkpoint=await node.exportCheckpoint();
  assert(checkpoint.rangeEnd===3&&checkpoint.events.length===3&&checkpoint.replayIndex.length===3,"export is complete");
  assert(checkpoint.manifest.roles.length===6&&checkpoint.manifest.replicationFactor===1,"D0 node owns all roles at R1");
  const backup=new GenesisBackupStore();const backupReceipt=await backup.commit(JSON.parse(JSON.stringify(checkpoint)),authority,NODE);
  assert(backup.size===1&&backupReceipt.checkpointHash===checkpoint.checkpointHash&&backupReceipt.stateRoot===before.stateRoot,"validated checkpoint commits atomically to local backup");
  assert(backupReceipt.eventCount===3&&backupReceipt.byteLength>0,"backup receipt binds complete serialized checkpoint");
  const disposal=await node.dispose();
  assert(disposal.disposed&&disposal.clearedEvents===3&&disposal.clearedReplayEntries===3,"source runtime is explicitly disposed after backup");
  await expectCode(()=>node.projection(),"GENESIS_NODE_DISPOSED");
  await expectCode(()=>node.append(c1),"GENESIS_NODE_DISPOSED");
  await expectCode(()=>node.exportCheckpoint(),"GENESIS_NODE_DISPOSED");
  const restored=await GenesisNode.restore(backup.load(checkpoint.checkpointHash),authority,NODE);const after=await restored.projection();
  assert(JSON.stringify(after)===JSON.stringify(before),"fresh restore projection is byte-identical");
  assert(after.stateRoot===before.stateRoot&&after.eventHead===before.eventHead,"fresh restore preserves state and history roots");
  await expectCode(()=>restored.append(c1),"GENESIS_EVENT_REPLAY");
  const c4=await issue("EVENT:0004",H3,H1);const e4=await restored.append(c4);
  assert(e4.ordinal===4&&e4.previousEventHash===checkpoint.eventHead,"restored node continues exact lineage");
  const checkpoint2=await restored.exportCheckpoint();assert(checkpoint2.previousCheckpointHash===checkpoint.checkpointHash,"next checkpoint binds previous head");
  await expectCode(()=>new GenesisNode({...manifest,roles:["GATEWAY"]},authority),"GENESIS_MANIFEST_INVALID");
  await expectCode(()=>new GenesisNode({...manifest,replicationFactor:"1"},authority),"GENESIS_MANIFEST_INVALID");
  const negativeNode=new GenesisNode(manifest,authority);
  await expectCode(async()=>negativeNode.append({...await issue("EVENT:BAD1",H1,H2),actorClass:"HUMAN"}),"GENESIS_COMMAND_INVALID");
  await expectCode(async()=>negativeNode.append({...await issue("EVENT:BAD2",H1,H2),extra:true}),"GENESIS_COMMAND_INVALID");
  await expectCode(async()=>negativeNode.append({...await issue("EVENT:BAD3",H1,H2),signature:H1}),"GENESIS_COMMAND_SIGNATURE_INVALID");
  await expectCode(()=>GenesisNode.restore({...checkpoint,extra:true},authority,NODE),"GENESIS_CHECKPOINT_INVALID");
  await expectCode(()=>GenesisNode.restore({...checkpoint,events:checkpoint.events.slice(0,-1)},authority,NODE),"GENESIS_CHECKPOINT_INVALID");
  await expectCode(()=>GenesisNode.restore({...checkpoint,events:[checkpoint.events[1],checkpoint.events[0],checkpoint.events[2]]},authority,NODE),"GENESIS_CHECKPOINT_SIGNATURE_INVALID");
  await expectCode(()=>GenesisNode.restore({...checkpoint,stateRoot:H1},authority,NODE),"GENESIS_CHECKPOINT_SIGNATURE_INVALID");
  await expectCode(()=>GenesisNode.restore({...checkpoint,eventHead:H1},authority,NODE),"GENESIS_CHECKPOINT_SIGNATURE_INVALID");
  await expectCode(()=>GenesisNode.restore({...checkpoint,replayIndex:checkpoint.replayIndex.slice(0,-1)},authority,NODE),"GENESIS_CHECKPOINT_INVALID");
  await expectCode(()=>GenesisNode.restore({...checkpoint,manifest:{...checkpoint.manifest,nodeId:"NODE:GENESIS:OTHER_A16"}},authority,NODE),"GENESIS_CHECKPOINT_IDENTITY_MISMATCH");
  await expectCode(()=>GenesisNode.restore(checkpoint,new GenesisFixtureAuthority("NODE-AUTHORITY:OTHER_A16","cd".repeat(32)),NODE),"GENESIS_CHECKPOINT_IDENTITY_MISMATCH");
  await expectCode(()=>GenesisNode.restore(checkpoint,authority,NODE,H1),"GENESIS_CHECKPOINT_STALE");
  const fabricated={...checkpoint,events:checkpoint.events.map((e,i)=>i===1?{...e,ordinal:7}:e)};
  await expectCode(()=>GenesisNode.restore(fabricated,authority,NODE),"GENESIS_CHECKPOINT_SIGNATURE_INVALID");
  await expectCode(()=>backup.commit({...checkpoint,stateRoot:H1},authority,NODE),"GENESIS_CHECKPOINT_SIGNATURE_INVALID");
  await expectCode(()=>backup.load(H1),"GENESIS_BACKUP_NOT_FOUND");
  const mutationStore=new GenesisBackupStore(),mutableCheckpoint=JSON.parse(JSON.stringify(checkpoint));const mutationPending=mutationStore.commit(mutableCheckpoint,authority,NODE);mutableCheckpoint.checkpointHash=H1;mutableCheckpoint.stateRoot=H2;mutableCheckpoint.events[0].valueCommitment=H3;const mutationReceipt=await mutationPending;
  assert(mutationReceipt.checkpointHash===checkpoint.checkpointHash&&mutationReceipt.stateRoot===checkpoint.stateRoot,"pending backup ignores caller mutation after canonical capture");
  const mutationRestored=await GenesisNode.restore(mutationStore.load(checkpoint.checkpointHash),authority,NODE);assert((await mutationRestored.projection()).stateRoot===checkpoint.stateRoot,"stored backup bytes restore and match receipt after caller mutation");
  await expectCode(()=>mutationStore.load(H1),"GENESIS_BACKUP_NOT_FOUND");
  const getterStore=new GenesisBackupStore(),getterCheckpoint=JSON.parse(JSON.stringify(checkpoint));let checkpointHashReads=0;Object.defineProperty(getterCheckpoint,"checkpointHash",{enumerable:true,configurable:true,get(){checkpointHashReads+=1;return checkpointHashReads===1?checkpoint.checkpointHash:H1}});const getterReceipt=await getterStore.commit(getterCheckpoint,authority,NODE);
  assert(checkpointHashReads===1&&getterReceipt.checkpointHash===checkpoint.checkpointHash,"getter-backed input is captured exactly once before validation");
  assert((await GenesisNode.restore(getterStore.load(checkpoint.checkpointHash),authority,NODE)).manifest.nodeId===NODE,"getter snapshot stores the exact representation that passed validation");
  const second=new GenesisNode(manifest,authority);for(const c of[c1,c2,c3])await second.append(c);const deterministic=await second.projection();
  assert(deterministic.stateRoot===before.stateRoot&&deterministic.eventHead===before.eventHead,"same signed corpus replays deterministically");
  assert((await second.exportCheckpoint()).checkpointHash===checkpoint.checkpointHash,"same corpus exports identical checkpoint");
  const concurrent=new GenesisNode(manifest,authority);const concurrentCommands=await Promise.all(Array.from({length:24},(_,i)=>issue(`EVENT:CONCURRENT:${String(i+1).padStart(2,"0")}`,i%2===0?H1:H2,i%3===0?H2:H3)));const concurrentEvents=await Promise.all(concurrentCommands.map(c=>concurrent.append(c)));
  assert(concurrentEvents.every((e,i)=>e.ordinal===i+1),"concurrent append receives one strict ordinal sequence");
  assert(concurrentEvents.every((e,i)=>e.previousEventHash===(i===0?"0".repeat(64):concurrentEvents[i-1].eventHash)),"concurrent append preserves one hash lineage");
  const concurrentCheckpoint=await concurrent.exportCheckpoint();assert(concurrentCheckpoint.rangeEnd===24&&new Set(concurrentCheckpoint.events.map(e=>e.ordinal)).size===24,"concurrent corpus exports complete unique range");
  const duplicate=await issue("EVENT:CONCURRENT:DUP",H3,H1);const duplicateResults=await Promise.allSettled([concurrent.append(duplicate),concurrent.append(duplicate)]);assert(duplicateResults.filter(v=>v.status==="fulfilled").length===1&&duplicateResults.filter(v=>v.status==="rejected"&&(v.reason instanceof GenesisNodeError)&&v.reason.code==="GENESIS_EVENT_REPLAY").length===1,"concurrent duplicate commits exactly once");
  process.stdout.write(JSON.stringify({schema_version:1,task_id:"NX-NODE-P01",status:"PASS",assertions,mode:"D0_GENESIS",protocol:"/nexus/shards/1.0",node_count:1,replication_factor:1,roles:manifest.roles,event_count:before.eventCount,state_root:before.stateRoot,event_head:before.eventHead,checkpoint_hash:checkpoint.checkpointHash,backup:{atomic_commit:true,validated_before_commit:true,stable_source_snapshot:true,stored_restore_verified:true,receipt_matches_stored_bytes:true,getter_read_once:true,storage_class:backupReceipt.storageClass,byte_length:backupReceipt.byteLength},lifecycle:{source_runtime_disposed:true,disposed_operations_denied:true},concurrency:{append_count:24,strict_ordinals:true,one_hash_lineage:true,duplicate_exactly_once:true},restore:{fresh_instance:true,same_projection:true,same_state_root:true,same_event_head:true,replay_denied:true,continued_lineage:true},negative:{manifest_roles:true,replication_type:true,actor_class:true,exact_command_shape:true,command_signature:true,checkpoint_exact_shape:true,prefix:true,reorder:true,state_root:true,event_head:true,replay_index:true,node_identity:true,authority:true,stale_checkpoint:true,fabricated_ordinal:true,backup_tamper:true,backup_missing:true,backup_concurrent_mutation:true,backup_getter_snapshot:true},network_operations:0,external_provider_operations:0,economic_operations:0,real_fund_operations:0,incremental_cost:{amount:0,currency:"EUR"}}));
}
void main().catch(e=>{process.stderr.write(e instanceof Error?(e.stack??e.message):String(e));process.exitCode=1});
