import { EscrowActionCommand, EscrowEvent, EscrowEventVerifier, EscrowSnapshot, EscrowSnapshotAttestation, FundOrderCommand, ListingActionRecorder, ListingEligibilityDecision, ListingExecutionAuthorization, ListingPolicyBoundary, ListingProfileBoundary, ListingPublishCommand, MarketplaceEscrowLedger, MarketplaceListingRegistry, MarketplacePolicyError } from "./index";
import { ActionEnvelope, ChainPolicyError, NexusActionsSandbox, PreparedAction } from "../../chain-actions-api/index";
import { ChainReducer, EventAuthenticityVerifier, IndexedChainEvent, RepairAuthorizationVerifier, RepairCommitStore, serializeObservationForVerification, serializePayloadForVerification } from "../../chain-adapter/api/index";
declare const process:{stdout:{write(value:string):void}};
let assertions=0; function assert(v:unknown,m:string):asserts v{assertions++;if(!v)throw new Error(`ASSERT:${m}`);}
function expectMarket(fn:()=>unknown,code:string):void{let actual="NO_ERROR";try{fn();}catch(e){actual=e instanceof MarketplacePolicyError?e.code:String(e);}assert(actual===code,`expected ${code}, got ${actual}`);}
async function expectMarketAsync(fn:()=>Promise<unknown>,code:string):Promise<void>{let actual="NO_ERROR";try{await fn();}catch(e){actual=e instanceof MarketplacePolicyError?e.code:e instanceof ChainPolicyError?e.code:String(e);}assert(actual===code,`expected ${code}, got ${actual}`);}
class Issuer<T extends object>{private readonly values=new Set<string>();issue(v:T):T{this.values.add(JSON.stringify(v));return v;}verify(v:Readonly<T>):boolean{return this.values.has(JSON.stringify(v));}}
class Profiles implements ListingProfileBoundary{private active=new Set<string>();add(p:string,g:number){this.active.add(`${p}|${g}`);}remove(p:string,g:number){this.active.delete(`${p}|${g}`);}isActiveMarketProfile(p:string,g:number){return this.active.has(`${p}|${g}`);}}
class Policies implements ListingPolicyBoundary{state={version:1,enabled:true};set(version:number,enabled:boolean){this.state={version,enabled};}current(){return Object.freeze({...this.state});}}
class Events implements EscrowEventVerifier{private readonly values=new Set<string>();register(events:readonly EscrowEvent[]){for(const e of events)this.values.add(JSON.stringify(e));}verify(e:Readonly<EscrowEvent>){return this.values.has(JSON.stringify(e));}}
class Authenticity implements EventAuthenticityVerifier{private p="";private o="";register(v:IndexedChainEvent){this.p=serializePayloadForVerification(v.payload);this.o=serializeObservationForVerification(v);return v;}verifyFinalizedObservation(v:IndexedChainEvent){return this.p===serializePayloadForVerification(v.payload)&&this.o===serializeObservationForVerification(v);}}

const NOW="2026-08-09T23:00:00.000Z", NOW_MS=Date.parse(NOW), EXP="2026-08-09T23:05:00.000Z", H128="a".repeat(128);
const LISTING="1".repeat(64), CLASSIFIED="2".repeat(64), MANIFEST="3".repeat(64), SELLER="4".repeat(64), BUYER="5".repeat(64), RESOLVER="6".repeat(64), SESSION="7".repeat(64), CONTROLLER="8".repeat(64), TERMS="9".repeat(64), PAYMENT="b".repeat(64), EVIDENCE="c".repeat(64);

async function main():Promise<void>{
  const profiles=new Profiles(),policies=new Policies();profiles.add(SELLER,3);profiles.add(BUYER,7);
  const registry=new MarketplaceListingRegistry(profiles,policies),commandIssuer=new Issuer<ListingPublishCommand>(),decisionIssuer=new Issuer<ListingEligibilityDecision>(),authIssuer=new Issuer<ListingExecutionAuthorization>();
  const relayer=`erd1${"r".repeat(58)}`,contractAddress=`erd1${"q".repeat(58)}`,sandbox=new NexusActionsSandbox({async verifyEd25519(){const m=mutation;mutation=()=>{};m();return true;}});let mutation=()=>{};
  sandbox.registerCapability({controller:CONTROLLER,actorKind:"HUMAN",actorCommitment:SELLER,sessionPublicKey:SESSION,scopes:["MARKET_PUBLIC"],maxActions:4,validFromMs:NOW_MS-1000,expiresAtMs:NOW_MS+60_000,authorizedRelayers:[relayer]},CONTROLLER,NOW_MS);
  let retained:PreparedAction|null=null;const recorder:ListingActionRecorder={async prepareAction(e,s,x){retained=await sandbox.prepareAction(e as ActionEnvelope,s,x);return {envelope:e,context:x,opaque:retained};},commitPreparedAction(p){const e=sandbox.commitPreparedAction(p.opaque as PreparedAction);return {...e,actionClass:"PUBLIC_ACTION"};},abortPreparedAction(p){sandbox.abortPreparedAction(p.opaque as PreparedAction);}};
  const context={chainId:"D",contractAddress,relayer,relayerAgreementVerified:true,nowMs:NOW_MS,payments:[] as readonly unknown[]};
  function command(listingCommitment:string,mode:"CLASSIFIED_ONLY"|"ESCROW_CHECKOUT",overrides:Partial<ListingPublishCommand>={}):ListingPublishCommand{return commandIssuer.issue({schemaVersion:1,listingCommitment,manifestHash:MANIFEST,sellerProfileCommitment:SELLER,sellerProfileGeneration:3,category:"ELECTRONICS",mode,condition:"USED",territory:"RO",tokenId:"TESTUSDC-123",priceAtomic:"100000",traderStatus:"NON_TRADER",syntheticLabel:"SYSTEM_TEST",publishedAt:NOW,signature:H128,...overrides});}
  function decision(c:ListingPublishCommand,id:string,overrides:Partial<ListingEligibilityDecision>={}):ListingEligibilityDecision{return decisionIssuer.issue({schemaVersion:1,decisionId:id,listingCommitment:c.listingCommitment,manifestHash:c.manifestHash,sellerProfileCommitment:c.sellerProfileCommitment,sellerProfileGeneration:c.sellerProfileGeneration,category:c.category,mode:c.mode,territory:c.territory,tokenId:c.tokenId,priceAtomic:c.priceAtomic,prohibitedGoodsClear:true,scamClear:true,duplicateClear:true,recallClear:true,productSafetyClear:true,traderDisclosureComplete:true,policyVersion:policies.state.version,evaluatedAt:NOW,expiresAt:EXP,issuerKeyId:"KEY:MARKET:1",signature:H128,...overrides});}
  function authorization(c:ListingPublishCommand,d:ListingEligibilityDecision,id:string,nonce:string):ListingExecutionAuthorization{return authIssuer.issue({schemaVersion:1,authorizationId:id,decisionId:d.decisionId,listingCommitment:c.listingCommitment,manifestHash:c.manifestHash,sellerProfileCommitment:c.sellerProfileCommitment,sellerProfileGeneration:c.sellerProfileGeneration,category:c.category,mode:c.mode,condition:c.condition,territory:c.territory,tokenId:c.tokenId,priceAtomic:c.priceAtomic,traderStatus:c.traderStatus,actionNonce:nonce,sessionPublicKey:SESSION,chainId:"D",contractAddress,policyVersion:d.policyVersion,evaluatedAt:NOW,expiresAt:EXP,issuerKeyId:"KEY:RELAYER:1",signature:H128});}
  function envelope(c:ListingPublishCommand,nonce:bigint){return {version:1 as const,actorKind:"HUMAN" as const,actorCommitment:SELLER,actionType:"LISTING_CREATE" as const,objectCommitment:c.listingCommitment,payloadHashOrCid:c.manifestHash,visibilityClass:"PUBLIC" as const,actionNonce:nonce,issuedAtMs:NOW_MS-100,expiresAtMs:NOW_MS+10_000,sessionPublicKey:SESSION};}
  const c=command(LISTING,"ESCROW_CHECKOUT"),d=decision(c,"DECISION:LISTING:1"),a=authorization(c,d,"AUTH:LISTING:1","1"),e=envelope(c,1n);
  await expectMarketAsync(()=>registry.executePublish({...c,extra:true},d,a,e,H128,context,{verify:()=>true},decisionIssuer,authIssuer,recorder,NOW),"LISTING_COMMAND_INVALID");
  await expectMarketAsync(()=>registry.executePublish(c,{...d,prohibitedGoodsClear:"true"},a,e,H128,context,commandIssuer,{verify:()=>true},authIssuer,recorder,NOW),"LISTING_PROHIBITED");
  const prohibited=decision(c,"DECISION:LISTING:PROHIBITED",{prohibitedGoodsClear:false as true});await expectMarketAsync(()=>registry.executePublish(c,prohibited,authorization(c,prohibited,"AUTH:LISTING:PROHIBITED","1"),e,H128,context,commandIssuer,decisionIssuer,authIssuer,recorder,NOW),"LISTING_PROHIBITED");
  const substituted=decision(c,"DECISION:LISTING:SUB",{priceAtomic:"99999"});await expectMarketAsync(()=>registry.executePublish(c,substituted,authorization(c,substituted,"AUTH:LISTING:SUB","1"),e,H128,context,commandIssuer,decisionIssuer,authIssuer,recorder,NOW),"LISTING_DECISION_BINDING_MISMATCH");
  const coordinated=command(LISTING,"CLASSIFIED_ONLY",{category:"FASHION",condition:"NEW",territory:"DE",tokenId:"TESTEGLD-123",priceAtomic:"90000",traderStatus:"TRADER"}),coordinatedDecision=decision(coordinated,"DECISION:LISTING:COORDINATED");await expectMarketAsync(()=>registry.executePublish(coordinated,coordinatedDecision,a,envelope(coordinated,1n),H128,context,commandIssuer,decisionIssuer,authIssuer,recorder,NOW),"LISTING_AUTHORIZATION_BINDING_MISMATCH");
  mutation=()=>policies.set(2,false);await expectMarketAsync(()=>registry.executePublish(c,d,a,e,H128,context,commandIssuer,decisionIssuer,authIssuer,recorder,NOW),"LISTING_EXECUTION_STATE_CONFLICT");
  await expectMarketAsync(()=>Promise.resolve(sandbox.commitPreparedAction(retained as PreparedAction)),"PREPARED_ACTION_INVALID");assert(sandbox.drainEvents().length===0,"policy race records no listing action");policies.set(1,true);
  const listing=await registry.executePublish(c,d,a,e,H128,context,commandIssuer,decisionIssuer,authIssuer,recorder,NOW);assert(listing.state==="ACTIVE"&&listing.protectedCheckout,"allowed listing activates only after action commit");assert(sandbox.drainEvents().length===1,"listing create emits one distinct action");
  await expectMarketAsync(()=>registry.executePublish(c,d,a,e,H128,context,commandIssuer,decisionIssuer,authIssuer,recorder,NOW),"LISTING_REPLAY");
  const cc=command(CLASSIFIED,"CLASSIFIED_ONLY"),cd=decision(cc,"DECISION:CLASSIFIED:1"),ca=authorization(cc,cd,"AUTH:CLASSIFIED:1","2");await registry.executePublish(cc,cd,ca,envelope(cc,2n),H128,context,commandIssuer,decisionIssuer,authIssuer,recorder,NOW);sandbox.drainEvents();

  const fundIssuer=new Issuer<FundOrderCommand>(),actionIssuer=new Issuer<EscrowActionCommand>();
  function fund(escrowId:string,listingCommitment=LISTING,overrides:Partial<FundOrderCommand>={}):FundOrderCommand{return fundIssuer.issue({schemaVersion:1,actionId:`ACTION:FUND:${escrowId}`,escrowId,listingCommitment,listingStateVersion:1,buyerProfileCommitment:BUYER,buyerProfileGeneration:7,sellerProfileCommitment:SELLER,sellerProfileGeneration:3,paymentKey:PAYMENT,tokenId:"TESTUSDC-123",principalAtomic:"100000",platformFeeAtomic:"2000",totalAtomic:"102000",realValueAtomic:"0",termsHash:TERMS,acceptBy:"2026-08-10T00:00:00.000Z",fulfilBy:"2026-08-11T00:00:00.000Z",autoReleaseAt:"2026-08-12T00:00:00.000Z",policyVersion:1,syntheticLabel:"SYSTEM_TEST",occurredAt:NOW,signature:H128,...overrides});}
  function action(escrowId:string,id:string,version:number,actor:string,overrides:Partial<EscrowActionCommand>={}):EscrowActionCommand{return actionIssuer.issue({schemaVersion:1,actionId:id,escrowId,expectedVersion:version,actorProfileCommitment:actor,outcomeBuyerBps:0,outcomeSellerBps:0,evidenceCommitment:EVIDENCE,occurredAt:NOW,signature:H128,...overrides});}
  const classifiedLedger=new MarketplaceEscrowLedger(registry,profiles,RESOLVER);expectMarket(()=>classifiedLedger.fundOrder(fund("ESCROW:CLASSIFIED",CLASSIFIED),fundIssuer,NOW),"LISTING_NOT_ESCROW_ELIGIBLE");
  expectMarket(()=>classifiedLedger.fundOrder(fund("ESCROW:CAP",LISTING,{totalAtomic:"1000001",principalAtomic:"980001",platformFeeAtomic:"20000"}),fundIssuer,NOW),"ESCROW_LISTING_BINDING_MISMATCH");
  const releaseLedger=new MarketplaceEscrowLedger(registry,profiles,RESOLVER),f=fund("ESCROW:RELEASE");assert(releaseLedger.fundOrder(f,fundIssuer,NOW).state==="FUNDED","protected order funds with test token only");
  expectMarket(()=>releaseLedger.fundOrder(f,fundIssuer,NOW),"ESCROW_REPLAY");
  assert(releaseLedger.sellerAccept(action(f.escrowId,"ACTION:ACCEPT:1",1,SELLER),actionIssuer,NOW).state==="ACCEPTED","seller accepts");
  assert(releaseLedger.markFulfilled(action(f.escrowId,"ACTION:FULFIL:1",2,SELLER),actionIssuer,NOW).state==="FULFILLED","seller fulfills");
  expectMarket(()=>releaseLedger.buyerAccept(action(f.escrowId,"ACTION:WRONG:1",3,SELLER),actionIssuer,NOW),"ESCROW_ACTOR_DENIED");
  const released=releaseLedger.buyerAccept(action(f.escrowId,"ACTION:BUYER:ACCEPT:1",3,BUYER),actionIssuer,NOW);assert(released.state==="RELEASED"&&released.sellerCreditAtomic==="100000"&&released.platformCreditAtomic==="2000","release conserves principal and fee");
  expectMarket(()=>releaseLedger.cancelBeforeAccept(action(f.escrowId,"ACTION:LATE:1",4,BUYER),actionIssuer,NOW),"ESCROW_TRANSITION_INVALID");
  const snapshotIssuer=new Issuer<EscrowSnapshot>(),attestation:EscrowSnapshotAttestation={checkpointId:"CHECKPOINT:RELEASE:1",eventSetCommitment:"d".repeat(64),issuedAt:NOW,expiresAt:EXP,issuerKeyId:"KEY:CHECKPOINT:1",signature:H128};
  const fullSnapshot=snapshotIssuer.issue(releaseLedger.snapshot(attestation)),eventVerifier=new Events();eventVerifier.register(fullSnapshot.events);const restored=MarketplaceEscrowLedger.restore(fullSnapshot,attestation.checkpointId,registry,profiles,RESOLVER,eventVerifier,snapshotIssuer,NOW);assert(restored.get(f.escrowId)?.state==="RELEASED","signed event replay restores released order");
  const tampered={...fullSnapshot,events:fullSnapshot.events.map(e=>({...e}))};(tampered.events[3] as EscrowEvent).sellerCreditAtomic="99999";expectMarket(()=>MarketplaceEscrowLedger.restore(tampered,attestation.checkpointId,registry,profiles,RESOLVER,eventVerifier,snapshotIssuer,NOW),"ESCROW_CHECKPOINT_INVALID");
  const prefix={...fullSnapshot,eventCount:3,events:fullSnapshot.events.slice(0,3)};expectMarket(()=>MarketplaceEscrowLedger.restore(prefix,attestation.checkpointId,registry,profiles,RESOLVER,eventVerifier,snapshotIssuer,NOW),"ESCROW_CHECKPOINT_INVALID");
  const fabricatedEvent={...fullSnapshot.events[0],eventOrdinal:2,state:"RELEASED" as const,stateVersion:2,actionId:"ACTION:FABRICATED:RELEASE",action:"BUYER_ACCEPT" as const,actorProfileCommitment:BUYER,buyerCreditAtomic:"0",sellerCreditAtomic:"100000",platformCreditAtomic:"2000"},fabricatedSnapshot={...fullSnapshot,checkpointId:"CHECKPOINT:FABRICATED:1",eventCount:2,events:[fullSnapshot.events[0],fabricatedEvent]};expectMarket(()=>MarketplaceEscrowLedger.restore(fabricatedSnapshot,fabricatedSnapshot.checkpointId,registry,profiles,RESOLVER,{verify:()=>true},{verify:()=>true},NOW),"ESCROW_SNAPSHOT_INVALID");
  const resolverSubstitution={...fullSnapshot,resolverCommitment:BUYER};expectMarket(()=>MarketplaceEscrowLedger.restore(resolverSubstitution,attestation.checkpointId,registry,profiles,BUYER,{verify:()=>true},{verify:()=>true},NOW),"ESCROW_SNAPSHOT_INVALID");
  const refundLedger=new MarketplaceEscrowLedger(registry,profiles,RESOLVER),rf=fund("ESCROW:REFUND");refundLedger.fundOrder(rf,fundIssuer,NOW);refundLedger.setPausedNewOrders(true);const refunded=refundLedger.cancelBeforeAccept(action(rf.escrowId,"ACTION:REFUND:1",1,BUYER),actionIssuer,NOW);assert(refunded.state==="REFUNDED"&&refunded.buyerCreditAtomic==="102000","refund remains available while new orders paused");expectMarket(()=>refundLedger.fundOrder(fund("ESCROW:PAUSED"),fundIssuer,NOW),"NEW_ORDERS_PAUSED");
  const disputeLedger=new MarketplaceEscrowLedger(registry,profiles,RESOLVER),df=fund("ESCROW:DISPUTE");disputeLedger.fundOrder(df,fundIssuer,NOW);disputeLedger.sellerAccept(action(df.escrowId,"ACTION:DISPUTE:ACCEPT",1,SELLER),actionIssuer,NOW);disputeLedger.openDispute(action(df.escrowId,"ACTION:DISPUTE:OPEN",2,BUYER),actionIssuer,NOW);expectMarket(()=>disputeLedger.resolveDispute(action(df.escrowId,"ACTION:DISPUTE:WRONG",3,BUYER,{outcomeBuyerBps:5000,outcomeSellerBps:5000}),actionIssuer,NOW),"ESCROW_ACTOR_DENIED");const resolved=disputeLedger.resolveDispute(action(df.escrowId,"ACTION:DISPUTE:RESOLVE",3,RESOLVER,{outcomeBuyerBps:6000,outcomeSellerBps:4000}),actionIssuer,NOW);assert(BigInt(resolved.buyerCreditAtomic)+BigInt(resolved.sellerCreditAtomic)+BigInt(resolved.platformCreditAtomic)===102000n,"dispute split conserves all funded test units");
  const lateAcceptLedger=new MarketplaceEscrowLedger(registry,profiles,RESOLVER),laf=fund("ESCROW:LATE:ACCEPT");lateAcceptLedger.fundOrder(laf,fundIssuer,NOW);expectMarket(()=>lateAcceptLedger.sellerAccept(action(laf.escrowId,"ACTION:LATE:ACCEPT",1,SELLER,{occurredAt:NOW}),actionIssuer,"2026-08-10T00:00:01.000Z"),"ESCROW_ACCEPT_DEADLINE_EXPIRED");
  const lateFulfilLedger=new MarketplaceEscrowLedger(registry,profiles,RESOLVER),lff=fund("ESCROW:LATE:FULFIL");lateFulfilLedger.fundOrder(lff,fundIssuer,NOW);lateFulfilLedger.sellerAccept(action(lff.escrowId,"ACTION:LATE:FULFIL:ACCEPT",1,SELLER),actionIssuer,NOW);expectMarket(()=>lateFulfilLedger.markFulfilled(action(lff.escrowId,"ACTION:LATE:FULFIL",2,SELLER,{occurredAt:NOW}),actionIssuer,"2026-08-11T00:00:01.000Z"),"ESCROW_FULFIL_DEADLINE_EXPIRED");
  const resolverCollisionLedger=new MarketplaceEscrowLedger(registry,profiles,BUYER);expectMarket(()=>resolverCollisionLedger.fundOrder(fund("ESCROW:RESOLVER:COLLISION"),fundIssuer,NOW),"ESCROW_PROFILE_DENIED");

  const auth=new Authenticity(),indexed=auth.register({network:"devnet",contractAddress,originalTxHash:"d".repeat(64),sourceTxHash:"e".repeat(64),sourceKind:"SMART_CONTRACT_RESULT",eventIndex:0,shard:1,blockNonce:10n,blockHash:"f".repeat(64),hyperblockNonce:11n,hyperblockHash:"0".repeat(64),canonicality:"FINALIZED_CANONICAL",finality:"HYPERBLOCK_FINAL",contentHash:"1".repeat(64),authenticityProofHash:"2".repeat(64),payload:{kind:"ACTION_EXECUTED",aggregateId:"LISTING_1",aggregateVersion:1,actorCommitment:SELLER,objectCommitment:LISTING,actionClass:"PUBLIC_ACTION",status:"EXECUTED_SUCCESS"}}),repairVerifier:RepairAuthorizationVerifier={verifyRepairAuthorization(){return false;}},repairStore:RepairCommitStore={commitRepairAtomically(){return "COMMITTED";}},reducer=new ChainReducer(auth,repairVerifier,repairStore);assert(reducer.ingest(indexed)==="APPLIED"&&reducer.snapshot().actions[0].objectCommitment===LISTING,"listing action reaches authentic final reducer state");
  process.stdout.write(JSON.stringify({schema_version:1,task_id:"NX-MARKET-P01",status:"PASS",assertions,actor_class:"SYSTEM_TEST",listing:{active:true,moderated:true,market_profile:true,distinct_action:true,classifed_without_escrow:true,reconciled:true},escrow:{real_value_atomic:"0",max_test_total_atomic:"1000000",release:true,refund:true,dispute:true,conservation:true,restore:true},negative:{exact_shape:true,prohibited_goods:true,boolean_string:true,price_substitution:true,coordinated_terms_substitution:true,policy_race:true,retained_prepared_action:true,listing_replay:true,classified_escrow_denied:true,cap:true,funding_replay:true,actor_separation:true,terminal_reentry:true,snapshot_tamper:true,snapshot_prefix:true,fabricated_transition:true,snapshot_resolver_binding:true,accept_deadline:true,fulfil_deadline:true,authoritative_deadline_time:true,pause_refund:true,resolver_separation:true,resolver_collision:true},network_operations:0,provider_operations:0,economic_operations:0,incremental_cost:{amount:0,currency:"EUR"}}));
}
void main();
