export type ListingMode = "CLASSIFIED_ONLY" | "ESCROW_CHECKOUT";
export type ListingCategory = "ELECTRONICS" | "VEHICLES_PARTS" | "HOME_GARDEN" | "FASHION" | "SPORTS_BOOKS" | "BUSINESS_EQUIPMENT";
export type ListingState = "ACTIVE" | "RESERVED" | "SOLD" | "CLOSED" | "REMOVED";
export type EscrowState = "FUNDED" | "ACCEPTED" | "FULFILLED" | "DISPUTED" | "RELEASED" | "REFUNDED" | "RESOLVED";

export class MarketplacePolicyError extends Error {
  constructor(readonly code: string) { super(code); this.name = "MarketplacePolicyError"; }
}

export interface SignedVerifier<T> { verify(value: Readonly<T>): boolean }
export interface ListingProfileBoundary { isActiveMarketProfile(profileCommitment: string, generation: number): boolean }
export interface ListingPolicyBoundary { current(territory: string, category: ListingCategory): Readonly<{ version: number; enabled: boolean }> }

export interface ListingPublishCommand {
  schemaVersion: 1; listingCommitment: string; manifestHash: string; sellerProfileCommitment: string;
  sellerProfileGeneration: number; category: ListingCategory; mode: ListingMode; condition: "NEW" | "USED" | "REFURBISHED";
  territory: string; tokenId: string; priceAtomic: string; traderStatus: "TRADER" | "NON_TRADER";
  syntheticLabel: "SYSTEM_TEST"; publishedAt: string; signature: string;
}
export interface ListingEligibilityDecision {
  schemaVersion: 1; decisionId: string; listingCommitment: string; manifestHash: string; sellerProfileCommitment: string;
  sellerProfileGeneration: number; category: ListingCategory; mode: ListingMode; territory: string; tokenId: string;
  priceAtomic: string; prohibitedGoodsClear: true; scamClear: true; duplicateClear: true; recallClear: true;
  productSafetyClear: true; traderDisclosureComplete: true; policyVersion: number; evaluatedAt: string; expiresAt: string;
  issuerKeyId: string; signature: string;
}
export interface ListingExecutionAuthorization {
  schemaVersion: 1; authorizationId: string; decisionId: string; listingCommitment: string; manifestHash: string;
  sellerProfileCommitment: string; sellerProfileGeneration: number; category: ListingCategory; mode: ListingMode;
  condition: "NEW" | "USED" | "REFURBISHED"; territory: string; tokenId: string; priceAtomic: string;
  traderStatus: "TRADER" | "NON_TRADER"; actionNonce: string; sessionPublicKey: string;
  chainId: string; contractAddress: string; policyVersion: number; evaluatedAt: string; expiresAt: string;
  issuerKeyId: string; signature: string;
}
export interface ListingActionEnvelope {
  version: 1; actorKind: "HUMAN" | "AGENT"; actorCommitment: string; actionType: "LISTING_CREATE";
  objectCommitment: string; payloadHashOrCid: string; visibilityClass: "PUBLIC"; actionNonce: bigint;
  issuedAtMs: number; expiresAtMs: number; sessionPublicKey: string;
}
export interface ListingExecutionContext { chainId: string; contractAddress: string; relayer: string; relayerAgreementVerified: boolean; nowMs: number; payments: readonly unknown[] }
export interface PreparedListingAction { readonly envelope: ListingActionEnvelope; readonly context: ListingExecutionContext; readonly opaque: unknown }
export interface ListingRecordedEvent { identifier: "ActionRecorded"; actorCommitment: string; objectCommitment: string; actionNonce: string; actionClass: "PUBLIC_ACTION" }
export interface ListingActionRecorder {
  prepareAction(envelope: ListingActionEnvelope, signatureHex: string, context: ListingExecutionContext): Promise<PreparedListingAction>;
  commitPreparedAction(prepared: PreparedListingAction): ListingRecordedEvent;
  abortPreparedAction(prepared: PreparedListingAction): void;
}
export interface ListingProjection extends Omit<ListingPublishCommand, "signature" | "publishedAt"> {
  state: ListingState; stateVersion: number; policyVersion: number; publishedAt: string; protectedCheckout: boolean;
}

export interface FundOrderCommand {
  schemaVersion: 1; actionId: string; escrowId: string; listingCommitment: string; listingStateVersion: number;
  buyerProfileCommitment: string; buyerProfileGeneration: number; sellerProfileCommitment: string; sellerProfileGeneration: number;
  paymentKey: string; tokenId: string; principalAtomic: string; platformFeeAtomic: string; totalAtomic: string;
  realValueAtomic: "0"; termsHash: string; acceptBy: string; fulfilBy: string; autoReleaseAt: string;
  policyVersion: number; syntheticLabel: "SYSTEM_TEST"; occurredAt: string; signature: string;
}
export interface EscrowActionCommand {
  schemaVersion: 1; actionId: string; escrowId: string; expectedVersion: number; actorProfileCommitment: string;
  outcomeBuyerBps: number; outcomeSellerBps: number; evidenceCommitment: string; occurredAt: string; signature: string;
}
export interface EscrowProjection {
  schemaVersion: 1; escrowId: string; listingCommitment: string; buyerProfileCommitment: string; sellerProfileCommitment: string;
  paymentKey: string; tokenId: string; principalAtomic: string; platformFeeAtomic: string; totalAtomic: string;
  termsHash: string; acceptBy: string; fulfilBy: string; autoReleaseAt: string; policyVersion: number;
  syntheticLabel: "SYSTEM_TEST"; state: EscrowState; stateVersion: number; buyerCreditAtomic: string;
  sellerCreditAtomic: string; platformCreditAtomic: string; updatedAt: string;
}
export interface EscrowEvent extends EscrowProjection { eventOrdinal: number; actionId: string; action: "FUND" | "ACCEPT" | "FULFIL" | "BUYER_ACCEPT" | "REFUND" | "DISPUTE" | "RESOLVE"; actorProfileCommitment: string; evidenceCommitment: string; signature: string }
export interface EscrowEventVerifier { verify(event: Readonly<EscrowEvent>): boolean }
export interface EscrowSnapshot {
  schemaVersion: 1; pausedNewOrders: boolean; checkpointId: string; eventCount: number; eventSetCommitment: string; resolverCommitment: string;
  issuedAt: string; expiresAt: string; issuerKeyId: string; signature: string; events: readonly EscrowEvent[];
}
export interface EscrowSnapshotAttestation { checkpointId: string; eventSetCommitment: string; issuedAt: string; expiresAt: string; issuerKeyId: string; signature: string }
export interface EscrowSnapshotVerifier { verify(snapshot: Readonly<EscrowSnapshot>): boolean }

const HASH = /^[a-f0-9]{64}$/;
const SIGNATURE = /^[a-f0-9]{128}$/;
const ID = /^[A-Z][A-Z0-9:_-]{2,79}$/;
const TERRITORY = /^[A-Z]{2}$/;
const TOKEN = /^TEST[A-Z0-9-]{2,28}$/;
const AMOUNT = /^(0|[1-9][0-9]{0,30})$/;
const CATEGORIES: readonly ListingCategory[] = ["ELECTRONICS", "VEHICLES_PARTS", "HOME_GARDEN", "FASHION", "SPORTS_BOOKS", "BUSINESS_EQUIPMENT"];
const MAX_TEST_TOTAL = 1_000_000n;
function fail(code: string): never { throw new MarketplacePolicyError(code); }
function plain(value: unknown, keys: readonly string[], code: string): Record<string, unknown> {
  if (value === null || typeof value !== "object" || Object.getPrototypeOf(value) !== Object.prototype || Object.keys(value).sort().join("|") !== [...keys].sort().join("|")) fail(code);
  const descriptors = Object.getOwnPropertyDescriptors(value); if (Object.values(descriptors).some((d) => d.get || d.set || !d.enumerable)) fail(code);
  return value as Record<string, unknown>;
}
function text(value: unknown, pattern: RegExp, code: string): string { if (typeof value !== "string" || !pattern.test(value)) fail(code); return value; }
function integer(value: unknown, min: number, max: number, code: string): number { if (typeof value !== "number" || !Number.isSafeInteger(value) || value < min || value > max) fail(code); return value; }
function exact<T extends string>(value: unknown, allowed: readonly T[], code: string): T { if (typeof value !== "string" || !allowed.includes(value as T)) fail(code); return value as T; }
function iso(value: unknown, code: string): string { if (typeof value !== "string" || !/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(value) || !Number.isFinite(Date.parse(value))) fail(code); return value; }
function boolTrue(value: unknown, code: string): true { if (value !== true) fail(code); return true; }
function amount(value: unknown, code: string): string { return text(value, AMOUNT, code); }

const PUBLISH_KEYS = ["schemaVersion","listingCommitment","manifestHash","sellerProfileCommitment","sellerProfileGeneration","category","mode","condition","territory","tokenId","priceAtomic","traderStatus","syntheticLabel","publishedAt","signature"] as const;
const DECISION_KEYS = ["schemaVersion","decisionId","listingCommitment","manifestHash","sellerProfileCommitment","sellerProfileGeneration","category","mode","territory","tokenId","priceAtomic","prohibitedGoodsClear","scamClear","duplicateClear","recallClear","productSafetyClear","traderDisclosureComplete","policyVersion","evaluatedAt","expiresAt","issuerKeyId","signature"] as const;
const AUTH_KEYS = ["schemaVersion","authorizationId","decisionId","listingCommitment","manifestHash","sellerProfileCommitment","sellerProfileGeneration","category","mode","condition","territory","tokenId","priceAtomic","traderStatus","actionNonce","sessionPublicKey","chainId","contractAddress","policyVersion","evaluatedAt","expiresAt","issuerKeyId","signature"] as const;
const ENVELOPE_KEYS = ["version","actorKind","actorCommitment","actionType","objectCommitment","payloadHashOrCid","visibilityClass","actionNonce","issuedAtMs","expiresAtMs","sessionPublicKey"] as const;
const CONTEXT_KEYS = ["chainId","contractAddress","relayer","relayerAgreementVerified","nowMs","payments"] as const;
const FUND_KEYS = ["schemaVersion","actionId","escrowId","listingCommitment","listingStateVersion","buyerProfileCommitment","buyerProfileGeneration","sellerProfileCommitment","sellerProfileGeneration","paymentKey","tokenId","principalAtomic","platformFeeAtomic","totalAtomic","realValueAtomic","termsHash","acceptBy","fulfilBy","autoReleaseAt","policyVersion","syntheticLabel","occurredAt","signature"] as const;
const ESCROW_ACTION_KEYS = ["schemaVersion","actionId","escrowId","expectedVersion","actorProfileCommitment","outcomeBuyerBps","outcomeSellerBps","evidenceCommitment","occurredAt","signature"] as const;
const ESCROW_EVENT_KEYS = ["schemaVersion","escrowId","listingCommitment","buyerProfileCommitment","sellerProfileCommitment","paymentKey","tokenId","principalAtomic","platformFeeAtomic","totalAtomic","termsHash","acceptBy","fulfilBy","autoReleaseAt","policyVersion","syntheticLabel","state","stateVersion","buyerCreditAtomic","sellerCreditAtomic","platformCreditAtomic","updatedAt","eventOrdinal","actionId","action","actorProfileCommitment","evidenceCommitment","signature"] as const;
const SNAPSHOT_KEYS = ["schemaVersion","pausedNewOrders","checkpointId","eventCount","eventSetCommitment","resolverCommitment","issuedAt","expiresAt","issuerKeyId","signature","events"] as const;
const SNAPSHOT_ATTESTATION_KEYS = ["checkpointId","eventSetCommitment","issuedAt","expiresAt","issuerKeyId","signature"] as const;

function parsePublish(value: unknown): ListingPublishCommand {
  const o=plain(value,PUBLISH_KEYS,"LISTING_COMMAND_INVALID");
  if(o.schemaVersion!==1||o.syntheticLabel!=="SYSTEM_TEST") fail("LISTING_COMMAND_INVALID");
  return {schemaVersion:1,listingCommitment:text(o.listingCommitment,HASH,"LISTING_COMMAND_INVALID"),manifestHash:text(o.manifestHash,HASH,"LISTING_COMMAND_INVALID"),sellerProfileCommitment:text(o.sellerProfileCommitment,HASH,"LISTING_COMMAND_INVALID"),sellerProfileGeneration:integer(o.sellerProfileGeneration,1,Number.MAX_SAFE_INTEGER,"LISTING_COMMAND_INVALID"),category:exact(o.category,CATEGORIES,"LISTING_CATEGORY_DENIED"),mode:exact(o.mode,["CLASSIFIED_ONLY","ESCROW_CHECKOUT"],"LISTING_MODE_INVALID"),condition:exact(o.condition,["NEW","USED","REFURBISHED"],"LISTING_COMMAND_INVALID"),territory:text(o.territory,TERRITORY,"LISTING_TERRITORY_INVALID"),tokenId:text(o.tokenId,TOKEN,"LISTING_TOKEN_INVALID"),priceAtomic:amount(o.priceAtomic,"LISTING_PRICE_INVALID"),traderStatus:exact(o.traderStatus,["TRADER","NON_TRADER"],"LISTING_COMMAND_INVALID"),syntheticLabel:"SYSTEM_TEST",publishedAt:iso(o.publishedAt,"LISTING_COMMAND_INVALID"),signature:text(o.signature,SIGNATURE,"LISTING_COMMAND_INVALID")};
}
function parseDecision(value: unknown): ListingEligibilityDecision {
  const o=plain(value,DECISION_KEYS,"LISTING_DECISION_INVALID"); if(o.schemaVersion!==1) fail("LISTING_DECISION_INVALID");
  return {schemaVersion:1,decisionId:text(o.decisionId,ID,"LISTING_DECISION_INVALID"),listingCommitment:text(o.listingCommitment,HASH,"LISTING_DECISION_INVALID"),manifestHash:text(o.manifestHash,HASH,"LISTING_DECISION_INVALID"),sellerProfileCommitment:text(o.sellerProfileCommitment,HASH,"LISTING_DECISION_INVALID"),sellerProfileGeneration:integer(o.sellerProfileGeneration,1,Number.MAX_SAFE_INTEGER,"LISTING_DECISION_INVALID"),category:exact(o.category,CATEGORIES,"LISTING_CATEGORY_DENIED"),mode:exact(o.mode,["CLASSIFIED_ONLY","ESCROW_CHECKOUT"],"LISTING_DECISION_INVALID"),territory:text(o.territory,TERRITORY,"LISTING_DECISION_INVALID"),tokenId:text(o.tokenId,TOKEN,"LISTING_DECISION_INVALID"),priceAtomic:amount(o.priceAtomic,"LISTING_DECISION_INVALID"),prohibitedGoodsClear:boolTrue(o.prohibitedGoodsClear,"LISTING_PROHIBITED"),scamClear:boolTrue(o.scamClear,"LISTING_SCAM_RISK"),duplicateClear:boolTrue(o.duplicateClear,"LISTING_DUPLICATE"),recallClear:boolTrue(o.recallClear,"LISTING_RECALL"),productSafetyClear:boolTrue(o.productSafetyClear,"LISTING_PRODUCT_SAFETY"),traderDisclosureComplete:boolTrue(o.traderDisclosureComplete,"LISTING_TRADER_DISCLOSURE"),policyVersion:integer(o.policyVersion,1,Number.MAX_SAFE_INTEGER,"LISTING_DECISION_INVALID"),evaluatedAt:iso(o.evaluatedAt,"LISTING_DECISION_INVALID"),expiresAt:iso(o.expiresAt,"LISTING_DECISION_INVALID"),issuerKeyId:text(o.issuerKeyId,ID,"LISTING_DECISION_INVALID"),signature:text(o.signature,SIGNATURE,"LISTING_DECISION_INVALID")};
}
function parseAuthorization(value: unknown): ListingExecutionAuthorization {
  const o=plain(value,AUTH_KEYS,"LISTING_AUTHORIZATION_INVALID"); if(o.schemaVersion!==1) fail("LISTING_AUTHORIZATION_INVALID");
  return {schemaVersion:1,authorizationId:text(o.authorizationId,ID,"LISTING_AUTHORIZATION_INVALID"),decisionId:text(o.decisionId,ID,"LISTING_AUTHORIZATION_INVALID"),listingCommitment:text(o.listingCommitment,HASH,"LISTING_AUTHORIZATION_INVALID"),manifestHash:text(o.manifestHash,HASH,"LISTING_AUTHORIZATION_INVALID"),sellerProfileCommitment:text(o.sellerProfileCommitment,HASH,"LISTING_AUTHORIZATION_INVALID"),sellerProfileGeneration:integer(o.sellerProfileGeneration,1,Number.MAX_SAFE_INTEGER,"LISTING_AUTHORIZATION_INVALID"),category:exact(o.category,CATEGORIES,"LISTING_AUTHORIZATION_INVALID"),mode:exact(o.mode,["CLASSIFIED_ONLY","ESCROW_CHECKOUT"],"LISTING_AUTHORIZATION_INVALID"),condition:exact(o.condition,["NEW","USED","REFURBISHED"],"LISTING_AUTHORIZATION_INVALID"),territory:text(o.territory,TERRITORY,"LISTING_AUTHORIZATION_INVALID"),tokenId:text(o.tokenId,TOKEN,"LISTING_AUTHORIZATION_INVALID"),priceAtomic:amount(o.priceAtomic,"LISTING_AUTHORIZATION_INVALID"),traderStatus:exact(o.traderStatus,["TRADER","NON_TRADER"],"LISTING_AUTHORIZATION_INVALID"),actionNonce:amount(o.actionNonce,"LISTING_AUTHORIZATION_INVALID"),sessionPublicKey:text(o.sessionPublicKey,HASH,"LISTING_AUTHORIZATION_INVALID"),chainId:text(o.chainId,/^[A-Z0-9]{1,12}$/,"LISTING_AUTHORIZATION_INVALID"),contractAddress:text(o.contractAddress,/^erd1[a-z0-9]{58}$/,"LISTING_AUTHORIZATION_INVALID"),policyVersion:integer(o.policyVersion,1,Number.MAX_SAFE_INTEGER,"LISTING_AUTHORIZATION_INVALID"),evaluatedAt:iso(o.evaluatedAt,"LISTING_AUTHORIZATION_INVALID"),expiresAt:iso(o.expiresAt,"LISTING_AUTHORIZATION_INVALID"),issuerKeyId:text(o.issuerKeyId,ID,"LISTING_AUTHORIZATION_INVALID"),signature:text(o.signature,SIGNATURE,"LISTING_AUTHORIZATION_INVALID")};
}
function parseEnvelope(value: unknown): ListingActionEnvelope { const o=plain(value,ENVELOPE_KEYS,"LISTING_ENVELOPE_INVALID"); if(o.version!==1||o.actionType!=="LISTING_CREATE"||o.visibilityClass!=="PUBLIC") fail("LISTING_ENVELOPE_INVALID"); return {version:1,actorKind:exact(o.actorKind,["HUMAN","AGENT"],"LISTING_ENVELOPE_INVALID"),actorCommitment:text(o.actorCommitment,HASH,"LISTING_ENVELOPE_INVALID"),actionType:"LISTING_CREATE",objectCommitment:text(o.objectCommitment,HASH,"LISTING_ENVELOPE_INVALID"),payloadHashOrCid:text(o.payloadHashOrCid,HASH,"LISTING_ENVELOPE_INVALID"),visibilityClass:"PUBLIC",actionNonce:typeof o.actionNonce==="bigint"?o.actionNonce:fail("LISTING_ENVELOPE_INVALID"),issuedAtMs:integer(o.issuedAtMs,0,Number.MAX_SAFE_INTEGER,"LISTING_ENVELOPE_INVALID"),expiresAtMs:integer(o.expiresAtMs,0,Number.MAX_SAFE_INTEGER,"LISTING_ENVELOPE_INVALID"),sessionPublicKey:text(o.sessionPublicKey,HASH,"LISTING_ENVELOPE_INVALID")}; }
function parseContext(value: unknown): ListingExecutionContext { const o=plain(value,CONTEXT_KEYS,"LISTING_CONTEXT_INVALID"); if(o.relayerAgreementVerified!==true||!Array.isArray(o.payments)||o.payments.length!==0) fail("LISTING_CONTEXT_INVALID"); return {chainId:text(o.chainId,/^[A-Z0-9]{1,12}$/,"LISTING_CONTEXT_INVALID"),contractAddress:text(o.contractAddress,/^erd1[a-z0-9]{58}$/,"LISTING_CONTEXT_INVALID"),relayer:text(o.relayer,/^erd1[a-z0-9]{58}$/,"LISTING_CONTEXT_INVALID"),relayerAgreementVerified:true,nowMs:integer(o.nowMs,0,Number.MAX_SAFE_INTEGER,"LISTING_CONTEXT_INVALID"),payments:[]}; }

export class MarketplaceListingRegistry {
  private readonly listings=new Map<string,ListingProjection>(); private readonly consumedAuthorizations=new Set<string>();
  constructor(private readonly profiles: ListingProfileBoundary, private readonly policies: ListingPolicyBoundary) {}
  get(listingCommitment:string):Readonly<ListingProjection>|null { const v=this.listings.get(listingCommitment); return v?{...v}:null; }
  async executePublish(commandInput:unknown,decisionInput:unknown,authorizationInput:unknown,envelopeInput:unknown,sessionSignatureInput:unknown,contextInput:unknown,commandVerifier:SignedVerifier<ListingPublishCommand>,decisionVerifier:SignedVerifier<ListingEligibilityDecision>,authorizationVerifier:SignedVerifier<ListingExecutionAuthorization>,recorder:ListingActionRecorder,nowInput:unknown):Promise<Readonly<ListingProjection>> {
    const c=parsePublish(commandInput),d=parseDecision(decisionInput),a=parseAuthorization(authorizationInput),e=parseEnvelope(envelopeInput),x=parseContext(contextInput),now=iso(nowInput,"LISTING_TIME_INVALID"),nowMs=Date.parse(now);
    if(typeof sessionSignatureInput!=="string"||!SIGNATURE.test(sessionSignatureInput)) fail("LISTING_SESSION_SIGNATURE_INVALID");
    if(!commandVerifier.verify(c)) fail("LISTING_COMMAND_SIGNATURE_INVALID"); if(!decisionVerifier.verify(d)) fail("LISTING_DECISION_SIGNATURE_INVALID"); if(!authorizationVerifier.verify(a)) fail("LISTING_AUTHORIZATION_SIGNATURE_INVALID");
    if(this.listings.has(c.listingCommitment)) fail("LISTING_REPLAY"); if(this.consumedAuthorizations.has(a.authorizationId)) fail("LISTING_AUTHORIZATION_REPLAY");
    if(Date.parse(c.publishedAt)>nowMs||Date.parse(d.evaluatedAt)>nowMs||Date.parse(d.expiresAt)<=nowMs||Date.parse(a.evaluatedAt)>nowMs||Date.parse(a.expiresAt)<=nowMs) fail("LISTING_CONTEXT_EXPIRED");
    const binding=["listingCommitment","manifestHash","sellerProfileCommitment","sellerProfileGeneration","category","mode","territory","tokenId","priceAtomic"] as const; if(binding.some(k=>c[k]!==d[k])) fail("LISTING_DECISION_BINDING_MISMATCH");
    const authBinding=["listingCommitment","manifestHash","sellerProfileCommitment","sellerProfileGeneration","category","mode","condition","territory","tokenId","priceAtomic","traderStatus"] as const;
    if(a.decisionId!==d.decisionId||a.policyVersion!==d.policyVersion||authBinding.some(k=>a[k]!==c[k])) fail("LISTING_AUTHORIZATION_BINDING_MISMATCH");
    if(e.actorCommitment!==c.sellerProfileCommitment||e.objectCommitment!==c.listingCommitment||e.payloadHashOrCid!==c.manifestHash||e.actionNonce.toString()!==a.actionNonce||e.sessionPublicKey!==a.sessionPublicKey||x.chainId!==a.chainId||x.contractAddress!==a.contractAddress) fail("LISTING_ENVELOPE_BINDING_MISMATCH");
    if(!this.profiles.isActiveMarketProfile(c.sellerProfileCommitment,c.sellerProfileGeneration)) fail("MARKET_PROFILE_STALE"); const policy=this.policies.current(c.territory,c.category); if(!policy.enabled||policy.version!==d.policyVersion) fail("LISTING_POLICY_STALE");
    let prepared:PreparedListingAction|null=null; try { prepared=await recorder.prepareAction(e,sessionSignatureInput,x); const current=this.policies.current(c.territory,c.category); if(!this.profiles.isActiveMarketProfile(c.sellerProfileCommitment,c.sellerProfileGeneration)||!current.enabled||current.version!==policy.version) fail("LISTING_EXECUTION_STATE_CONFLICT"); recorder.commitPreparedAction(prepared); const p:ListingProjection={...c,state:"ACTIVE",stateVersion:1,policyVersion:d.policyVersion,protectedCheckout:c.mode==="ESCROW_CHECKOUT",publishedAt:c.publishedAt}; delete (p as Partial<ListingPublishCommand>).signature; this.listings.set(c.listingCommitment,Object.freeze(p)); this.consumedAuthorizations.add(a.authorizationId); return {...p}; } catch(error){ if(prepared) recorder.abortPreparedAction(prepared); throw error; }
  }
}

function parseFund(value:unknown):FundOrderCommand { const o=plain(value,FUND_KEYS,"FUND_ORDER_INVALID"); if(o.schemaVersion!==1||o.syntheticLabel!=="SYSTEM_TEST"||o.realValueAtomic!=="0") fail("FUND_ORDER_INVALID"); return {schemaVersion:1,actionId:text(o.actionId,ID,"FUND_ORDER_INVALID"),escrowId:text(o.escrowId,ID,"FUND_ORDER_INVALID"),listingCommitment:text(o.listingCommitment,HASH,"FUND_ORDER_INVALID"),listingStateVersion:integer(o.listingStateVersion,1,Number.MAX_SAFE_INTEGER,"FUND_ORDER_INVALID"),buyerProfileCommitment:text(o.buyerProfileCommitment,HASH,"FUND_ORDER_INVALID"),buyerProfileGeneration:integer(o.buyerProfileGeneration,1,Number.MAX_SAFE_INTEGER,"FUND_ORDER_INVALID"),sellerProfileCommitment:text(o.sellerProfileCommitment,HASH,"FUND_ORDER_INVALID"),sellerProfileGeneration:integer(o.sellerProfileGeneration,1,Number.MAX_SAFE_INTEGER,"FUND_ORDER_INVALID"),paymentKey:text(o.paymentKey,HASH,"FUND_ORDER_INVALID"),tokenId:text(o.tokenId,TOKEN,"FUND_ORDER_INVALID"),principalAtomic:amount(o.principalAtomic,"FUND_ORDER_INVALID"),platformFeeAtomic:amount(o.platformFeeAtomic,"FUND_ORDER_INVALID"),totalAtomic:amount(o.totalAtomic,"FUND_ORDER_INVALID"),realValueAtomic:"0",termsHash:text(o.termsHash,HASH,"FUND_ORDER_INVALID"),acceptBy:iso(o.acceptBy,"FUND_ORDER_INVALID"),fulfilBy:iso(o.fulfilBy,"FUND_ORDER_INVALID"),autoReleaseAt:iso(o.autoReleaseAt,"FUND_ORDER_INVALID"),policyVersion:integer(o.policyVersion,1,Number.MAX_SAFE_INTEGER,"FUND_ORDER_INVALID"),syntheticLabel:"SYSTEM_TEST",occurredAt:iso(o.occurredAt,"FUND_ORDER_INVALID"),signature:text(o.signature,SIGNATURE,"FUND_ORDER_INVALID")}; }
function parseEscrowAction(value:unknown):EscrowActionCommand { const o=plain(value,ESCROW_ACTION_KEYS,"ESCROW_ACTION_INVALID"); if(o.schemaVersion!==1) fail("ESCROW_ACTION_INVALID"); return {schemaVersion:1,actionId:text(o.actionId,ID,"ESCROW_ACTION_INVALID"),escrowId:text(o.escrowId,ID,"ESCROW_ACTION_INVALID"),expectedVersion:integer(o.expectedVersion,1,Number.MAX_SAFE_INTEGER,"ESCROW_ACTION_INVALID"),actorProfileCommitment:text(o.actorProfileCommitment,HASH,"ESCROW_ACTION_INVALID"),outcomeBuyerBps:integer(o.outcomeBuyerBps,0,10000,"ESCROW_ACTION_INVALID"),outcomeSellerBps:integer(o.outcomeSellerBps,0,10000,"ESCROW_ACTION_INVALID"),evidenceCommitment:text(o.evidenceCommitment,HASH,"ESCROW_ACTION_INVALID"),occurredAt:iso(o.occurredAt,"ESCROW_ACTION_INVALID"),signature:text(o.signature,SIGNATURE,"ESCROW_ACTION_INVALID")}; }
function parseEvent(value:unknown):EscrowEvent { const o=plain(value,ESCROW_EVENT_KEYS,"ESCROW_SNAPSHOT_INVALID"); if(o.schemaVersion!==1||o.syntheticLabel!=="SYSTEM_TEST") fail("ESCROW_SNAPSHOT_INVALID"); return {schemaVersion:1,escrowId:text(o.escrowId,ID,"ESCROW_SNAPSHOT_INVALID"),listingCommitment:text(o.listingCommitment,HASH,"ESCROW_SNAPSHOT_INVALID"),buyerProfileCommitment:text(o.buyerProfileCommitment,HASH,"ESCROW_SNAPSHOT_INVALID"),sellerProfileCommitment:text(o.sellerProfileCommitment,HASH,"ESCROW_SNAPSHOT_INVALID"),paymentKey:text(o.paymentKey,HASH,"ESCROW_SNAPSHOT_INVALID"),tokenId:text(o.tokenId,TOKEN,"ESCROW_SNAPSHOT_INVALID"),principalAtomic:amount(o.principalAtomic,"ESCROW_SNAPSHOT_INVALID"),platformFeeAtomic:amount(o.platformFeeAtomic,"ESCROW_SNAPSHOT_INVALID"),totalAtomic:amount(o.totalAtomic,"ESCROW_SNAPSHOT_INVALID"),termsHash:text(o.termsHash,HASH,"ESCROW_SNAPSHOT_INVALID"),acceptBy:iso(o.acceptBy,"ESCROW_SNAPSHOT_INVALID"),fulfilBy:iso(o.fulfilBy,"ESCROW_SNAPSHOT_INVALID"),autoReleaseAt:iso(o.autoReleaseAt,"ESCROW_SNAPSHOT_INVALID"),policyVersion:integer(o.policyVersion,1,Number.MAX_SAFE_INTEGER,"ESCROW_SNAPSHOT_INVALID"),syntheticLabel:"SYSTEM_TEST",state:exact(o.state,["FUNDED","ACCEPTED","FULFILLED","DISPUTED","RELEASED","REFUNDED","RESOLVED"],"ESCROW_SNAPSHOT_INVALID"),stateVersion:integer(o.stateVersion,1,Number.MAX_SAFE_INTEGER,"ESCROW_SNAPSHOT_INVALID"),buyerCreditAtomic:amount(o.buyerCreditAtomic,"ESCROW_SNAPSHOT_INVALID"),sellerCreditAtomic:amount(o.sellerCreditAtomic,"ESCROW_SNAPSHOT_INVALID"),platformCreditAtomic:amount(o.platformCreditAtomic,"ESCROW_SNAPSHOT_INVALID"),updatedAt:iso(o.updatedAt,"ESCROW_SNAPSHOT_INVALID"),eventOrdinal:integer(o.eventOrdinal,1,Number.MAX_SAFE_INTEGER,"ESCROW_SNAPSHOT_INVALID"),actionId:text(o.actionId,ID,"ESCROW_SNAPSHOT_INVALID"),action:exact(o.action,["FUND","ACCEPT","FULFIL","BUYER_ACCEPT","REFUND","DISPUTE","RESOLVE"],"ESCROW_SNAPSHOT_INVALID"),actorProfileCommitment:text(o.actorProfileCommitment,HASH,"ESCROW_SNAPSHOT_INVALID"),evidenceCommitment:text(o.evidenceCommitment,HASH,"ESCROW_SNAPSHOT_INVALID"),signature:text(o.signature,SIGNATURE,"ESCROW_SNAPSHOT_INVALID")}; }
function parseSnapshotAttestation(value:unknown):EscrowSnapshotAttestation { const o=plain(value,SNAPSHOT_ATTESTATION_KEYS,"ESCROW_CHECKPOINT_INVALID"); return {checkpointId:text(o.checkpointId,ID,"ESCROW_CHECKPOINT_INVALID"),eventSetCommitment:text(o.eventSetCommitment,HASH,"ESCROW_CHECKPOINT_INVALID"),issuedAt:iso(o.issuedAt,"ESCROW_CHECKPOINT_INVALID"),expiresAt:iso(o.expiresAt,"ESCROW_CHECKPOINT_INVALID"),issuerKeyId:text(o.issuerKeyId,ID,"ESCROW_CHECKPOINT_INVALID"),signature:text(o.signature,SIGNATURE,"ESCROW_CHECKPOINT_INVALID")}; }

export class MarketplaceEscrowLedger {
  private readonly orders=new Map<string,EscrowProjection>(); private readonly usedActions=new Set<string>(); private readonly events:EscrowEvent[]=[]; private pausedNewOrders=false;
  constructor(private readonly listings:MarketplaceListingRegistry,private readonly profiles:ListingProfileBoundary,private readonly resolverCommitment:string){ text(resolverCommitment,HASH,"RESOLVER_INVALID"); }
  setPausedNewOrders(paused:boolean):void { if(typeof paused!=="boolean") fail("PAUSE_INVALID"); this.pausedNewOrders=paused; }
  get(escrowId:string):Readonly<EscrowProjection>|null { const v=this.orders.get(escrowId); return v?{...v}:null; }
  fundOrder(input:unknown,verifier:SignedVerifier<FundOrderCommand>,nowInput:unknown):Readonly<EscrowProjection>{ const c=parseFund(input),now=iso(nowInput,"ESCROW_TIME_INVALID"); if(this.pausedNewOrders) fail("NEW_ORDERS_PAUSED"); if(!verifier.verify(c)) fail("FUND_SIGNATURE_INVALID"); if(this.usedActions.has(c.actionId)||this.orders.has(c.escrowId)) fail("ESCROW_REPLAY"); if(Date.parse(c.occurredAt)>Date.parse(now)||Date.parse(c.acceptBy)<=Date.parse(now)||!(Date.parse(c.acceptBy)<Date.parse(c.fulfilBy)&&Date.parse(c.fulfilBy)<Date.parse(c.autoReleaseAt))) fail("ESCROW_DEADLINE_INVALID"); const listing=this.listings.get(c.listingCommitment); if(!listing||listing.state!=="ACTIVE"||listing.mode!=="ESCROW_CHECKOUT"||listing.stateVersion!==c.listingStateVersion) fail("LISTING_NOT_ESCROW_ELIGIBLE"); if(listing.sellerProfileCommitment!==c.sellerProfileCommitment||listing.sellerProfileGeneration!==c.sellerProfileGeneration||listing.tokenId!==c.tokenId||listing.priceAtomic!==c.principalAtomic||listing.policyVersion!==c.policyVersion) fail("ESCROW_LISTING_BINDING_MISMATCH"); if(c.buyerProfileCommitment===c.sellerProfileCommitment||this.resolverCommitment===c.buyerProfileCommitment||this.resolverCommitment===c.sellerProfileCommitment||!this.profiles.isActiveMarketProfile(c.buyerProfileCommitment,c.buyerProfileGeneration)||!this.profiles.isActiveMarketProfile(c.sellerProfileCommitment,c.sellerProfileGeneration)) fail("ESCROW_PROFILE_DENIED"); const principal=BigInt(c.principalAtomic),fee=BigInt(c.platformFeeAtomic),total=BigInt(c.totalAtomic); if(principal<=0n||fee*10_000n>principal*500n||principal+fee!==total||total>MAX_TEST_TOTAL) fail("ESCROW_AMOUNT_CAP_OR_CONSERVATION"); const p:EscrowProjection={schemaVersion:1,escrowId:c.escrowId,listingCommitment:c.listingCommitment,buyerProfileCommitment:c.buyerProfileCommitment,sellerProfileCommitment:c.sellerProfileCommitment,paymentKey:c.paymentKey,tokenId:c.tokenId,principalAtomic:c.principalAtomic,platformFeeAtomic:c.platformFeeAtomic,totalAtomic:c.totalAtomic,termsHash:c.termsHash,acceptBy:c.acceptBy,fulfilBy:c.fulfilBy,autoReleaseAt:c.autoReleaseAt,policyVersion:c.policyVersion,syntheticLabel:"SYSTEM_TEST",state:"FUNDED",stateVersion:1,buyerCreditAtomic:"0",sellerCreditAtomic:"0",platformCreditAtomic:"0",updatedAt:c.occurredAt}; this.record(p,c.actionId,"FUND",c.buyerProfileCommitment,c.termsHash,c.signature); return {...p}; }
  sellerAccept(input:unknown,v:SignedVerifier<EscrowActionCommand>,now:unknown){return this.transition(input,v,now,["FUNDED"],"ACCEPTED","SELLER","ACCEPT");}
  markFulfilled(input:unknown,v:SignedVerifier<EscrowActionCommand>,now:unknown){return this.transition(input,v,now,["ACCEPTED"],"FULFILLED","SELLER","FULFIL");}
  buyerAccept(input:unknown,v:SignedVerifier<EscrowActionCommand>,now:unknown){return this.transition(input,v,now,["FULFILLED"],"RELEASED","BUYER","BUYER_ACCEPT");}
  cancelBeforeAccept(input:unknown,v:SignedVerifier<EscrowActionCommand>,now:unknown){return this.transition(input,v,now,["FUNDED"],"REFUNDED","BUYER","REFUND");}
  openDispute(input:unknown,v:SignedVerifier<EscrowActionCommand>,now:unknown){return this.transition(input,v,now,["ACCEPTED","FULFILLED"],"DISPUTED","PARTY","DISPUTE");}
  resolveDispute(input:unknown,v:SignedVerifier<EscrowActionCommand>,now:unknown){return this.transition(input,v,now,["DISPUTED"],"RESOLVED","RESOLVER","RESOLVE");}
  snapshot(attestationInput:unknown):EscrowSnapshot{const a=parseSnapshotAttestation(attestationInput);return {schemaVersion:1,pausedNewOrders:this.pausedNewOrders,checkpointId:a.checkpointId,eventCount:this.events.length,eventSetCommitment:a.eventSetCommitment,resolverCommitment:this.resolverCommitment,issuedAt:a.issuedAt,expiresAt:a.expiresAt,issuerKeyId:a.issuerKeyId,signature:a.signature,events:this.events.map(e=>({...e}))};}
  static restore(snapshotInput:unknown,expectedCheckpointId:string,listings:MarketplaceListingRegistry,profiles:ListingProfileBoundary,resolverCommitment:string,eventVerifier:EscrowEventVerifier,snapshotVerifier:EscrowSnapshotVerifier,nowInput:unknown):MarketplaceEscrowLedger {
    const s=plain(snapshotInput,SNAPSHOT_KEYS,"ESCROW_SNAPSHOT_INVALID"); if(s.schemaVersion!==1||typeof s.pausedNewOrders!=="boolean"||!Array.isArray(s.events)) fail("ESCROW_SNAPSHOT_INVALID");
    const snapshot:EscrowSnapshot={schemaVersion:1,pausedNewOrders:s.pausedNewOrders,checkpointId:text(s.checkpointId,ID,"ESCROW_SNAPSHOT_INVALID"),eventCount:integer(s.eventCount,0,Number.MAX_SAFE_INTEGER,"ESCROW_SNAPSHOT_INVALID"),eventSetCommitment:text(s.eventSetCommitment,HASH,"ESCROW_SNAPSHOT_INVALID"),resolverCommitment:text(s.resolverCommitment,HASH,"ESCROW_SNAPSHOT_INVALID"),issuedAt:iso(s.issuedAt,"ESCROW_SNAPSHOT_INVALID"),expiresAt:iso(s.expiresAt,"ESCROW_SNAPSHOT_INVALID"),issuerKeyId:text(s.issuerKeyId,ID,"ESCROW_SNAPSHOT_INVALID"),signature:text(s.signature,SIGNATURE,"ESCROW_SNAPSHOT_INVALID"),events:s.events as EscrowEvent[]};
    const now=iso(nowInput,"ESCROW_TIME_INVALID"); if(snapshot.checkpointId!==text(expectedCheckpointId,ID,"ESCROW_CHECKPOINT_INVALID")||snapshot.resolverCommitment!==resolverCommitment||snapshot.eventCount!==snapshot.events.length||Date.parse(snapshot.issuedAt)>Date.parse(now)||Date.parse(snapshot.expiresAt)<=Date.parse(now)||!snapshotVerifier.verify(snapshot)) fail("ESCROW_CHECKPOINT_INVALID");
    const ledger=new MarketplaceEscrowLedger(listings,profiles,resolverCommitment); for(const raw of snapshot.events){ const e=parseEvent(raw); if(!eventVerifier.verify(e)||e.eventOrdinal!==ledger.events.length+1||ledger.usedActions.has(e.actionId)) fail("ESCROW_SNAPSHOT_INVALID"); const existing=ledger.orders.get(e.escrowId); ledger.validateReplayedEvent(existing,e); ledger.assertProjectionConservation(e); ledger.orders.set(e.escrowId,Object.freeze({...e}));ledger.events.push(Object.freeze({...e}));ledger.usedActions.add(e.actionId); } ledger.pausedNewOrders=snapshot.pausedNewOrders; return ledger;
  }
  private transition(input:unknown,verifier:SignedVerifier<EscrowActionCommand>,nowInput:unknown,from:EscrowState[],to:EscrowState,role:"BUYER"|"SELLER"|"PARTY"|"RESOLVER",action:EscrowEvent["action"]):Readonly<EscrowProjection>{ const c=parseEscrowAction(input),now=iso(nowInput,"ESCROW_TIME_INVALID"); if(!verifier.verify(c)) fail("ESCROW_ACTION_SIGNATURE_INVALID"); if(this.usedActions.has(c.actionId)) fail("ESCROW_REPLAY"); const p=this.orders.get(c.escrowId); if(!p||p.stateVersion!==c.expectedVersion||!from.includes(p.state)) fail("ESCROW_TRANSITION_INVALID"); if(Date.parse(c.occurredAt)>Date.parse(now)||Date.parse(c.occurredAt)<Date.parse(p.updatedAt)) fail("ESCROW_TIME_INVALID"); if(action==="ACCEPT"&&Date.parse(now)>Date.parse(p.acceptBy)) fail("ESCROW_ACCEPT_DEADLINE_EXPIRED"); if(action==="FULFIL"&&Date.parse(now)>Date.parse(p.fulfilBy)) fail("ESCROW_FULFIL_DEADLINE_EXPIRED"); if(action==="DISPUTE"&&Date.parse(now)>Date.parse(p.autoReleaseAt)) fail("ESCROW_DISPUTE_DEADLINE_EXPIRED"); const expected=role==="BUYER"?p.buyerProfileCommitment:role==="SELLER"?p.sellerProfileCommitment:role==="RESOLVER"?this.resolverCommitment:null; if(expected?c.actorProfileCommitment!==expected:![p.buyerProfileCommitment,p.sellerProfileCommitment].includes(c.actorProfileCommitment)) fail("ESCROW_ACTOR_DENIED"); if(action!=="RESOLVE"&&(c.outcomeBuyerBps!==0||c.outcomeSellerBps!==0)) fail("ESCROW_OUTCOME_INVALID"); if(action==="RESOLVE"&&c.outcomeBuyerBps+c.outcomeSellerBps!==10000) fail("ESCROW_OUTCOME_INVALID"); let buyer=0n,seller=0n,platform=0n,total=BigInt(p.totalAtomic),principal=BigInt(p.principalAtomic),fee=BigInt(p.platformFeeAtomic); if(to==="REFUNDED"){buyer=total;} else if(to==="RELEASED"){seller=principal;platform=fee;} else if(to==="RESOLVED"){const distributable=total-fee; buyer=distributable*BigInt(c.outcomeBuyerBps)/10000n; seller=distributable-buyer; platform=fee;} const next:EscrowProjection={...p,state:to,stateVersion:p.stateVersion+1,buyerCreditAtomic:buyer.toString(),sellerCreditAtomic:seller.toString(),platformCreditAtomic:platform.toString(),updatedAt:c.occurredAt}; this.assertProjectionConservation(next); this.record(next,c.actionId,action,c.actorProfileCommitment,c.evidenceCommitment,c.signature); return {...next}; }
  private validateReplayedEvent(previous:EscrowProjection|undefined,e:EscrowEvent):void {
    if(!previous){if(e.action!=="FUND"||e.state!=="FUNDED"||e.stateVersion!==1||e.actorProfileCommitment!==e.buyerProfileCommitment||e.evidenceCommitment!==e.termsHash||this.resolverCommitment===e.buyerProfileCommitment||this.resolverCommitment===e.sellerProfileCommitment)fail("ESCROW_SNAPSHOT_INVALID");return;}
    const immutable=["listingCommitment","buyerProfileCommitment","sellerProfileCommitment","paymentKey","tokenId","principalAtomic","platformFeeAtomic","totalAtomic","termsHash","acceptBy","fulfilBy","autoReleaseAt","policyVersion","syntheticLabel"] as const;if(immutable.some(k=>previous[k]!==e[k])||e.stateVersion!==previous.stateVersion+1||Date.parse(e.updatedAt)<Date.parse(previous.updatedAt))fail("ESCROW_SNAPSHOT_INVALID");
    const valid=(e.action==="ACCEPT"&&previous.state==="FUNDED"&&e.state==="ACCEPTED"&&e.actorProfileCommitment===e.sellerProfileCommitment&&Date.parse(e.updatedAt)<=Date.parse(e.acceptBy))||(e.action==="FULFIL"&&previous.state==="ACCEPTED"&&e.state==="FULFILLED"&&e.actorProfileCommitment===e.sellerProfileCommitment&&Date.parse(e.updatedAt)<=Date.parse(e.fulfilBy))||(e.action==="BUYER_ACCEPT"&&previous.state==="FULFILLED"&&e.state==="RELEASED"&&e.actorProfileCommitment===e.buyerProfileCommitment)||(e.action==="REFUND"&&previous.state==="FUNDED"&&e.state==="REFUNDED"&&e.actorProfileCommitment===e.buyerProfileCommitment)||(e.action==="DISPUTE"&&["ACCEPTED","FULFILLED"].includes(previous.state)&&e.state==="DISPUTED"&&[e.buyerProfileCommitment,e.sellerProfileCommitment].includes(e.actorProfileCommitment)&&Date.parse(e.updatedAt)<=Date.parse(e.autoReleaseAt))||(e.action==="RESOLVE"&&previous.state==="DISPUTED"&&e.state==="RESOLVED"&&e.actorProfileCommitment===this.resolverCommitment);if(!valid)fail("ESCROW_SNAPSHOT_INVALID");
  }
  private assertProjectionConservation(p:EscrowProjection):void { const credits=BigInt(p.buyerCreditAtomic)+BigInt(p.sellerCreditAtomic)+BigInt(p.platformCreditAtomic); const terminal=["RELEASED","REFUNDED","RESOLVED"].includes(p.state); if((terminal&&credits!==BigInt(p.totalAtomic))||(!terminal&&credits!==0n)) fail("ESCROW_CONSERVATION_INVALID"); }
  private record(p:EscrowProjection,actionId:string,action:EscrowEvent["action"],actor:string,evidence:string,signature:string):void { const e:EscrowEvent={...p,eventOrdinal:this.events.length+1,actionId,action,actorProfileCommitment:actor,evidenceCommitment:evidence,signature}; this.assertProjectionConservation(e); this.orders.set(p.escrowId,Object.freeze({...p})); this.usedActions.add(actionId); this.events.push(Object.freeze(e)); }
}
