[CmdletBinding()]
param(
    [string]$RunId = ('NX-SOCIAL-P01-' + [DateTimeOffset]::UtcNow.ToString('yyyyMMddTHHmmssfffZ') + '-' + [Guid]::NewGuid().ToString('N').Substring(0, 8)),
    [ValidateSet('UNSPECIFIED', 'A32', 'C01', 'C04', 'C06', 'C08')][string]$ExecutorRole = 'UNSPECIFIED'
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$timer = [Diagnostics.Stopwatch]::StartNew(); $failures = [Collections.Generic.List[string]]::new(); $assertions = 0
function Assert-Social { param([bool]$Condition, [string]$Message) $script:assertions++; if (-not $Condition) { $script:failures.Add($Message) } }
function Read-Utf8 { param([string]$Path) [IO.File]::ReadAllText($Path, [Text.Encoding]::UTF8) }
function Get-Sha256 { param([string]$Path) (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant() }
function Get-StringSha256 { param([string]$Value) $sha = [Security.Cryptography.SHA256]::Create(); try { ([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Value)))).Replace('-', '').ToLowerInvariant() } finally { $sha.Dispose() } }
function Get-IncludedNodeRuntime { $root = Join-Path ([Environment]::GetFolderPath('LocalApplicationData')) 'OpenAI\Codex\bin'; if (-not (Test-Path -LiteralPath $root)) { return $null }; Get-ChildItem -LiteralPath $root -Filter node.exe -File -Recurse -ErrorAction SilentlyContinue | Sort-Object FullName | Select-Object -Last 1 -ExpandProperty FullName }
function Invoke-LocalNode { param([string]$Node, [string[]]$Arguments, [string]$WorkingDirectory) $quoted = @($Arguments | ForEach-Object { '"' + $_.Replace('"', '\"') + '"' }) -join ' '; $info = [Diagnostics.ProcessStartInfo]::new(); $info.FileName = $Node; $info.Arguments = $quoted; $info.WorkingDirectory = $WorkingDirectory; $info.UseShellExecute = $false; $info.CreateNoWindow = $true; $info.RedirectStandardOutput = $true; $info.RedirectStandardError = $true; $process = [Diagnostics.Process]::new(); $process.StartInfo = $info; try { if (-not $process.Start()) { throw 'Node process did not start.' }; $stdout = $process.StandardOutput.ReadToEnd(); $stderr = $process.StandardError.ReadToEnd(); if (-not $process.WaitForExit(30000)) { $process.Kill(); throw 'Node process exceeded 30 seconds.' }; [ordered]@{ exit_code = $process.ExitCode; stdout = $stdout.Trim(); stderr = $stderr.Trim(); cpu_seconds = [math]::Round($process.TotalProcessorTime.TotalSeconds, 4) } } finally { $process.Dispose() } }

$repoRoot = Split-Path -Parent $PSScriptRoot
$paths = [ordered]@{
  source = Join-Path $repoRoot 'packages\social\api\index.ts'
  tests = Join-Path $repoRoot 'packages\social\api\index.test.ts'
  contract = Join-Path $repoRoot 'packages\social\api\social-contract.v1.json'
  media = Join-Path $repoRoot 'packages\media\api\index.ts'
  chain_actions = Join-Path $repoRoot 'packages\chain-actions-api\index.ts'
  chain_reducer = Join-Path $repoRoot 'packages\chain-adapter\api\index.ts'
  action_doc = Join-Path $repoRoot 'docs\09-action-ledger-classifieds.md'
  clips_doc = Join-Path $repoRoot 'docs\15-recommendations-clips-watch-live-kids.md'
  architecture = Join-Path $repoRoot 'architecture\bounded-contexts.yaml'
  backlog_p0 = Join-Path $PSScriptRoot 'backlog-p0.yaml'
  backlog_p1 = Join-Path $PSScriptRoot 'backlog-p1.yaml'
  capacity = Join-Path $PSScriptRoot 'capacity-scorecard.yaml'
  progress = Join-Path $PSScriptRoot 'product-progress.yaml'
  checkpoint = Join-Path $PSScriptRoot 'checkpoints\NX-SOCIAL-P01.md'
  spend = Join-Path $PSScriptRoot 'spend-control.yaml'
  media_evidence = Join-Path $PSScriptRoot 'evidence\NX-MEDIA-001-validation.json'
  moderation_evidence = Join-Path $PSScriptRoot 'evidence\NX-MOD-P01-validation.json'
  chain_evidence = Join-Path $PSScriptRoot 'evidence\NX-CHAIN-002-validation.json'
  boundary_checker = Join-Path $repoRoot 'security\source-boundary-check.js'
  tsc = Join-Path $repoRoot 'packages\contracts\node_modules\typescript\bin\tsc'
  package_lock = Join-Path $repoRoot 'packages\contracts\package-lock.json'
  validator = $PSCommandPath
}
foreach ($path in $paths.Values) { Assert-Social (Test-Path -LiteralPath $path -PathType Leaf) "Missing artifact: $path" }
Assert-Social ($RunId -match '^NX-SOCIAL-P01-[A-Za-z0-9T._-]+$') 'Run ID format is invalid.'; Assert-Social ($ExecutorRole -ne 'UNSPECIFIED') 'ExecutorRole must be explicit.'
$source = Read-Utf8 $paths.source; $tests = Read-Utf8 $paths.tests; $contract = Read-Utf8 $paths.contract | ConvertFrom-Json; $actionDoc = Read-Utf8 $paths.action_doc; $clipsDoc = Read-Utf8 $paths.clips_doc; $architecture = Read-Utf8 $paths.architecture; $backlogP0 = Read-Utf8 $paths.backlog_p0; $backlogP1 = Read-Utf8 $paths.backlog_p1; $capacity = Read-Utf8 $paths.capacity; $progress = Read-Utf8 $paths.progress; $checkpoint = Read-Utf8 $paths.checkpoint; $spend = Read-Utf8 $paths.spend; $mediaEvidence = Read-Utf8 $paths.media_evidence | ConvertFrom-Json; $moderationEvidence = Read-Utf8 $paths.moderation_evidence | ConvertFrom-Json; $chainEvidence = Read-Utf8 $paths.chain_evidence | ConvertFrom-Json

$task = [regex]::Match($backlogP1, '(?ms)^  - task_id:\s*NX-SOCIAL-P01\s*\r?\n(.*?)(?=^  - task_id:|\z)'); Assert-Social $task.Success 'NX-SOCIAL-P01 missing.'
if ($task.Success) { Assert-Social ($task.Groups[1].Value -match '(?m)^\s+record_kind:\s*task_packet\s*$') 'Not a task packet.'; Assert-Social ($task.Groups[1].Value -match '(?m)^\s+owner_agent:\s*A32\s*$') 'Owner is not A32.'; Assert-Social ($task.Groups[1].Value -match '(?m)^\s+status:\s*(in_progress|review)\s*$') 'Packet is not active.'; Assert-Social ($task.Groups[1].Value -match '(?m)^\s+risk_class:\s*T1\s*$') 'Packet is not T1.' }
foreach ($dependency in @('NX-MEDIA-001', 'NX-CHAIN-001', 'NX-CHAIN-002', 'NX-OBS-001')) { $record = [regex]::Match($backlogP0, ('(?ms)^  - task_id:\s*' + [regex]::Escape($dependency) + '\s*\r?\n(.*?)(?=^  - task_id:|\z)')); Assert-Social ($record.Success -and $record.Groups[1].Value -match '(?m)^\s+status:\s*done\s*$') "P0 dependency not done: $dependency" }
foreach ($dependency in @('NX-PROFILE-P01', 'NX-MOD-P01')) { $record = [regex]::Match($backlogP1, ('(?ms)^  - task_id:\s*' + [regex]::Escape($dependency) + '\s*\r?\n(.*?)(?=^  - task_id:|\z)')); Assert-Social ($record.Success -and $record.Groups[1].Value -match '(?m)^\s+status:\s*done\s*$') "P1 dependency not done: $dependency" }
$activePackets = @([regex]::Matches($backlogP1, '(?ms)^  - task_id:\s*(\S+)\s*\r?\n(.*?)(?=^  - task_id:|\z)') | Where-Object { $_.Groups[2].Value -match '(?m)^\s+record_kind:\s*task_packet\s*$' -and $_.Groups[2].Value -match '(?m)^\s+status:\s*(in_progress|review)\s*$' } | ForEach-Object { $_.Groups[1].Value }); Assert-Social ($activePackets.Count -eq 1 -and $activePackets[0] -eq 'NX-SOCIAL-P01') 'WIP one violated.'
Assert-Social ($capacity -match '(?m)^\s+active_task_id:\s+NX-SOCIAL-P01\s*$' -and $capacity -match '(?m)^\s+active_packets:\s+1\s*$') 'Capacity mismatch.'; Assert-Social ($progress -match '(?m)^\s+active_packet_id:\s+NX-SOCIAL-P01\s*$') 'Progress mismatch.'; Assert-Social ($checkpoint -match '(?m)^- Stare:\s*`(in_progress|review)`\s*$') 'Checkpoint mismatch.'
Assert-Social ($architecture -match '(?ms)^  - id:\s*social\s*\r?\n.*?^\s+owner:\s*A32\s*$' -and $architecture -match '(?ms)^  - id:\s*social\s*\r?\n.*?^\s+public_api_path:\s*packages/social/api\s*$') 'Social architecture boundary missing.'
Assert-Social ($contract.schemaVersion -eq 1 -and $contract.owner -eq 'A32' -and $contract.surface -eq 'CLIPS' -and [int]$contract.durationSeconds.minimum -eq 3 -and [int]$contract.durationSeconds.maximum -eq 180) 'Contract identity or duration drifted.'
Assert-Social ([bool]$contract.labels.syntheticRequiredInPacket -and [bool]$contract.labels.paidPromotionDisclosureRequired -and [bool]$contract.labels.organicMetricsExcludedForSyntheticOrPaid -and -not [bool]$contract.kidsEligible -and $contract.engagement.likeAction -eq 'distinct_PUBLIC_ACTION' -and [bool]$contract.engagement.signedDecisionRequired -and [bool]$contract.engagement.signedExecutionAuthorizationRequired -and [bool]$contract.engagement.exactEnvelopeAndChainDomainBinding -and [bool]$contract.engagement.oneTimeAtomicConsumption -and [bool]$contract.engagement.postSignatureStateVersionCas -and [bool]$contract.engagement.postSignaturePolicyVersionCas -and [bool]$contract.engagement.preparedActionAbortOnConflict -and [bool]$contract.engagement.activeViewerProfileRequired -and [bool]$contract.engagement.blockAudienceDeviceChecked -and [bool]$contract.purge.verifiedMediaPurgeRequired) 'Contract policy drifted.'
foreach ($fragment in @('| Social | post/edit/tombstone, like/unlike', 'actor_kind=HUMAN|AGENT|SYSTEM_TEST', 'EPHEMERAL_EXCLUDED')) { Assert-Social ($actionDoc.Contains($fragment)) "Action spec missing: $fragment" }
foreach ($fragment in @('TikTok-like', '180 secunde', 'organic vs paid/agent/synthetic separation', 'Kids nu are behavioral ads', 'like/unlike, comment/reply')) { Assert-Social ($clipsDoc.Contains($fragment)) "Clips spec missing: $fragment" }
foreach ($fragment in @('SocialClipRegistry', 'ClipEligibilityDecision', 'ClipEngagementDecision', 'LikeExecutionAuthorization', 'LikeActionRecorder', 'ClipProfileBoundary', 'ClipEngagementPolicyBoundary', 'policyVersion', 'abortPreparedAction', 'executeLike', 'LIKE_ENVELOPE_BINDING_MISMATCH', 'LIKE_AUTHORIZATION_REPLAY', 'CLIP_EXECUTION_STATE_CONFLICT', 'CLIP_PROMOTION_DISCLOSURE_REQUIRED', 'organicMetricEligible: false', 'kidsEligible: false', 'CLIP_PURGE_UNVERIFIED')) { Assert-Social ($source.Contains($fragment)) "Source control missing: $fragment" }
foreach ($fragment in @('synthetic media upload is authorized', 'playable synthetic clip is labelled', 'profile race after async signature creates no action', 'policy race after async signature creates no action', 'PREPARED_ACTION_INVALID', 'one distinct like records', 'like reaches terminal state', 'four-target media purge', 'target_substitution', 'authorization_then_purge', 'playback_after_purge')) { Assert-Social ($tests.Contains($fragment)) "Test control missing: $fragment" }
Assert-Social ($source -notmatch '(?i)(fetch\s*\(|XMLHttpRequest|HttpClient|WebClient|Invoke-WebRequest|https?\.request|child_process|net\.connect|dgram\.|console\.log)') 'Social runtime can perform network/process/log operations.'
Assert-Social ($mediaEvidence.status -eq 'PASS' -and $moderationEvidence.status -eq 'PASS' -and $chainEvidence.status -eq 'PASS') 'Dependency evidence incomplete.'; Assert-Social ($spend -match '(?m)^mode:\s*default_deny_spend\s*$' -and $spend -match '(?m)^\s*max_incremental_amount:\s*0\s*$') 'Spend guard missing.'
$credentialPattern = '^(AWS_|AZURE_|GOOGLE_APPLICATION_CREDENTIALS$|OPENAI_API_KEY$|TWILIO_|MAPBOX_|CLOUDFLARE_|STRIPE_|PINATA_|IPFS_|MATRIX_|XMONEY_)'; $credentialNames = @([Environment]::GetEnvironmentVariables().Keys | ForEach-Object { [string]$_ } | Where-Object { $_ -match $credentialPattern }); Assert-Social ($credentialNames.Count -eq 0) 'Production/billing credential names present.'

$node = Get-IncludedNodeRuntime; Assert-Social ($null -ne $node) 'Included Node missing.'; $ephemeralRoot = Join-Path $repoRoot '.ephemeral'; [IO.Directory]::CreateDirectory($ephemeralRoot) | Out-Null; $runRoot = Join-Path $ephemeralRoot ('NX-SOCIAL-P01-validator-' + [Guid]::NewGuid().ToString('N')); [IO.Directory]::CreateDirectory($runRoot) | Out-Null; $compile = $null; $testRuns = @(); $testReceipt = $null; $boundary = $null
try { if ($null -ne $node) { $compile = Invoke-LocalNode $node @($paths.tsc, '--strict', '--target', 'ES2022', '--module', 'commonjs', '--lib', 'ES2022,DOM', '--outDir', $runRoot, $paths.source, $paths.tests, $paths.media, $paths.chain_actions, $paths.chain_reducer) $repoRoot; Assert-Social ($compile.exit_code -eq 0) "Strict TypeScript compilation failed: $($compile.stderr)"; if ($compile.exit_code -eq 0) { $testPath = Join-Path $runRoot 'social\api\index.test.js'; 1..3 | ForEach-Object { $script:testRuns += Invoke-LocalNode $node @($testPath) $repoRoot }; foreach ($run in $testRuns) { Assert-Social ($run.exit_code -eq 0) "Social tests failed: $($run.stderr)" }; Assert-Social (@($testRuns.stdout | Sort-Object -Unique).Count -eq 1) 'Non-deterministic receipts.'; try { $testReceipt = $testRuns[0].stdout | ConvertFrom-Json } catch { Assert-Social $false 'Receipt is not JSON.' } }; $manifest = [pscustomobject]@{ knownSpecifiers = [pscustomobject]@{ '@nexus/profile' = 'profile_core'; '@nexus/moderation' = 'moderation'; '@nexus/media' = 'media'; '@nexus/recommendations' = 'recommendations'; '@nexus/chain' = 'chain_integration'; '@nexus/contracts' = 'contract_registry' }; knownSchemas = @('social', 'profile_core', 'moderation', 'media', 'recommendations', 'chain_integration', 'contract_registry'); contexts = [pscustomobject]@{ social = [pscustomobject]@{ allowedImports = @('profile_core', 'moderation', 'media', 'recommendations', 'chain_integration', 'contract_registry') } }; items = @([pscustomobject]@{ id = 'packages/social/api/index.ts'; sourceContext = 'social'; text = $source }) }; $manifestPath = Join-Path $runRoot 'boundary.json'; [IO.File]::WriteAllText($manifestPath, ($manifest | ConvertTo-Json -Depth 8), [Text.UTF8Encoding]::new($false)); $boundaryRun = Invoke-LocalNode $node @($paths.boundary_checker, $manifestPath) $repoRoot; Assert-Social ($boundaryRun.exit_code -eq 0) "Boundary checker failed: $($boundaryRun.stderr)"; if ($boundaryRun.exit_code -eq 0) { $boundary = $boundaryRun.stdout | ConvertFrom-Json } } } finally { $rootPrefix = [IO.Path]::GetFullPath($ephemeralRoot).TrimEnd('\') + '\'; $resolved = [IO.Path]::GetFullPath($runRoot); if ((Test-Path -LiteralPath $runRoot) -and $resolved.StartsWith($rootPrefix, [StringComparison]::OrdinalIgnoreCase)) { Remove-Item -LiteralPath $runRoot -Recurse -Force } }
Assert-Social ($null -ne $testReceipt) 'Test receipt missing.'
if ($null -ne $testReceipt) { Assert-Social ($testReceipt.task_id -eq 'NX-SOCIAL-P01' -and $testReceipt.status -eq 'PASS' -and [int]$testReceipt.assertions -ge 34) 'Scenario receipt regressed.'; Assert-Social ([bool]$testReceipt.media.authorized -and [bool]$testReceipt.media.moderated -and [bool]$testReceipt.media.playable -and [bool]$testReceipt.media.purged -and [int]$testReceipt.media.purge_targets -eq 4) 'Media lifecycle failed.'; Assert-Social ([bool]$testReceipt.labels.synthetic -and -not [bool]$testReceipt.labels.organic_metric_eligible -and -not [bool]$testReceipt.labels.kids_eligible) 'Synthetic/Kids labels failed.'; Assert-Social ($testReceipt.action.type -eq 'LIKE' -and [bool]$testReceipt.action.distinct_transaction -and [bool]$testReceipt.action.exact_authorization_binding -and [bool]$testReceipt.action.authorization_one_time -and [bool]$testReceipt.action.async_state_cas -and [bool]$testReceipt.action.policy_version_cas -and [bool]$testReceipt.action.prepared_abort -and [bool]$testReceipt.action.terminal -and [bool]$testReceipt.action.reconciled -and [int]$testReceipt.action.viewer_profile_generation -eq 9) 'Like action lifecycle failed.'; foreach ($property in @('exact_shape', 'forged_signature', 'creator_profile_generation_substitution', 'viewer_profile_generation_substitution', 'moderation_pending', 'promotion_undeclared', 'boolean_string', 'engagement_blocked', 'engagement_boolean_string', 'target_substitution', 'async_profile_race', 'async_policy_race', 'retained_prepared_commit', 'authorization_replay', 'publish_replay', 'action_replay', 'authorization_then_purge', 'engage_during_purge', 'playback_after_purge', 'purge_replay')) { Assert-Social ([bool]$testReceipt.negative.$property) "Negative failed: $property" }; Assert-Social ([int]$testReceipt.network_operations -eq 0 -and [int]$testReceipt.provider_operations -eq 0 -and [int]$testReceipt.economic_operations -eq 0 -and [decimal]$testReceipt.incremental_cost.amount -eq 0) 'Tests escaped zero-effect mode.' }
$boundaryFindings = @(); if ($null -ne $boundary) { foreach ($item in @($boundary.results)) { foreach ($finding in @($item.findings)) { $boundaryFindings += "$($item.id):$finding" } } }; Assert-Social ($null -ne $boundary -and $boundaryFindings.Count -eq 0) ('Boundary findings: ' + ($boundaryFindings -join ','))
$artifactHashes = [ordered]@{}; foreach ($path in $paths.Values) { if (Test-Path -LiteralPath $path -PathType Leaf) { $relative = $path.Substring($repoRoot.Length).TrimStart('\').Replace('\', '/'); $artifactHashes[$relative] = Get-Sha256 $path } }; $subject = Get-StringSha256 (($artifactHashes.GetEnumerator() | Sort-Object Key | ForEach-Object { "$($_.Key)=$($_.Value)" }) -join "`n"); $timer.Stop()
$result = [ordered]@{ schema_version = 1; task_id = 'NX-SOCIAL-P01'; run_id = $RunId; executor_role = $ExecutorRole; status = if ($failures.Count -eq 0) { 'PASS' } else { 'FAIL' }; scope = 'local_moderated_synthetic_clip_like_terminal_reducer_and_purge_proof'; assertions = $assertions; scenario_assertions = if ($null -ne $testReceipt) { [int]$testReceipt.assertions } else { 0 }; deterministic_repetitions = @($testRuns).Count; failures = @($failures); media = if ($null -ne $testReceipt) { $testReceipt.media } else { $null }; labels = if ($null -ne $testReceipt) { $testReceipt.labels } else { $null }; action = if ($null -ne $testReceipt) { $testReceipt.action } else { $null }; source_boundary_findings = $boundaryFindings.Count; credential_name_matches = $credentialNames.Count; network_operations = 0; economic_operations = 0; external_provider_operations = 0; incremental_cost = [ordered]@{ amount = 0; currency = 'EUR' }; claims_excluded = @('real_upload', 'managed_storage', 'managed_transcode', 'public_cdn', 'external_moderation', 'real_user_metrics', 'production_ranking', 'kids_surface', 'mainnet_transaction', 'formal_security_audit'); review_subject_sha256 = $subject; artifact_sha256 = $artifactHashes; duration_seconds = [math]::Round($timer.Elapsed.TotalSeconds, 4) }
$result | ConvertTo-Json -Depth 12; if ($failures.Count -gt 0) { exit 1 }
