[CmdletBinding()]
param(
  [string]$RunId = ('NX-EXPERIENCE-P01-' + [DateTimeOffset]::UtcNow.ToString('yyyyMMddTHHmmssfffZ') + '-' + [Guid]::NewGuid().ToString('N').Substring(0,8)),
  [ValidateSet('UNSPECIFIED','A42','C02','C04','C06','C08','C10')][string]$ExecutorRole = 'UNSPECIFIED'
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$timer = [Diagnostics.Stopwatch]::StartNew(); $failures = [Collections.Generic.List[string]]::new(); $assertions = 0
function Assert-Experience([bool]$Condition,[string]$Message) { $script:assertions++; if (-not $Condition) { $script:failures.Add($Message) } }
function Read-Utf8([string]$Path) { [IO.File]::ReadAllText($Path,[Text.Encoding]::UTF8) }
function Get-Sha([string]$Path) { (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant() }
function Get-TextSha([string]$Value) { $sha=[Security.Cryptography.SHA256]::Create(); try { ([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Value)))).Replace('-','').ToLowerInvariant() } finally { $sha.Dispose() } }
function Get-NodeRuntime { $runtimeRoot=Join-Path ([Environment]::GetFolderPath('LocalApplicationData')) 'OpenAI\Codex\bin'; if(Test-Path -LiteralPath $runtimeRoot){ Get-ChildItem -LiteralPath $runtimeRoot -Filter node.exe -File -Recurse | Sort-Object FullName | Select-Object -Last 1 -ExpandProperty FullName } }
function Invoke-Node([string]$Node,[string[]]$Arguments,[string]$WorkingDirectory) { $quoted=@($Arguments|ForEach-Object{'"'+$_.Replace('"','\"')+'"'}) -join ' '; $info=[Diagnostics.ProcessStartInfo]::new(); $info.FileName=$Node; $info.Arguments=$quoted; $info.WorkingDirectory=$WorkingDirectory; $info.UseShellExecute=$false; $info.CreateNoWindow=$true; $info.RedirectStandardOutput=$true; $info.RedirectStandardError=$true; $process=[Diagnostics.Process]::new(); $process.StartInfo=$info; try { if(-not $process.Start()){throw 'node start failed'}; $stdout=$process.StandardOutput.ReadToEnd(); $stderr=$process.StandardError.ReadToEnd(); if(-not $process.WaitForExit(30000)){$process.Kill();throw 'node timeout'}; [ordered]@{exit_code=$process.ExitCode;stdout=$stdout.Trim();stderr=$stderr.Trim();cpu_seconds=[math]::Round($process.TotalProcessorTime.TotalSeconds,4)} } finally {$process.Dispose()} }

$root=Split-Path -Parent $PSScriptRoot
$paths=[ordered]@{
  source=Join-Path $root 'packages\experience\api\index.ts'
  tests=Join-Path $root 'packages\experience\api\index.test.ts'
  contract=Join-Path $root 'packages\experience\api\experience-contract.v1.json'
  experience_doc=Join-Path $root 'docs\21-cross-mode-content-communication-identity.md'
  identity_doc=Join-Path $root 'docs\13-global-auth-agent-network.md'
  dating_doc=Join-Path $root 'docs\14-dating-pulse-discretion-trust.md'
  clips_doc=Join-Path $root 'docs\15-recommendations-clips-watch-live-kids.md'
  engagement_doc=Join-Path $root 'docs\20-engagement-integrity-viral-ranking.md'
  architecture=Join-Path $root 'architecture\bounded-contexts.yaml'
  backlog0=Join-Path $PSScriptRoot 'backlog-p0.yaml'
  backlog1=Join-Path $PSScriptRoot 'backlog-p1.yaml'
  capacity=Join-Path $PSScriptRoot 'capacity-scorecard.yaml'
  progress=Join-Path $PSScriptRoot 'product-progress.yaml'
  checkpoint=Join-Path $PSScriptRoot 'checkpoints\NX-EXPERIENCE-P01.md'
  spend=Join-Path $PSScriptRoot 'spend-control.yaml'
  engage_evidence=Join-Path $PSScriptRoot 'evidence\NX-ENGAGE-P01-validation.json'
  chat_evidence=Join-Path $PSScriptRoot 'evidence\NX-CHAT-P01-validation.json'
  media_evidence=Join-Path $PSScriptRoot 'evidence\NX-MEDIA-001-validation.json'
  profile_evidence=Join-Path $PSScriptRoot 'evidence\NX-PROFILE-P01-validation.json'
  trust_evidence=Join-Path $PSScriptRoot 'evidence\NX-TRUST-P01-validation.json'
  boundary_checker=Join-Path $root 'security\source-boundary-check.js'
  tsc=Join-Path $root 'packages\contracts\node_modules\typescript\bin\tsc'
  lock=Join-Path $root 'packages\contracts\package-lock.json'
  validator=$PSCommandPath
}
foreach($path in $paths.Values){Assert-Experience (Test-Path -LiteralPath $path -PathType Leaf) "Missing artifact: $path"}
Assert-Experience ($RunId -match '^NX-EXPERIENCE-P01-[A-Za-z0-9T._-]+$') 'Run id invalid'; Assert-Experience ($ExecutorRole -ne 'UNSPECIFIED') 'Executor role required'
$source=Read-Utf8 $paths.source; $tests=Read-Utf8 $paths.tests; $contract=Read-Utf8 $paths.contract|ConvertFrom-Json; $doc=Read-Utf8 $paths.experience_doc; $b0=Read-Utf8 $paths.backlog0; $b1=Read-Utf8 $paths.backlog1; $capacity=Read-Utf8 $paths.capacity; $progress=Read-Utf8 $paths.progress; $checkpoint=Read-Utf8 $paths.checkpoint; $spend=Read-Utf8 $paths.spend; $architecture=Read-Utf8 $paths.architecture
$task=[regex]::Match($b1,'(?ms)^  - task_id:\s*NX-EXPERIENCE-P01\s*\r?\n(.*?)(?=^  - task_id:|\z)'); Assert-Experience $task.Success 'Packet missing'
if($task.Success){Assert-Experience ($task.Groups[1].Value -match '(?m)^\s+record_kind:\s*task_packet\s*$') 'Record kind drift';Assert-Experience ($task.Groups[1].Value -match '(?m)^\s+owner_agent:\s*A42\s*$') 'Owner drift';Assert-Experience ($task.Groups[1].Value -match '(?m)^\s+status:\s*(in_progress|review)\s*$') 'Packet inactive';Assert-Experience ($task.Groups[1].Value -match '(?m)^\s+risk_class:\s*T0\s*$') 'Risk drift';Assert-Experience ($task.Groups[1].Value -match '(?m)^\s+control_reviewers:\s*\[C02, C04, C06, C08, C10\]\s*$') 'Review roles drift'}
foreach($dependency in @('NX-SEC-001','NX-CTRL-001')){$record=[regex]::Match($b0,('(?ms)^  - task_id:\s*'+[regex]::Escape($dependency)+'\s*\r?\n(.*?)(?=^  - task_id:|\z)'));Assert-Experience ($record.Success -and $record.Groups[1].Value -match '(?m)^\s+status:\s*done\s*$') "P0 dependency not done: $dependency"}
foreach($dependency in @('NX-ENGAGE-P01','NX-CHAT-P01','NX-PROFILE-P01','NX-TRUST-P01')){$record=[regex]::Match($b1,('(?ms)^  - task_id:\s*'+[regex]::Escape($dependency)+'\s*\r?\n(.*?)(?=^  - task_id:|\z)'));Assert-Experience ($record.Success -and $record.Groups[1].Value -match '(?m)^\s+status:\s*done\s*$') "P1 dependency not done: $dependency"}
$mediaRecord=[regex]::Match($b0,'(?ms)^  - task_id:\s*NX-MEDIA-001\s*\r?\n(.*?)(?=^  - task_id:|\z)');Assert-Experience ($mediaRecord.Success -and $mediaRecord.Groups[1].Value -match '(?m)^\s+status:\s*done\s*$') 'Media dependency not done'
$active=@([regex]::Matches($b1,'(?ms)^  - task_id:\s*(\S+)\s*\r?\n(.*?)(?=^  - task_id:|\z)')|Where-Object{$_.Groups[2].Value -match '(?m)^\s+record_kind:\s*task_packet\s*$' -and $_.Groups[2].Value -match '(?m)^\s+status:\s*(in_progress|review)\s*$'}|ForEach-Object{$_.Groups[1].Value});Assert-Experience ($active.Count -eq 1 -and $active[0] -eq 'NX-EXPERIENCE-P01') 'WIP one violated'
Assert-Experience ($capacity -match '(?m)^\s+active_task_id:\s+NX-EXPERIENCE-P01\s*$' -and $capacity -match '(?m)^\s+active_packets:\s+1\s*$' -and $capacity -match '(?m)^\s+current_packet_status:\s+(in_progress|review)\s*$') 'Capacity mismatch';Assert-Experience ($progress -match '(?m)^\s+active_packet_id:\s+NX-EXPERIENCE-P01\s*$') 'Progress mismatch';Assert-Experience ($checkpoint -match '(?m)^- Stare:\s*`(in_progress|review)`\s*$') 'Checkpoint mismatch'
Assert-Experience ($architecture -match '(?ms)^  - id:\s*experience\s*\r?\n.*?^\s+owner:\s*A42\s*$' -and $architecture -match '(?ms)^  - id:\s*experience\s*\r?\n.*?^\s+public_api_path:\s*packages/experience/api\s*$') 'Experience boundary missing'
Assert-Experience ($contract.schemaVersion -eq 1 -and $contract.contractVersion -eq '1.0.0' -and $contract.owner -eq 'A42' -and $contract.mode -eq 'LOCAL_DETERMINISTIC_SYSTEM_TEST') 'Contract identity drift'
Assert-Experience (@($contract.story.durationOptions).Count -eq 6 -and [bool]$contract.story.untilRemovedProjectsAsHighlight -and [bool]$contract.story.audienceSafetyRightsAndPurgeAlwaysOverrideDuration -and [bool]$contract.story.enforcementReceiptBindsRuleReasonTerritoryDurationAndAppeal -and -not [bool]$contract.story.datingSaveOrExportDefault) 'Story policy drift'
Assert-Experience (@($contract.pulse.formats).Count -eq 8 -and [bool]$contract.pulse.sourceProvenanceRequired -and [bool]$contract.pulse.materialEditCreatesGeneration -and [bool]$contract.pulse.withdrawCreatesTombstone -and -not [bool]$contract.pulse.creatorMayEraseForeignReply) 'Pulse policy drift'
Assert-Experience ([bool]$contract.saveAndDownload.profileScopedCollections -and [bool]$contract.saveAndDownload.offlineCacheEncryptedAndExpiring -and [bool]$contract.saveAndDownload.downloadRequiresAuthorAudienceRightsAndLicense -and [bool]$contract.saveAndDownload.signedAudienceAndRightsReceiptsRequired -and [bool]$contract.saveAndDownload.offlineGrantBindsProfileDeviceContentKeyEpochAndExpiry -and [bool]$contract.saveAndDownload.offlineGrantBindsLicenseRightsStateAndPurgeEpoch -and [bool]$contract.saveAndDownload.offlineAccessDeniedAfterWithdrawalPurgeExpiryOrRevocation -and [bool]$contract.saveAndDownload.generatedWatermarkReceiptRequiredBeforeExport -and [bool]$contract.saveAndDownload.watermarkAlsoBindsDeviceAndExportArtifact -and [bool]$contract.saveAndDownload.watermarkInnerContentAndDeviceMustMatchRequest -and @($contract.saveAndDownload.watermarkFields).Count -eq 4) 'Save/download drift'
Assert-Experience (@($contract.communication.messageFilters).Count -eq 8 -and @($contract.communication.callKinds).Count -eq 5 -and [bool]$contract.communication.recordingRequiresExplicitParticipantNoticeAndConsent -and [bool]$contract.communication.recordingConsentReceiptPerParticipant -and [bool]$contract.communication.datingE2EEAndSessionReceiptRequired -and [bool]$contract.communication.datingE2EEReceiptBindsCanonicalPeersDevicesSuiteAndSessionKey -and -not [bool]$contract.communication.datingContactMetadataLeakageAllowed -and -not [bool]$contract.communication.realRtcProviderInPacket) 'Communication policy drift'
Assert-Experience ([bool]$contract.discovery.globalTrendCrossRegionNormalizationRequired -and [bool]$contract.discovery.globalInterestWeightingRequired -and [bool]$contract.discovery.candidateProfileIsolationRequired -and -not [bool]$contract.discovery.duplicateCandidateCommitmentsAllowed -and [int]$contract.discovery.breakingMinIndependentSources -eq 2 -and [bool]$contract.discovery.breakingValidTrustEvidenceReceiptRequired -and [bool]$contract.discovery.breakingIndependentRegisteredSourceRootsRequired -and [int]$contract.discovery.globalSignedRegionalAggregatesMinRegions -eq 2 -and -not [bool]$contract.discovery.breakingPaidPlacementAllowed -and -not [bool]$contract.discovery.breakingPoliticalViewpointTargetingAllowed -and -not [bool]$contract.discovery.breakingInterruptsDatingCallsOrMessages -and -not [bool]$contract.discovery.datingPublicGlobalOrBreakingLensAllowed) 'Discovery policy drift'
Assert-Experience ([bool]$contract.securityReceipts.exactShapeAndDataOnlyBoundary -and [bool]$contract.securityReceipts.accessorsAndProxiesRejected -and [bool]$contract.securityReceipts.authorityRolesSeparated -and [bool]$contract.securityReceipts.revocationEnforced -and [bool]$contract.securityReceipts.concurrentIssueSingleNonceWinner -and [bool]$contract.securityReceipts.snapshotBundleSignedAndDurableCheckpointBound -and [bool]$contract.securityReceipts.restoreUsesIsolatedReceiptRegistryAndIsFailAtomic -and [bool]$contract.securityReceipts.receiptNoncePrefixOmissionDenied -and -not [bool]$contract.timeAuthority.callerProvidedDecisionTimeAllowed -and [bool]$contract.timeAuthority.injectedMonotonicClockRequired -and [bool]$contract.timeAuthority.authoritativeTimeRecheckedAfterAwaitAndBeforeCommit -and [bool]$contract.timeAuthority.receiptRevocationVersionRecheckedBeforeDecision) 'Receipt/time authority drift'
Assert-Experience (-not [bool]$contract.followerIntegrity.followerMarketplaceAllowed -and [bool]$contract.followerIntegrity.qualifiedAudienceSeparateFromRawCount -and [int]$contract.followerIntegrity.paidAgentSyntheticIncentivizedOrQuarantinedOrganicContribution -eq 0 -and -not [bool]$contract.followerIntegrity.rawFollowerCountDirectCreatorRewardAllowed) 'Follower integrity drift'
foreach($property in @('networkOperationsMax','providerOperationsMax','economicOperationsMax','organicMetricOperationsMax','realFundOperationsMax','incrementalCostEurMax')){Assert-Experience ([decimal]$contract.effects.$property -eq 0) "Effect limit escaped: $property"}
foreach($fragment in @('nodeIsProxy','assertDataTree','structuredClone','LocalMonotonicExperienceClock','LocalSecurityReceiptRegistry','REPLAY_RECEIPT_CAPABILITY','stateVersion','forkEmpty','SecurityReceipt','MediaLifecycleClaim','WatermarkClaim','EnforcementClaim','authorityRootCommitment','STORY_ENFORCEMENT_PURGE','SAFETY_RIGHTS_PURGE','PULSE_WITHDRAW','CONTENT_SOURCE','RECORDING_CONSENT','E2EE_SESSION','participantDeviceBinding','X25519_AES256_GCM','EXPERIENCE_DATING_ROOM_DENIED','OFFLINE_GRANT','WATERMARK_GENERATED','mediaLifecycle','watermark','enforcement','AGE_PROOF','WALLET_BINDING','LOCATION_CONSENT','REGIONAL_AGGREGATE','SOURCE_CONTROL','OFFICIAL_ALERT','BREAKING_SIGNED_CORROBORATED_MAJOR_IMPACT','securityReceiptsCommitment','importBundle','EXPERIENCE_DISCOVERY_DUPLICATE')){Assert-Experience ($source.Contains($fragment)) "Source control missing: $fragment"}
foreach($fragment in @('Story visibility uses the injected monotonic clock','role-separated safety or rights authority','quote and repost require signed source provenance','REVOKE-BEFORE-COMMIT','every participant signed consent','Dating call requires signed E2EE session','PEER-SUBSTITUTION','getter-backed command is rejected before accessor execution','proxy-backed follower is denied','exportBundle rejects proxy-backed commitment arrays','async caller mutation cannot change captured command','failed restore leaves destination receipt registry','snapshot expiring during verifier await','fresh restore reconstructs receipt-bound projections and receipt registry','offline cache returns a signed expiring device-bound grant','keyEpoch: 8','rightsState: "WITHDRAWN"','generated Nexus creator content code watermark receipt','creatorHandle: "other.creator"','wrongOuterWatermark','EXPERIENCE_TIME_OVERRIDE_DENIED','Dating age requires signed age receipt','payment username requires signed wallet binding','identity accessor is rejected before execution','paid synthetic and quarantined followers','Near uses signed profile-scoped coarse location','Global requires signed aggregates from at least two independent regions','Global normalization is deterministic','Breaking requires signed Trust evidence','two labels controlled by one source root','Kids receives only guardian-attested')){Assert-Experience ($tests.Contains($fragment)) "Test control missing: $fragment"}
foreach($fragment in @('**Pulse**','Until I remove it','Save in Nexus','Download to device','Nexus Meetings','| Work |','qualified audience','**Breaking**','minimum','Dating, calls')){Assert-Experience ($doc.Contains($fragment)) "Normative policy missing: $fragment"}
Assert-Experience ($source -notmatch '(?i)(fetch\s*\(|XMLHttpRequest|HttpClient|WebClient|Invoke-WebRequest|https?\.request|child_process|net\.connect|dgram\.|console\.log|process\.)') 'Runtime network/process/log capability detected'
Assert-Experience ($spend -match '(?m)^mode:\s*default_deny_spend\s*$' -and $spend -match '(?m)^\s*max_incremental_amount:\s*0\s*$') 'Spend guard drift'
foreach($name in @('engage_evidence','chat_evidence','media_evidence','profile_evidence','trust_evidence')){$evidence=Read-Utf8 $paths[$name]|ConvertFrom-Json;Assert-Experience ($evidence.status -eq 'PASS') "Dependency evidence not PASS: $name"}
$credentialPattern='^(AWS_|AZURE_|GOOGLE_APPLICATION_CREDENTIALS$|OPENAI_API_KEY$|TWILIO_|MAPBOX_|CLOUDFLARE_|STRIPE_|PINATA_|IPFS_|MATRIX_|XMONEY_)';$credentialNames=@([Environment]::GetEnvironmentVariables().Keys|ForEach-Object{[string]$_}|Where-Object{$_ -match $credentialPattern});Assert-Experience ($credentialNames.Count -eq 0) 'Production/billing credential name present'

$node=Get-NodeRuntime;Assert-Experience ($null -ne $node) 'Included Node missing';$ephemeralRoot=Join-Path $root '.ephemeral';[IO.Directory]::CreateDirectory($ephemeralRoot)|Out-Null;$runRoot=Join-Path $ephemeralRoot ('NX-EXPERIENCE-P01-'+[Guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($runRoot)|Out-Null;$runs=@();$receipt=$null;$boundary=$null
try{if($null -ne $node){$compile=Invoke-Node $node @($paths.tsc,'--strict','--target','ES2022','--module','commonjs','--lib','ES2022,DOM','--outDir',$runRoot,$paths.source,$paths.tests) $root;Assert-Experience ($compile.exit_code -eq 0) "Compile failed: $($compile.stderr)";if($compile.exit_code -eq 0){$testPath=Join-Path $runRoot 'index.test.js';1..3|ForEach-Object{$script:runs+=Invoke-Node $node @($testPath) $root};foreach($run in $runs){Assert-Experience ($run.exit_code -eq 0) "Scenario failed: $($run.stderr)"};Assert-Experience (@($runs.stdout|Sort-Object -Unique).Count -eq 1) 'Scenario output nondeterministic';try{$receipt=$runs[0].stdout|ConvertFrom-Json}catch{Assert-Experience $false 'Scenario receipt invalid'}};$manifest=[pscustomobject]@{knownSpecifiers=[pscustomobject]@{};knownSchemas=@('experience');contexts=[pscustomobject]@{experience=[pscustomobject]@{allowedImports=@()}};items=@([pscustomobject]@{id='packages/experience/api/index.ts';sourceContext='experience';text=$source})};$manifestPath=Join-Path $runRoot 'boundary.json';[IO.File]::WriteAllText($manifestPath,($manifest|ConvertTo-Json -Depth 8),[Text.UTF8Encoding]::new($false));$boundaryRun=Invoke-Node $node @($paths.boundary_checker,$manifestPath) $root;Assert-Experience ($boundaryRun.exit_code -eq 0) "Boundary failed: $($boundaryRun.stderr)";if($boundaryRun.exit_code -eq 0){$boundary=$boundaryRun.stdout|ConvertFrom-Json}}}finally{$safe=[IO.Path]::GetFullPath($ephemeralRoot).TrimEnd('\')+'\';$resolved=[IO.Path]::GetFullPath($runRoot);if((Test-Path -LiteralPath $runRoot)-and $resolved.StartsWith($safe,[StringComparison]::OrdinalIgnoreCase)){Remove-Item -LiteralPath $runRoot -Recurse -Force}}
Assert-Experience ($null -ne $receipt) 'Scenario receipt missing'
if($null -ne $receipt){Assert-Experience ($receipt.task_id -eq 'NX-EXPERIENCE-P01' -and $receipt.status -eq 'PASS' -and [int]$receipt.assertions -ge 77) 'Scenario regression';foreach($group in @('input_boundary','time','stories','pulse','communication','save_download','identity','discovery','follower_integrity','receipts')){Assert-Experience ($null -ne $receipt.$group) "Receipt group missing: $group"};Assert-Experience ([bool]$receipt.input_boundary.accessor_rejected_without_execution -and [bool]$receipt.input_boundary.proxy_rejected -and [bool]$receipt.input_boundary.public_helper_proxy_rejected_without_traps -and [bool]$receipt.input_boundary.async_mutation_captured -and [bool]$receipt.time.injected_monotonic_clock -and [bool]$receipt.time.caller_historical_override_denied -and [bool]$receipt.time.post_await_recheck -and [bool]$receipt.time.queued_authorization_expiry_denied -and [bool]$receipt.time.expired_story_promotion_denied -and [bool]$receipt.receipts.role_separated -and [bool]$receipt.receipts.revocable -and [bool]$receipt.receipts.revocation_race_denied -and [bool]$receipt.receipts.nonce_prefix_omission_denied -and [bool]$receipt.receipts.fresh_restore -and [bool]$receipt.receipts.fail_atomic_restore -and [bool]$receipt.stories.enforcement_metadata_bound -and [bool]$receipt.communication.participant_signed_recording_consent -and [bool]$receipt.communication.dating_e2ee -and [bool]$receipt.communication.dating_e2ee_peer_device_suite_key_bound -and [bool]$receipt.save_download.encrypted_expiring_device_grant -and [bool]$receipt.save_download.lifecycle_key_license_rights_purge_bound -and [bool]$receipt.save_download.generated_watermark_receipt -and [bool]$receipt.save_download.watermark_fields_device_artifact_bound -and [bool]$receipt.save_download.revocation_survives_restore -and [bool]$receipt.discovery.near_signed_coarse_consent -and [bool]$receipt.discovery.global_signed_cross_region_normalized -and [bool]$receipt.discovery.breaking_signed_trust -and [bool]$receipt.discovery.breaking_independent_source_roots_or_official -and [bool]$receipt.discovery.async_time_version_conflict_denied -and -not [bool]$receipt.discovery.paid_breaking -and -not [bool]$receipt.discovery.political_targeting -and -not [bool]$receipt.discovery.interrupts_private_surfaces -and [bool]$receipt.discovery.duplicate_candidates_denied -and [bool]$receipt.discovery.deterministic) 'Security/discovery proof failed';Assert-Experience ($receipt.actor_class -eq 'SYSTEM_TEST' -and [int]$receipt.synthetic_isolation.organic_events -eq 0 -and [int]$receipt.synthetic_isolation.rewards_accrued -eq 0 -and [int]$receipt.synthetic_isolation.reputation_delta -eq 0) 'Synthetic isolation failed';Assert-Experience ([int]$receipt.network_operations -eq 0 -and [int]$receipt.provider_operations -eq 0 -and [int]$receipt.economic_operations -eq 0 -and [int]$receipt.real_fund_operations -eq 0 -and [decimal]$receipt.incremental_cost.amount -eq 0) 'Effects escaped'}
$boundaryFindings=@();if($null -ne $boundary){foreach($item in @($boundary.results)){foreach($finding in @($item.findings)){$boundaryFindings+="$($item.id):$finding"}}};Assert-Experience ($null -ne $boundary -and $boundaryFindings.Count -eq 0) ('Boundary findings: '+($boundaryFindings -join ','))
$hashes=[ordered]@{};foreach($path in $paths.Values){if(Test-Path -LiteralPath $path -PathType Leaf){$relative=$path.Substring($root.Length).TrimStart('\').Replace('\','/');$hashes[$relative]=Get-Sha $path}};$subject=Get-TextSha (($hashes.GetEnumerator()|Sort-Object Key|ForEach-Object{"$($_.Key)=$($_.Value)"}) -join "`n");$timer.Stop()
$result=[ordered]@{schema_version=1;task_id='NX-EXPERIENCE-P01';run_id=$RunId;executor_role=$ExecutorRole;status=if($failures.Count -eq 0){'PASS'}else{'FAIL'};scope='local_cross_mode_story_pulse_identity_communication_and_discovery_proof';assertions=$assertions;scenario_assertions=if($receipt){[int]$receipt.assertions}else{0};deterministic_repetitions=@($runs).Count;failures=@($failures);stories=if($receipt){$receipt.stories}else{$null};pulse=if($receipt){$receipt.pulse}else{$null};communication=if($receipt){$receipt.communication}else{$null};save_download=if($receipt){$receipt.save_download}else{$null};identity=if($receipt){$receipt.identity}else{$null};discovery=if($receipt){$receipt.discovery}else{$null};follower_integrity=if($receipt){$receipt.follower_integrity}else{$null};receipts=if($receipt){$receipt.receipts}else{$null};synthetic_isolation=if($receipt){$receipt.synthetic_isolation}else{$null};source_boundary_findings=$boundaryFindings.Count;credential_name_matches=$credentialNames.Count;network_operations=0;external_provider_operations=0;economic_operations=0;real_fund_operations=0;incremental_cost=[ordered]@{amount=0;currency='EUR'};claims_excluded=@('production identity','real user data','real media and DRM','RTC provider','calendar provider','production persistence','production ranking metrics','external legal opinion','mainnet and real funds');review_subject_sha256=$subject;artifact_sha256=$hashes;duration_seconds=[math]::Round($timer.Elapsed.TotalSeconds,4)}
$result|ConvertTo-Json -Depth 12;if($failures.Count -gt 0){exit 1}
