[CmdletBinding()]
param(
  [string]$RunId = ('NX-ADULT-P01-' + [DateTimeOffset]::UtcNow.ToString('yyyyMMddTHHmmssfffZ') + '-' + [Guid]::NewGuid().ToString('N').Substring(0,8)),
  [ValidateSet('UNSPECIFIED','A43','C02','C04','C05','C06','C08')][string]$ExecutorRole = 'UNSPECIFIED'
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop';$timer=[Diagnostics.Stopwatch]::StartNew();$failures=[Collections.Generic.List[string]]::new();$assertions=0
function Assert-Adult([bool]$Condition,[string]$Message){$script:assertions++;if(-not$Condition){$script:failures.Add($Message)}}
function Read-Utf8([string]$Path){[IO.File]::ReadAllText($Path,[Text.Encoding]::UTF8)}
function Get-Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Get-TextSha([string]$Value){$sha=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Value)))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()}}
function Get-NodeRuntime{$runtimeRoot=Join-Path ([Environment]::GetFolderPath('LocalApplicationData')) 'OpenAI\Codex\bin';if(Test-Path -LiteralPath $runtimeRoot){Get-ChildItem -LiteralPath $runtimeRoot -Filter node.exe -File -Recurse|Sort-Object FullName|Select-Object -Last 1 -ExpandProperty FullName}}
function Invoke-Node([string]$Node,[string[]]$Arguments,[string]$WorkingDirectory){$quoted=@($Arguments|ForEach-Object{'"'+$_.Replace('"','\"')+'"'})-join' ';$info=[Diagnostics.ProcessStartInfo]::new();$info.FileName=$Node;$info.Arguments=$quoted;$info.WorkingDirectory=$WorkingDirectory;$info.UseShellExecute=$false;$info.CreateNoWindow=$true;$info.RedirectStandardOutput=$true;$info.RedirectStandardError=$true;$process=[Diagnostics.Process]::new();$process.StartInfo=$info;try{if(-not$process.Start()){throw'node start failed'};$stdout=$process.StandardOutput.ReadToEnd();$stderr=$process.StandardError.ReadToEnd();if(-not$process.WaitForExit(30000)){$process.Kill();throw'node timeout'};[ordered]@{exit_code=$process.ExitCode;stdout=$stdout.Trim();stderr=$stderr.Trim();cpu_seconds=[math]::Round($process.TotalProcessorTime.TotalSeconds,4)}}finally{$process.Dispose()}}

$root=Split-Path -Parent $PSScriptRoot
$paths=[ordered]@{
 source=Join-Path $root 'packages\adult\api\index.ts';tests=Join-Path $root 'packages\adult\api\index.test.ts';contract=Join-Path $root 'packages\adult\api\adult-contract.v1.json';economics_doc=Join-Path $root 'docs\18-creator-node-adult-economy.md';security_doc=Join-Path $root 'docs\04-security-compliance.md';architecture=Join-Path $root 'architecture\bounded-contexts.yaml';backlog0=Join-Path $PSScriptRoot 'backlog-p0.yaml';backlog1=Join-Path $PSScriptRoot 'backlog-p1.yaml';capacity=Join-Path $PSScriptRoot 'capacity-scorecard.yaml';progress=Join-Path $PSScriptRoot 'product-progress.yaml';checkpoint=Join-Path $PSScriptRoot 'checkpoints\NX-ADULT-P01.md';spend=Join-Path $PSScriptRoot 'spend-control.yaml';econ_evidence=Join-Path $PSScriptRoot 'evidence\NX-ECON-P01-validation.json';media_evidence=Join-Path $PSScriptRoot 'evidence\NX-MEDIA-001-validation.json';mod_evidence=Join-Path $PSScriptRoot 'evidence\NX-MOD-P01-validation.json';chain_evidence=Join-Path $PSScriptRoot 'evidence\NX-CHAIN-001-rust-validation.json';boundary_checker=Join-Path $root 'security\source-boundary-check.js';tsc=Join-Path $root 'packages\contracts\node_modules\typescript\bin\tsc';lock=Join-Path $root 'packages\contracts\package-lock.json';validator=$PSCommandPath
}
foreach($path in $paths.Values){Assert-Adult (Test-Path -LiteralPath $path -PathType Leaf) "Missing artifact: $path"}
Assert-Adult ($RunId-match'^NX-ADULT-P01-[A-Za-z0-9T._-]+$') 'Run id invalid';Assert-Adult ($ExecutorRole-ne'UNSPECIFIED') 'Executor role required'
$source=Read-Utf8 $paths.source;$tests=Read-Utf8 $paths.tests;$contract=Read-Utf8 $paths.contract|ConvertFrom-Json;$doc=Read-Utf8 $paths.economics_doc;$security=Read-Utf8 $paths.security_doc;$architecture=Read-Utf8 $paths.architecture;$b0=Read-Utf8 $paths.backlog0;$b1=Read-Utf8 $paths.backlog1;$capacity=Read-Utf8 $paths.capacity;$progress=Read-Utf8 $paths.progress;$checkpoint=Read-Utf8 $paths.checkpoint;$spend=Read-Utf8 $paths.spend
$task=[regex]::Match($b1,'(?ms)^  - task_id:\s*NX-ADULT-P01\s*\r?\n(.*?)(?=^  - task_id:|\z)');Assert-Adult $task.Success 'Packet missing';if($task.Success){Assert-Adult ($task.Groups[1].Value-match'(?m)^\s+record_kind:\s*task_packet\s*$') 'Record kind';Assert-Adult ($task.Groups[1].Value-match'(?m)^\s+owner_agent:\s*A43\s*$') 'Owner';Assert-Adult ($task.Groups[1].Value-match'(?m)^\s+status:\s*(in_progress|review)\s*$') 'Packet inactive';Assert-Adult ($task.Groups[1].Value-match'(?m)^\s+risk_class:\s*T0\s*$') 'Risk';Assert-Adult ($task.Groups[1].Value-match'(?m)^\s+control_reviewers:\s*\[C02, C04, C05, C06, C08\]\s*$') 'Review roles'}
foreach($dependency in @('NX-AUTH-001','NX-MEDIA-001','NX-CHAIN-001','NX-CHAIN-002')){$record=[regex]::Match($b0,('(?ms)^  - task_id:\s*'+[regex]::Escape($dependency)+'\s*\r?\n(.*?)(?=^  - task_id:|\z)'));Assert-Adult ($record.Success-and$record.Groups[1].Value-match'(?m)^\s+status:\s*done\s*$') "Dependency not done: $dependency"}
foreach($dependency in @('NX-ECON-P01','NX-MOD-P01')){$record=[regex]::Match($b1,('(?ms)^  - task_id:\s*'+[regex]::Escape($dependency)+'\s*\r?\n(.*?)(?=^  - task_id:|\z)'));Assert-Adult ($record.Success-and$record.Groups[1].Value-match'(?m)^\s+status:\s*done\s*$') "Dependency not done: $dependency"}
$active=@([regex]::Matches($b1,'(?ms)^  - task_id:\s*(\S+)\s*\r?\n(.*?)(?=^  - task_id:|\z)')|Where-Object{$_.Groups[2].Value-match'(?m)^\s+record_kind:\s*task_packet\s*$'-and$_.Groups[2].Value-match'(?m)^\s+status:\s*(in_progress|review)\s*$'}|ForEach-Object{$_.Groups[1].Value});Assert-Adult ($active.Count-eq1-and$active[0]-eq'NX-ADULT-P01') 'WIP one violated'
Assert-Adult ($capacity-match'(?m)^\s+active_task_id:\s+NX-ADULT-P01\s*$'-and$capacity-match'(?m)^\s+active_packets:\s+1\s*$') 'Capacity mismatch';Assert-Adult ($progress-match'(?m)^\s+active_packet_id:\s+NX-ADULT-P01\s*$'-and$progress-match'(?m)^\s+complete_market_ready_product_percent:\s+59\s*$') 'Progress mismatch';Assert-Adult ($checkpoint-match'(?m)^- Stare:\s*`(in_progress|review)`\s*$') 'Checkpoint mismatch'
Assert-Adult ($architecture-match'(?ms)^  - id:\s*adult\s*\r?\n.*?^\s+owner:\s*A43\s*$'-and$architecture-match'(?ms)^  - id:\s*adult\s*\r?\n.*?^\s+public_api_path:\s*packages/adult/api\s*$') 'Adult boundary missing'
Assert-Adult ($contract.schemaVersion-eq1-and$contract.contractVersion-eq'1.0.0'-and$contract.owner-eq'A43'-and$contract.mode-eq'LOCAL_DETERMINISTIC_SYSTEM_TEST') 'Contract identity'
Assert-Adult ($contract.surface.channel-eq'WEB_SEPARATE'-and-not[bool]$contract.surface.mobileStoreCatalogAllowed-and-not[bool]$contract.surface.corePreviewOrDeepLinkAllowed-and-not[bool]$contract.surface.publicIpfsAllowed-and$contract.surface.countryDefault-eq'DENY') 'Surface gate'
Assert-Adult ([bool]$contract.publication.viewerAgeAssuranceRequired-and[bool]$contract.publication.creatorAndEveryPerformerAgeIdentityLivenessRequired-and[bool]$contract.publication.perAssetConsentRightsTerritoryExpiryAndRevocationRequired-and[bool]$contract.publication.prepublicationAutomatedSafetyRequired-and[bool]$contract.publication.immutableIllegalityAndCsamEscalationRequired-and[bool]$contract.publication.nciiAndNonConsensualDeepfakeDenied-and[bool]$contract.publication.escortTraffickingAndSexualServicesDenied) 'Publication gate'
Assert-Adult (@($contract.entitlement.offers).Count-eq7-and[bool]$contract.entitlement.freeDiscoveryStillAgeGated-and-not[bool]$contract.entitlement.freeDiscoveryVisibleOutsidePrive-and[bool]$contract.entitlement.encryptedPerAssetKeyRequired-and-not[bool]$contract.entitlement.viewerGraphPublic-and-not[bool]$contract.entitlement.exactEntitlementOnChain-and[bool]$contract.entitlement.accessRechecksCurrentAgeConsentRightsTerritoryAndTakedown) 'Entitlement gate'
Assert-Adult (@($contract.paidRooms.kinds).Count-eq2-and[bool]$contract.paidRooms.preauthorizedEscrowRequired-and[bool]$contract.paidRooms.escrowBindsPayerPayeeSessionTokenRateCapPolicyFeeAndExpiry-and[bool]$contract.paidRooms.escrowAuthorizationSingleUseAtOpen-and[bool]$contract.paidRooms.perMinuteMeteringReceiptRequired-and[bool]$contract.paidRooms.visibleRateAndTimerRequired-and[bool]$contract.paidRooms.automaticStopAtAuthorizedLimit-and-not[bool]$contract.paidRooms.recordingDefault-and[bool]$contract.paidRooms.recordingRequiresAllParticipantConsent-and[bool]$contract.paidRooms.recordingConsentBindsParticipantDeviceSessionPurposeGenerationAndExpiry-and-not[bool]$contract.paidRooms.offPlatformSexualServicesSolicitationAllowed) 'Paid rooms gate'
Assert-Adult ([bool]$contract.purge.revokesDiscovery-and[bool]$contract.purge.revokesPlaybackAndKeys-and[bool]$contract.purge.ciphertextPurgeRequired-and[bool]$contract.purge.minimumLawfulEvidenceOnly-and[bool]$contract.purge.legalHoldNeverRestoresDiscoveryOrPlayback) 'Purge gate'
Assert-Adult ($contract.settlement.publicActionClass-eq'PRIVATE_SETTLEMENT'-and[bool]$contract.settlement.opaqueCommitmentOnly-and[bool]$contract.settlement.quoteAndSettlementOneTime-and[bool]$contract.settlement.exactLiabilityConservation-and@($contract.settlement.capabilityBindings).Count-eq15-and[int]$contract.settlement.systemTestEconomicEffect-eq0) 'Settlement gate'
Assert-Adult ([int]$contract.creatorEconomics.defaultContentSplitBps.creator-eq8000-and[int]$contract.creatorEconomics.defaultContentSplitBps.nexus-eq1200-and[int]$contract.creatorEconomics.defaultContentSplitBps.provider-eq500-and[int]$contract.creatorEconomics.defaultContentSplitBps.reserve-eq300-and[int]$contract.creatorEconomics.defaultTipSplitBps.creator-eq9000-and[bool]$contract.creatorEconomics.creatorShareDominant-and[bool]$contract.creatorEconomics.feesShownBeforeConfirmation-and$contract.creatorEconomics.referralRewardSource-eq'NEXUS_NET_FEE_OR_MARKETING_BUDGET_ONLY'-and[bool]$contract.creatorEconomics.referralRequiresQualifiedNonSyntheticActivation-and-not[bool]$contract.creatorEconomics.referralOnGrossConsumerFunds-and-not[bool]$contract.creatorEconomics.multiLevelRecruitmentRewardAllowed-and-not[bool]$contract.creatorEconomics.paidFollowerOrFakeUserRewardAllowed) 'Creator economics gate'
Assert-Adult ([bool]$contract.security.exactShapeDataOnlyBoundary-and[bool]$contract.security.accessorsAndProxiesRejectedBeforeExecution-and[bool]$contract.security.independentAuthorityRootsRequired-and[bool]$contract.security.currentStatePreAndPostAwaitCas-and[bool]$contract.security.signedOrderedReceipts-and[bool]$contract.security.persistentNonceAndAuthorizationReplayProtection-and[bool]$contract.security.signedDurableCheckpoint-and[bool]$contract.security.restoreExactShapeAndFailAtomic) 'Security gate'
foreach($property in @('networkOperationsMax','providerOperationsMax','economicOperationsMax','realFundOperationsMax','realIdentityOperationsMax','realMediaOperationsMax','incrementalCostEurMax')){Assert-Adult ([decimal]$contract.effects.$property-eq0) "Effect escaped: $property"}
foreach($fragment in @('nodeIsProxy','assertData','LocalAdultEvidenceVault','item.root === root','AGE_IDENTITY','CONSENT','RIGHTS','MODERATION','COUNTRY','SETTLEMENT','WEB_SEPARATE','FREE_DISCOVERY','PAID_1_TO_1_CALL','countryEnabled','providerApproved','amlApproved','taxApproved','sanctionsClear','ADULT_EXECUTION_STATE_CONFLICT','ledgerVersion','assetAtValidation','entitlementAtValidation','PRIVATE_SETTLEMENT','allocateCreatorEconomics','referralFundedFromNexusOnly','AdultPaidRoomLedger','consumeOnce','AUTO_CLOSED_LIMIT','PRIVATE_ROOM_METER','scanAdultPublicLeakage','LocalAdultSnapshotAuthority','DurableAdultCheckpoint','ADULT_CHECKPOINT_STALE','ADULT_EVENT_REPLAY','verifyHistorical','forkEmpty')){Assert-Adult ($source.Contains($fragment)) "Source control missing: $fragment"}
foreach($fragment in @('every performer and evidence retained as commitments','public action contains no sensitive graph','private entitlement granted','only opaque settlement commitment','settlement terms bind generation policy token fee schedule quote expiry','concurrent settlements over the same current entitlement have exactly one CAS winner','recording consent scope binds participant device session purpose','room escrow terms bind token expiry recording purpose and fee schedule','free discovery offer still required full age','creator gets dominant 80 percent','tip model targets 90 percent','multi-level recruitment receive zero','paid one-to-one call opens only with visible rate timer','automatically stops at authorized balance limit','paid live room uses the same capped','badConservation','accessor rejected without execution','proxy rejected before traps','revoked consent cannot create entitlement','purge revokes discovery playback and keys','concurrent command has one winner','fresh restore reconstructs complete ordered history','failed restore leaves external evidence vault unchanged','ADULT_SNAPSHOT_INVALID')){Assert-Adult ($tests.Contains($fragment)) "Scenario missing: $fragment"}
foreach($fragment in @('Nexus Privé','18+ age assurance','consimțământ semnat','web/PWA separat','Nu ajung în clar on-chain','Country Capability Matrix','Free Discovery','Paid 1:1 Call','80% creator','Creator referrals','schemă piramidală')){Assert-Adult ($doc.Contains($fragment)) "Normative adult policy missing: $fragment"}
Assert-Adult ($doc.Contains('Wallet login nu substituie verificarea de vârstă/identitate')) 'Wallet/age boundary missing'
Assert-Adult ($source-notmatch'(?i)(fetch\s*\(|XMLHttpRequest|HttpClient|WebClient|Invoke-WebRequest|https?\.request|child_process|net\.connect|dgram\.|console\.log)') 'Network/process/log capability detected';Assert-Adult ($spend-match'(?m)^mode:\s*default_deny_spend\s*$'-and$spend-match'(?m)^\s*max_incremental_amount:\s*0\s*$') 'Spend drift'
foreach($name in @('econ_evidence','media_evidence','mod_evidence','chain_evidence')){$evidence=Read-Utf8 $paths[$name]|ConvertFrom-Json;Assert-Adult ($evidence.status-eq'PASS') "Dependency evidence not PASS: $name"}
$credentialPattern='^(AWS_|AZURE_|GOOGLE_APPLICATION_CREDENTIALS$|OPENAI_API_KEY$|TWILIO_|MAPBOX_|CLOUDFLARE_|STRIPE_|PINATA_|IPFS_|MATRIX_|XMONEY_)';$credentialNames=@([Environment]::GetEnvironmentVariables().Keys|ForEach-Object{[string]$_}|Where-Object{$_-match$credentialPattern});Assert-Adult ($credentialNames.Count-eq0) 'Production/billing credential present'

$node=Get-NodeRuntime;Assert-Adult ($null-ne$node) 'Included Node missing';$ephemeralRoot=Join-Path $root '.ephemeral';[IO.Directory]::CreateDirectory($ephemeralRoot)|Out-Null;$runRoot=Join-Path $ephemeralRoot ('NX-ADULT-P01-'+[Guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($runRoot)|Out-Null;$runs=@();$receipt=$null;$boundary=$null
try{if($null-ne$node){$compile=Invoke-Node $node @($paths.tsc,'--strict','--target','ES2022','--module','commonjs','--lib','ES2022,DOM','--outDir',$runRoot,$paths.source,$paths.tests) $root;Assert-Adult ($compile.exit_code-eq0) "Compile failed: $($compile.stderr)";if($compile.exit_code-eq0){$testPath=Join-Path $runRoot 'index.test.js';1..3|ForEach-Object{$script:runs+=Invoke-Node $node @($testPath) $root};foreach($run in $runs){Assert-Adult ($run.exit_code-eq0) "Scenario failed: $($run.stderr)"};Assert-Adult (@($runs.stdout|Sort-Object -Unique).Count-eq1) 'Nondeterministic output';try{$receipt=$runs[0].stdout|ConvertFrom-Json}catch{Assert-Adult $false 'Scenario receipt invalid'}};$manifest=[pscustomobject]@{knownSpecifiers=[pscustomobject]@{};knownSchemas=@('adult');contexts=[pscustomobject]@{adult=[pscustomobject]@{allowedImports=@()}};items=@([pscustomobject]@{id='packages/adult/api/index.ts';sourceContext='adult';text=$source})};$manifestPath=Join-Path $runRoot 'boundary.json';[IO.File]::WriteAllText($manifestPath,($manifest|ConvertTo-Json -Depth 8),[Text.UTF8Encoding]::new($false));$boundaryRun=Invoke-Node $node @($paths.boundary_checker,$manifestPath) $root;Assert-Adult ($boundaryRun.exit_code-eq0) "Boundary failed: $($boundaryRun.stderr)";if($boundaryRun.exit_code-eq0){$boundary=$boundaryRun.stdout|ConvertFrom-Json}}}finally{$safe=[IO.Path]::GetFullPath($ephemeralRoot).TrimEnd('\')+'\';$resolved=[IO.Path]::GetFullPath($runRoot);if((Test-Path -LiteralPath $runRoot)-and$resolved.StartsWith($safe,[StringComparison]::OrdinalIgnoreCase)){Remove-Item -LiteralPath $runRoot -Recurse -Force}}
Assert-Adult ($null-ne$receipt) 'Scenario receipt missing';if($null-ne$receipt){Assert-Adult ($receipt.task_id-eq'NX-ADULT-P01'-and$receipt.status-eq'PASS'-and[int]$receipt.assertions-ge82) 'Scenario regression';foreach($group in @('surface','publication','entitlement','paid_rooms','purge','settlement','creator_economics','input_boundary','concurrency','restore','privacy','synthetic_isolation')){Assert-Adult ($null-ne$receipt.$group) "Receipt group missing: $group"};Assert-Adult ([bool]$receipt.surface.web_separate-and-not[bool]$receipt.surface.mobile_store_catalog-and-not[bool]$receipt.surface.public_ipfs-and[bool]$receipt.publication.every_performer_age_identity_liveness_consent-and[bool]$receipt.publication.free_discovery_fully_gated-and[bool]$receipt.entitlement.current_evidence_recheck-and[bool]$receipt.paid_rooms.live-and[bool]$receipt.paid_rooms.one_to_one_call-and[bool]$receipt.paid_rooms.signed_per_minute_metering-and[bool]$receipt.paid_rooms.automatic_limit_stop-and[int]$receipt.paid_rooms.public_graph_leakage-eq0-and[bool]$receipt.purge.keys-and[bool]$receipt.settlement.quote_single_use-and[bool]$receipt.settlement.exact_conservation-and[int]$receipt.creator_economics.content_creator_bps-eq8000-and[int]$receipt.creator_economics.tip_creator_bps-eq9000-and[bool]$receipt.creator_economics.referral_from_nexus_fee_only-and[bool]$receipt.creator_economics.paid_agent_synthetic_referral_zero-and[bool]$receipt.creator_economics.multi_level_referral_zero-and[bool]$receipt.input_boundary.accessor_zero_execution-and[bool]$receipt.input_boundary.proxy_zero_traps-and[bool]$receipt.concurrency.one_winner-and[bool]$receipt.restore.durable_checkpoint-and[bool]$receipt.restore.replay_denied_after_restart-and[bool]$receipt.restore.fail_atomic-and[int]$receipt.privacy.public_leakage_findings-eq0) 'Critical proof missing';foreach($property in @('network_operations','provider_operations','economic_operations','real_fund_operations','real_identity_operations','real_media_operations')){Assert-Adult ([int]$receipt.synthetic_isolation.$property-eq0) "Runtime effect escaped: $property"}}
$boundaryFindings=@();if($null-ne$boundary){foreach($item in @($boundary.results)){foreach($finding in @($item.findings)){$boundaryFindings+="$($item.id):$finding"}}};Assert-Adult ($null-ne$boundary-and$boundaryFindings.Count-eq0) ('Source boundary findings: '+($boundaryFindings-join','))
$hashes=[ordered]@{};foreach($entry in $paths.GetEnumerator()){$hashes[$entry.Key]=(Get-Sha $entry.Value)};$subjectLines=@($hashes.GetEnumerator()|ForEach-Object{"$($_.Key)=$($_.Value)"}|Sort-Object);$subject=Get-TextSha ($subjectLines-join"`n")
$timer.Stop();$result=[ordered]@{schema_version=1;task_id='NX-ADULT-P01';run_id=$RunId;executor_role=$ExecutorRole;status=if($failures.Count-eq0){'PASS'}else{'FAIL'};scope='local_synthetic_prive_free_paid_creator_economics_room_metering_entitlement_purge_opaque_settlement_and_restore';assertions=$assertions;scenario_assertions=if($receipt){[int]$receipt.assertions}else{0};deterministic_repetitions=@($runs).Count;failures=@($failures);surface=if($receipt){$receipt.surface}else{$null};publication=if($receipt){$receipt.publication}else{$null};entitlement=if($receipt){$receipt.entitlement}else{$null};paid_rooms=if($receipt){$receipt.paid_rooms}else{$null};purge=if($receipt){$receipt.purge}else{$null};settlement=if($receipt){$receipt.settlement}else{$null};creator_economics=if($receipt){$receipt.creator_economics}else{$null};input_boundary=if($receipt){$receipt.input_boundary}else{$null};concurrency=if($receipt){$receipt.concurrency}else{$null};restore=if($receipt){$receipt.restore}else{$null};privacy=if($receipt){$receipt.privacy}else{$null};synthetic_isolation=if($receipt){$receipt.synthetic_isolation}else{$null};source_boundary_findings=$boundaryFindings.Count;credential_name_matches=$credentialNames.Count;network_operations=0;provider_operations=0;economic_operations=0;real_fund_operations=0;real_identity_operations=0;real_media_operations=0;incremental_cost=[ordered]@{amount=0;currency='EUR'};claims_excluded=@('real_people','real_age_or_identity','real_adult_media','production_providers','payments','mainnet','country_legal_opinion','formal_security_audit','statutory_reporting_operations');review_subject_sha256=$subject;artifact_sha256=$hashes;duration_seconds=[math]::Round($timer.Elapsed.TotalSeconds,4)}
$result|ConvertTo-Json -Depth 16 -Compress
if($failures.Count-ne0){exit 1}
