[CmdletBinding()]
param(
  [string]$RunId = ('NX-ENGAGE-P01-' + [DateTimeOffset]::UtcNow.ToString('yyyyMMddTHHmmssfffZ') + '-' + [Guid]::NewGuid().ToString('N').Substring(0,8)),
  [ValidateSet('UNSPECIFIED','A42','C02','C04','C06','C08','C10')][string]$ExecutorRole = 'UNSPECIFIED'
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$timer = [Diagnostics.Stopwatch]::StartNew(); $failures = [Collections.Generic.List[string]]::new(); $assertions = 0
function Assert-Engage([bool]$Condition,[string]$Message) { $script:assertions++; if (-not $Condition) { $script:failures.Add($Message) } }
function Read-Utf8([string]$Path) { [IO.File]::ReadAllText($Path,[Text.Encoding]::UTF8) }
function Get-Sha([string]$Path) { (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant() }
function Get-TextSha([string]$Value) { $sha=[Security.Cryptography.SHA256]::Create(); try { ([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Value)))).Replace('-','').ToLowerInvariant() } finally { $sha.Dispose() } }
function Get-NodeRuntime { $runtimeRoot=Join-Path ([Environment]::GetFolderPath('LocalApplicationData')) 'OpenAI\Codex\bin'; if(Test-Path -LiteralPath $runtimeRoot){ Get-ChildItem -LiteralPath $runtimeRoot -Filter node.exe -File -Recurse | Sort-Object FullName | Select-Object -Last 1 -ExpandProperty FullName } }
function Invoke-Node([string]$Node,[string[]]$Arguments,[string]$WorkingDirectory) { $quoted=@($Arguments|ForEach-Object{'"'+$_.Replace('"','\"')+'"'}) -join ' '; $info=[Diagnostics.ProcessStartInfo]::new(); $info.FileName=$Node; $info.Arguments=$quoted; $info.WorkingDirectory=$WorkingDirectory; $info.UseShellExecute=$false; $info.CreateNoWindow=$true; $info.RedirectStandardOutput=$true; $info.RedirectStandardError=$true; $process=[Diagnostics.Process]::new(); $process.StartInfo=$info; try { if(-not $process.Start()){throw 'node start failed'}; $stdout=$process.StandardOutput.ReadToEnd(); $stderr=$process.StandardError.ReadToEnd(); if(-not $process.WaitForExit(30000)){$process.Kill();throw 'node timeout'}; [ordered]@{exit_code=$process.ExitCode;stdout=$stdout.Trim();stderr=$stderr.Trim();cpu_seconds=[math]::Round($process.TotalProcessorTime.TotalSeconds,4)} } finally {$process.Dispose()} }

$root=Split-Path -Parent $PSScriptRoot
$paths=[ordered]@{
  source=Join-Path $root 'packages\recommendations\api\index.ts'
  tests=Join-Path $root 'packages\recommendations\api\index.test.ts'
  contract=Join-Path $root 'packages\recommendations\api\engagement-contract.v1.json'
  engagement_doc=Join-Path $root 'docs\20-engagement-integrity-viral-ranking.md'
  action_doc=Join-Path $root 'docs\09-action-ledger-classifieds.md'
  business_doc=Join-Path $root 'docs\11-business-services-promotion-reviews.md'
  dating_doc=Join-Path $root 'docs\14-dating-pulse-discretion-trust.md'
  clips_doc=Join-Path $root 'docs\15-recommendations-clips-watch-live-kids.md'
  architecture=Join-Path $root 'architecture\bounded-contexts.yaml'
  backlog0=Join-Path $PSScriptRoot 'backlog-p0.yaml'
  backlog1=Join-Path $PSScriptRoot 'backlog-p1.yaml'
  capacity=Join-Path $PSScriptRoot 'capacity-scorecard.yaml'
  progress=Join-Path $PSScriptRoot 'product-progress.yaml'
  checkpoint=Join-Path $PSScriptRoot 'checkpoints\NX-ENGAGE-P01.md'
  spend=Join-Path $PSScriptRoot 'spend-control.yaml'
  trust_evidence=Join-Path $PSScriptRoot 'evidence\NX-TRUST-P01-validation.json'
  social_evidence=Join-Path $PSScriptRoot 'evidence\NX-SOCIAL-P01-validation.json'
  profile_evidence=Join-Path $PSScriptRoot 'evidence\NX-PROFILE-P01-validation.json'
  dating_evidence=Join-Path $PSScriptRoot 'evidence\NX-DATING-P01-validation.json'
  market_evidence=Join-Path $PSScriptRoot 'evidence\NX-MARKET-P01-validation.json'
  business_evidence=Join-Path $PSScriptRoot 'evidence\NX-BIZ-P01-validation.json'
  boundary_checker=Join-Path $root 'security\source-boundary-check.js'
  tsc=Join-Path $root 'packages\contracts\node_modules\typescript\bin\tsc'
  lock=Join-Path $root 'packages\contracts\package-lock.json'
  validator=$PSCommandPath
}
foreach($path in $paths.Values){Assert-Engage (Test-Path -LiteralPath $path -PathType Leaf) "Missing artifact: $path"}
Assert-Engage ($RunId -match '^NX-ENGAGE-P01-[A-Za-z0-9T._-]+$') 'Run id invalid'; Assert-Engage ($ExecutorRole -ne 'UNSPECIFIED') 'Executor role required'
$source=Read-Utf8 $paths.source; $tests=Read-Utf8 $paths.tests; $contract=Read-Utf8 $paths.contract|ConvertFrom-Json; $doc=Read-Utf8 $paths.engagement_doc; $b0=Read-Utf8 $paths.backlog0; $b1=Read-Utf8 $paths.backlog1; $capacity=Read-Utf8 $paths.capacity; $progress=Read-Utf8 $paths.progress; $checkpoint=Read-Utf8 $paths.checkpoint; $spend=Read-Utf8 $paths.spend; $architecture=Read-Utf8 $paths.architecture
$task=[regex]::Match($b1,'(?ms)^  - task_id:\s*NX-ENGAGE-P01\s*\r?\n(.*?)(?=^  - task_id:|\z)'); Assert-Engage $task.Success 'Packet missing'
if($task.Success){Assert-Engage ($task.Groups[1].Value -match '(?m)^\s+record_kind:\s*task_packet\s*$') 'Record kind drift';Assert-Engage ($task.Groups[1].Value -match '(?m)^\s+owner_agent:\s*A42\s*$') 'Owner drift';Assert-Engage ($task.Groups[1].Value -match '(?m)^\s+status:\s*(in_progress|review)\s*$') 'Packet inactive';Assert-Engage ($task.Groups[1].Value -match '(?m)^\s+risk_class:\s*T0\s*$') 'Risk drift';Assert-Engage ($task.Groups[1].Value -match '(?m)^\s+control_reviewers:\s*\[C02, C04, C06, C08, C10\]\s*$') 'Review roles drift'}
foreach($dependency in @('NX-SEC-001','NX-CTRL-001')){$record=[regex]::Match($b0,('(?ms)^  - task_id:\s*'+[regex]::Escape($dependency)+'\s*\r?\n(.*?)(?=^  - task_id:|\z)'));Assert-Engage ($record.Success -and $record.Groups[1].Value -match '(?m)^\s+status:\s*done\s*$') "P0 dependency not done: $dependency"}
foreach($dependency in @('NX-TRUST-P01','NX-SOCIAL-P01','NX-PROFILE-P01','NX-DATING-P01','NX-MARKET-P01','NX-BIZ-P01')){$record=[regex]::Match($b1,('(?ms)^  - task_id:\s*'+[regex]::Escape($dependency)+'\s*\r?\n(.*?)(?=^  - task_id:|\z)'));Assert-Engage ($record.Success -and $record.Groups[1].Value -match '(?m)^\s+status:\s*done\s*$') "P1 dependency not done: $dependency"}
$active=@([regex]::Matches($b1,'(?ms)^  - task_id:\s*(\S+)\s*\r?\n(.*?)(?=^  - task_id:|\z)')|Where-Object{$_.Groups[2].Value -match '(?m)^\s+record_kind:\s*task_packet\s*$' -and $_.Groups[2].Value -match '(?m)^\s+status:\s*(in_progress|review)\s*$'}|ForEach-Object{$_.Groups[1].Value});Assert-Engage ($active.Count -eq 1 -and $active[0] -eq 'NX-ENGAGE-P01') 'WIP one violated'
Assert-Engage ($capacity -match '(?m)^\s+active_task_id:\s+NX-ENGAGE-P01\s*$' -and $capacity -match '(?m)^\s+active_packets:\s+1\s*$' -and $capacity -match '(?m)^\s+current_packet_status:\s+review\s*$') 'Capacity mismatch';Assert-Engage ($progress -match '(?m)^\s+active_packet_id:\s+NX-ENGAGE-P01\s*$') 'Progress mismatch';Assert-Engage ($checkpoint -match '(?m)^- Stare:\s*`review`\s*$') 'Checkpoint mismatch'
Assert-Engage ($architecture -match '(?ms)^  - id:\s*recommendations\s*\r?\n.*?^\s+owner:\s*A42\s*$' -and $architecture -match '(?ms)^  - id:\s*recommendations\s*\r?\n.*?^\s+public_api_path:\s*packages/recommendations/api\s*$') 'Recommendations boundary missing'
Assert-Engage ($contract.schemaVersion -eq 1 -and $contract.contractVersion -eq '1.0.0' -and $contract.owner -eq 'A42' -and $contract.mode -eq 'LOCAL_DETERMINISTIC_SYSTEM_TEST') 'Contract identity drift'
Assert-Engage (@($contract.surfaces).Count -eq 13 -and @($contract.actions).Count -eq 8 -and $contract.expressivePalettes.SOCIAL_PULSE_WATCH_LIVE.Count -eq 6 -and $contract.expressivePalettes.WORK_CONTENT.Count -eq 4 -and $contract.expressivePalettes.DATING.Count -eq 0) 'Surface/action/palette coverage drift'
foreach($property in @('appendOnly','oneActiveReactionPerActorObjectGeneration','authorWithdrawalCreatesTombstone','materialEditCreatesGeneration','moderationRequiresSeparateAuthority','signedOneTimeReceipts','orderedSha256Lineage','restoreReplaysStateMachine','surfaceObjectMatrixRequired','actorAndOwnerProfileTypeBindingRequired')){Assert-Engage ([bool]$contract.integrity.$property) "Integrity control false: $property"}
Assert-Engage (-not [bool]$contract.integrity.creatorMayEraseForeignContent -and -not [bool]$contract.privacy.publicNegativeCount -and -not [bool]$contract.privacy.datingPersonNegativeScore -and -not [bool]$contract.privacy.workPersonNegativeScore -and -not [bool]$contract.privacy.kidsCompetitiveNegativeCount -and -not [bool]$contract.privacy.rawReactionGraphOnChain -and [bool]$contract.privacy.batchCommitmentOnly -and -not [bool]$contract.privacy.crossProfileSignalSharingDefault) 'Privacy/non-erasure drift'
Assert-Engage ([int]$contract.rankingPolicy.minEffectiveImpressions -eq 50 -and [int]$contract.rankingPolicy.minIndependentClusters -eq 10 -and [int]$contract.rankingPolicy.maxClusterContributionBps -eq 1000 -and [int]$contract.rankingPolicy.globalNegativePenaltyCapBps -eq 2000 -and [int]$contract.rankingPolicy.explorationFloorBps -eq 1000 -and [bool]$contract.rankingPolicy.explorationAllocationPerCohortRequired -and [bool]$contract.rankingPolicy.rankingOrderInvariantRequired -and [bool]$contract.rankingPolicy.conflictingDuplicateActorExcluded -and -not [bool]$contract.rankingPolicy.dislikeAloneMayRemove) 'Ranking policy drift'
Assert-Engage ((@($contract.rankingPolicy.excludedTraffic) -join ',') -eq 'PAID,AGENT,SYSTEM_TEST,INCENTIVIZED,QUARANTINED') 'Excluded traffic drift'
Assert-Engage ($contract.fakeOpinionPolicy.uiLabel -eq 'Fake' -and [bool]$contract.fakeOpinionPolicy.isUserOpinion -and [bool]$contract.fakeOpinionPolicy.countsAsQualifiedSentiment -and -not [bool]$contract.fakeOpinionPolicy.isTruthVerdict -and -not [bool]$contract.fakeOpinionPolicy.directUnqualifiedDownrankAllowed -and -not [bool]$contract.fakeOpinionPolicy.directTakedownAllowed -and [bool]$contract.fakeOpinionPolicy.routesToTrustLensAggregate -and -not [bool]$contract.fakeOpinionPolicy.publicCount) 'Fake opinion policy drift'
foreach($property in @('networkOperationsMax','providerOperationsMax','economicOperationsMax','organicMetricOperationsMax','realFundOperationsMax','incrementalCostEurMax')){Assert-Engage ([decimal]$contract.effects.$property -eq 0) "Effect limit escaped: $property"}
foreach($fragment in @('EngagementLedger','NEGATIVE_SEMANTIC','EXPRESSIVE_REACTION','FAKE_OPINION','FAKE_OPINION_AGGREGATE','qualifiedSentimentEligible','expressiveAllowed','ProfileType','profileTypeForSurface','objectAllowed','ENGAGEMENT_PROFILE_TYPE_BINDING_MISMATCH','ENGAGEMENT_SURFACE_OBJECT_DENIED','ownerProfileCommitment','publicNegativeCount','ENGAGEMENT_PUBLIC_NEGATIVE_COUNT_FORBIDDEN','ENGAGEMENT_WITHDRAW_DENIED','MODERATION_TOMBSTONE','LocalSnapshotAuthority','DurableEngagementCheckpoint','ENGAGEMENT_CHECKPOINT_STALE','ENGAGEMENT_EXECUTION_CONFLICT','viralFairRank','negativeLowerConfidenceBps','globalNegativePenaltyCapBps','allocateExploration','reservedNewSlots','floorSatisfied','NEVER_FROM_DISLIKE')){Assert-Engage ($source.Contains($fragment)) "Source control missing: $fragment"}
foreach($fragment in @('creator cannot erase another author','author withdrawal purges the public body','same actor nonce commits exactly one','Dating Pass is private','market negative action means private','social Love is an aggregate-eligible','Fake is a qualified user opinion','qualified diverse Fake opinions count','Work content offers professional reactions','Kids expressive reactions remain private','ACTION:INVALID:MARKET:PROFILE','ACTION:INVALID:KIDS:JOB','ACTION:INVALID:SOCIAL:LESSON','ENGAGEMENT_PROFILE_TYPE_BINDING_MISMATCH','single-cluster dislike raid','diverse persistent dissatisfaction','ranking is order invariant','exploration reserves at least ten percent','exploration allocation is deterministic','paid agent synthetic and quarantined traffic','fresh restore deterministically','prefix_denied')){Assert-Engage ($tests.Contains($fragment)) "Test control missing: $fragment"}
foreach($fragment in @('`Not for me`','Creatorul nu poate','long-press','`FAKE_OPINION`','`AI-generated/provenance`','exploration floor','paid, agentic, synthetic','`REMOVE`','batch commitment','DSA, art. 27')){Assert-Engage ($doc.Contains($fragment)) "Normative policy missing: $fragment"}
Assert-Engage ($source -notmatch '(?i)(fetch\s*\(|XMLHttpRequest|HttpClient|WebClient|Invoke-WebRequest|https?\.request|child_process|net\.connect|dgram\.|console\.log|process\.)') 'Runtime network/process/log capability detected'
Assert-Engage ($spend -match '(?m)^mode:\s*default_deny_spend\s*$' -and $spend -match '(?m)^\s*max_incremental_amount:\s*0\s*$') 'Spend guard drift'
foreach($name in @('trust_evidence','social_evidence','profile_evidence','dating_evidence','market_evidence','business_evidence')){$evidence=Read-Utf8 $paths[$name]|ConvertFrom-Json;Assert-Engage ($evidence.status -eq 'PASS') "Dependency evidence not PASS: $name"}
$credentialPattern='^(AWS_|AZURE_|GOOGLE_APPLICATION_CREDENTIALS$|OPENAI_API_KEY$|TWILIO_|MAPBOX_|CLOUDFLARE_|STRIPE_|PINATA_|IPFS_|MATRIX_|XMONEY_)';$credentialNames=@([Environment]::GetEnvironmentVariables().Keys|ForEach-Object{[string]$_}|Where-Object{$_ -match $credentialPattern});Assert-Engage ($credentialNames.Count -eq 0) 'Production/billing credential name present'

$node=Get-NodeRuntime;Assert-Engage ($null -ne $node) 'Included Node missing';$ephemeralRoot=Join-Path $root '.ephemeral';[IO.Directory]::CreateDirectory($ephemeralRoot)|Out-Null;$runRoot=Join-Path $ephemeralRoot ('NX-ENGAGE-P01-'+[Guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($runRoot)|Out-Null;$runs=@();$receipt=$null;$boundary=$null
try{if($null -ne $node){$compile=Invoke-Node $node @($paths.tsc,'--strict','--target','ES2022','--module','commonjs','--lib','ES2022,DOM','--outDir',$runRoot,$paths.source,$paths.tests) $root;Assert-Engage ($compile.exit_code -eq 0) "Compile failed: $($compile.stderr)";if($compile.exit_code -eq 0){$testPath=Join-Path $runRoot 'index.test.js';1..3|ForEach-Object{$script:runs+=Invoke-Node $node @($testPath) $root};foreach($run in $runs){Assert-Engage ($run.exit_code -eq 0) "Scenario failed: $($run.stderr)"};Assert-Engage (@($runs.stdout|Sort-Object -Unique).Count -eq 1) 'Scenario output nondeterministic';try{$receipt=$runs[0].stdout|ConvertFrom-Json}catch{Assert-Engage $false 'Scenario receipt invalid'}};$manifest=[pscustomobject]@{knownSpecifiers=[pscustomobject]@{};knownSchemas=@('recommendations');contexts=[pscustomobject]@{recommendations=[pscustomobject]@{allowedImports=@()}};items=@([pscustomobject]@{id='packages/recommendations/api/index.ts';sourceContext='recommendations';text=$source})};$manifestPath=Join-Path $runRoot 'boundary.json';[IO.File]::WriteAllText($manifestPath,($manifest|ConvertTo-Json -Depth 8),[Text.UTF8Encoding]::new($false));$boundaryRun=Invoke-Node $node @($paths.boundary_checker,$manifestPath) $root;Assert-Engage ($boundaryRun.exit_code -eq 0) "Boundary failed: $($boundaryRun.stderr)";if($boundaryRun.exit_code -eq 0){$boundary=$boundaryRun.stdout|ConvertFrom-Json}}}finally{$safe=[IO.Path]::GetFullPath($ephemeralRoot).TrimEnd('\')+'\';$resolved=[IO.Path]::GetFullPath($runRoot);if((Test-Path -LiteralPath $runRoot)-and $resolved.StartsWith($safe,[StringComparison]::OrdinalIgnoreCase)){Remove-Item -LiteralPath $runRoot -Recurse -Force}}
Assert-Engage ($null -ne $receipt) 'Scenario receipt missing'
if($null -ne $receipt){Assert-Engage ($receipt.task_id -eq 'NX-ENGAGE-P01' -and $receipt.status -eq 'PASS' -and [int]$receipt.assertions -ge 41) 'Scenario regression';foreach($property in @('append_only','one_active_reaction','creator_foreign_erasure_denied','author_withdrawal_tombstone','edit_revision_history','material_generation','separate_moderation_authority','surface_object_matrix','profile_type_binding')){Assert-Engage ([bool]$receipt.state_machine.$property) "State proof false: $property"};Assert-Engage (-not [bool]$receipt.state_machine.public_negative_count -and [int]$receipt.modes.covered -eq 13 -and [bool]$receipt.modes.dating_pass_private -and [bool]$receipt.modes.work_person_dislike_denied -and [bool]$receipt.modes.market_not_interested_private -and [bool]$receipt.modes.kids_show_less_private -and [bool]$receipt.modes.expressive_palette_surface_scoped -and [bool]$receipt.modes.fake_opinion_counts_as_qualified_sentiment -and [bool]$receipt.modes.fake_opinion_is_not_truth_verdict) 'Mode/privacy proof failed';Assert-Engage ([int]$receipt.ranking.raid_penalty_bps -eq 0 -and [int]$receipt.ranking.genuine_penalty_bps -gt 0 -and [int]$receipt.ranking.genuine_penalty_bps -le 2000 -and [int]$receipt.ranking.fake_opinion_penalty_bps -eq [int]$receipt.ranking.genuine_penalty_bps -and [int]$receipt.ranking.exploration_floor_bps -eq 1000 -and [int]$receipt.ranking.exploration_allocated_bps -ge 1000 -and [bool]$receipt.ranking.order_invariant -and [bool]$receipt.ranking.conflicting_duplicates_excluded -and -not [bool]$receipt.ranking.dislike_removal -and [int]$receipt.ranking.excluded_organic_count -eq 0) 'Ranking proof failed';foreach($property in @('signed','one_time','ordered_sha256','batch_commitment','fresh_restore','durable_checkpoint','prefix_denied')){Assert-Engage ([bool]$receipt.receipts.$property) "Receipt proof false: $property"};Assert-Engage ($receipt.actor_class -eq 'SYSTEM_TEST' -and [int]$receipt.synthetic_isolation.organic_events -eq 0 -and [int]$receipt.synthetic_isolation.rewards_accrued -eq 0 -and [int]$receipt.synthetic_isolation.reputation_delta -eq 0) 'Synthetic isolation failed';Assert-Engage ([int]$receipt.network_operations -eq 0 -and [int]$receipt.provider_operations -eq 0 -and [int]$receipt.economic_operations -eq 0 -and [int]$receipt.real_fund_operations -eq 0 -and [decimal]$receipt.incremental_cost.amount -eq 0) 'Effects escaped'}
$boundaryFindings=@();if($null -ne $boundary){foreach($item in @($boundary.results)){foreach($finding in @($item.findings)){$boundaryFindings+="$($item.id):$finding"}}};Assert-Engage ($null -ne $boundary -and $boundaryFindings.Count -eq 0) ('Boundary findings: '+($boundaryFindings -join ','))
$hashes=[ordered]@{};foreach($path in $paths.Values){if(Test-Path -LiteralPath $path -PathType Leaf){$relative=$path.Substring($root.Length).TrimStart('\').Replace('\','/');$hashes[$relative]=Get-Sha $path}};$subject=Get-TextSha (($hashes.GetEnumerator()|Sort-Object Key|ForEach-Object{"$($_.Key)=$($_.Value)"}) -join "`n");$timer.Stop()
$result=[ordered]@{schema_version=1;task_id='NX-ENGAGE-P01';run_id=$RunId;executor_role=$ExecutorRole;status=if($failures.Count -eq 0){'PASS'}else{'FAIL'};scope='local_append_only_private_negative_preference_and_viral_fair_ranking_proof';assertions=$assertions;scenario_assertions=if($receipt){[int]$receipt.assertions}else{0};deterministic_repetitions=@($runs).Count;failures=@($failures);state_machine=if($receipt){$receipt.state_machine}else{$null};modes=if($receipt){$receipt.modes}else{$null};ranking=if($receipt){$receipt.ranking}else{$null};receipts=if($receipt){$receipt.receipts}else{$null};synthetic_isolation=if($receipt){$receipt.synthetic_isolation}else{$null};source_boundary_findings=$boundaryFindings.Count;credential_name_matches=$credentialNames.Count;network_operations=0;external_provider_operations=0;economic_operations=0;real_fund_operations=0;incremental_cost=[ordered]@{amount=0;currency='EUR'};claims_excluded=@($contract.claimsExcluded);review_subject_sha256=$subject;artifact_sha256=$hashes;duration_seconds=[math]::Round($timer.Elapsed.TotalSeconds,4)}
$result|ConvertTo-Json -Depth 12;if($failures.Count -gt 0){exit 1}
