[CmdletBinding()]
param(
    [string]$RunId = ('NX-CHAIN-002-' + [DateTimeOffset]::UtcNow.ToString('yyyyMMddTHHmmssfffZ') + '-' + [Guid]::NewGuid().ToString('N').Substring(0, 8)),
    [ValidateSet('UNSPECIFIED', 'A22', 'A20', 'A13', 'C03', 'C09', 'C10')][string]$ExecutorRole = 'UNSPECIFIED'
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$timer = [Diagnostics.Stopwatch]::StartNew(); $failures = [Collections.Generic.List[string]]::new(); $assertions = 0
function Assert-Reducer { param([bool]$Condition, [string]$Message) $script:assertions++; if (-not $Condition) { $script:failures.Add($Message) } }
function Read-Utf8 { param([string]$Path) [IO.File]::ReadAllText($Path, [Text.Encoding]::UTF8) }
function Get-Sha256 { param([string]$Path) (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant() }
function Get-StringSha256 { param([string]$Value) $sha = [Security.Cryptography.SHA256]::Create(); try { $hash = $sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Value)) } finally { $sha.Dispose() }; ([BitConverter]::ToString($hash)).Replace('-', '').ToLowerInvariant() }
function Get-Node { $root = Join-Path ([Environment]::GetFolderPath('LocalApplicationData')) 'OpenAI\Codex\bin'; if (Test-Path -LiteralPath $root) { Get-ChildItem -LiteralPath $root -Filter node.exe -File -Recurse -ErrorAction SilentlyContinue | Sort-Object FullName | Select-Object -Last 1 -ExpandProperty FullName } }
function Invoke-Node { param([string]$Node, [string[]]$Arguments, [string]$WorkingDirectory) $quoted = @($Arguments | ForEach-Object { '"' + $_.Replace('"', '\"') + '"' }) -join ' '; $info = [Diagnostics.ProcessStartInfo]::new(); $info.FileName = $Node; $info.Arguments = $quoted; $info.WorkingDirectory = $WorkingDirectory; $info.UseShellExecute = $false; $info.CreateNoWindow = $true; $info.RedirectStandardOutput = $true; $info.RedirectStandardError = $true; $process = [Diagnostics.Process]::new(); $process.StartInfo = $info; try { if (-not $process.Start()) { throw 'Node did not start.' }; $stdout = $process.StandardOutput.ReadToEnd(); $stderr = $process.StandardError.ReadToEnd(); if (-not $process.WaitForExit(30000)) { $process.Kill(); throw 'Node exceeded 30 seconds.' }; [ordered]@{ exit_code = $process.ExitCode; stdout = $stdout.Trim(); stderr = $stderr.Trim(); cpu_seconds = [math]::Round($process.TotalProcessorTime.TotalSeconds, 4) } } finally { $process.Dispose() } }

$repoRoot = Split-Path -Parent $PSScriptRoot
$paths = [ordered]@{
  source = Join-Path $repoRoot 'packages\chain-adapter\api\index.ts'; tests = Join-Path $repoRoot 'packages\chain-adapter\api\index.test.ts'; contract = Join-Path $repoRoot 'packages\chain-adapter\api\reducer-contract.v1.json'
  indexedSchema = Join-Path $repoRoot 'packages\chain-adapter\api\indexed-observation.v1.schema.json'; reducerPrisma = Join-Path $repoRoot 'packages\chain-adapter\api\reducer-model.prisma'
  event = Join-Path $repoRoot 'packages\contracts\events\action.chain.executed.v1.schema.json'; prisma = Join-Path $repoRoot 'packages\contracts\data\action-model.prisma'; architecture = Join-Path $repoRoot 'architecture\bounded-contexts.yaml'
  backlog = Join-Path $PSScriptRoot 'backlog-p0.yaml'; scorecard = Join-Path $PSScriptRoot 'capacity-scorecard.yaml'; checkpoint = Join-Path $PSScriptRoot 'checkpoints\NX-CHAIN-002.md'
  spend = Join-Path $PSScriptRoot 'spend-control.yaml'; guard = Join-Path $PSScriptRoot 'zero-cost-child-test.ps1'; capEvidence = Join-Path $PSScriptRoot 'evidence\NX-CAP-001-validation.json'
  checker = Join-Path $repoRoot 'security\source-boundary-check.js'; tsc = Join-Path $repoRoot 'packages\contracts\node_modules\typescript\bin\tsc'; lock = Join-Path $repoRoot 'packages\contracts\package-lock.json'
  architectureDoc = Join-Path $repoRoot 'docs\01-technical-architecture.md'; contractsDoc = Join-Path $repoRoot 'docs\02-smart-contracts.md'; validator = $PSCommandPath
}
foreach ($path in $paths.Values) { Assert-Reducer (Test-Path -LiteralPath $path -PathType Leaf) "Missing artifact: $path" }
Assert-Reducer ($RunId -match '^NX-CHAIN-002-[A-Za-z0-9T._-]+$') 'Run ID invalid.'; Assert-Reducer ($ExecutorRole -ne 'UNSPECIFIED') 'ExecutorRole required.'
$source = Read-Utf8 $paths.source; $tests = Read-Utf8 $paths.tests; $contract = Read-Utf8 $paths.contract | ConvertFrom-Json; $indexedSchema = Read-Utf8 $paths.indexedSchema | ConvertFrom-Json; $event = Read-Utf8 $paths.event | ConvertFrom-Json
$reducerPrisma = Read-Utf8 $paths.reducerPrisma; $prisma = Read-Utf8 $paths.prisma; $architecture = Read-Utf8 $paths.architecture; $backlog = Read-Utf8 $paths.backlog; $scorecard = Read-Utf8 $paths.scorecard; $checkpoint = Read-Utf8 $paths.checkpoint
$task = [regex]::Match($backlog, '(?ms)^  - task_id:\s*NX-CHAIN-002\s*\r?\n(.*?)(?=^  - task_id:|\z)'); Assert-Reducer $task.Success 'Task missing.'
if ($task.Success) { Assert-Reducer ($task.Groups[1].Value -match '(?m)^\s+owner_agent:\s*A22\s*$') 'Owner mismatch.'; Assert-Reducer ($task.Groups[1].Value -match '(?m)^\s+status:\s*(in_progress|review)\s*$') 'Task state invalid.'; Assert-Reducer ($task.Groups[1].Value -match '(?m)^\s+risk_class:\s*T0\s*$') 'Risk class mismatch.' }
Assert-Reducer ($scorecard -match '(?m)^\s+active_packets:\s+1\s*$' -and $scorecard -match '(?m)^\s+active_task_id:\s+NX-CHAIN-002\s*$') 'WIP/active task mismatch.'
Assert-Reducer ($checkpoint -match '(?m)^- Stare:\s*`(in_progress|review)`\s*$') 'Checkpoint state mismatch.'
Assert-Reducer ($architecture -match '(?ms)^  - id:\s*chain_integration\s*\r?\n.*?^\s+owner:\s*A22\s*$' -and $architecture -match '(?ms)^  - id:\s*chain_integration\s*\r?\n.*?^\s+public_api_path:\s*packages/chain-adapter/api\s*$') 'Architecture ownership/path mismatch.'

Assert-Reducer ($contract.schemaVersion -eq 1 -and $contract.contractVersion -eq '1.0.0' -and $contract.owner -eq 'A22') 'Reducer contract identity mismatch.'
Assert-Reducer ($contract.authoritativePredicate.canonicality -eq 'FINALIZED_CANONICAL' -and $contract.authoritativePredicate.finality -eq 'HYPERBLOCK_FINAL' -and $contract.authoritativePredicate.otherObservations -eq 'IGNORE') 'Authoritative predicate mismatch.'
Assert-Reducer ([bool]$contract.eventAuthenticity.verifierInjectionRequired -and [bool]$contract.eventAuthenticity.payloadMustMatchContentHash -and [bool]$contract.eventAuthenticity.restartAndRepairMustReverify -and (($contract.eventAuthenticity.persistedAnchors -join '|') -eq 'contentHash|authenticityProofHash') -and $contract.eventAuthenticity.invalidResult -eq 'DENY_BEFORE_PERSISTENCE') 'Event authenticity contract is incomplete.'
foreach ($field in @('network', 'contractAddress', 'originalTxHash', 'sourceTxHash', 'sourceKind', 'eventIndex', 'shard', 'blockNonce', 'blockHash', 'hyperblockNonce', 'hyperblockHash', 'canonicality', 'finality')) { Assert-Reducer ($field -in @($contract.eventAuthenticity.persistedLineage)) "Persisted lineage contract missing: $field" }
Assert-Reducer (($contract.idempotencyKey -join '|') -eq 'network|originalTxHash|sourceTxHash|eventIndex') 'Idempotency key mismatch.'
Assert-Reducer (($contract.deterministicOrder -join '|') -eq 'hyperblockNonce|blockNonce|sourceTxHash|eventIndex') 'Deterministic order mismatch.'
foreach ($invariant in @('journal_debits_equal_credits', 'no_negative_account_balance', 'contract_asset_equals_total_liabilities', 'observed_chain_balance_equals_contract_asset')) { Assert-Reducer ($invariant -in @($contract.accounting.invariants)) "Accounting invariant missing: $invariant" }
Assert-Reducer ($contract.checkpoint.failureMode -eq 'SERVE_VERIFIED_CHECKPOINT_MUTATIONS_DISABLED' -and $contract.checkpoint.atomicity -eq 'generation_compare_after_async_hash_before_promotion_for_every_checkpointed_field' -and $contract.checkpoint.concurrentMutationResult -eq 'DENY_CHECKPOINT_PROMOTION' -and -not [bool]$contract.repair.automaticEconomicWrite) 'Rollback or repair contract unsafe.'
foreach ($requirement in @('authenticated_authorization_verifier', 'subject_state_root_binding', 'authoritative_event_set_binding', 'finite_validity_window', 'single_use_approval')) { Assert-Reducer ($requirement -in @($contract.repair.requires)) "Repair control missing: $requirement" }
Assert-Reducer ($contract.repair.replayResult -eq 'DENY' -and $contract.repair.fabricatedRoleOrQuorumResult -eq 'DENY') 'Repair authorization fail-closed contract missing.'
Assert-Reducer ($contract.repair.durableCommit -eq 'unique_approval_receipt_and_replacement_event_set_in_one_serializable_transaction_before_memory_promotion' -and $contract.repair.restartRecovery -eq 'reload_complete_committed_observations_then_reverify') 'Durable repair commit contract missing.'
Assert-Reducer (-not [bool]$contract.privacy.rawWalletOrProfileAllowed -and [bool]$contract.privacy.commitmentsOnly -and -not [bool]$contract.privacy.kidsEventsAllowed) 'Privacy/Kids contract unsafe.'
Assert-Reducer ([int]$contract.localRtoFixture.events -eq 500 -and [int]$contract.localRtoFixture.maximumMilliseconds -eq 2000) 'Local RTO fixture mismatch.'
Assert-Reducer ($event.properties.data.properties.canonicality.const -eq 'FINALIZED_CANONICAL' -and $event.properties.data.properties.finality.const -eq 'HYPERBLOCK_FINAL') 'Source event finality contract drifted.'
Assert-Reducer ($prisma -match '@@id\(\[network, originalTxHash, sourceTxHash, eventIndex\]\)') 'Prisma event idempotency key drifted.'
foreach ($field in @('network', 'contractAddress', 'originalTxHash', 'sourceTxHash', 'sourceKind', 'eventIndex', 'shard', 'blockNonce', 'blockHash', 'hyperblockNonce', 'hyperblockHash', 'contentHash', 'authenticityProofHash', 'canonicality', 'finality', 'payload')) { Assert-Reducer ($indexedSchema.required -contains $field) "Indexed observation schema missing: $field" }
Assert-Reducer ($indexedSchema.additionalProperties -eq $false -and $indexedSchema.'x-persistence-model' -eq 'VerifiedChainObservation') 'Indexed observation authenticity schema drifted.'
foreach ($field in @('contractAddress', 'sourceKind', 'shard', 'blockNonce', 'blockHash', 'hyperblockNonce', 'hyperblockHash', 'contentHash', 'authenticityProofHash')) { Assert-Reducer ($reducerPrisma -match "(?m)^\s*$field\s+String|(?m)^\s*$field\s+Int") "Reducer persistence missing lineage/authenticity field: $field" }
Assert-Reducer ($reducerPrisma -match '@@id\(\[network, originalTxHash, sourceTxHash, eventIndex\]\)' -and $reducerPrisma -match '(?m)^model ReducerRepairCommit\s*\{' -and $reducerPrisma -match '(?m)^\s*approvalId\s+String\s+@id' -and $reducerPrisma -match '(?m)^\s*observations\s+Json') 'Reducer persistence lacks idempotency or durable unique repair commit.'

$sourceFragments = @('FINALITY_CANONICALITY_MISMATCH', 'EventAuthenticityVerifier', 'authenticityProofHash', 'serializeObservationForPersistence', 'restoreObservationFromPersistence', 'EVENT_AUTHENTICITY_INVALID', 'REPAIR_EVENT_AUTHENTICITY_INVALID', 'canonicalValue', 'AGGREGATE_VERSION_CONFLICT', 'BALANCE_OBSERVATION_CONFLICT', 'JOURNAL_UNBALANCED', 'NEGATIVE_LEDGER_BALANCE', 'ACCOUNTING_EQUATION_MISMATCH', 'CHAIN_BALANCE_MISMATCH', 'SERVE_VERIFIED_CHECKPOINT_MUTATIONS_DISABLED', 'createAndPromoteCheckpoint', 'capturedGeneration', 'CHECKPOINT_CONCURRENT_MUTATION', 'verifyCheckpoint', 'repairFromAuthoritative', 'RepairAuthorizationVerifier', 'RepairCommitStore', 'commitRepairAtomically', 'subjectStateRoot', 'authoritativeSetHash', 'expiresAtMs', 'REPAIR_APPROVAL_REPLAY', 'sourceQuorumVerified', 'economicEffect !== false', 'REPAIR_NOT_REQUIRED')
foreach ($fragment in $sourceFragments) { Assert-Reducer ($source.Contains($fragment)) "Source control missing: $fragment" }
Assert-Reducer ($source -notmatch '(?i)(fetch\s*\(|XMLHttpRequest|HttpClient|WebClient|Invoke-WebRequest|https?\.request|child_process|net\.connect)') 'Reducer contains network/process capability.'
Assert-Reducer ($source -notmatch '(?i)(emailAddress|phoneNumber|latitude|longitude|messagePlaintext|datingTarget|childId)\s*[:=]') 'Reducer contains forbidden plaintext model.'
foreach ($fragment in @('out-of-order delivery converges', 'database serialize reload reconstructs identical deterministic state', 'database round trip preserves canonical state root', 'prefinalized observation is ignored', 'invalid event authenticity is denied before persistence', 'different balances at one hyperblock require reconciliation', 'double-entry journals reconcile exactly', 'one account cannot spend another account liability', 'tampered checkpoint is rejected', 'rollback serves last verified checkpoint', 'repair atomically persists approval consumption', 'cross-restart replay test', 'REPAIR_AUTHORIZATION_INVALID', 'REPAIR_APPROVAL_REPLAY', 'CHECKPOINT_CONCURRENT_MUTATION', 'duplicate counter mutation is generation fenced', 'ignored observation counter mutation is generation fenced', 'full authoritative rebuild')) { Assert-Reducer ($tests.Contains($fragment)) "Test control missing: $fragment" }

$cap = Read-Utf8 $paths.capEvidence | ConvertFrom-Json; Assert-Reducer ($cap.status -eq 'PASS' -and [int]$cap.blocked_economic_actions -ge 1 -and [int]$cap.blocked_unallowlisted_egress_actions -ge 1) 'Zero-cost guard evidence invalid.'
Assert-Reducer ($cap.artifact_sha256.'planning/spend-control.yaml' -eq (Get-Sha256 $paths.spend) -and $cap.artifact_sha256.'planning/zero-cost-child-test.ps1' -eq (Get-Sha256 $paths.guard)) 'Zero-cost controls drifted.'
$credentialPattern = '^(AWS_|AZURE_|GOOGLE_APPLICATION_CREDENTIALS$|OPENAI_API_KEY$|TWILIO_|MAPBOX_|CLOUDFLARE_|STRIPE_|PINATA_|IPFS_|MATRIX_)'; $credentialNames = @([Environment]::GetEnvironmentVariables().Keys | ForEach-Object { [string]$_ } | Where-Object { $_ -match $credentialPattern }); Assert-Reducer ($credentialNames.Count -eq 0) 'Billing/production credentials present.'

$node = Get-Node; Assert-Reducer ($null -ne $node) 'Included Node runtime missing.'; $ephemeral = Join-Path $repoRoot '.ephemeral'; if (-not (Test-Path -LiteralPath $ephemeral)) { [void](New-Item -ItemType Directory -Path $ephemeral) }; $runRoot = Join-Path $ephemeral ('NX-CHAIN-002-validator-' + [Guid]::NewGuid().ToString('N')); [void](New-Item -ItemType Directory -Path $runRoot)
$receipt = $null; $boundary = $null; $compile = $null; $testRun = $null
try { if ($null -ne $node) { $compile = Invoke-Node $node @($paths.tsc, '--strict', '--target', 'ES2022', '--module', 'commonjs', '--lib', 'ES2022,DOM', '--outDir', $runRoot, $paths.source, $paths.tests) $repoRoot; Assert-Reducer ($compile.exit_code -eq 0) "TypeScript compile failed: $($compile.stderr)"; if ($compile.exit_code -eq 0) { $testRun = Invoke-Node $node @((Join-Path $runRoot 'index.test.js')) $repoRoot; Assert-Reducer ($testRun.exit_code -eq 0) "Reducer tests failed: $($testRun.stderr)"; if ($testRun.exit_code -eq 0) { try { $receipt = $testRun.stdout | ConvertFrom-Json } catch { Assert-Reducer $false 'Test receipt is not JSON.' } } }; $manifest = [pscustomobject]@{ knownSpecifiers = [pscustomobject]@{ chain_actions = 'chain_actions'; chain_escrow = 'chain_escrow'; contract_registry = 'contract_registry' }; knownSchemas = @('chain_integration', 'chain_actions', 'chain_escrow', 'contract_registry'); contexts = [pscustomobject]@{ chain_integration = [pscustomobject]@{ allowedImports = @('chain_actions', 'chain_escrow', 'contract_registry') } }; items = @([pscustomobject]@{ id = 'packages/chain-adapter/api/index.ts'; sourceContext = 'chain_integration'; text = $source }, [pscustomobject]@{ id = 'packages/chain-adapter/api/index.test.ts'; sourceContext = 'chain_integration'; text = $tests }) }; $manifestPath = Join-Path $runRoot 'boundary.json'; [IO.File]::WriteAllText($manifestPath, ($manifest | ConvertTo-Json -Depth 8), [Text.UTF8Encoding]::new($false)); $boundaryRun = Invoke-Node $node @($paths.checker, $manifestPath) $repoRoot; Assert-Reducer ($boundaryRun.exit_code -eq 0) "Boundary checker failed: $($boundaryRun.stderr)"; if ($boundaryRun.exit_code -eq 0) { $boundary = $boundaryRun.stdout | ConvertFrom-Json } } } finally { $prefix = [IO.Path]::GetFullPath($ephemeral).TrimEnd('\') + '\'; $resolved = [IO.Path]::GetFullPath($runRoot); if ((Test-Path -LiteralPath $runRoot) -and $resolved.StartsWith($prefix, [StringComparison]::OrdinalIgnoreCase)) { Remove-Item -LiteralPath $runRoot -Recurse -Force } }
Assert-Reducer ($null -ne $receipt) 'Test receipt missing.'
if ($null -ne $receipt) { Assert-Reducer ($receipt.status -eq 'PASS' -and $receipt.task_id -eq 'NX-CHAIN-002') 'Test receipt failed.'; Assert-Reducer ([int]$receipt.assertions -ge 70) 'Scenario assertions regressed.'; Assert-Reducer ([bool]$receipt.replay_report.duplicate_idempotent -and [bool]$receipt.replay_report.out_of_order_converged -and [bool]$receipt.replay_report.prefinalized_reorg_ignored -and [bool]$receipt.replay_report.persistence_round_trip -and [bool]$receipt.replay_report.state_root_preserved) 'Replay acceptance failed.'; Assert-Reducer ([int]$receipt.reconciliation_report.balanced_journals -eq 3 -and $receipt.reconciliation_report.final_asset -eq $receipt.reconciliation_report.final_liability) 'Reconciliation acceptance failed.'; Assert-Reducer ([bool]$receipt.failure_injection.served_checkpoint -and $receipt.failure_injection.balance_mismatch -eq 'MUTATIONS_DISABLED' -and $receipt.failure_injection.checkpoint_concurrent_mutation -eq 'DENY' -and $receipt.failure_injection.duplicate_counter_concurrent_mutation -eq 'DENY' -and $receipt.failure_injection.ignored_counter_concurrent_mutation -eq 'DENY') 'Failure injection/rollback failed.'; Assert-Reducer ([bool]$receipt.repair_authorization.authenticated -and [bool]$receipt.repair_authorization.subject_bound -and [bool]$receipt.repair_authorization.event_set_bound -and [bool]$receipt.repair_authorization.expiring -and [bool]$receipt.repair_authorization.replay_denied -and [bool]$receipt.repair_authorization.cross_restart_replay_denied -and [bool]$receipt.repair_authorization.atomic_persistent_commit) 'Repair authorization acceptance failed.'; Assert-Reducer ([bool]$receipt.rebuild_rto.within_limit -and [int]$receipt.rebuild_rto.elapsed_ms -lt [int]$receipt.rebuild_rto.declared_limit_ms) 'Local rebuild RTO failed.'; Assert-Reducer ([bool]$receipt.synthetic_only -and [int]$receipt.network_operations -eq 0 -and [int]$receipt.economic_operations -eq 0) 'Tests are not zero-effect synthetic.' }
$boundaryFindings = @(); if ($null -ne $boundary) { foreach ($item in @($boundary.results)) { foreach ($finding in @($item.findings)) { $boundaryFindings += "$($item.id):$finding" } } }; Assert-Reducer ($null -ne $boundary -and $boundaryFindings.Count -eq 0) ('Boundary findings: ' + ($boundaryFindings -join ','))
$hashes = [ordered]@{}; foreach ($path in $paths.Values) { if (Test-Path -LiteralPath $path -PathType Leaf) { $relative = $path.Substring($repoRoot.Length).TrimStart('\').Replace('\', '/'); $hashes[$relative] = Get-Sha256 $path } }; $subject = Get-StringSha256 (($hashes.GetEnumerator() | Sort-Object Key | ForEach-Object { "$($_.Key)=$($_.Value)" }) -join "`n"); $timer.Stop()
$result = [ordered]@{ schema_version = 1; task_id = 'NX-CHAIN-002'; run_id = $RunId; executor_role = $ExecutorRole; status = if ($failures.Count -eq 0) { 'PASS' } else { 'FAIL' }; assertions = $assertions; scenario_assertions = if ($null -ne $receipt) { [int]$receipt.assertions } else { 0 }; failures = @($failures); acceptance = if ($null -ne $receipt) { $receipt } else { $null }; source_boundary_findings = $boundaryFindings.Count; credential_name_matches = $credentialNames.Count; network_operations = 0; economic_operations = 0; incremental_cost = [ordered]@{ amount = 0; currency = 'EUR' }; claims_excluded = @('mainnet_repair', 'production_rto', 'real_funds_reconciliation', 'external_chain_audit'); review_subject_sha256 = $subject; artifact_sha256 = $hashes; duration_seconds = [math]::Round($timer.Elapsed.TotalSeconds, 4) }
$result | ConvertTo-Json -Depth 12; if ($failures.Count -gt 0) { exit 1 }
