[CmdletBinding()]param(
  [string]$RunId=('NX-DATING-P01-'+[DateTimeOffset]::UtcNow.ToString('yyyyMMddTHHmmssfffZ')+'-'+[Guid]::NewGuid().ToString('N').Substring(0,8)),
  [ValidateSet('UNSPECIFIED','A33','C02','C04','C06','C08')][string]$ExecutorRole='UNSPECIFIED'
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$timer=[Diagnostics.Stopwatch]::StartNew()
$failures=[Collections.Generic.List[string]]::new()
$assertions=0
function Assert-Dating([bool]$Condition,[string]$Message){$script:assertions++;if(-not $Condition){$script:failures.Add($Message)}}
function Read-Utf8([string]$Path){[IO.File]::ReadAllText($Path,[Text.Encoding]::UTF8)}
function Get-Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Get-TextSha([string]$Value){$s=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($s.ComputeHash([Text.Encoding]::UTF8.GetBytes($Value)))).Replace('-','').ToLowerInvariant()}finally{$s.Dispose()}}
function Get-Node{$r=Join-Path([Environment]::GetFolderPath('LocalApplicationData'))'OpenAI\Codex\bin';if(Test-Path -LiteralPath $r){Get-ChildItem -LiteralPath $r -Filter node.exe -File -Recurse|Sort-Object FullName|Select-Object -Last 1 -ExpandProperty FullName}}
function Invoke-Node([string]$Node,[string[]]$Arguments,[string]$WorkingDirectory){$q=@($Arguments|ForEach-Object{'"'+$_.Replace('"','\"')+'"'})-join' ';$i=[Diagnostics.ProcessStartInfo]::new();$i.FileName=$Node;$i.Arguments=$q;$i.WorkingDirectory=$WorkingDirectory;$i.UseShellExecute=$false;$i.CreateNoWindow=$true;$i.RedirectStandardOutput=$true;$i.RedirectStandardError=$true;$p=[Diagnostics.Process]::new();$p.StartInfo=$i;try{if(-not$p.Start()){throw'node start failed'};$o=$p.StandardOutput.ReadToEnd();$e=$p.StandardError.ReadToEnd();if(-not$p.WaitForExit(30000)){$p.Kill();throw'node timeout'};[ordered]@{exit_code=$p.ExitCode;stdout=$o.Trim();stderr=$e.Trim()}}finally{$p.Dispose()}}

$root=Split-Path -Parent $PSScriptRoot
$paths=[ordered]@{
  source=Join-Path $root 'packages\dating\api\index.ts'; tests=Join-Path $root 'packages\dating\api\index.test.ts'; contract=Join-Path $root 'packages\dating\api\dating-contract.v1.json'; chain=Join-Path $root 'packages\chain-actions-api\index.ts'; chain_tests=Join-Path $root 'packages\chain-actions-api\index.test.ts'
  dating_doc=Join-Path $root 'docs\14-dating-pulse-discretion-trust.md'; flows=Join-Path $root 'docs\05-user-flows.md'; security_doc=Join-Path $root 'docs\04-security-compliance.md'; ledger_doc=Join-Path $root 'docs\09-action-ledger-classifieds.md'; architecture=Join-Path $root 'architecture\bounded-contexts.yaml'
  backlog0=Join-Path $PSScriptRoot 'backlog-p0.yaml'; backlog1=Join-Path $PSScriptRoot 'backlog-p1.yaml'; capacity=Join-Path $PSScriptRoot 'capacity-scorecard.yaml'; progress=Join-Path $PSScriptRoot 'product-progress.yaml'; checkpoint=Join-Path $PSScriptRoot 'checkpoints\NX-DATING-P01.md'; spend=Join-Path $PSScriptRoot 'spend-control.yaml'
  profile_evidence=Join-Path $PSScriptRoot 'evidence\NX-PROFILE-P01-validation.json'; chat_evidence=Join-Path $PSScriptRoot 'evidence\NX-CHAT-P01-validation.json'; moderation_evidence=Join-Path $PSScriptRoot 'evidence\NX-MOD-P01-validation.json'; security_evidence=Join-Path $PSScriptRoot 'evidence\NX-SEC-001-validation.json'; chain_evidence=Join-Path $PSScriptRoot 'evidence\NX-CHAIN-002-validation.json'
  boundary=Join-Path $root 'security\source-boundary-check.js'; tsc=Join-Path $root 'packages\contracts\node_modules\typescript\bin\tsc'; lock=Join-Path $root 'packages\contracts\package-lock.json'; validator=$PSCommandPath
}
foreach($p in $paths.Values){Assert-Dating (Test-Path -LiteralPath $p -PathType Leaf) "Missing: $p"}
Assert-Dating ($RunId-match'^NX-DATING-P01-[A-Za-z0-9T._-]+$') 'Run invalid'
Assert-Dating ($ExecutorRole-ne'UNSPECIFIED') 'Role required'
$source=Read-Utf8 $paths.source;$tests=Read-Utf8 $paths.tests;$contract=Read-Utf8 $paths.contract|ConvertFrom-Json;$b0=Read-Utf8 $paths.backlog0;$b1=Read-Utf8 $paths.backlog1;$cap=Read-Utf8 $paths.capacity;$progress=Read-Utf8 $paths.progress;$checkpoint=Read-Utf8 $paths.checkpoint;$architecture=Read-Utf8 $paths.architecture;$spend=Read-Utf8 $paths.spend
$task=[regex]::Match($b1,'(?ms)^  - task_id:\s*NX-DATING-P01\s*\r?\n(.*?)(?=^  - task_id:|\z)')
Assert-Dating $task.Success 'Packet missing'
if($task.Success){Assert-Dating ($task.Groups[1].Value-match'(?m)^\s+owner_agent:\s*A33\s*$') 'Owner drift';Assert-Dating ($task.Groups[1].Value-match'(?m)^\s+status:\s*(in_progress|review)\s*$') 'Packet inactive';Assert-Dating ($task.Groups[1].Value-match'(?m)^\s+risk_class:\s*T0\s*$') 'Risk drift'}
foreach($d in @('NX-CHAIN-001','NX-CHAIN-002','NX-SEC-001')){$m=[regex]::Match($b0,('(?ms)^  - task_id:\s*'+$d+'\s*\r?\n(.*?)(?=^  - task_id:|\z)'));Assert-Dating ($m.Success-and$m.Groups[1].Value-match'(?m)^\s+status:\s*done\s*$') "P0 dependency $d"}
foreach($d in @('NX-PROFILE-P01','NX-CHAT-P01','NX-MOD-P01')){$m=[regex]::Match($b1,('(?ms)^  - task_id:\s*'+$d+'\s*\r?\n(.*?)(?=^  - task_id:|\z)'));Assert-Dating ($m.Success-and$m.Groups[1].Value-match'(?m)^\s+status:\s*done\s*$') "P1 dependency $d"}
$active=@([regex]::Matches($b1,'(?ms)^  - task_id:\s*(\S+)\s*\r?\n(.*?)(?=^  - task_id:|\z)')|Where-Object{$_.Groups[2].Value-match'(?m)^\s+record_kind:\s*task_packet\s*$'-and$_.Groups[2].Value-match'(?m)^\s+status:\s*(in_progress|review)\s*$'}|ForEach-Object{$_.Groups[1].Value})
Assert-Dating ($active.Count-eq1-and$active[0]-eq'NX-DATING-P01') 'WIP violated'
Assert-Dating ($cap-match'(?m)^\s+active_task_id:\s+NX-DATING-P01\s*$'-and$cap-match'(?m)^\s+active_packets:\s+1\s*$') 'Capacity mismatch'
Assert-Dating ($progress-match'(?m)^\s+active_packet_id:\s+NX-DATING-P01\s*$') 'Progress mismatch'
Assert-Dating ($checkpoint-match'(?m)^- Stare:\s*`(in_progress|review)`\s*$') 'Checkpoint mismatch'
Assert-Dating ($architecture-match'(?ms)^  - id:\s*dating\s*\r?\n.*?^\s+owner:\s*A33\s*$') 'Dating boundary missing'

Assert-Dating ($contract.schemaVersion-eq1-and$contract.owner-eq'A33'-and$contract.surface-eq'DATING_PRIVATE_COMMITMENTS') 'Contract identity'
Assert-Dating ([bool]$contract.trust.adultVerified-and[bool]$contract.trust.photoMatch-and[int]$contract.trust.recentLivenessMaxDays-eq30-and-not[bool]$contract.trust.rawKycStored-and[bool]$contract.trust.currentAuthorityRequired-and[bool]$contract.trust.claimAndVersionBound-and[bool]$contract.trust.preAndPostPrepareCas) 'Trust contract'
Assert-Dating (-not[bool]$contract.privacy.targetInApiOrChain-and-not[bool]$contract.privacy.preferenceInApiOrChain-and-not[bool]$contract.privacy.preciseLocationInApiOrChain-and[int]$contract.privacy.saltEntropyBits-ge128-and[bool]$contract.privacy.generatedOnDevice-and-not[bool]$contract.privacy.globalSearchEligible) 'Privacy contract'
Assert-Dating ($contract.action.type-eq'PRIVATE_ACTION'-and[bool]$contract.action.exactAuthorizationBinding-and[bool]$contract.action.exactChainReceiptBindingBeforeEmission-and[bool]$contract.action.postSignatureProfilePolicyTrustCas-and[bool]$contract.action.preparedAbortOnConflict-and[bool]$contract.action.oneTimeAuthorization-and[bool]$contract.action.persistentNonceKey) 'Action contract'
Assert-Dating ([bool]$contract.restore.signedAuthorizationPerReceipt-and[bool]$contract.restore.orderedHashLineage-and[bool]$contract.restore.durableCheckpointHeadRequired-and[bool]$contract.restore.rebuildsAuthorizationAndNonceIndexes-and[bool]$contract.restore.exactShape) 'Restore contract'
foreach($f in @('DatingTrustClaims','DatingTrustBoundary','trustExpiresAt','trustClaimId','trustVersion','preparePrivateAction','PRIVATE_ACTION','PRIVATE_COMMITMENT','targetIncludedInClear:false','saltEntropyBits:128','DATING_EXECUTION_STATE_CONFLICT','commitPreparedAction(prepared,expected)','abortPreparedAction','usedNonces','receiptCanonical','DatingCheckpointBoundary','scanDatingLeakage','static async restore')){Assert-Dating $source.Contains($f) "Source missing $f"}
foreach($f in @('trust race aborts prepared token','policy race produces no private action','PREPARED_ACTION_INVALID','PREPARED_ACTION_BINDING_MISMATCH','commit failure creates no orphan event','same authorization concurrency has exactly one winner','DATING_ENVELOPE_BINDING_MISMATCH','DATING_AUTH_REPLAY','target preference orientation or location','checkpoint remains free','DATING_CHECKPOINT_STALE','likedProfile')){Assert-Dating $tests.Contains($f) "Test missing $f"}
foreach($pair in @(@($paths.dating_doc,'Adult Verified'),@($paths.dating_doc,'Sex life'),@($paths.flows,'PRIVATE_ACTION'),@($paths.security_doc,'Special/sensibil'),@($paths.ledger_doc,'PRIVATE_ACTION'))){Assert-Dating (Read-Utf8 $pair[0]).Contains($pair[1]) "Normative missing $($pair[1])"}
Assert-Dating ($source-notmatch'(?i)(fetch\s*\(|XMLHttpRequest|HttpClient|WebClient|Invoke-WebRequest|https?\.request|child_process|net\.connect|console\.log)') 'Runtime effect capability'
Assert-Dating ($spend-match'(?m)^mode:\s*default_deny_spend\s*$'-and$spend-match'(?m)^\s*max_incremental_amount:\s*0\s*$') 'Spend guard'
foreach($ep in @($paths.profile_evidence,$paths.chat_evidence,$paths.moderation_evidence,$paths.security_evidence,$paths.chain_evidence)){$ev=Read-Utf8 $ep|ConvertFrom-Json;Assert-Dating ($ev.status-eq'PASS') "Dependency evidence $ep"}
$cred='^(AWS_|AZURE_|GOOGLE_APPLICATION_CREDENTIALS$|OPENAI_API_KEY$|TWILIO_|MAPBOX_|CLOUDFLARE_|STRIPE_|PINATA_|IPFS_|MATRIX_|XMONEY_)';$names=@([Environment]::GetEnvironmentVariables().Keys|ForEach-Object{[string]$_}|Where-Object{$_-match$cred});Assert-Dating ($names.Count-eq0) 'Credentials present'

$node=Get-Node;Assert-Dating ($null-ne$node) 'Node missing';$base=Join-Path $root '.ephemeral';[IO.Directory]::CreateDirectory($base)|Out-Null;$run=Join-Path $base ('NX-DATING-P01-'+[Guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($run)|Out-Null;$runs=@();$receipt=$null;$boundaryResult=$null
try{if($null-ne$node){$c=Invoke-Node $node @($paths.tsc,'--strict','--target','ES2022','--module','commonjs','--lib','ES2022,DOM','--outDir',$run,$paths.source,$paths.tests,$paths.chain) $root;Assert-Dating ($c.exit_code-eq0) "Compile: $($c.stderr)";if($c.exit_code-eq0){$test=Join-Path $run 'dating\api\index.test.js';1..3|ForEach-Object{$script:runs+=Invoke-Node $node @($test) $root};foreach($x in $runs){Assert-Dating ($x.exit_code-eq0) "Tests: $($x.stderr)"};Assert-Dating (@($runs.stdout|Sort-Object -Unique).Count-eq1) 'Nondeterministic';try{$receipt=$runs[0].stdout|ConvertFrom-Json}catch{Assert-Dating $false 'Bad receipt'}};$manifest=[pscustomobject]@{knownSpecifiers=[pscustomobject]@{'@nexus/profile'='profile_core';'@nexus/moderation'='moderation';'@nexus/messaging'='messaging';'@nexus/chain'='chain_integration';'@nexus/contracts'='contract_registry'};knownSchemas=@('dating','profile_core','moderation','messaging','chain_integration','contract_registry');contexts=[pscustomobject]@{dating=[pscustomobject]@{allowedImports=@('profile_core','moderation','messaging','chain_integration','contract_registry')}};items=@([pscustomobject]@{id='packages/dating/api/index.ts';sourceContext='dating';text=$source})};$mp=Join-Path $run 'boundary.json';[IO.File]::WriteAllText($mp,($manifest|ConvertTo-Json -Depth 8),[Text.UTF8Encoding]::new($false));$br=Invoke-Node $node @($paths.boundary,$mp) $root;Assert-Dating ($br.exit_code-eq0) "Boundary: $($br.stderr)";if($br.exit_code-eq0){$boundaryResult=$br.stdout|ConvertFrom-Json}}}
finally{$prefix=[IO.Path]::GetFullPath($base).TrimEnd('\')+'\';$resolved=[IO.Path]::GetFullPath($run);if((Test-Path -LiteralPath $run)-and$resolved.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){Remove-Item -LiteralPath $run -Recurse -Force}}
Assert-Dating ($null-ne$receipt) 'Receipt missing'
if($null-ne$receipt){Assert-Dating ($receipt.status-eq'PASS'-and[int]$receipt.assertions-ge26) 'Receipt regression';Assert-Dating ([bool]$receipt.profile.adult_verified-and[bool]$receipt.profile.trust_current_state-and[bool]$receipt.profile.incognito-and-not[bool]$receipt.profile.global_search-and-not[bool]$receipt.profile.organic_metrics) 'Profile isolation';Assert-Dating ($receipt.private_actions.action_class-eq'PRIVATE_ACTION'-and[int]$receipt.private_actions.count-eq2-and[int]$receipt.private_actions.salt_entropy_bits-ge128-and-not[bool]$receipt.private_actions.target_in_clear-and[bool]$receipt.private_actions.exact_chain_receipt-and[bool]$receipt.private_actions.ordered_lineage) 'Private actions';Assert-Dating ([int]$receipt.leakage.target-eq0-and[int]$receipt.leakage.preference-eq0-and[int]$receipt.leakage.orientation-eq0-and[int]$receipt.leakage.location-eq0-and[int]$receipt.leakage.pii-eq0) 'Leakage';foreach($p in @('exact_shape','boolean_string','trust_race','policy_race','retained_prepared_action','envelope_substitution','chain_receipt_substitution','commit_failure','authorization_replay','nonce_replay','concurrent_authorization','restore_replay','snapshot_exact_shape','snapshot_target_leak','snapshot_prefix','snapshot_fabrication')){Assert-Dating ([bool]$receipt.negative.$p) "Negative $p"};Assert-Dating ([int]$receipt.network_operations-eq0-and[int]$receipt.provider_operations-eq0-and[int]$receipt.economic_operations-eq0-and[decimal]$receipt.incremental_cost.amount-eq0) 'Effects escaped'}
$findings=@();if($null-ne$boundaryResult){foreach($item in @($boundaryResult.results)){foreach($f in @($item.findings)){$findings+="$($item.id):$f"}}};Assert-Dating ($null-ne$boundaryResult-and$findings.Count-eq0) ('Boundary findings '+($findings-join','))
$hashes=[ordered]@{};foreach($p in $paths.Values){if(Test-Path -LiteralPath $p -PathType Leaf){$rel=$p.Substring($root.Length).TrimStart('\').Replace('\','/');$hashes[$rel]=Get-Sha $p}};$subject=Get-TextSha(($hashes.GetEnumerator()|Sort-Object Key|ForEach-Object{"$($_.Key)=$($_.Value)"})-join"`n")
$timer.Stop();$result=[ordered]@{schema_version=1;task_id='NX-DATING-P01';run_id=$RunId;executor_role=$ExecutorRole;status=if($failures.Count-eq0){'PASS'}else{'FAIL'};scope='local_synthetic_adult_dating_isolation_private_commitment_and_fail_closed_restore';assertions=$assertions;scenario_assertions=if($receipt){[int]$receipt.assertions}else{0};deterministic_repetitions=@($runs).Count;failures=@($failures);profile=if($receipt){$receipt.profile}else{$null};private_actions=if($receipt){$receipt.private_actions}else{$null};leakage=if($receipt){$receipt.leakage}else{$null};negative=if($receipt){$receipt.negative}else{$null};source_boundary_findings=$findings.Count;credential_name_matches=$names.Count;network_operations=0;economic_operations=0;external_provider_operations=0;real_fund_operations=0;incremental_cost=[ordered]@{amount=0;currency='EUR'};claims_excluded=@('real_users','real_kyc','external_liveness','production_matching','mainnet','legal_opinion','formal_security_audit','meet_safe_e2e');review_subject_sha256=$subject;artifact_sha256=$hashes;duration_seconds=[math]::Round($timer.Elapsed.TotalSeconds,4)}
$result|ConvertTo-Json -Depth 12
if($failures.Count-gt0){exit 1}
