[CmdletBinding()]
param(
    [string]$RunId = ('NX-CHAT-P01-' + [DateTimeOffset]::UtcNow.ToString('yyyyMMddTHHmmssfffZ') + '-' + [Guid]::NewGuid().ToString('N').Substring(0, 8)),
    [ValidateSet('UNSPECIFIED', 'A14', 'C01', 'C02', 'C04', 'C06')][string]$ExecutorRole = 'UNSPECIFIED'
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$timer = [Diagnostics.Stopwatch]::StartNew(); $failures = [Collections.Generic.List[string]]::new(); $assertions = 0
function Assert-Chat { param([bool]$Condition, [string]$Message) $script:assertions++; if (-not $Condition) { $script:failures.Add($Message) } }
function Read-Utf8 { param([string]$Path) [IO.File]::ReadAllText($Path, [Text.Encoding]::UTF8) }
function Get-Sha256 { param([string]$Path) (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant() }
function Get-StringSha256 { param([string]$Value) $sha = [Security.Cryptography.SHA256]::Create(); try { ([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Value)))).Replace('-', '').ToLowerInvariant() } finally { $sha.Dispose() } }
function Get-IncludedNodeRuntime { $root = Join-Path ([Environment]::GetFolderPath('LocalApplicationData')) 'OpenAI\Codex\bin'; if (-not (Test-Path -LiteralPath $root)) { return $null }; Get-ChildItem -LiteralPath $root -Filter node.exe -File -Recurse -ErrorAction SilentlyContinue | Sort-Object FullName | Select-Object -Last 1 -ExpandProperty FullName }
function Invoke-LocalNode { param([string]$Node, [string[]]$Arguments, [string]$WorkingDirectory) $quoted = @($Arguments | ForEach-Object { '"' + $_.Replace('"', '\"') + '"' }) -join ' '; $info = [Diagnostics.ProcessStartInfo]::new(); $info.FileName = $Node; $info.Arguments = $quoted; $info.WorkingDirectory = $WorkingDirectory; $info.UseShellExecute = $false; $info.CreateNoWindow = $true; $info.RedirectStandardOutput = $true; $info.RedirectStandardError = $true; $process = [Diagnostics.Process]::new(); $process.StartInfo = $info; try { if (-not $process.Start()) { throw 'Node process did not start.' }; $stdout = $process.StandardOutput.ReadToEnd(); $stderr = $process.StandardError.ReadToEnd(); if (-not $process.WaitForExit(30000)) { $process.Kill(); throw 'Node process exceeded 30 seconds.' }; [ordered]@{ exit_code = $process.ExitCode; stdout = $stdout.Trim(); stderr = $stderr.Trim(); cpu_seconds = [math]::Round($process.TotalProcessorTime.TotalSeconds, 4) } } finally { $process.Dispose() } }

$repoRoot = Split-Path -Parent $PSScriptRoot
$paths = [ordered]@{
  source = Join-Path $repoRoot 'packages\messaging\api\index.ts'
  tests = Join-Path $repoRoot 'packages\messaging\api\index.test.ts'
  contract = Join-Path $repoRoot 'packages\messaging\api\messaging-contract.v1.json'
  chain_actions = Join-Path $repoRoot 'packages\chain-actions-api\index.ts'
  chain_reducer = Join-Path $repoRoot 'packages\chain-adapter\api\index.ts'
  smart_contract_doc = Join-Path $repoRoot 'docs\02-smart-contracts.md'
  security_doc = Join-Path $repoRoot 'docs\04-security-compliance.md'
  action_doc = Join-Path $repoRoot 'docs\09-action-ledger-classifieds.md'
  architecture = Join-Path $repoRoot 'architecture\bounded-contexts.yaml'
  backlog_p0 = Join-Path $PSScriptRoot 'backlog-p0.yaml'
  backlog_p1 = Join-Path $PSScriptRoot 'backlog-p1.yaml'
  capacity = Join-Path $PSScriptRoot 'capacity-scorecard.yaml'
  progress = Join-Path $PSScriptRoot 'product-progress.yaml'
  checkpoint = Join-Path $PSScriptRoot 'checkpoints\NX-CHAT-P01.md'
  spend = Join-Path $PSScriptRoot 'spend-control.yaml'
  cap_evidence = Join-Path $PSScriptRoot 'evidence\NX-CAP-001-validation.json'
  chain_evidence = Join-Path $PSScriptRoot 'evidence\NX-CHAIN-002-validation.json'
  boundary_checker = Join-Path $repoRoot 'security\source-boundary-check.js'
  tsc = Join-Path $repoRoot 'packages\contracts\node_modules\typescript\bin\tsc'
  package_lock = Join-Path $repoRoot 'packages\contracts\package-lock.json'
  validator = $PSCommandPath
}
foreach ($path in $paths.Values) { Assert-Chat (Test-Path -LiteralPath $path -PathType Leaf) "Missing artifact: $path" }
Assert-Chat ($RunId -match '^NX-CHAT-P01-[A-Za-z0-9T._-]+$') 'Run ID format is invalid.'; Assert-Chat ($ExecutorRole -ne 'UNSPECIFIED') 'ExecutorRole must be explicit.'
$source = Read-Utf8 $paths.source; $tests = Read-Utf8 $paths.tests; $contract = Read-Utf8 $paths.contract | ConvertFrom-Json; $smartDoc = Read-Utf8 $paths.smart_contract_doc; $securityDoc = Read-Utf8 $paths.security_doc; $actionDoc = Read-Utf8 $paths.action_doc; $architecture = Read-Utf8 $paths.architecture; $backlogP0 = Read-Utf8 $paths.backlog_p0; $backlogP1 = Read-Utf8 $paths.backlog_p1; $capacity = Read-Utf8 $paths.capacity; $progress = Read-Utf8 $paths.progress; $checkpoint = Read-Utf8 $paths.checkpoint; $spend = Read-Utf8 $paths.spend; $capEvidence = Read-Utf8 $paths.cap_evidence | ConvertFrom-Json; $chainEvidence = Read-Utf8 $paths.chain_evidence | ConvertFrom-Json

$task = [regex]::Match($backlogP1, '(?ms)^  - task_id:\s*NX-CHAT-P01\s*\r?\n(.*?)(?=^  - task_id:|\z)'); Assert-Chat $task.Success 'NX-CHAT-P01 missing.'
if ($task.Success) { Assert-Chat ($task.Groups[1].Value -match '(?m)^\s+record_kind:\s*task_packet\s*$') 'Not a task packet.'; Assert-Chat ($task.Groups[1].Value -match '(?m)^\s+owner_agent:\s*A14\s*$') 'Owner is not A14.'; Assert-Chat ($task.Groups[1].Value -match '(?m)^\s+status:\s*(in_progress|review)\s*$') 'Packet is not active.'; Assert-Chat ($task.Groups[1].Value -match '(?m)^\s+risk_class:\s*T0\s*$') 'Packet is not T0.' }
foreach ($dependency in @('NX-AUTH-001', 'NX-PLAT-001', 'NX-CHAIN-001', 'NX-CHAIN-002')) { $record = [regex]::Match($backlogP0, ('(?ms)^  - task_id:\s*' + [regex]::Escape($dependency) + '\s*\r?\n(.*?)(?=^  - task_id:|\z)')); Assert-Chat ($record.Success -and $record.Groups[1].Value -match '(?m)^\s+status:\s*done\s*$') "P0 dependency not done: $dependency" }
foreach ($dependency in @('NX-PROFILE-P01', 'NX-MOD-P01')) { $record = [regex]::Match($backlogP1, ('(?ms)^  - task_id:\s*' + [regex]::Escape($dependency) + '\s*\r?\n(.*?)(?=^  - task_id:|\z)')); Assert-Chat ($record.Success -and $record.Groups[1].Value -match '(?m)^\s+status:\s*done\s*$') "P1 dependency not done: $dependency" }
$activePackets = @([regex]::Matches($backlogP1, '(?ms)^  - task_id:\s*(\S+)\s*\r?\n(.*?)(?=^  - task_id:|\z)') | Where-Object { $_.Groups[2].Value -match '(?m)^\s+record_kind:\s*task_packet\s*$' -and $_.Groups[2].Value -match '(?m)^\s+status:\s*(in_progress|review)\s*$' } | ForEach-Object { $_.Groups[1].Value }); Assert-Chat ($activePackets.Count -eq 1 -and $activePackets[0] -eq 'NX-CHAT-P01') 'WIP one violated.'
Assert-Chat ($capacity -match '(?m)^\s+active_task_id:\s+NX-CHAT-P01\s*$' -and $capacity -match '(?m)^\s+active_packets:\s+1\s*$') 'Capacity mismatch.'; Assert-Chat ($progress -match '(?m)^\s+active_packet_id:\s+NX-CHAT-P01\s*$') 'Progress mismatch.'; Assert-Chat ($checkpoint -match '(?m)^- Stare:\s*`(in_progress|review)`\s*$') 'Checkpoint mismatch.'
Assert-Chat ($architecture -match '(?ms)^  - id:\s*messaging\s*\r?\n.*?^\s+owner:\s*A14\s*$' -and $architecture -match '(?ms)^  - id:\s*messaging\s*\r?\n.*?^\s+public_api_path:\s*packages/messaging/api\s*$') 'Messaging architecture boundary missing.'

Assert-Chat ($contract.schemaVersion -eq 1 -and $contract.contractVersion -eq '1.0.0' -and $contract.owner -eq 'A14') 'Contract identity drifted.'; Assert-Chat (@($contract.conversationKinds).Count -eq 1 -and $contract.conversationKinds[0] -eq 'ONE_TO_ONE' -and @($contract.messageStates).Count -eq 4) 'Conversation/state contract drifted.'
Assert-Chat (-not [bool]$contract.rules.plaintextAcceptedByService -and -not [bool]$contract.rules.ciphertextAcceptedByActionLedger -and [bool]$contract.rules.activeProfileAndGenerationRequired -and [bool]$contract.rules.activeDeviceRequired -and [bool]$contract.rules.keyRotationRequiresNextEpoch -and [bool]$contract.rules.rotationPersistsCurrentEpochAndDevice -and [bool]$contract.rules.sendRecipientImmutableForLifecycle -and [bool]$contract.rules.blockBeforeSendDeliveryRead -and [bool]$contract.rules.accessDecisionSignedByPolicyEngine -and [bool]$contract.rules.audienceGrantRequired -and -not [bool]$contract.rules.privateActionTargetInClear -and [int]$contract.rules.privateCommitmentMinimumEntropyBits -ge 128 -and [bool]$contract.rules.verifiedCheckpointRequiredForRestore -and [bool]$contract.rules.replayDeniedAcrossRestart -and [bool]$contract.rules.syntheticOnlyInCurrentPacket) 'Messaging rules drifted.'
foreach ($fragment in @('recordPrivateAction', 'genericCommitment', 'ActionRecorded')) { Assert-Chat ($smartDoc.Contains($fragment)) "Smart-contract specification missing: $fragment" }
foreach ($fragment in @('E2EE chat', 'Matrix facade', 'device keys', 'delivery state', 'PRIVATE_ACTION', 'nu ciphertext/plaintext')) { Assert-Chat ($securityDoc.Contains($fragment)) "Security specification missing: $fragment" }
foreach ($fragment in @('| Chat | send/edit/tombstone', 'generic salted commitment', 'targetul sau semantica', 'reducer replay')) { Assert-Chat ($actionDoc.Contains($fragment)) "Action-ledger specification missing: $fragment" }
foreach ($fragment in @('OneToOneMessagingFacade', 'MessagingAccessDecision', 'rotateConversationCapability', 'currentCapabilities', 'recipientProfiles', 'conversationParticipants', 'CAPABILITY_STALE', 'CONVERSATION_PARTICIPANTS_STALE', 'ACCESS_DECISION_BINDING_MISMATCH', 'RECEIPT_ACTOR_DENIED', 'RECEIPT_TIME_INVALID', 'MESSAGING_CHECKPOINT_UNVERIFIED', 'buildPrivateActionCommitment')) { Assert-Chat ($source.Contains($fragment)) "Source control missing: $fragment" }
foreach ($fragment in @('private action is terminal and reconciled', 'service projection excludes recipient', 'recipient delivery advances state', 'recipient_substitution_denied', 'recipient_substitution_denied_after_restart', 'duplicate_rotation_denied', 'old_capability_denied_after_rotation', 'old_capability_denied_after_restart', 'out_of_order_receipt_denied', 'sender tombstone remains available after block', 'message lifecycle survives verified restart', 'policy_binding_substitution_denied')) { Assert-Chat ($tests.Contains($fragment)) "Test control missing: $fragment" }
Assert-Chat ($source -notmatch '(?i)(fetch\s*\(|XMLHttpRequest|HttpClient|WebClient|Invoke-WebRequest|https?\.request|child_process|net\.connect|dgram\.|console\.log)') 'Messaging runtime can perform network/process/log operations.'
Assert-Chat ($capEvidence.status -eq 'PASS' -and [int]$capEvidence.blocked_economic_actions -ge 1 -and [int]$capEvidence.blocked_unallowlisted_egress_actions -ge 1 -and $chainEvidence.status -eq 'PASS') 'Dependency evidence incomplete.'; Assert-Chat ($spend -match '(?m)^mode:\s*default_deny_spend\s*$' -and $spend -match '(?m)^\s*max_incremental_amount:\s*0\s*$') 'Spend guard missing.'
$credentialPattern = '^(AWS_|AZURE_|GOOGLE_APPLICATION_CREDENTIALS$|OPENAI_API_KEY$|TWILIO_|MAPBOX_|CLOUDFLARE_|STRIPE_|PINATA_|IPFS_|MATRIX_|XMONEY_)'; $credentialNames = @([Environment]::GetEnvironmentVariables().Keys | ForEach-Object { [string]$_ } | Where-Object { $_ -match $credentialPattern }); Assert-Chat ($credentialNames.Count -eq 0) 'Production/billing credential names present.'

$node = Get-IncludedNodeRuntime; Assert-Chat ($null -ne $node) 'Included Node missing.'; $ephemeralRoot = Join-Path $repoRoot '.ephemeral'; [IO.Directory]::CreateDirectory($ephemeralRoot) | Out-Null; $runRoot = Join-Path $ephemeralRoot ('NX-CHAT-P01-validator-' + [Guid]::NewGuid().ToString('N')); [IO.Directory]::CreateDirectory($runRoot) | Out-Null; $compile = $null; $testRuns = @(); $testReceipt = $null; $boundary = $null
try { if ($null -ne $node) { $compile = Invoke-LocalNode $node @($paths.tsc, '--strict', '--target', 'ES2022', '--module', 'commonjs', '--lib', 'ES2022,DOM', '--outDir', $runRoot, $paths.source, $paths.tests, $paths.chain_actions, $paths.chain_reducer) $repoRoot; Assert-Chat ($compile.exit_code -eq 0) "Strict TypeScript compilation failed: $($compile.stderr)"; if ($compile.exit_code -eq 0) { $testPath = Join-Path $runRoot 'messaging\api\index.test.js'; 1..3 | ForEach-Object { $script:testRuns += Invoke-LocalNode $node @($testPath) $repoRoot }; foreach ($run in $testRuns) { Assert-Chat ($run.exit_code -eq 0) "Chat tests failed: $($run.stderr)" }; Assert-Chat (@($testRuns.stdout | Sort-Object -Unique).Count -eq 1) 'Non-deterministic receipts.'; try { $testReceipt = $testRuns[0].stdout | ConvertFrom-Json } catch { Assert-Chat $false 'Receipt is not JSON.' } }; $items = @([pscustomobject]@{ id = 'packages/messaging/api/index.ts'; sourceContext = 'messaging'; text = $source }, [pscustomobject]@{ id = 'packages/messaging/api/index.test.ts'; sourceContext = 'messaging'; text = $tests }); $manifest = [pscustomobject]@{ knownSpecifiers = [pscustomobject]@{ '@nexus/profile' = 'profile_core'; '@nexus/moderation' = 'moderation'; '@nexus/chain' = 'chain_integration'; '@nexus/contracts' = 'contract_registry' }; knownSchemas = @('messaging', 'profile_core', 'moderation', 'chain_integration', 'contract_registry'); contexts = [pscustomobject]@{ messaging = [pscustomobject]@{ allowedImports = @('profile_core', 'moderation', 'chain_integration', 'contract_registry') } }; items = $items }; $manifestPath = Join-Path $runRoot 'boundary.json'; [IO.File]::WriteAllText($manifestPath, ($manifest | ConvertTo-Json -Depth 8), [Text.UTF8Encoding]::new($false)); $boundaryRun = Invoke-LocalNode $node @($paths.boundary_checker, $manifestPath) $repoRoot; Assert-Chat ($boundaryRun.exit_code -eq 0) "Boundary checker failed: $($boundaryRun.stderr)"; if ($boundaryRun.exit_code -eq 0) { $boundary = $boundaryRun.stdout | ConvertFrom-Json } } } finally { $rootPrefix = [IO.Path]::GetFullPath($ephemeralRoot).TrimEnd('\') + '\'; $resolved = [IO.Path]::GetFullPath($runRoot); if ((Test-Path -LiteralPath $runRoot) -and $resolved.StartsWith($rootPrefix, [StringComparison]::OrdinalIgnoreCase)) { Remove-Item -LiteralPath $runRoot -Recurse -Force } }
Assert-Chat ($null -ne $testReceipt) 'Test receipt missing.'
if ($null -ne $testReceipt) { Assert-Chat ($testReceipt.task_id -eq 'NX-CHAT-P01' -and $testReceipt.status -eq 'PASS' -and [int]$testReceipt.assertions -ge 41) 'Scenario receipt regressed.'; Assert-Chat ([int]$testReceipt.e2ee_boundary.service_plaintext_fields -eq 0 -and [int]$testReceipt.e2ee_boundary.chain_target_fields -eq 0 -and [int]$testReceipt.e2ee_boundary.chain_ciphertext_fields -eq 0) 'E2EE boundary leakage.'; Assert-Chat ($testReceipt.chain.action_class -eq 'PRIVATE_ACTION' -and [bool]$testReceipt.chain.terminal -and [bool]$testReceipt.chain.reconciled) 'Chain terminal/reconciliation missing.'; foreach ($property in @('sent', 'delivered', 'read', 'tombstoned', 'restored')) { Assert-Chat ([bool]$testReceipt.lifecycle.$property) "Lifecycle failed: $property" }; foreach ($property in @('block_before_send', 'block_before_delivery', 'audience_before_send', 'revoked_device_denied', 'revoked_device_read_denied', 'stale_profile_generation_denied', 'sender_delivery_receipt_denied', 'recipient_tombstone_denied', 'recipient_substitution_denied', 'recipient_substitution_denied_after_restart', 'out_of_order_receipt_denied', 'duplicate_rotation_denied', 'old_capability_denied_after_rotation', 'old_capability_denied_after_restart', 'message_replay_denied_after_restart', 'receipt_replay_denied_after_restart', 'access_decision_replay_denied', 'snapshot_lineage_tamper_denied', 'checkpoint_required', 'plaintext_field_denied', 'policy_binding_substitution_denied', 'policy_boolean_string_denied', 'key_epoch_skip_denied', 'clear_target_attestation_denied', 'weak_entropy_denied')) { Assert-Chat ([bool]$testReceipt.negative.$property) "Negative failed: $property" }; Assert-Chat ([int]$testReceipt.network_operations -eq 0 -and [int]$testReceipt.economic_operations -eq 0 -and [int]$testReceipt.external_provider_operations -eq 0 -and [decimal]$testReceipt.incremental_cost.amount -eq 0) 'Tests escaped zero-effect mode.' }
$boundaryFindings = @(); if ($null -ne $boundary) { foreach ($item in @($boundary.results)) { foreach ($finding in @($item.findings)) { $boundaryFindings += "$($item.id):$finding" } } }; Assert-Chat ($null -ne $boundary -and $boundaryFindings.Count -eq 0) ('Boundary findings: ' + ($boundaryFindings -join ','))
$artifactHashes = [ordered]@{}; foreach ($path in $paths.Values) { if (Test-Path -LiteralPath $path -PathType Leaf) { $relative = $path.Substring($repoRoot.Length).TrimStart('\').Replace('\', '/'); $artifactHashes[$relative] = Get-Sha256 $path } }; $subject = Get-StringSha256 (($artifactHashes.GetEnumerator() | Sort-Object Key | ForEach-Object { "$($_.Key)=$($_.Value)" }) -join "`n"); $timer.Stop()
$result = [ordered]@{ schema_version = 1; task_id = 'NX-CHAT-P01'; run_id = $RunId; executor_role = $ExecutorRole; status = if ($failures.Count -eq 0) { 'PASS' } else { 'FAIL' }; scope = 'local_one_to_one_e2ee_private_action_and_reducer_proof'; assertions = $assertions; scenario_assertions = if ($null -ne $testReceipt) { [int]$testReceipt.assertions } else { 0 }; deterministic_repetitions = @($testRuns).Count; failures = @($failures); e2ee_boundary = if ($null -ne $testReceipt) { $testReceipt.e2ee_boundary } else { $null }; chain = if ($null -ne $testReceipt) { $testReceipt.chain } else { $null }; lifecycle = if ($null -ne $testReceipt) { $testReceipt.lifecycle } else { $null }; source_boundary_findings = $boundaryFindings.Count; credential_name_matches = $credentialNames.Count; network_operations = 0; economic_operations = 0; external_provider_operations = 0; incremental_cost = [ordered]@{ amount = 0; currency = 'EUR' }; claims_excluded = @('production_e2ee', 'matrix_provider', 'real_device_keys', 'real_messages', 'push_delivery', 'production_persistence_adapter', 'mainnet_transaction', 'formal_cryptographic_audit'); review_subject_sha256 = $subject; artifact_sha256 = $artifactHashes; duration_seconds = [math]::Round($timer.Elapsed.TotalSeconds, 4) }
$result | ConvertTo-Json -Depth 12; if ($failures.Count -gt 0) { exit 1 }
