[CmdletBinding()]
param(
  [string]$RunId = ('NX-MARKET-P01-' + [DateTimeOffset]::UtcNow.ToString('yyyyMMddTHHmmssfffZ') + '-' + [Guid]::NewGuid().ToString('N').Substring(0,8)),
  [ValidateSet('UNSPECIFIED','A34','C03','C05','C06','C10')][string]$ExecutorRole='UNSPECIFIED'
)
Set-StrictMode -Version Latest; $ErrorActionPreference='Stop'; $timer=[Diagnostics.Stopwatch]::StartNew(); $failures=[Collections.Generic.List[string]]::new(); $assertions=0
function Assert-Market { param([bool]$Condition,[string]$Message) $script:assertions++; if(-not $Condition){$script:failures.Add($Message)} }
function Read-Utf8 { param([string]$Path) [IO.File]::ReadAllText($Path,[Text.Encoding]::UTF8) }
function Get-Sha256 { param([string]$Path) (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant() }
function Get-StringSha256 { param([string]$Value) $sha=[Security.Cryptography.SHA256]::Create(); try{([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Value)))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()} }
function Get-IncludedNodeRuntime { $root=Join-Path ([Environment]::GetFolderPath('LocalApplicationData')) 'OpenAI\Codex\bin'; if(-not(Test-Path -LiteralPath $root)){return $null}; Get-ChildItem -LiteralPath $root -Filter node.exe -File -Recurse -ErrorAction SilentlyContinue|Sort-Object FullName|Select-Object -Last 1 -ExpandProperty FullName }
function Invoke-LocalNode { param([string]$Node,[string[]]$Arguments,[string]$WorkingDirectory) $quoted=@($Arguments|ForEach-Object{'"'+$_.Replace('"','\"')+'"'}) -join ' '; $info=[Diagnostics.ProcessStartInfo]::new();$info.FileName=$Node;$info.Arguments=$quoted;$info.WorkingDirectory=$WorkingDirectory;$info.UseShellExecute=$false;$info.CreateNoWindow=$true;$info.RedirectStandardOutput=$true;$info.RedirectStandardError=$true;$p=[Diagnostics.Process]::new();$p.StartInfo=$info;try{if(-not$p.Start()){throw 'Node did not start'};$stdout=$p.StandardOutput.ReadToEnd();$stderr=$p.StandardError.ReadToEnd();if(-not$p.WaitForExit(30000)){$p.Kill();throw 'Node timeout'};[ordered]@{exit_code=$p.ExitCode;stdout=$stdout.Trim();stderr=$stderr.Trim();cpu_seconds=[math]::Round($p.TotalProcessorTime.TotalSeconds,4)}}finally{$p.Dispose()} }
$repoRoot=Split-Path -Parent $PSScriptRoot
$paths=[ordered]@{
 source=Join-Path $repoRoot 'packages\marketplace\api\index.ts'; tests=Join-Path $repoRoot 'packages\marketplace\api\index.test.ts'; contract=Join-Path $repoRoot 'packages\marketplace\api\marketplace-contract.v1.json'; gateway=Join-Path $repoRoot 'packages\commerce\api\index.ts'; chain_actions=Join-Path $repoRoot 'packages\chain-actions-api\index.ts'; chain_reducer=Join-Path $repoRoot 'packages\chain-adapter\api\index.ts'; smart_contract_doc=Join-Path $repoRoot 'docs\02-smart-contracts.md'; flows_doc=Join-Path $repoRoot 'docs\05-user-flows.md'; action_doc=Join-Path $repoRoot 'docs\09-action-ledger-classifieds.md'; economics_doc=Join-Path $repoRoot 'docs\10-supernova-economics-compliance.md'; architecture=Join-Path $repoRoot 'architecture\bounded-contexts.yaml'; backlog_p0=Join-Path $PSScriptRoot 'backlog-p0.yaml'; backlog_p1=Join-Path $PSScriptRoot 'backlog-p1.yaml'; capacity=Join-Path $PSScriptRoot 'capacity-scorecard.yaml'; progress=Join-Path $PSScriptRoot 'product-progress.yaml'; checkpoint=Join-Path $PSScriptRoot 'checkpoints\NX-MARKET-P01.md'; spend=Join-Path $PSScriptRoot 'spend-control.yaml'; profile_evidence=Join-Path $PSScriptRoot 'evidence\NX-PROFILE-P01-validation.json'; moderation_evidence=Join-Path $PSScriptRoot 'evidence\NX-MOD-P01-validation.json'; chain_evidence=Join-Path $PSScriptRoot 'evidence\NX-CHAIN-002-validation.json'; security_evidence=Join-Path $PSScriptRoot 'evidence\NX-SEC-001-validation.json'; boundary_checker=Join-Path $repoRoot 'security\source-boundary-check.js'; tsc=Join-Path $repoRoot 'packages\contracts\node_modules\typescript\bin\tsc'; package_lock=Join-Path $repoRoot 'packages\contracts\package-lock.json'; validator=$PSCommandPath
}
foreach($path in $paths.Values){Assert-Market (Test-Path -LiteralPath $path -PathType Leaf) "Missing artifact: $path"}
Assert-Market ($RunId -match '^NX-MARKET-P01-[A-Za-z0-9T._-]+$') 'Run ID invalid.';Assert-Market ($ExecutorRole -ne 'UNSPECIFIED') 'ExecutorRole must be explicit.'
$source=Read-Utf8 $paths.source;$tests=Read-Utf8 $paths.tests;$contract=Read-Utf8 $paths.contract|ConvertFrom-Json;$architecture=Read-Utf8 $paths.architecture;$backlog0=Read-Utf8 $paths.backlog_p0;$backlog1=Read-Utf8 $paths.backlog_p1;$capacity=Read-Utf8 $paths.capacity;$progress=Read-Utf8 $paths.progress;$checkpoint=Read-Utf8 $paths.checkpoint;$spend=Read-Utf8 $paths.spend
$task=[regex]::Match($backlog1,'(?ms)^  - task_id:\s*NX-MARKET-P01\s*\r?\n(.*?)(?=^  - task_id:|\z)');Assert-Market $task.Success 'Packet missing.';if($task.Success){Assert-Market ($task.Groups[1].Value-match'(?m)^\s+owner_agent:\s*A34\s*$') 'Owner drift.';Assert-Market ($task.Groups[1].Value-match'(?m)^\s+status:\s*(in_progress|review)\s*$') 'Packet inactive.';Assert-Market ($task.Groups[1].Value-match'(?m)^\s+risk_class:\s*T0\s*$') 'Risk drift.'}
foreach($dependency in @('NX-CHAIN-001','NX-CHAIN-002','NX-SEC-001')){$r=[regex]::Match($backlog0,('(?ms)^  - task_id:\s*'+[regex]::Escape($dependency)+'\s*\r?\n(.*?)(?=^  - task_id:|\z)'));Assert-Market ($r.Success-and$r.Groups[1].Value-match'(?m)^\s+status:\s*done\s*$') "P0 dependency not done: $dependency"}
foreach($dependency in @('NX-PROFILE-P01','NX-MOD-P01')){$r=[regex]::Match($backlog1,('(?ms)^  - task_id:\s*'+[regex]::Escape($dependency)+'\s*\r?\n(.*?)(?=^  - task_id:|\z)'));Assert-Market ($r.Success-and$r.Groups[1].Value-match'(?m)^\s+status:\s*done\s*$') "P1 dependency not done: $dependency"}
$active=@([regex]::Matches($backlog1,'(?ms)^  - task_id:\s*(\S+)\s*\r?\n(.*?)(?=^  - task_id:|\z)')|Where-Object{$_.Groups[2].Value-match'(?m)^\s+record_kind:\s*task_packet\s*$'-and$_.Groups[2].Value-match'(?m)^\s+status:\s*(in_progress|review)\s*$'}|ForEach-Object{$_.Groups[1].Value});Assert-Market ($active.Count-eq1-and$active[0]-eq'NX-MARKET-P01') 'WIP one violated.'
Assert-Market ($capacity-match'(?m)^\s+active_task_id:\s+NX-MARKET-P01\s*$'-and$capacity-match'(?m)^\s+active_packets:\s+1\s*$') 'Capacity mismatch.';Assert-Market ($progress-match'(?m)^\s+active_packet_id:\s+NX-MARKET-P01\s*$') 'Progress mismatch.';Assert-Market ($checkpoint-match'(?m)^- Stare:\s*`(in_progress|review)`\s*$') 'Checkpoint mismatch.'
Assert-Market ($architecture-match'(?ms)^  - id:\s*commerce\s*\r?\n.*?^\s+owner:\s*A34\s*$'-and$architecture-match'(?ms)^  - id:\s*commerce\s*\r?\n.*?^\s+public_api_path:\s*packages/commerce/api\s*$') 'Commerce boundary missing.'
Assert-Market ($contract.schemaVersion-eq1-and$contract.owner-eq'A34'-and$contract.surface-eq'MARKETPLACE_OLX') 'Contract identity drift.';Assert-Market (-not[bool]$contract.listing.classifiedOnlyHasEscrowOrFee-and[bool]$contract.listing.prohibitedGoodsFailClosed-and[bool]$contract.listing.activeAfterModerationAndExecutedAction) 'Listing policy drift.';Assert-Market ($contract.escrow.realValueAtomic-eq'0'-and$contract.escrow.maxTestTotalAtomic-eq'1000000'-and[int]$contract.escrow.maxPlatformFeeBps-eq500-and[bool]$contract.escrow.terminalConservationRequired-and[bool]$contract.escrow.refundAvailableWhileNewOrdersPaused-and[bool]$contract.escrow.acceptAndFulfilDeadlinesEnforced-and[bool]$contract.escrow.resolverMustBeIndependentFromParties-and[bool]$contract.escrow.signedCheckpointRequired-and[bool]$contract.escrow.restoreReappliesStateMachine) 'Escrow contract drift.'
foreach($fragment in @('MarketplaceListingRegistry','MarketplaceEscrowLedger','ListingEligibilityDecision','ListingExecutionAuthorization','traderStatus','prohibitedGoodsClear','prepareAction','abortPreparedAction','LISTING_EXECUTION_STATE_CONFLICT','MAX_TEST_TOTAL','realValueAtomic: "0"','ESCROW_CONSERVATION_INVALID','ESCROW_ACCEPT_DEADLINE_EXPIRED','ESCROW_FULFIL_DEADLINE_EXPIRED','EscrowSnapshotVerifier','expectedCheckpointId','validateReplayedEvent','static restore')){Assert-Market ($source.Contains($fragment)) "Source control missing: $fragment"}
foreach($fragment in @('prohibitedGoodsClear','policy race records no listing action','CLASSIFIED_ONLY','refund remains available while new orders paused','dispute split conserves','ESCROW_SNAPSHOT_INVALID','listing action reaches authentic final reducer state')){Assert-Market ($tests.Contains($fragment)) "Test control missing: $fragment"}
foreach($pair in @(@($paths.smart_contract_doc,'nexus-marketplace'),@($paths.flows_doc,'Marketplace OLX-like'),@($paths.action_doc,'ESCROW_CHECKOUT'),@($paths.economics_doc,'storage numai pentru capability, nonce, escrow'))){Assert-Market ((Read-Utf8 $pair[0]).Contains($pair[1])) "Normative fragment missing: $($pair[1])"}
Assert-Market ($source-notmatch'(?i)(fetch\s*\(|XMLHttpRequest|HttpClient|WebClient|Invoke-WebRequest|https?\.request|child_process|net\.connect|dgram\.|console\.log)') 'Runtime can perform network/process/log operations.';Assert-Market ($spend-match'(?m)^mode:\s*default_deny_spend\s*$'-and$spend-match'(?m)^\s*max_incremental_amount:\s*0\s*$') 'Spend guard missing.'
foreach($evidencePath in @($paths.profile_evidence,$paths.moderation_evidence,$paths.chain_evidence,$paths.security_evidence)){if(Test-Path -LiteralPath $evidencePath){$ev=Read-Utf8 $evidencePath|ConvertFrom-Json;Assert-Market ($ev.status-eq'PASS') "Dependency evidence not PASS: $evidencePath"}}
$credentialPattern='^(AWS_|AZURE_|GOOGLE_APPLICATION_CREDENTIALS$|OPENAI_API_KEY$|TWILIO_|MAPBOX_|CLOUDFLARE_|STRIPE_|PINATA_|IPFS_|MATRIX_|XMONEY_)';$credentialNames=@([Environment]::GetEnvironmentVariables().Keys|ForEach-Object{[string]$_}|Where-Object{$_-match$credentialPattern});Assert-Market ($credentialNames.Count-eq0) 'Billing credential names present.'
$node=Get-IncludedNodeRuntime;Assert-Market ($null-ne$node) 'Included Node missing.';$ephemeralRoot=Join-Path $repoRoot '.ephemeral';[IO.Directory]::CreateDirectory($ephemeralRoot)|Out-Null;$runRoot=Join-Path $ephemeralRoot ('NX-MARKET-P01-validator-'+[Guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($runRoot)|Out-Null;$compile=$null;$testRuns=@();$receipt=$null;$boundary=$null
try{if($null-ne$node){$compile=Invoke-LocalNode $node @($paths.tsc,'--strict','--target','ES2022','--module','commonjs','--lib','ES2022,DOM','--outDir',$runRoot,$paths.source,$paths.tests,$paths.gateway,$paths.chain_actions,$paths.chain_reducer) $repoRoot;Assert-Market ($compile.exit_code-eq0) "TypeScript compilation failed: $($compile.stderr)";if($compile.exit_code-eq0){$testPath=Join-Path $runRoot 'marketplace\api\index.test.js';1..3|ForEach-Object{$script:testRuns+=Invoke-LocalNode $node @($testPath) $repoRoot};foreach($run in $testRuns){Assert-Market ($run.exit_code-eq0) "Tests failed: $($run.stderr)"};Assert-Market (@($testRuns.stdout|Sort-Object -Unique).Count-eq1) 'Non-deterministic receipt.';try{$receipt=$testRuns[0].stdout|ConvertFrom-Json}catch{Assert-Market $false 'Receipt invalid.'}};$manifest=[pscustomobject]@{knownSpecifiers=[pscustomobject]@{'@nexus/profile'='profile_core';'@nexus/moderation'='moderation';'@nexus/chain'='chain_integration';'@nexus/contracts'='contract_registry'};knownSchemas=@('commerce','profile_core','moderation','chain_integration','contract_registry');contexts=[pscustomobject]@{commerce=[pscustomobject]@{allowedImports=@('profile_core','moderation','chain_integration','contract_registry')}};items=@([pscustomobject]@{id='packages/marketplace/api/index.ts';sourceContext='commerce';text=$source})};$manifestPath=Join-Path $runRoot 'boundary.json';[IO.File]::WriteAllText($manifestPath,($manifest|ConvertTo-Json -Depth 8),[Text.UTF8Encoding]::new($false));$b=Invoke-LocalNode $node @($paths.boundary_checker,$manifestPath) $repoRoot;Assert-Market ($b.exit_code-eq0) "Boundary checker failed: $($b.stderr)";if($b.exit_code-eq0){$boundary=$b.stdout|ConvertFrom-Json}}}finally{$prefix=[IO.Path]::GetFullPath($ephemeralRoot).TrimEnd('\')+'\';$resolved=[IO.Path]::GetFullPath($runRoot);if((Test-Path -LiteralPath $runRoot)-and$resolved.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){Remove-Item -LiteralPath $runRoot -Recurse -Force}}
Assert-Market ($null-ne$receipt) 'Test receipt missing.';if($null-ne$receipt){Assert-Market ($receipt.task_id-eq'NX-MARKET-P01'-and$receipt.status-eq'PASS'-and[int]$receipt.assertions-ge33) 'Scenario receipt regressed.';Assert-Market ([bool]$receipt.listing.active-and[bool]$receipt.listing.moderated-and[bool]$receipt.listing.distinct_action-and[bool]$receipt.listing.reconciled) 'Listing proof failed.';Assert-Market ($receipt.escrow.real_value_atomic-eq'0'-and[bool]$receipt.escrow.release-and[bool]$receipt.escrow.refund-and[bool]$receipt.escrow.dispute-and[bool]$receipt.escrow.conservation-and[bool]$receipt.escrow.restore) 'Escrow proof failed.';foreach($p in @('exact_shape','prohibited_goods','boolean_string','price_substitution','coordinated_terms_substitution','policy_race','retained_prepared_action','listing_replay','classified_escrow_denied','cap','funding_replay','actor_separation','terminal_reentry','snapshot_tamper','snapshot_prefix','fabricated_transition','snapshot_resolver_binding','accept_deadline','fulfil_deadline','authoritative_deadline_time','pause_refund','resolver_separation','resolver_collision')){Assert-Market ([bool]$receipt.negative.$p) "Negative failed: $p"};Assert-Market ([int]$receipt.network_operations-eq0-and[int]$receipt.provider_operations-eq0-and[int]$receipt.economic_operations-eq0-and[decimal]$receipt.incremental_cost.amount-eq0) 'Tests escaped zero-effect mode.'}
$findings=@();if($null-ne$boundary){foreach($item in @($boundary.results)){foreach($finding in @($item.findings)){$findings+="$($item.id):$finding"}}};Assert-Market ($null-ne$boundary-and$findings.Count-eq0) ('Boundary findings: '+($findings-join','))
$hashes=[ordered]@{};foreach($path in $paths.Values){if(Test-Path -LiteralPath $path -PathType Leaf){$relative=$path.Substring($repoRoot.Length).TrimStart('\').Replace('\','/');$hashes[$relative]=Get-Sha256 $path}};$subject=Get-StringSha256 (($hashes.GetEnumerator()|Sort-Object Key|ForEach-Object{"$($_.Key)=$($_.Value)"})-join"`n");$timer.Stop()
$result=[ordered]@{schema_version=1;task_id='NX-MARKET-P01';run_id=$RunId;executor_role=$ExecutorRole;status=if($failures.Count-eq0){'PASS'}else{'FAIL'};scope='local_legal_listing_distinct_action_and_zero_real_value_capped_escrow_release_refund_dispute';assertions=$assertions;scenario_assertions=if($null-ne$receipt){[int]$receipt.assertions}else{0};deterministic_repetitions=@($testRuns).Count;failures=@($failures);listing=if($null-ne$receipt){$receipt.listing}else{$null};escrow=if($null-ne$receipt){$receipt.escrow}else{$null};source_boundary_findings=$findings.Count;credential_name_matches=$credentialNames.Count;network_operations=0;economic_operations=0;external_provider_operations=0;real_fund_operations=0;incremental_cost=[ordered]@{amount=0;currency='EUR'};claims_excluded=@('real_goods','real_funds','mainnet','external_kyc','tax_opinion','formal_legal_opinion','production_persistence','production_dispute_resolution');review_subject_sha256=$subject;artifact_sha256=$hashes;duration_seconds=[math]::Round($timer.Elapsed.TotalSeconds,4)}
$result|ConvertTo-Json -Depth 12;if($failures.Count-gt0){exit 1}
