// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct NexusActionsProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for NexusActionsProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = NexusActionsProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        NexusActionsProxyMethods { wrapped_tx: tx }
    }
}

pub struct NexusActionsProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> NexusActionsProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        chain_id: Arg0,
        pauser: Arg1,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .argument(&chain_id)
            .argument(&pauser)
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> NexusActionsProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> NexusActionsProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    /// Owner allowlists funded protocol relayers. A capability can select only 
    /// one currently allowlisted relayer, keeping every call one-action-only. 
    pub fn set_relayer_allowed<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
        Arg1: ProxyArg<bool>,
    >(
        self,
        relayer: Arg0,
        allowed: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setRelayerAllowed")
            .argument(&relayer)
            .argument(&allowed)
            .original_result()
    }

    pub fn set_pauser<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        pauser: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setPauser")
            .argument(&pauser)
            .original_result()
    }

    pub fn pause_action_type<
        Arg0: ProxyArg<u16>,
        Arg1: ProxyArg<bool>,
    >(
        self,
        action_type: Arg0,
        paused: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("pauseActionType")
            .argument(&action_type)
            .argument(&paused)
            .original_result()
    }

    pub fn pause_relayer<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
        Arg1: ProxyArg<bool>,
    >(
        self,
        relayer: Arg0,
        paused: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("pauseRelayer")
            .argument(&relayer)
            .argument(&paused)
            .original_result()
    }

    /// Direct wallet call. No payment is accepted because the endpoint is not 
    /// annotated payable. The session key cannot authorize financial actions. 
    pub fn register_capability<
        Arg0: ProxyArg<u8>,
        Arg1: ProxyArg<ManagedByteArray<Env::Api, 32usize>>,
        Arg2: ProxyArg<ManagedByteArray<Env::Api, 32usize>>,
        Arg3: ProxyArg<u32>,
        Arg4: ProxyArg<u32>,
        Arg5: ProxyArg<u64>,
        Arg6: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        actor_kind: Arg0,
        actor_commitment: Arg1,
        session_public_key: Arg2,
        scope_bits: Arg3,
        max_actions: Arg4,
        expires_at: Arg5,
        authorized_relayer: Arg6,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("registerCapability")
            .argument(&actor_kind)
            .argument(&actor_commitment)
            .argument(&session_public_key)
            .argument(&scope_bits)
            .argument(&max_actions)
            .argument(&expires_at)
            .argument(&authorized_relayer)
            .original_result()
    }

    pub fn revoke_capability<
        Arg0: ProxyArg<ManagedByteArray<Env::Api, 32usize>>,
    >(
        self,
        session_public_key: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("revokeCapability")
            .argument(&session_public_key)
            .original_result()
    }

    /// Rotation can only reduce the remaining authority of the old key. 
    pub fn rotate_capability<
        Arg0: ProxyArg<ManagedByteArray<Env::Api, 32usize>>,
        Arg1: ProxyArg<ManagedByteArray<Env::Api, 32usize>>,
        Arg2: ProxyArg<u32>,
        Arg3: ProxyArg<u32>,
        Arg4: ProxyArg<u64>,
        Arg5: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        old_session_public_key: Arg0,
        new_session_public_key: Arg1,
        new_scope_bits: Arg2,
        new_max_actions: Arg3,
        new_expires_at: Arg4,
        new_authorized_relayer: Arg5,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("rotateCapability")
            .argument(&old_session_public_key)
            .argument(&new_session_public_key)
            .argument(&new_scope_bits)
            .argument(&new_max_actions)
            .argument(&new_expires_at)
            .argument(&new_authorized_relayer)
            .original_result()
    }

    pub fn record_action<
        Arg0: ProxyArg<ActionEnvelope<Env::Api>>,
        Arg1: ProxyArg<ManagedByteArray<Env::Api, 64usize>>,
    >(
        self,
        envelope: Arg0,
        session_signature: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("recordAction")
            .argument(&envelope)
            .argument(&session_signature)
            .original_result()
    }

    pub fn record_private_action<
        Arg0: ProxyArg<ManagedByteArray<Env::Api, 32usize>>,
        Arg1: ProxyArg<ActionEnvelope<Env::Api>>,
        Arg2: ProxyArg<ManagedByteArray<Env::Api, 64usize>>,
    >(
        self,
        generic_commitment: Arg0,
        envelope: Arg1,
        session_signature: Arg2,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("recordPrivateAction")
            .argument(&generic_commitment)
            .argument(&envelope)
            .argument(&session_signature)
            .original_result()
    }

    /// Canonical bytes signed by the device session key. The domain includes 
    /// protocol version, configured chain id, and this contract's raw address. 
    pub fn get_signing_message<
        Arg0: ProxyArg<ActionEnvelope<Env::Api>>,
    >(
        self,
        envelope: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedBuffer<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getSigningMessage")
            .argument(&envelope)
            .original_result()
    }

    pub fn get_capability<
        Arg0: ProxyArg<ManagedByteArray<Env::Api, 32usize>>,
    >(
        self,
        session_public_key: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, OptionalValue<SessionCapability<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getCapability")
            .argument(&session_public_key)
            .original_result()
    }

    pub fn chain_id(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedBuffer<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getChainId")
            .original_result()
    }

    pub fn domain_separator(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedByteArray<Env::Api, 32usize>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getDomainSeparator")
            .original_result()
    }

    pub fn pauser(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedAddress<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getPauser")
            .original_result()
    }

    pub fn relayer_allowed<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        relayer: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, bool> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("isRelayerAllowed")
            .argument(&relayer)
            .original_result()
    }

    pub fn relayer_paused<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        relayer: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, bool> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("isRelayerPaused")
            .argument(&relayer)
            .original_result()
    }

    pub fn action_paused<
        Arg0: ProxyArg<u16>,
    >(
        self,
        action_type: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, bool> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("isActionPaused")
            .argument(&action_type)
            .original_result()
    }
}

#[type_abi]
#[derive(TopEncode, TopDecode, NestedEncode, NestedDecode, Clone, PartialEq, Eq)]
pub struct ActionEnvelope<Api>
where
    Api: ManagedTypeApi,
{
    pub version: u16,
    pub actor_kind: u8,
    pub actor_commitment: ManagedByteArray<Api, 32usize>,
    pub action_type: u16,
    pub object_commitment: ManagedByteArray<Api, 32usize>,
    pub payload_hash_or_cid: ManagedByteArray<Api, 32usize>,
    pub visibility_class: u8,
    pub action_nonce: u64,
    pub issued_at: u64,
    pub expires_at: u64,
    pub session_public_key: ManagedByteArray<Api, 32usize>,
}

#[type_abi]
#[derive(TopEncode, TopDecode, NestedEncode, NestedDecode, Clone)]
pub struct SessionCapability<Api>
where
    Api: ManagedTypeApi,
{
    pub schema_version: u16,
    pub controller: ManagedAddress<Api>,
    pub actor_kind: u8,
    pub actor_commitment: ManagedByteArray<Api, 32usize>,
    pub scope_bits: u32,
    pub max_actions: u32,
    pub used_actions: u32,
    pub valid_from: u64,
    pub expires_at: u64,
    pub last_action_nonce: u64,
    pub authorized_relayer: ManagedAddress<Api>,
    pub active: bool,
}
