export type PaymentState = "PREVIEWED" | "SIGNED" | "SUBMITTED" | "ORDERED" | "EXECUTED_SUCCESS" | "FAILED_TERMINAL";
export type PaymentRail = "MULTIVERSX_DIRECT" | "XMONEY_MERCHANT";
export type XMoneyState = "CREATED" | "PENDING" | "PAID" | "FAILED" | "REFUNDED";

export class PaymentPolicyError extends Error {
  constructor(public readonly code: string) { super(code); this.name = "PaymentPolicyError"; }
}

const HEX64 = /^[0-9a-f]{64}$/;
const ALIAS = /^@[a-z0-9][a-z0-9._-]{2,31}$/;
const ADDRESS = /^erd1[0-9a-z]{58}$/;
const TOKEN = /^(EGLD|[A-Z0-9]{3,12}-[a-f0-9]{6})$/;
const ID = /^[A-Z0-9][A-Z0-9:._-]{2,127}$/;
const COUNTRY = /^[A-Z]{2}$/;
const ISO = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/;
const POLICY_HASH = "3763fbc42da4e0fcf47d6a13232453a3655b450c40959383ec20e948da08739c";

function fail(code: string): never { throw new PaymentPolicyError(code); }
function plain(value: unknown, keys: readonly string[], code: string): Record<string, unknown> {
  let own: PropertyKey[]; let descriptors: Record<PropertyKey, PropertyDescriptor>; let proto: object | null;
  try { if (value === null || typeof value !== "object" || Array.isArray(value)) fail(code); own = Reflect.ownKeys(value); descriptors = Object.getOwnPropertyDescriptors(value); proto = Object.getPrototypeOf(value); } catch { fail(code); }
  if (proto !== Object.prototype && proto !== null) fail(code);
  if (own.some((key) => typeof key !== "string") || own.length !== keys.length || keys.some((key) => !own.includes(key))) fail(code);
  for (const key of keys) { const descriptor = descriptors[key]; if (!descriptor || !("value" in descriptor) || descriptor.get || descriptor.set) fail(code); }
  return value as Record<string, unknown>;
}
function list(value: unknown, code: string): unknown[] { if (!Array.isArray(value)) fail(code); return value; }
function text(value: unknown, pattern: RegExp, code: string): string { if (typeof value !== "string" || !pattern.test(value)) fail(code); return value; }
function exact<T extends string>(value: unknown, choices: readonly T[], code: string): T { if (typeof value !== "string" || !choices.includes(value as T)) fail(code); return value as T; }
function bool(value: unknown, code: string): boolean { if (typeof value !== "boolean") fail(code); return value; }
function integer(value: unknown, min: number, max: number, code: string): number { if (!Number.isSafeInteger(value) || (value as number) < min || (value as number) > max) fail(code); return value as number; }
function positive(value: unknown, code: string): bigint { if (typeof value !== "bigint" || value <= 0n) fail(code); return value; }
function nonnegative(value: unknown, code: string): bigint { if (typeof value !== "bigint" || value < 0n) fail(code); return value; }
function signed(value: unknown, code: string): bigint { if (typeof value !== "bigint") fail(code); return value; }
function iso(value: unknown, code: string): string { if (typeof value !== "string" || !ISO.test(value) || !Number.isFinite(Date.parse(value))) fail(code); return value; }
function active(issuedAt: string, expiresAt: string, now: string, code: string): void { if (Date.parse(issuedAt) > Date.parse(now) || Date.parse(expiresAt) <= Date.parse(now) || Date.parse(issuedAt) >= Date.parse(expiresAt)) fail(code); }
function frozen<T extends object>(value: T): Readonly<T> { for (const child of Object.values(value)) if (child && typeof child === "object") frozen(child); return Object.freeze(value); }
function sameBigint(a: bigint, b: bigint): boolean { return a === b; }
function bindingKey(receipt: ResolutionReceipt): string { return [receipt.receiptId, receipt.aliasHash, receipt.aliasVersion, receipt.senderProfileId, receipt.senderAddress, receipt.receiverAddress, receipt.network, receipt.tokenId, receipt.tokenDecimals, receipt.atomicAmount.toString(), receipt.policyHash, receipt.issuedAt, receipt.expiresAt, receipt.resolverKeyId, receipt.signature].join("|"); }
function webhookKey(event: XMoneyWebhook): string { return [event.eventId, event.orderId, event.state, event.occurredAt, event.signature].join("|"); }
function orderKey(order: Pick<XOrder, "nexusPaymentId" | "idempotencyKey" | "atomicAmount" | "currency">): string { return [order.nexusPaymentId, order.idempotencyKey, order.atomicAmount.toString(), order.currency].join("|"); }

export interface PaymentPolicy { schemaVersion: 1; contractVersion: "1.0.0"; policyHash: string; effectiveAt: string; expiresAt: string; network: "devnet"; tokenId: string; tokenDecimals: number; maxAtomicAmount: bigint; maxReceiptLifetimeSeconds: number; realValueCap: 0 }
export const DEFAULT_PAYMENT_POLICY: PaymentPolicy = frozen({ schemaVersion: 1, contractVersion: "1.0.0", policyHash: POLICY_HASH, effectiveAt: "2026-08-01T00:00:00Z", expiresAt: "2027-08-01T00:00:00Z", network: "devnet", tokenId: "USDC-350c4e", tokenDecimals: 6, maxAtomicAmount: 1n, maxReceiptLifetimeSeconds: 120, realValueCap: 0 }) as PaymentPolicy;
const POLICY_KEYS = ["schemaVersion", "contractVersion", "policyHash", "effectiveAt", "expiresAt", "network", "tokenId", "tokenDecimals", "maxAtomicAmount", "maxReceiptLifetimeSeconds", "realValueCap"] as const;
export function validatePaymentPolicy(input: unknown, nowInput: unknown): Readonly<PaymentPolicy> {
  const o = plain(input, POLICY_KEYS, "PAYMENT_POLICY_INVALID"), now = iso(nowInput, "PAYMENT_POLICY_TIME_INVALID");
  if (o.schemaVersion !== 1 || o.contractVersion !== "1.0.0" || o.realValueCap !== 0) fail("PAYMENT_POLICY_INVALID");
  const result: PaymentPolicy = { schemaVersion: 1, contractVersion: "1.0.0", policyHash: text(o.policyHash, HEX64, "PAYMENT_POLICY_INVALID"), effectiveAt: iso(o.effectiveAt, "PAYMENT_POLICY_TIME_INVALID"), expiresAt: iso(o.expiresAt, "PAYMENT_POLICY_TIME_INVALID"), network: exact(o.network, ["devnet"], "NETWORK_INVALID"), tokenId: text(o.tokenId, TOKEN, "TOKEN_INVALID"), tokenDecimals: integer(o.tokenDecimals, 0, 18, "TOKEN_DECIMALS_INVALID"), maxAtomicAmount: positive(o.maxAtomicAmount, "PAYMENT_POLICY_INVALID"), maxReceiptLifetimeSeconds: integer(o.maxReceiptLifetimeSeconds, 1, 300, "PAYMENT_POLICY_INVALID"), realValueCap: 0 };
  active(result.effectiveAt, result.expiresAt, now, "PAYMENT_POLICY_NOT_ACTIVE");
  const known = DEFAULT_PAYMENT_POLICY;
  if (result.policyHash !== known.policyHash || result.effectiveAt !== known.effectiveAt || result.expiresAt !== known.expiresAt || result.network !== known.network || result.tokenId !== known.tokenId || result.tokenDecimals !== known.tokenDecimals || result.maxAtomicAmount !== known.maxAtomicAmount || result.maxReceiptLifetimeSeconds !== known.maxReceiptLifetimeSeconds) fail("PAYMENT_POLICY_HASH_CONTENT_MISMATCH");
  return frozen(result) as Readonly<PaymentPolicy>;
}

export function normalizePaymentAlias(input: unknown): string { if (typeof input !== "string") fail("ALIAS_INVALID"); const normalized = input.normalize("NFKC").toLowerCase(); if (normalized !== input || !ALIAS.test(normalized)) fail("ALIAS_INVALID"); return normalized; }

export interface PaymentPreview { alias: string; senderProfileId: string; senderAddress: string; network: "devnet"; tokenId: string; tokenDecimals: number; atomicAmount: bigint }
export interface PaymentCapability { schemaVersion: 1; subjectProfileId: string; countryCode: string; network: "devnet"; tokenId: string; tokenDecimals: number; maxAtomicAmount: bigint; directTransferAllowed: boolean; merchantCheckoutAllowed: boolean; sanctionsClear: boolean; transactionMonitoringClear: boolean; policyHash: string; issuedAt: string; expiresAt: string; issuerKeyId: string; signature: string }
export interface PaymentCapabilityVerifier { verify(capability: Readonly<PaymentCapability>): boolean }
export interface PaymentAuthorization { schemaVersion: 1; rail: PaymentRail; subjectProfileId: string; countryCode: string; policyHash: string; network: "devnet"; tokenId: string; tokenDecimals: number; atomicAmount: bigint; capability: PaymentCapability; authorizedAt: string }
const PREVIEW_KEYS = ["alias", "senderProfileId", "senderAddress", "network", "tokenId", "tokenDecimals", "atomicAmount"] as const;
const CAPABILITY_KEYS = ["schemaVersion", "subjectProfileId", "countryCode", "network", "tokenId", "tokenDecimals", "maxAtomicAmount", "directTransferAllowed", "merchantCheckoutAllowed", "sanctionsClear", "transactionMonitoringClear", "policyHash", "issuedAt", "expiresAt", "issuerKeyId", "signature"] as const;
function parsePreview(value: unknown): PaymentPreview { const o = plain(value, PREVIEW_KEYS, "PREVIEW_INVALID"); return { alias: normalizePaymentAlias(o.alias), senderProfileId: text(o.senderProfileId, ID, "PROFILE_ID_INVALID"), senderAddress: text(o.senderAddress, ADDRESS, "SENDER_INVALID"), network: exact(o.network, ["devnet"], "NETWORK_INVALID"), tokenId: text(o.tokenId, TOKEN, "TOKEN_INVALID"), tokenDecimals: integer(o.tokenDecimals, 0, 18, "TOKEN_DECIMALS_INVALID"), atomicAmount: positive(o.atomicAmount, "AMOUNT_INVALID") }; }
function parseCapability(value: unknown): PaymentCapability { const o = plain(value, CAPABILITY_KEYS, "PAYMENT_CAPABILITY_INVALID"); if (o.schemaVersion !== 1) fail("PAYMENT_CAPABILITY_INVALID"); return { schemaVersion: 1, subjectProfileId: text(o.subjectProfileId, ID, "PAYMENT_CAPABILITY_INVALID"), countryCode: text(o.countryCode, COUNTRY, "PAYMENT_CAPABILITY_INVALID"), network: exact(o.network, ["devnet"], "NETWORK_INVALID"), tokenId: text(o.tokenId, TOKEN, "TOKEN_INVALID"), tokenDecimals: integer(o.tokenDecimals, 0, 18, "TOKEN_DECIMALS_INVALID"), maxAtomicAmount: positive(o.maxAtomicAmount, "PAYMENT_CAPABILITY_INVALID"), directTransferAllowed: bool(o.directTransferAllowed, "PAYMENT_CAPABILITY_INVALID"), merchantCheckoutAllowed: bool(o.merchantCheckoutAllowed, "PAYMENT_CAPABILITY_INVALID"), sanctionsClear: bool(o.sanctionsClear, "PAYMENT_CAPABILITY_INVALID"), transactionMonitoringClear: bool(o.transactionMonitoringClear, "PAYMENT_CAPABILITY_INVALID"), policyHash: text(o.policyHash, HEX64, "PAYMENT_CAPABILITY_INVALID"), issuedAt: iso(o.issuedAt, "PAYMENT_CAPABILITY_INVALID"), expiresAt: iso(o.expiresAt, "PAYMENT_CAPABILITY_INVALID"), issuerKeyId: text(o.issuerKeyId, ID, "PAYMENT_CAPABILITY_INVALID"), signature: text(o.signature, HEX64, "PAYMENT_CAPABILITY_INVALID") }; }
export function authorizePayment(previewInput: unknown, railInput: unknown, capabilityInput: unknown, verifier: PaymentCapabilityVerifier, nowInput: unknown, policyInput: unknown = DEFAULT_PAYMENT_POLICY): Readonly<PaymentAuthorization> {
  const preview = parsePreview(previewInput), rail = exact(railInput, ["MULTIVERSX_DIRECT", "XMONEY_MERCHANT"], "PAYMENT_RAIL_INVALID"), capability = parseCapability(capabilityInput), now = iso(nowInput, "PAYMENT_CAPABILITY_INVALID"), policy = validatePaymentPolicy(policyInput, now);
  active(capability.issuedAt, capability.expiresAt, now, "PAYMENT_CAPABILITY_NOT_ACTIVE");
  if (!verifier || verifier.verify(frozen({ ...capability })) !== true) fail("PAYMENT_CAPABILITY_SIGNATURE_INVALID");
  if (capability.subjectProfileId !== preview.senderProfileId || capability.network !== preview.network || capability.tokenId !== preview.tokenId || capability.tokenDecimals !== preview.tokenDecimals || capability.policyHash !== policy.policyHash) fail("PAYMENT_CAPABILITY_BINDING_MISMATCH");
  if (preview.network !== policy.network || preview.tokenId !== policy.tokenId || preview.tokenDecimals !== policy.tokenDecimals || preview.atomicAmount > policy.maxAtomicAmount || preview.atomicAmount > capability.maxAtomicAmount) fail("PAYMENT_POLICY_DENIED");
  if (!capability.sanctionsClear || !capability.transactionMonitoringClear || (rail === "MULTIVERSX_DIRECT" ? !capability.directTransferAllowed : !capability.merchantCheckoutAllowed)) fail("PAYMENT_CAPABILITY_DENIED");
  return frozen({ schemaVersion: 1 as const, rail, subjectProfileId: preview.senderProfileId, countryCode: capability.countryCode, policyHash: policy.policyHash, network: preview.network, tokenId: preview.tokenId, tokenDecimals: preview.tokenDecimals, atomicAmount: preview.atomicAmount, capability: { ...capability }, authorizedAt: now });
}

export interface AliasRecord { alias: string; aliasVersion: number; receiverAddress: string; network: "devnet"; status: "ACTIVE" | "REVOKED" }
export interface ResolutionReceipt { schemaVersion: 1; receiptId: string; aliasHash: string; aliasVersion: number; senderProfileId: string; senderAddress: string; receiverAddress: string; network: "devnet"; tokenId: string; tokenDecimals: number; atomicAmount: bigint; policyHash: string; issuedAt: string; expiresAt: string; resolverKeyId: string; signature: string }
export interface ResolutionVerifier { verifyReceipt(receipt: Readonly<ResolutionReceipt>, normalizedAlias: string): boolean; verifyAddress(address: string, network: "devnet"): boolean }
const ALIAS_KEYS = ["alias", "aliasVersion", "receiverAddress", "network", "status"] as const;
const RECEIPT_KEYS = ["schemaVersion", "receiptId", "aliasHash", "aliasVersion", "senderProfileId", "senderAddress", "receiverAddress", "network", "tokenId", "tokenDecimals", "atomicAmount", "policyHash", "issuedAt", "expiresAt", "resolverKeyId", "signature"] as const;
function parseAliasRecord(value: unknown): AliasRecord { const o = plain(value, ALIAS_KEYS, "ALIAS_RECORD_INVALID"); return { alias: normalizePaymentAlias(o.alias), aliasVersion: integer(o.aliasVersion, 1, Number.MAX_SAFE_INTEGER, "ALIAS_VERSION_INVALID"), receiverAddress: text(o.receiverAddress, ADDRESS, "RECEIVER_INVALID"), network: exact(o.network, ["devnet"], "NETWORK_INVALID"), status: exact(o.status, ["ACTIVE", "REVOKED"], "ALIAS_STATUS_INVALID") }; }
function parseReceipt(value: unknown): ResolutionReceipt { const o = plain(value, RECEIPT_KEYS, "RESOLUTION_RECEIPT_INVALID"); if (o.schemaVersion !== 1) fail("RESOLUTION_RECEIPT_INVALID"); return { schemaVersion: 1, receiptId: text(o.receiptId, ID, "RESOLUTION_RECEIPT_INVALID"), aliasHash: text(o.aliasHash, HEX64, "ALIAS_HASH_INVALID"), aliasVersion: integer(o.aliasVersion, 1, Number.MAX_SAFE_INTEGER, "ALIAS_VERSION_INVALID"), senderProfileId: text(o.senderProfileId, ID, "PROFILE_ID_INVALID"), senderAddress: text(o.senderAddress, ADDRESS, "SENDER_INVALID"), receiverAddress: text(o.receiverAddress, ADDRESS, "RECEIVER_INVALID"), network: exact(o.network, ["devnet"], "NETWORK_INVALID"), tokenId: text(o.tokenId, TOKEN, "TOKEN_INVALID"), tokenDecimals: integer(o.tokenDecimals, 0, 18, "TOKEN_DECIMALS_INVALID"), atomicAmount: positive(o.atomicAmount, "AMOUNT_INVALID"), policyHash: text(o.policyHash, HEX64, "PAYMENT_POLICY_INVALID"), issuedAt: iso(o.issuedAt, "RECEIPT_TIME_INVALID"), expiresAt: iso(o.expiresAt, "RECEIPT_TIME_INVALID"), resolverKeyId: text(o.resolverKeyId, ID, "RESOLVER_KEY_INVALID"), signature: text(o.signature, HEX64, "RESOLUTION_SIGNATURE_INVALID") }; }
export function verifyResolution(receiptInput: unknown, previewInput: unknown, currentAliasInput: unknown, authorizationInput: unknown, verifier: ResolutionVerifier, capabilityVerifier: PaymentCapabilityVerifier, nowInput: unknown, policyInput: unknown = DEFAULT_PAYMENT_POLICY): Readonly<ResolutionReceipt> {
  const receipt = parseReceipt(receiptInput), preview = parsePreview(previewInput), current = parseAliasRecord(currentAliasInput), authorization = parseAuthorization(authorizationInput), now = iso(nowInput, "RECEIPT_TIME_INVALID"), policy = validatePaymentPolicy(policyInput, now);
  active(receipt.issuedAt, receipt.expiresAt, now, "RESOLUTION_EXPIRED"); if ((Date.parse(receipt.expiresAt) - Date.parse(receipt.issuedAt)) / 1000 > policy.maxReceiptLifetimeSeconds) fail("RESOLUTION_LIFETIME_EXCEEDED");
  if (current.status !== "ACTIVE") fail("ALIAS_REVOKED");
  if (current.alias !== preview.alias || current.aliasVersion !== receipt.aliasVersion || current.receiverAddress !== receipt.receiverAddress || current.network !== receipt.network) fail("ALIAS_STALE_OR_SUBSTITUTED");
  if (preview.senderProfileId !== receipt.senderProfileId || preview.senderAddress !== receipt.senderAddress || preview.network !== receipt.network || preview.tokenId !== receipt.tokenId || preview.tokenDecimals !== receipt.tokenDecimals || preview.atomicAmount !== receipt.atomicAmount || receipt.policyHash !== policy.policyHash) fail("PREVIEW_BINDING_MISMATCH");
  const recomputedAuthorization = authorizePayment(preview, authorization.rail, authorization.capability, capabilityVerifier, now, policy);
  if (authorization.rail !== "MULTIVERSX_DIRECT" || authorization.subjectProfileId !== receipt.senderProfileId || authorization.policyHash !== receipt.policyHash || authorization.network !== receipt.network || authorization.tokenId !== receipt.tokenId || authorization.tokenDecimals !== receipt.tokenDecimals || authorization.atomicAmount !== receipt.atomicAmount || authorization.countryCode !== recomputedAuthorization.countryCode || authorization.authorizedAt !== recomputedAuthorization.authorizedAt || bindingCapability(authorization.capability) !== bindingCapability(recomputedAuthorization.capability)) fail("AUTHORIZATION_BINDING_MISMATCH");
  const result = frozen({ ...receipt }); if (!verifier || verifier.verifyReceipt(result, preview.alias) !== true || verifier.verifyAddress(result.senderAddress, result.network) !== true || verifier.verifyAddress(result.receiverAddress, result.network) !== true) fail("RESOLUTION_SIGNATURE_INVALID"); return result;
}
const AUTHORIZATION_KEYS = ["schemaVersion", "rail", "subjectProfileId", "countryCode", "policyHash", "network", "tokenId", "tokenDecimals", "atomicAmount", "capability", "authorizedAt"] as const;
function bindingCapability(value: PaymentCapability): string { return [value.schemaVersion, value.subjectProfileId, value.countryCode, value.network, value.tokenId, value.tokenDecimals, value.maxAtomicAmount.toString(), value.directTransferAllowed, value.merchantCheckoutAllowed, value.sanctionsClear, value.transactionMonitoringClear, value.policyHash, value.issuedAt, value.expiresAt, value.issuerKeyId, value.signature].join("|"); }
function parseAuthorization(value: unknown): PaymentAuthorization { const o = plain(value, AUTHORIZATION_KEYS, "PAYMENT_AUTHORIZATION_INVALID"); if (o.schemaVersion !== 1) fail("PAYMENT_AUTHORIZATION_INVALID"); return { schemaVersion: 1, rail: exact(o.rail, ["MULTIVERSX_DIRECT", "XMONEY_MERCHANT"], "PAYMENT_RAIL_INVALID"), subjectProfileId: text(o.subjectProfileId, ID, "PAYMENT_AUTHORIZATION_INVALID"), countryCode: text(o.countryCode, COUNTRY, "PAYMENT_AUTHORIZATION_INVALID"), policyHash: text(o.policyHash, HEX64, "PAYMENT_AUTHORIZATION_INVALID"), network: exact(o.network, ["devnet"], "NETWORK_INVALID"), tokenId: text(o.tokenId, TOKEN, "TOKEN_INVALID"), tokenDecimals: integer(o.tokenDecimals, 0, 18, "TOKEN_DECIMALS_INVALID"), atomicAmount: positive(o.atomicAmount, "AMOUNT_INVALID"), capability: parseCapability(o.capability), authorizedAt: iso(o.authorizedAt, "PAYMENT_AUTHORIZATION_INVALID") }; }

export interface DevnetEsdtTransferDraft { chainId: "D"; sender: string; receiver: string; nonce: bigint; value: "0"; gasLimit: 600000; data: string; receiptId: string; policyHash: string }
function asciiHex(value: string): string { let out = ""; for (const char of value) { const code = char.charCodeAt(0); if (code > 0x7f) fail("TOKEN_INVALID"); out += code.toString(16).padStart(2, "0"); } return out; }
export function buildDevnetEsdtTransferDraft(receiptInput: unknown, nonceInput: unknown): Readonly<DevnetEsdtTransferDraft> { const receipt = parseReceipt(receiptInput), nonce = nonnegative(nonceInput, "NONCE_INVALID"); if (receipt.network !== "devnet" || receipt.tokenId === "EGLD") fail("ESDT_DRAFT_INVALID"); const amountHex = receipt.atomicAmount.toString(16).padStart(receipt.atomicAmount.toString(16).length + receipt.atomicAmount.toString(16).length % 2, "0"); return frozen({ chainId: "D" as const, sender: receipt.senderAddress, receiver: receipt.receiverAddress, nonce, value: "0" as const, gasLimit: 600000 as const, data: `ESDTTransfer@${asciiHex(receipt.tokenId)}@${amountHex}`, receiptId: receipt.receiptId, policyHash: receipt.policyHash }); }

interface PaymentRecord { paymentId: string; state: PaymentState; receipt: ResolutionReceipt; txHash: string | null; failureCode: string | null }
export interface ChainObservation { txHash: string; network: "devnet"; tokenId: string; senderAddress: string; receiverAddress: string; senderDeltaAtomic: bigint; receiverDeltaAtomic: bigint; chainStatus: "SUCCESS" | "FAILED"; blockNonce: bigint; indexedAt: string }
export interface ChainObservationVerifier { verify(observation: Readonly<ChainObservation>, receipt: Readonly<ResolutionReceipt>): boolean }
interface DirectEvent { eventId: string; paymentId: string; ordinal: number; nextState: PaymentState; txHash: string | null; failureCode: string | null; observation: ChainObservation | null; fingerprint: string }
export interface DirectLedgerSnapshot { schemaVersion: 1; records: PaymentRecord[]; events: DirectEvent[] }
const DIRECT_RECORD_KEYS = ["paymentId", "state", "receipt", "txHash", "failureCode"] as const;
const DIRECT_EVENT_KEYS = ["eventId", "paymentId", "ordinal", "nextState", "txHash", "failureCode", "observation", "fingerprint"] as const;
const OBSERVATION_KEYS = ["txHash", "network", "tokenId", "senderAddress", "receiverAddress", "senderDeltaAtomic", "receiverDeltaAtomic", "chainStatus", "blockNonce", "indexedAt"] as const;
function parseObservation(value: unknown): ChainObservation { const o = plain(value, OBSERVATION_KEYS, "CHAIN_OBSERVATION_INVALID"); return { txHash: text(o.txHash, HEX64, "CHAIN_OBSERVATION_INVALID"), network: exact(o.network, ["devnet"], "NETWORK_INVALID"), tokenId: text(o.tokenId, TOKEN, "TOKEN_INVALID"), senderAddress: text(o.senderAddress, ADDRESS, "SENDER_INVALID"), receiverAddress: text(o.receiverAddress, ADDRESS, "RECEIVER_INVALID"), senderDeltaAtomic: signed(o.senderDeltaAtomic, "CHAIN_OBSERVATION_INVALID"), receiverDeltaAtomic: signed(o.receiverDeltaAtomic, "CHAIN_OBSERVATION_INVALID"), chainStatus: exact(o.chainStatus, ["SUCCESS", "FAILED"], "CHAIN_STATUS_INVALID"), blockNonce: nonnegative(o.blockNonce, "CHAIN_OBSERVATION_INVALID"), indexedAt: iso(o.indexedAt, "CHAIN_OBSERVATION_INVALID") }; }
function observationKey(value: ChainObservation | null): string { return value === null ? "" : [value.txHash, value.network, value.tokenId, value.senderAddress, value.receiverAddress, value.senderDeltaAtomic.toString(), value.receiverDeltaAtomic.toString(), value.chainStatus, value.blockNonce.toString(), value.indexedAt].join("|"); }
function validExecutionObservation(observation: ChainObservation, receipt: ResolutionReceipt, txHash: string | null): boolean { return observation.chainStatus === "SUCCESS" && observation.txHash === txHash && observation.network === receipt.network && observation.tokenId === receipt.tokenId && observation.senderAddress === receipt.senderAddress && observation.receiverAddress === receipt.receiverAddress && observation.senderDeltaAtomic === -receipt.atomicAmount && observation.receiverDeltaAtomic === receipt.atomicAmount && observation.senderDeltaAtomic + observation.receiverDeltaAtomic === 0n; }
function directEventFingerprint(eventId: string, paymentId: string, ordinal: number, nextState: PaymentState, txHash: string | null, failureCode: string | null, observation: ChainObservation | null, receipt: ResolutionReceipt): string { return [eventId, paymentId, ordinal, nextState, txHash ?? "", failureCode ?? "", observationKey(observation), bindingKey(receipt)].join("|"); }
export class DirectPaymentLedger {
  private readonly records = new Map<string, PaymentRecord>(); private readonly events = new Map<string, DirectEvent>();
  static restore(input: unknown, verifier: ChainObservationVerifier): DirectPaymentLedger {
    const o = plain(input, ["schemaVersion", "records", "events"], "DIRECT_SNAPSHOT_INVALID"); if (o.schemaVersion !== 1 || !verifier || typeof verifier.verify !== "function") fail("DIRECT_SNAPSHOT_INVALID");
    const ledger = new DirectPaymentLedger(), stored = new Map<string, PaymentRecord>(), parsedEvents: DirectEvent[] = [];
    for (const item of list(o.records, "DIRECT_SNAPSHOT_INVALID")) { const r = plain(item, DIRECT_RECORD_KEYS, "DIRECT_SNAPSHOT_INVALID"), receipt = parseReceipt(r.receipt), state = exact(r.state, ["PREVIEWED", "SIGNED", "SUBMITTED", "ORDERED", "EXECUTED_SUCCESS", "FAILED_TERMINAL"], "DIRECT_SNAPSHOT_INVALID"), txHash = r.txHash === null ? null : text(r.txHash, HEX64, "DIRECT_SNAPSHOT_INVALID"), failureCode = r.failureCode === null ? null : text(r.failureCode, ID, "DIRECT_SNAPSHOT_INVALID"), paymentId = text(r.paymentId, ID, "DIRECT_SNAPSHOT_INVALID"); if (stored.has(paymentId)) fail("DIRECT_SNAPSHOT_INVALID"); stored.set(paymentId, { paymentId, state, receipt, txHash, failureCode }); }
    const eventIds = new Set<string>();
    for (const item of list(o.events, "DIRECT_SNAPSHOT_INVALID")) { const e = plain(item, DIRECT_EVENT_KEYS, "DIRECT_SNAPSHOT_INVALID"), eventId = text(e.eventId, ID, "DIRECT_SNAPSHOT_INVALID"), paymentId = text(e.paymentId, ID, "DIRECT_SNAPSHOT_INVALID"), ordinal = integer(e.ordinal, 1, Number.MAX_SAFE_INTEGER, "DIRECT_SNAPSHOT_INVALID"), nextState = exact(e.nextState, ["SIGNED", "SUBMITTED", "ORDERED", "EXECUTED_SUCCESS", "FAILED_TERMINAL"], "DIRECT_SNAPSHOT_INVALID"), txHash = e.txHash === null ? null : text(e.txHash, HEX64, "DIRECT_SNAPSHOT_INVALID"), failureCode = e.failureCode === null ? null : text(e.failureCode, ID, "DIRECT_SNAPSHOT_INVALID"), observation = e.observation === null ? null : parseObservation(e.observation), fingerprint = text(e.fingerprint, /^.{3,8192}$/, "DIRECT_SNAPSHOT_INVALID"); if (eventIds.has(eventId) || !stored.has(paymentId)) fail("DIRECT_SNAPSHOT_INVALID"); eventIds.add(eventId); parsedEvents.push({ eventId, paymentId, ordinal, nextState, txHash, failureCode, observation, fingerprint }); }
    for (const record of stored.values()) {
      const lineage = parsedEvents.filter((event) => event.paymentId === record.paymentId).sort((a, b) => a.ordinal - b.ordinal); let state: PaymentState = "PREVIEWED", txHash: string | null = null, failureCode: string | null = null;
      for (let index = 0; index < lineage.length; index++) { const event = lineage[index]; if (event.ordinal !== index + 1 || event.fingerprint !== directEventFingerprint(event.eventId, event.paymentId, event.ordinal, event.nextState, event.txHash, event.failureCode, event.observation, record.receipt)) fail("DIRECT_SNAPSHOT_INVALID"); const expected: Partial<Record<PaymentState, PaymentState>> = { PREVIEWED: "SIGNED", SIGNED: "SUBMITTED", SUBMITTED: "ORDERED", ORDERED: "EXECUTED_SUCCESS" }; if (event.nextState === "FAILED_TERMINAL") { if (state === "EXECUTED_SUCCESS" || state === "FAILED_TERMINAL" || event.failureCode === null || event.txHash !== txHash || event.observation !== null) fail("DIRECT_SNAPSHOT_INVALID"); failureCode = event.failureCode; state = event.nextState; continue; } if (expected[state] !== event.nextState || event.failureCode !== null) fail("DIRECT_SNAPSHOT_INVALID"); if (event.nextState !== "EXECUTED_SUCCESS" && event.observation !== null) fail("DIRECT_SNAPSHOT_INVALID"); if (event.nextState === "SIGNED" && event.txHash !== null) fail("DIRECT_SNAPSHOT_INVALID"); if (event.nextState === "SUBMITTED") { if (event.txHash === null) fail("DIRECT_SNAPSHOT_INVALID"); txHash = event.txHash; } if ((event.nextState === "ORDERED" || event.nextState === "EXECUTED_SUCCESS") && (txHash === null || event.txHash !== txHash)) fail("DIRECT_SNAPSHOT_INVALID"); if (event.nextState === "EXECUTED_SUCCESS" && (event.observation === null || !validExecutionObservation(event.observation, record.receipt, txHash) || verifier.verify(frozen({ ...event.observation }), frozen({ ...record.receipt })) !== true)) fail("DIRECT_SNAPSHOT_INVALID"); state = event.nextState; }
      if (record.state !== state || record.txHash !== txHash || record.failureCode !== failureCode) fail("DIRECT_SNAPSHOT_INVALID"); ledger.records.set(record.paymentId, record);
    }
    for (const event of parsedEvents) ledger.events.set(event.eventId, event); return ledger;
  }
  create(paymentIdInput: unknown, receiptInput: unknown): Readonly<PaymentRecord> { const paymentId = text(paymentIdInput, ID, "PAYMENT_ID_INVALID"), receipt = parseReceipt(receiptInput); if (this.records.has(paymentId)) fail("PAYMENT_DUPLICATE"); const record: PaymentRecord = { paymentId, state: "PREVIEWED", receipt, txHash: null, failureCode: null }; this.records.set(paymentId, record); return frozen({ ...record, receipt: { ...record.receipt } }); }
  transition(paymentIdInput: unknown, eventIdInput: unknown, nextInput: unknown, receiptInput: unknown, txHashInput: unknown = null, failureCodeInput: unknown = null): Readonly<PaymentRecord> { const paymentId = text(paymentIdInput, ID, "PAYMENT_ID_INVALID"), eventId = text(eventIdInput, ID, "EVENT_ID_INVALID"), next = exact(nextInput, ["SIGNED", "SUBMITTED", "ORDERED", "FAILED_TERMINAL"], "PAYMENT_STATE_INVALID"), receipt = parseReceipt(receiptInput), record = this.records.get(paymentId); if (!record) fail("PAYMENT_NOT_FOUND"); if (this.events.has(eventId)) fail("PAYMENT_EVENT_REPLAY"); if (bindingKey(record.receipt) !== bindingKey(receipt)) fail("PAYMENT_RECEIPT_SUBSTITUTED"); if (record.state === "EXECUTED_SUCCESS" || record.state === "FAILED_TERMINAL") fail("PAYMENT_TRANSITION_INVALID"); const expected: Partial<Record<PaymentState, PaymentState>> = { PREVIEWED: "SIGNED", SIGNED: "SUBMITTED", SUBMITTED: "ORDERED" }; if (next !== "FAILED_TERMINAL" && expected[record.state] !== next) fail("PAYMENT_TRANSITION_INVALID"); let txHash = record.txHash, failureCode: string | null = null; if (next === "SUBMITTED") txHash = text(txHashInput, HEX64, "TX_HASH_REQUIRED"); if (next === "ORDERED") { const candidate = text(txHashInput, HEX64, "TX_HASH_REQUIRED"); if (candidate !== record.txHash) fail("TX_HASH_SUBSTITUTED"); txHash = candidate; } if (next === "FAILED_TERMINAL") failureCode = text(failureCodeInput, ID, "FAILURE_CODE_REQUIRED"); const ordinal = [...this.events.values()].filter((event) => event.paymentId === paymentId).length + 1, fingerprint = directEventFingerprint(eventId, paymentId, ordinal, next, txHash, failureCode, null, receipt); record.state = next; record.txHash = txHash; record.failureCode = failureCode; this.events.set(eventId, { eventId, paymentId, ordinal, nextState: next, txHash, failureCode, observation: null, fingerprint }); return frozen({ ...record, receipt: { ...record.receipt } }); }
  reconcileExecution(paymentIdInput: unknown, eventIdInput: unknown, receiptInput: unknown, observationInput: unknown, verifier: ChainObservationVerifier): Readonly<PaymentRecord> { const paymentId = text(paymentIdInput, ID, "PAYMENT_ID_INVALID"), eventId = text(eventIdInput, ID, "EVENT_ID_INVALID"), receipt = parseReceipt(receiptInput), record = this.records.get(paymentId); if (!record) fail("PAYMENT_NOT_FOUND"); if (this.events.has(eventId)) fail("PAYMENT_EVENT_REPLAY"); if (record.state !== "ORDERED" || bindingKey(record.receipt) !== bindingKey(receipt)) fail("PAYMENT_RECONCILIATION_INVALID"); const observation = parseObservation(observationInput); if (!verifier || verifier.verify(frozen({ ...observation }), frozen({ ...receipt })) !== true) fail("CHAIN_OBSERVATION_UNVERIFIED"); if (!validExecutionObservation(observation, receipt, record.txHash)) fail("CHAIN_EFFECT_MISMATCH"); record.state = "EXECUTED_SUCCESS"; const txHash = observation.txHash, ordinal = [...this.events.values()].filter((event) => event.paymentId === paymentId).length + 1, fingerprint = directEventFingerprint(eventId, paymentId, ordinal, "EXECUTED_SUCCESS", txHash, null, observation, receipt); this.events.set(eventId, { eventId, paymentId, ordinal, nextState: "EXECUTED_SUCCESS", txHash, failureCode: null, observation, fingerprint }); return frozen({ ...record, receipt: { ...record.receipt } }); }
  snapshot(): Readonly<DirectLedgerSnapshot> { return frozen({ schemaVersion: 1 as const, records: [...this.records.values()].sort((a, b) => a.paymentId.localeCompare(b.paymentId)).map((record) => ({ ...record, receipt: { ...record.receipt } })), events: [...this.events.values()].sort((a, b) => a.eventId.localeCompare(b.eventId)).map((event) => ({ ...event })) }); }
  get(paymentIdInput: unknown): Readonly<PaymentRecord> { const record = this.records.get(text(paymentIdInput, ID, "PAYMENT_ID_INVALID")); if (!record) fail("PAYMENT_NOT_FOUND"); return frozen({ ...record, receipt: { ...record.receipt } }); }
}

const ORDER_KEYS = ["nexusPaymentId", "idempotencyKey", "atomicAmount", "currency"] as const;
const WEBHOOK_KEYS = ["eventId", "orderId", "state", "occurredAt", "signature"] as const;
interface XMoneyWebhook { eventId: string; orderId: string; state: XMoneyState; occurredAt: string; signature: string }
export interface XMoneyWebhookVerifier { verify(event: Readonly<XMoneyWebhook>): boolean }
interface XOrder { orderId: string; nexusPaymentId: string; idempotencyKey: string; atomicAmount: bigint; currency: string; state: XMoneyState; credited: boolean; creditedEver: boolean; facts: XMoneyState[] }
interface XEvent extends XMoneyWebhook { fingerprint: string }
export interface XMoneySnapshot { schemaVersion: 1; sequence: number; orders: XOrder[]; events: XEvent[] }
export class LocalXMoneyReconciler {
  private readonly orders = new Map<string, XOrder>(); private readonly byIdempotency = new Map<string, string>(); private readonly events = new Map<string, XEvent>(); private sequence = 0;
  static restore(input: unknown, verifier: XMoneyWebhookVerifier): LocalXMoneyReconciler {
    const o = plain(input, ["schemaVersion", "sequence", "orders", "events"], "XMONEY_SNAPSHOT_INVALID"); if (o.schemaVersion !== 1 || !verifier || typeof verifier.verify !== "function") fail("XMONEY_SNAPSHOT_INVALID"); const result = new LocalXMoneyReconciler(); result.sequence = integer(o.sequence, 0, Number.MAX_SAFE_INTEGER, "XMONEY_SNAPSHOT_INVALID"); const ordinals = new Set<number>();
    for (const item of list(o.orders, "XMONEY_SNAPSHOT_INVALID")) { const row = plain(item, ["orderId", "nexusPaymentId", "idempotencyKey", "atomicAmount", "currency", "state", "credited", "creditedEver", "facts"], "XMONEY_SNAPSHOT_INVALID"), order: XOrder = { orderId: text(row.orderId, ID, "XMONEY_SNAPSHOT_INVALID"), nexusPaymentId: text(row.nexusPaymentId, ID, "XMONEY_SNAPSHOT_INVALID"), idempotencyKey: text(row.idempotencyKey, ID, "XMONEY_SNAPSHOT_INVALID"), atomicAmount: positive(row.atomicAmount, "XMONEY_SNAPSHOT_INVALID"), currency: text(row.currency, /^(EGLD|USDC|EUR)$/, "XMONEY_SNAPSHOT_INVALID"), state: exact(row.state, ["CREATED", "PENDING", "PAID", "FAILED", "REFUNDED"], "XMONEY_SNAPSHOT_INVALID"), credited: bool(row.credited, "XMONEY_SNAPSHOT_INVALID"), creditedEver: bool(row.creditedEver, "XMONEY_SNAPSHOT_INVALID"), facts: list(row.facts, "XMONEY_SNAPSHOT_INVALID").map((fact) => exact(fact, ["CREATED", "PENDING", "PAID", "FAILED", "REFUNDED"], "XMONEY_SNAPSHOT_INVALID")) }; const match = /^XMONEY:ORDER:(\d+)$/.exec(order.orderId), ordinal = match ? Number(match[1]) : 0; if (!Number.isSafeInteger(ordinal) || ordinal < 1 || ordinals.has(ordinal) || result.orders.has(order.orderId) || result.byIdempotency.has(order.idempotencyKey) || new Set(order.facts).size !== order.facts.length) fail("XMONEY_SNAPSHOT_INVALID"); ordinals.add(ordinal); result.orders.set(order.orderId, order); result.byIdempotency.set(order.idempotencyKey, order.orderId); }
    if (ordinals.size !== result.sequence || (result.sequence > 0 && Math.max(...ordinals) !== result.sequence) || [...ordinals].some((value) => value > result.sequence)) fail("XMONEY_SNAPSHOT_INVALID");
    for (const item of list(o.events, "XMONEY_SNAPSHOT_INVALID")) { const row = plain(item, ["eventId", "orderId", "state", "occurredAt", "signature", "fingerprint"], "XMONEY_SNAPSHOT_INVALID"), event: XEvent = { eventId: text(row.eventId, ID, "XMONEY_SNAPSHOT_INVALID"), orderId: text(row.orderId, ID, "XMONEY_SNAPSHOT_INVALID"), state: exact(row.state, ["CREATED", "PENDING", "PAID", "FAILED", "REFUNDED"], "XMONEY_SNAPSHOT_INVALID"), occurredAt: iso(row.occurredAt, "XMONEY_SNAPSHOT_INVALID"), signature: text(row.signature, HEX64, "XMONEY_SNAPSHOT_INVALID"), fingerprint: text(row.fingerprint, /^.{3,1024}$/, "XMONEY_SNAPSHOT_INVALID") }; const signedEvent: XMoneyWebhook = { eventId: event.eventId, orderId: event.orderId, state: event.state, occurredAt: event.occurredAt, signature: event.signature }; if (result.events.has(event.eventId) || !result.orders.has(event.orderId) || event.fingerprint !== webhookKey(signedEvent) || verifier.verify(frozen({ ...signedEvent })) !== true) fail("XMONEY_SNAPSHOT_INVALID"); result.events.set(event.eventId, event); }
    for (const order of result.orders.values()) { const facts = new Set<XMoneyState>(["CREATED"]); for (const event of result.events.values()) if (event.orderId === order.orderId) facts.add(event.state); const expectedFacts = [...facts].sort(), actualFacts = [...order.facts].sort(), state = deriveXMoneyState(facts); if (expectedFacts.join("|") !== actualFacts.join("|") || order.state !== state || order.credited !== (state === "PAID") || order.creditedEver !== facts.has("PAID")) fail("XMONEY_SNAPSHOT_INVALID"); }
    return result;
  }
  createOrder(input: unknown): Readonly<XOrder> { const o = plain(input, ORDER_KEYS, "XMONEY_ORDER_INVALID"), proposed = { nexusPaymentId: text(o.nexusPaymentId, ID, "PAYMENT_ID_INVALID"), idempotencyKey: text(o.idempotencyKey, ID, "IDEMPOTENCY_KEY_INVALID"), atomicAmount: positive(o.atomicAmount, "AMOUNT_INVALID"), currency: text(o.currency, /^(EGLD|USDC|EUR)$/, "CURRENCY_INVALID") }, existingId = this.byIdempotency.get(proposed.idempotencyKey); if (existingId) { const existing = this.orders.get(existingId)!; if (orderKey(existing) !== orderKey(proposed)) fail("XMONEY_IDEMPOTENCY_CONFLICT"); return this.get(existingId); } const record: XOrder = { orderId: `XMONEY:ORDER:${++this.sequence}`, ...proposed, state: "CREATED", credited: false, creditedEver: false, facts: ["CREATED"] }; this.orders.set(record.orderId, record); this.byIdempotency.set(record.idempotencyKey, record.orderId); return frozen({ ...record, facts: [...record.facts] }); }
  applyWebhook(input: unknown, verifier: XMoneyWebhookVerifier, receivedAtInput: unknown): Readonly<{ duplicate: boolean; creditedNow: boolean; order: XOrder }> { const o = plain(input, WEBHOOK_KEYS, "XMONEY_WEBHOOK_INVALID"), event = frozen({ eventId: text(o.eventId, ID, "EVENT_ID_INVALID"), orderId: text(o.orderId, ID, "XMONEY_ORDER_INVALID"), state: exact(o.state, ["CREATED", "PENDING", "PAID", "FAILED", "REFUNDED"], "XMONEY_STATE_INVALID"), occurredAt: iso(o.occurredAt, "XMONEY_TIME_INVALID"), signature: text(o.signature, HEX64, "XMONEY_SIGNATURE_INVALID") }), receivedAt = iso(receivedAtInput, "XMONEY_TIME_INVALID"); if (Date.parse(event.occurredAt) > Date.parse(receivedAt) + 300_000) fail("XMONEY_EVENT_FROM_FUTURE"); if (!verifier || verifier.verify(event) !== true) fail("XMONEY_SIGNATURE_INVALID"); const order = this.orders.get(event.orderId); if (!order) fail("XMONEY_ORDER_NOT_FOUND"); const fingerprint = webhookKey(event), existing = this.events.get(event.eventId); if (existing !== undefined) { if (existing.fingerprint !== fingerprint) fail("XMONEY_EVENT_COLLISION"); return frozen({ duplicate: true, creditedNow: false, order: { ...order, facts: [...order.facts] } }); } const beforeCreditedEver = order.creditedEver, facts = new Set(order.facts); facts.add(event.state); order.facts = [...facts].sort(); order.state = deriveXMoneyState(facts); order.creditedEver = facts.has("PAID"); order.credited = order.state === "PAID"; const creditedNow = !beforeCreditedEver && order.creditedEver && !facts.has("REFUNDED"); this.events.set(event.eventId, { ...event, fingerprint }); return frozen({ duplicate: false, creditedNow, order: { ...order, facts: [...order.facts] } }); }
  snapshot(): Readonly<XMoneySnapshot> { return frozen({ schemaVersion: 1 as const, sequence: this.sequence, orders: [...this.orders.values()].sort((a, b) => a.orderId.localeCompare(b.orderId)).map((order) => ({ ...order, facts: [...order.facts] })), events: [...this.events.values()].sort((a, b) => a.eventId.localeCompare(b.eventId)).map((event) => ({ ...event })) }); }
  get(orderIdInput: unknown): Readonly<XOrder> { const order = this.orders.get(text(orderIdInput, ID, "XMONEY_ORDER_INVALID")); if (!order) fail("XMONEY_ORDER_NOT_FOUND"); return frozen({ ...order, facts: [...order.facts] }); }
}
function deriveXMoneyState(facts: Set<XMoneyState>): XMoneyState { if (facts.has("REFUNDED")) return "REFUNDED"; if (facts.has("PAID")) return "PAID"; if (facts.has("FAILED")) return "FAILED"; if (facts.has("PENDING")) return "PENDING"; return "CREATED"; }
