/**
 * The Etapa 4 flow of one capture: the account copy of the draft and the publication itself.
 *
 * `draftsClient.ts` owns the two endpoints the backup needs (`/api/uploads`, `/api/creator/drafts`)
 * and `publishClient.ts` owns `POST /api/posts`. This module is the order the web performs them in —
 * `public/creator-draft-sync.js` for the backup, the `composerForm` handler of `public/app.js` for the
 * publish — and the four rules that keep the two copies consistent:
 *
 * - the media travels before the row: a refused post leaves the object stored and the draft on the
 *   phone, never a half post;
 * - one idempotency key per intent, regenerated by the editor on every edit, so an answer lost on a
 *   bad connection is replayed by the server instead of writing a second post;
 * - everything the server checks locally (the publishing details, the audio declaration, the MIME
 *   list) is checked *before* the first byte leaves the phone;
 * - a failed backup never blocks a publish, and a successful publish removes the backup.
 */

import {
  creatorDraftId, draftFailure, draftFieldsFrom, draftScope, DraftError, localFileSize,
  syncCreatorDraft, uploadDraftMedia, type DraftFieldValue, type DraftMediaRef,
} from './draftsClient';
import { idempotencyKeyIsValid } from './idempotency';
import type { LocalCapture, LocalDraft } from './localCapture';
import { nexusApi } from './nexusApi';
import { normalizePublishing, PublishingError } from './publishing';
import {
  AUDIO_ATTRIBUTION_LIMIT, CREATOR_AUDIO_RIGHTS, publishFailure, publishPost, PublishError,
  type PostKind, type PublishIntent, type PublishedPost,
} from './publishClient';
import type { MeResponse } from './socialTypes';
import {
  extensionOf, uploadFailure, UploadClientError, uploadMimeForName,
  type UploadProgress, type UploadSource,
} from './uploadClient';

/** The account and the profile the editor writes for, read once when the editor opens. */
export type EditorIdentity = { userId: number; persona: string };

/**
 * `/api/me`, read the same way `app/index.tsx` reads it. The persona comes from the same answer, so a
 * post is never written into a profile the user is not currently on.
 */
export async function loadEditorIdentity(): Promise<EditorIdentity> {
  const me = await nexusApi<MeResponse>('/api/me');
  const userId = Number(me?.user?.id ?? 0);
  const persona = String(me?.persona ?? '').trim();
  if (!Number.isSafeInteger(userId) || userId < 1 || !persona) {
    throw new Error('Contul nu a putut fi citit. Autentifică-te din nou, apoi reia.');
  }
  return { userId, persona };
}

/** What the editor prints above the buttons: the phase in flight and how much of it is done. */
export type CaptureFlowProgress = {
  phase: UploadProgress['phase'] | 'writing';
  /** `0..100`; `0` while the total size is still unknown, never an invented number. */
  percent: number;
};

export type CaptureFlowReporter = (progress: CaptureFlowProgress) => void;

function reportUpload(progress: UploadProgress, report?: CaptureFlowReporter): void {
  if (!report) return;
  const total = Number(progress.total ?? 0);
  const sent = Number(progress.sent ?? 0);
  const percent = total > 0 ? Math.max(0, Math.min(100, Math.round((sent / total) * 100))) : 0;
  report({ phase: progress.phase, percent });
}


/** The account row of this capture, or `null` when its file name cannot produce a valid draft id. */
export function captureDraftId(capture: LocalCapture): string | null {
  try { return creatorDraftId(capture.name); } catch { return null; }
}

/**
 * The `fields` of the backup, in the shape the web's draft library reads back. The catalog track is
 * deliberately absent: `jamendo_track` describes a Jamendo selection the server resolves by its
 * two-hour token, and this editor does not publish one — writing the key would claim otherwise.
 */
export function captureDraftFields(draft: LocalDraft): Record<string, DraftFieldValue> {
  const localAudio = Boolean(draft.audioUri);
  return draftFieldsFrom({
    caption: draft.description,
    visibility: draft.visibility,
    provenance: draft.provenance,
    publishing: draft.publishing,
    overlayText: draft.overlayText,
    overlayY: draft.overlayY,
    audioRights: localAudio ? (draft.audioRights ?? null) : null,
    audioAttribution: localAudio ? (draft.audioAttribution ?? '') : '',
  });
}

/** The MIME type of the capture; `null` for a format outside the server's list (HEIC, MOV, M4V). */
export function captureUploadMime(capture: LocalCapture): string | null {
  return uploadMimeForName(capture.name);
}

/**
 * The MIME type of the phone audio file, from the name the user picked and, when that name carries no
 * extension the server knows, from the file this app stored (`<capture>.audio.<ext>`).
 */
export function audioUploadMime(draft: LocalDraft): string | null {
  if (!draft.audioUri) return null;
  return uploadMimeForName(draft.audioName ?? '') ?? uploadMimeForName(draft.audioUri);
}

/**
 * A catalog pick is a preview the app cannot publish: `POST /api/posts` resolves a Jamendo selection
 * by a token that is valid for two hours, and this editor keeps only the preview URL and its
 * attribution. Refusing it here, in words, is the only honest answer.
 */
export class CatalogAudioError extends Error {
  constructor() {
    super('Melodia aleasă din catalogul Nexus nu poate fi publicată din aplicație. Alege un fișier audio de pe telefon sau elimină melodia.');
    this.name = 'CatalogAudioError';
  }
}

/** True when the draft carries a catalog preview and no file this app could upload. */
export function catalogAudioSelected(draft: LocalDraft): boolean {
  return Boolean(draft.jamendoAudioUrl) && !draft.audioUri;
}

/** One object to upload, with the size read from disk when the manifest does not carry one. */
type UploadCandidate = { uri: string; name: string; mime: string | null; size: number };

function captureCandidate(capture: LocalCapture): UploadCandidate {
  return {
    uri: capture.uri,
    name: capture.name,
    mime: captureUploadMime(capture),
    size: capture.size > 0 ? capture.size : localFileSize(capture.uri),
  };
}

function audioCandidate(draft: LocalDraft): UploadCandidate | null {
  if (!draft.audioUri) return null;
  const stored = extensionOf(draft.audioUri);
  const name = draft.audioName && extensionOf(draft.audioName) ? draft.audioName : `audio.${stored || 'mp3'}`;
  return { uri: draft.audioUri, name, mime: audioUploadMime(draft), size: localFileSize(draft.audioUri) };
}

/** The upload source the provider wants; the size is what the progress is measured against. */
function uploadSource(candidate: UploadCandidate): UploadSource {
  return { uri: candidate.uri, name: candidate.name, size: candidate.size };
}

/**
 * The refusal the uploader would answer after the first chunk is answered here instead, before any of
 * the 20 MB leaves the phone: the server's MIME list is known and its message names the formats.
 */
function requireSupported(candidate: UploadCandidate): string {
  if (!candidate.mime) throw uploadFailure('UPLOAD_MIME_UNSUPPORTED', 415);
  return candidate.mime;
}

export type CaptureBackupRequest = {
  identity: EditorIdentity;
  capture: LocalCapture;
  draft: LocalDraft;
  /** `draftMutationKey(id, draft.updatedAt)`: the same key while nothing changed, a new one per edit. */
  key: string;
  signal?: AbortSignal;
  onProgress?: CaptureFlowReporter;
};

export type CaptureBackup = { id: string; media: DraftMediaRef[] };

/**
 * The account copy of the draft: the objects first, then the row — `public/creator-draft-sync.js:59`.
 * The local manifest is already on disk, so a failure here costs a backup, never a keystroke.
 */
export async function backupCapture(request: CaptureBackupRequest): Promise<CaptureBackup> {
  const id = captureDraftId(request.capture);
  if (!id) throw draftFailure('DRAFT_ID_INVALID');
  const source = captureCandidate(request.capture);
  const audio = audioCandidate(request.draft);
  const mime = requireSupported(source);
  return syncCreatorDraft({
    id,
    mode: 'post',
    fields: captureDraftFields(request.draft),
    expected: request.identity,
    key: request.key,
    source: { uri: source.uri, name: source.name, mime, size: source.size },
    audio: audio
      ? { uri: audio.uri, name: audio.name, mime: requireSupported(audio), size: audio.size }
      : null,
    signal: request.signal,
    onProgress: (progress) => reportUpload(progress, request.onProgress),
  });
}

/**
 * `normalizeCreatorAudio` refuses uploaded audio that carries no declaration, and the client must
 * never invent one: the right to use a file the user picked is the one thing only they can state.
 */
function assertAudioDeclaration(draft: LocalDraft, hasLocalAudio: boolean): void {
  if (!hasLocalAudio) return;
  if (!draft.audioRights || !CREATOR_AUDIO_RIGHTS.includes(draft.audioRights)) {
    throw publishFailure('PUBLISH_AUDIO_RIGHTS_REQUIRED', 0);
  }
  if ((draft.audioAttribution ?? '').trim().length > AUDIO_ATTRIBUTION_LIMIT) {
    throw publishFailure('PUBLISH_AUDIO_ATTRIBUTION', 0);
  }
}

export type CapturePublishRequest = {
  identity: EditorIdentity;
  capture: LocalCapture;
  draft: LocalDraft;
  /** `publishIntentKey()`: one key per publish intent, repeated verbatim when only the answer was lost. */
  key: string;
  /** `language` of the post. The editor offers no language field yet, so it stays `null`. */
  language?: string | null;
  signal?: AbortSignal;
  onProgress?: CaptureFlowReporter;
};

/**
 * The publish itself, in the order of the web's `composerForm`: validate what can be validated, upload
 * the source, upload the audio, then write the post. `public/app.js` sends the same body with the same
 * `social_post` / `social_audio` purposes, so an object uploaded for the account copy is reused here
 * instead of travelling a second time.
 */
export async function publishCapture(request: CapturePublishRequest): Promise<PublishedPost> {
  const { capture, draft } = request;
  if (catalogAudioSelected(draft)) throw new CatalogAudioError();
  if (!idempotencyKeyIsValid(request.key)) throw publishFailure('PUBLISH_INVALID', 0);
  const source = captureCandidate(capture);
  const audio = audioCandidate(draft);
  const sourceMime = requireSupported(source);
  const audioMime = audio ? requireSupported(audio) : null;
  // Everything the server checks without the media is checked now, so a details refusal never costs an
  // upload: `normalizePublishing` is the exact function `publishPost` runs, only earlier.
  const publishing = normalizePublishing(draft.publishing);
  assertAudioDeclaration(draft, Boolean(audio));
  const kind: PostKind = capture.kind === 'video' ? 'video' : 'image';
  const scope = draftScope(request.identity.userId, request.identity.persona);
  const uploaded = await uploadDraftMedia({
    scope,
    purpose: 'social_post',
    source: uploadSource(source),
    mime: sourceMime,
    signal: request.signal,
    onProgress: (progress) => reportUpload(progress, request.onProgress),
  });
  const intent: PublishIntent = {
    persona: request.identity.persona,
    caption: draft.description,
    visibility: draft.visibility,
    language: request.language ?? null,
    provenance: draft.provenance,
    publishing,
    kind,
    media: { hash: uploaded.hash, ext: uploaded.ext },
    audioRights: audio ? (draft.audioRights ?? null) : null,
    audioAttribution: audio ? (draft.audioAttribution ?? '') : '',
  };
  if (audio) {
    const track = await uploadDraftMedia({
      scope,
      purpose: 'social_audio',
      source: uploadSource(audio),
      mime: audioMime,
      signal: request.signal,
      onProgress: (progress) => reportUpload(progress, request.onProgress),
    });
    intent.audio = { hash: track.hash, ext: track.ext };
  }
  request.onProgress?.({ phase: 'writing', percent: 100 });
  return publishPost({
    intent, key: request.key, userId: request.identity.userId, signal: request.signal,
  });
}

/**
 * One Romanian sentence for anything the flow can raise. Each family keeps its own wording — a
 * `PublishError` names the refused rule, an `UploadClientError` the refused object — and the last line
 * is the promise the whole design rests on: the draft and the file stay on the phone.
 */
export function captureFlowErrorMessage(error: unknown): string {
  if (error instanceof CatalogAudioError) return error.message;
  if (error instanceof PublishError || error instanceof PublishingError) return error.message;
  if (error instanceof UploadClientError) return error.message;
  if (error instanceof DraftError) return error.message;
  if (error instanceof Error && error.message) return error.message;
  return 'Acțiunea nu a putut fi încheiată. Draftul și fișierul rămân pe telefon.';
}
