import { authorizeSaveDownload, ExperienceClock, ExperienceCommand, ExperienceCommandVerifier, ExperienceLedger, ExperiencePolicyError, LocalExperienceAuthority, LocalExperienceSnapshotAuthority, LocalMonotonicExperienceClock, LocalSecurityReceiptRegistry, presentIdentity, ProfileType, qualifyAudience, SecurityAuthorityRole, SecurityReceipt, SecurityReceiptKind, selectDiscovery } from "./index";
declare const process: { stdout: { write(value: string): void } };

let assertions = 0;
function assert(value: unknown, message: string): asserts value { assertions++; if (!value) throw new Error(message); }
async function denied(action: () => Promise<unknown>, code: string): Promise<void> { let actual = "NO_ERROR"; try { await action(); } catch (error) { actual = error instanceof ExperiencePolicyError ? error.code : String(error); } assert(actual === code, `expected ${code}, got ${actual}`); }
function deniedSync(action: () => unknown, code: string): void { let actual = "NO_ERROR"; try { action(); } catch (error) { actual = error instanceof ExperiencePolicyError ? error.code : String(error); } assert(actual === code, `expected ${code}, got ${actual}`); }
const H = (value: number): string => value.toString(16).padStart(64, "0"), ZERO = H(0), AT = "2026-01-01T10:00:00.000Z", AUTH_END = "2026-01-04T00:00:00.000Z";
const MEDIA_LIFECYCLE = { keyEpoch: 7, licenseCommitment: H(8801), rightsState: "ACTIVE" as const, purgeEpoch: 0 }, WATERMARK = { platformMark: "NEXUS" as const, creatorHandle: "nova.creator", contentCommitment: H(804), verificationCode: "VERIFY:CONTENT:804", exportArtifactCommitment: H(8802), deviceCommitment: H(803) };
async function digest(value: string): Promise<string> { const data = await globalThis.crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); return [...new Uint8Array(data)].map(byte => byte.toString(16).padStart(2, "0")).join(""); }

const clock = new LocalMonotonicExperienceClock(AT), receipts = new LocalSecurityReceiptRegistry(clock);
const authorityKeys: Record<SecurityAuthorityRole, string> = { PROFILE: "AUTH:PROFILE", AGE: "AUTH:AGE", WALLET: "AUTH:WALLET", CONSENT: "AUTH:CONSENT", GUARDIAN: "AUTH:GUARDIAN", TRUST: "AUTH:TRUST", SOURCE: "AUTH:SOURCE:A", OFFICIAL: "AUTH:OFFICIAL", MEDIA: "AUTH:MEDIA", RIGHTS: "AUTH:RIGHTS", MODERATION: "AUTH:MODERATION", DISCOVERY: "AUTH:DISCOVERY" };
function registerAuthorities(registry: LocalSecurityReceiptRegistry): void { let rootCounter = 700; for (const role of Object.keys(authorityKeys) as SecurityAuthorityRole[]) registry.register(role, authorityKeys[role], H(rootCounter++), `fixture-secret-${role.toLowerCase()}-0001`); registry.register("SOURCE", "AUTH:SOURCE:B", H(rootCounter++), "fixture-secret-source-b-0001"); }
registerAuthorities(receipts);
const authority = new LocalExperienceAuthority("AUTH:EXPERIENCE:FIXTURE", "local-experience-fixture-key", clock), snapshotAuthority = new LocalExperienceSnapshotAuthority("AUTH:SNAPSHOT:FIXTURE", "local-snapshot-fixture-key");
const receiptNonces = new Map<string, number>(); let receiptSequence = 0;
type ReceiptInput = Omit<SecurityReceipt, "schemaVersion" | "issuedAt" | "authorityRole" | "authorityKeyId" | "authorityRootCommitment" | "signature">;
async function attest(role: SecurityAuthorityRole, kind: SecurityReceiptKind, subject: string, object: string, binding: string, purpose: string, surface: SecurityReceipt["surface"], options: Partial<ReceiptInput> = {}, authorityKeyId?: string): Promise<string> { const selectedKey = authorityKeyId ?? authorityKeys[role], nonceKey = `${selectedKey}:${subject}:${purpose}`, nonce = (receiptNonces.get(nonceKey) ?? 0) + 1; receiptNonces.set(nonceKey, nonce); const input: ReceiptInput = { receiptId: `RECEIPT:${(++receiptSequence).toString().padStart(4, "0")}`, kind, subjectCommitment: subject, objectCommitment: object, bindingCommitment: binding, surface, generation: 1, jurisdiction: "GLOBAL", purpose, normalizedScoreBps: 0, qualifiedActors: 0, independentClusters: 0, trafficClean: true, mediaLifecycle: null, watermark: null, enforcement: null, nonce, policyVersion: 1, expiresAt: AUTH_END, ...options }; return (await receipts.issue(role, input, authorityKeyId)).commitment; }

type Unsigned = Omit<ExperienceCommand, "occurredAt" | "authorityKeyId" | "signature">;
function profile(surface: ExperienceCommand["surface"]): ProfileType { return surface === "MARKET" ? "MARKETPLACE" : surface; }
async function issue(overrides: Partial<Unsigned> & Pick<Unsigned, "commandId" | "objectCommitment" | "actorProfileCommitment" | "nonce">): Promise<Readonly<ExperienceCommand>> { const surface = overrides.surface ?? "SOCIAL", type = profile(surface), actor = overrides.actorProfileCommitment, base: Unsigned = { schemaVersion: 1, commandId: overrides.commandId, domain: "STORY", action: "STORY_PUBLISH", surface, actorProfileCommitment: actor, actorProfileType: type, ownerProfileCommitment: actor, ownerProfileType: type, objectCommitment: overrides.objectCommitment, payloadCommitment: H(900), priorPayloadCommitment: null, parentCommitment: null, sourceCommitment: null, storyDuration: "PT24H", pulseFormat: null, revisionKind: "NONE", generation: 1, roomKind: null, participants: [], receiptCommitments: [], encryptionMode: null, encryptionSuite: null, sessionKeyCommitment: null, recordingRequested: false, contactMetadataIncluded: false, audience: "PUBLIC", actorClass: "SYSTEM_TEST", nonce: overrides.nonce, policyVersion: 1, authorizationExpiresAt: AUTH_END }; return authority.issue({ ...base, ...overrides }); }
function baseDownload(overrides: Record<string, unknown> = {}): Record<string, unknown> { return { operation: "SAVE_IN_NEXUS", surface: "SOCIAL", profileType: "SOCIAL", profileCommitment: H(801), contentOwnerCommitment: H(802), deviceCommitment: H(803), objectCommitment: H(804), mediaLifecycle: MEDIA_LIFECYCLE, watermark: null, audienceReceiptCommitment: H(805), rightsReceiptCommitment: H(806), guardianReceiptCommitment: null, authorPolicyReceiptCommitment: null, offlineGrantReceiptCommitment: null, watermarkReceiptCommitment: null, ...overrides }; }
function baseIdentity(overrides: Record<string, unknown> = {}): Record<string, unknown> { return { profileCommitment: H(820), profileType: "SOCIAL", displayName: "Nova", handle: "nova.user", fullProfessionalName: null, exactAge: null, businessName: null, shareAgeOnSocial: false, ageReceiptCommitment: null, adultReceiptCommitment: null, walletReceiptCommitment: null, ...overrides }; }
function discoveryRequest(overrides: Record<string, unknown> = {}): Record<string, unknown> { return { lens: "FOR_YOU", profileCommitment: H(850), profileType: "SOCIAL", languagePreferences: ["ro", "en"], region: "RO-B", coarseGeohash: "sxfs12", locationMode: "DISABLED", locationReceiptCommitment: null, maxItems: 10, ...overrides }; }
type CandidateOptions = { profileType?: ProfileType; language?: string; region?: string; coarseGeohash?: string | null; interestScoreBps?: number; popularityBps?: number; trafficClass?: "HUMAN_ORGANIC" | "PAID" | "AGENT" | "SYSTEM_TEST" | "INCENTIVIZED"; quarantined?: boolean; paid?: boolean; politicalTargeting?: boolean; breakingImpact?: "NONE" | "MAJOR" | "CRITICAL"; publishedAt?: string; sourceDomains?: string[]; sourceReceiptCommitments?: string[]; officialAlertReceiptCommitment?: string | null; trustReceiptCommitment?: string | null; kidsReceiptCommitment?: string | null; regionalJurisdictions?: string[]; regionalReceiptCommitments?: string[]; trafficClean?: boolean; };
async function candidate(id: number, options: CandidateOptions = {}): Promise<Record<string, unknown>> { const profileType = options.profileType ?? "SOCIAL", surface = profileType === "MARKETPLACE" ? "MARKET" : profileType as SecurityReceipt["surface"], value = { candidateCommitment: H(id), profileType, language: options.language ?? "ro", region: options.region ?? "RO-B", coarseGeohash: options.coarseGeohash === undefined ? "sxfs99" : options.coarseGeohash, interestScoreBps: options.interestScoreBps ?? 5000, popularityBps: options.popularityBps ?? 5000, trafficClass: options.trafficClass ?? "HUMAN_ORGANIC", quarantined: options.quarantined ?? false, paid: options.paid ?? false, politicalTargeting: options.politicalTargeting ?? false, breakingImpact: options.breakingImpact ?? "NONE", publishedAt: options.publishedAt ?? "2026-01-01T10:00:00.000Z", sourceDomains: options.sourceDomains ?? [], sourceReceiptCommitments: options.sourceReceiptCommitments ?? [], officialAlertReceiptCommitment: options.officialAlertReceiptCommitment ?? null, trustReceiptCommitment: options.trustReceiptCommitment ?? null, kidsReceiptCommitment: options.kidsReceiptCommitment ?? null, regionalJurisdictions: options.regionalJurisdictions ?? [], regionalReceiptCommitments: options.regionalReceiptCommitments ?? [] }, trafficBinding = await digest(`TRAFFIC:${value.trafficClass}:${value.quarantined}:${value.paid}:${value.politicalTargeting}`), eligibilityReceiptCommitment = await attest("TRUST", "TRUST_EVIDENCE", value.candidateCommitment, value.candidateCommitment, trafficBinding, "DISCOVERY_ELIGIBILITY", surface, { jurisdiction: value.region, trafficClean: options.trafficClean ?? true }); return { ...value, eligibilityReceiptCommitment }; }

async function main(): Promise<void> {
  const ledger = new ExperienceLedger(authority, authority.keyId, clock, receipts), social = H(1), story = H(101), media = H(201);
  await ledger.append(await issue({ commandId: "CMD:STORY:24H", objectCommitment: story, actorProfileCommitment: social, nonce: 1, payloadCommitment: media }));
  assert(ledger.storyVisible(story), "24h Story is visible before expiry"); clock.advanceTo("2026-01-01T10:30:00.000Z");
  await ledger.append(await issue({ commandId: "CMD:STORY:PROMOTE", action: "STORY_PROMOTE_HIGHLIGHT", objectCommitment: story, actorProfileCommitment: social, nonce: 2, payloadCommitment: media, priorPayloadCommitment: media, storyDuration: "UNTIL_AUTHOR_REMOVES" }));
  assert(ledger.story(story).state === "HIGHLIGHT", "until removed is represented as Highlight");
  const expiringOwner = H(2), expiringStory = H(102), expiringMedia = H(202); await ledger.append(await issue({ commandId: "CMD:STORY:1H", objectCommitment: expiringStory, actorProfileCommitment: expiringOwner, nonce: 1, payloadCommitment: expiringMedia, storyDuration: "PT1H" })); clock.advanceTo("2026-01-01T12:00:00.000Z"); assert(!ledger.storyVisible(expiringStory), "Story visibility uses the injected monotonic clock");
  await denied(async () => ledger.append(await issue({ commandId: "CMD:STORY:LATE-PROMOTE", action: "STORY_PROMOTE_HIGHLIGHT", objectCommitment: expiringStory, actorProfileCommitment: expiringOwner, nonce: 2, payloadCommitment: expiringMedia, priorPayloadCommitment: expiringMedia, storyDuration: "UNTIL_AUTHOR_REMOVES" })), "EXPERIENCE_STORY_PROMOTE_DENIED");
  const moderator = H(3), enforcement = { appealCommitment: H(2003), duration: "PERMANENT", reasonCode: "ILLEGAL_CONTENT", ruleId: "DSA:ARTICLE:16", territory: "GLOBAL" }, enforcementCommitment = await digest(JSON.stringify(enforcement)), purgeReceipt = await attest("MODERATION", "SAFETY_RIGHTS_PURGE", moderator, expiringStory, expiringMedia, "STORY_PURGE", "SOCIAL", { enforcement });
  await ledger.append(await issue({ commandId: "CMD:STORY:SAFETY-PURGE", action: "STORY_ENFORCEMENT_PURGE", objectCommitment: expiringStory, actorProfileCommitment: moderator, ownerProfileCommitment: expiringOwner, nonce: 1, payloadCommitment: enforcementCommitment, priorPayloadCommitment: expiringMedia, storyDuration: "PT1H", receiptCommitments: [purgeReceipt] }));
  assert(ledger.story(expiringStory).state === "PURGED" && ledger.story(expiringStory).mediaCommitment === ZERO, "role-separated safety or rights authority overrides Story duration");
  const datingOwner = H(4); await ledger.append(await issue({ commandId: "CMD:DATING:STORY", surface: "DATING", objectCommitment: H(104), actorProfileCommitment: datingOwner, nonce: 1, audience: "PRIVATE" })); assert(ledger.story(H(104)).audience === "PRIVATE", "Dating Story is private");
  await denied(async () => ledger.append(await issue({ commandId: "CMD:DATING:PUBLIC", surface: "DATING", objectCommitment: H(105), actorProfileCommitment: H(5), nonce: 1, audience: "PUBLIC" })), "EXPERIENCE_STORY_AUDIENCE_DENIED");

  const pulseOwner = H(10), pulse = H(110), firstPayload = H(210), editedPayload = H(211); await ledger.append(await issue({ commandId: "CMD:PULSE:POST", domain: "PULSE", action: "PULSE_PUBLISH", objectCommitment: pulse, actorProfileCommitment: pulseOwner, nonce: 1, payloadCommitment: firstPayload, storyDuration: null, pulseFormat: "TEXT" }));
  await ledger.append(await issue({ commandId: "CMD:PULSE:EDIT", domain: "PULSE", action: "PULSE_EDIT", objectCommitment: pulse, actorProfileCommitment: pulseOwner, nonce: 2, payloadCommitment: editedPayload, priorPayloadCommitment: firstPayload, storyDuration: null, pulseFormat: "TEXT", revisionKind: "MATERIAL", generation: 2 })); assert(ledger.pulse(pulse).generation === 2, "material Pulse edit creates a visible generation");
  await ledger.append(await issue({ commandId: "CMD:PULSE:WITHDRAW", domain: "PULSE", action: "PULSE_WITHDRAW", objectCommitment: pulse, actorProfileCommitment: pulseOwner, nonce: 3, payloadCommitment: H(999), priorPayloadCommitment: editedPayload, storyDuration: null, pulseFormat: "TEXT", generation: 2 })); assert(ledger.pulse(pulse).state === "WITHDRAWN", "Pulse withdrawal keeps a tombstone");
  const quoteOwner = H(11), quote = H(111), quotePayload = H(212), sourceReceipt = await attest("RIGHTS", "CONTENT_SOURCE", quoteOwner, pulse, quotePayload, "QUOTE", "SOCIAL"); await ledger.append(await issue({ commandId: "CMD:PULSE:QUOTE", domain: "PULSE", action: "PULSE_PUBLISH", objectCommitment: quote, actorProfileCommitment: quoteOwner, nonce: 1, payloadCommitment: quotePayload, storyDuration: null, pulseFormat: "QUOTE", sourceCommitment: pulse, receiptCommitments: [sourceReceipt] })); assert(ledger.pulse(quote).sourceCommitment === pulse, "quote and repost require signed source provenance");
  await denied(async () => ledger.append(await issue({ commandId: "CMD:PULSE:NO-SOURCE-RECEIPT", domain: "PULSE", action: "PULSE_PUBLISH", objectCommitment: H(112), actorProfileCommitment: H(12), nonce: 1, storyDuration: null, pulseFormat: "QUOTE", sourceCommitment: pulse })), "EXPERIENCE_SOURCE_RECEIPT_REQUIRED");
  const revokeCommitActor = H(13), revokeCommitPulse = H(113), revokeCommitPayload = H(213), revokeCommitReceipt = await attest("RIGHTS", "CONTENT_SOURCE", revokeCommitActor, pulse, revokeCommitPayload, "QUOTE", "SOCIAL"), originalAssertCurrent = receipts.assertCurrent.bind(receipts); let commitRechecks = 0; (receipts as any).assertCurrent = (values: readonly string[]) => { commitRechecks++; if (commitRechecks === 3) receipts.revoke(revokeCommitReceipt); originalAssertCurrent(values); }; try { await denied(async () => ledger.append(await issue({ commandId: "CMD:PULSE:REVOKE-BEFORE-COMMIT", domain: "PULSE", action: "PULSE_PUBLISH", objectCommitment: revokeCommitPulse, actorProfileCommitment: revokeCommitActor, nonce: 1, payloadCommitment: revokeCommitPayload, storyDuration: null, pulseFormat: "QUOTE", sourceCommitment: pulse, receiptCommitments: [revokeCommitReceipt] })), "EXPERIENCE_RECEIPT_INVALID"); } finally { (receipts as any).assertCurrent = originalAssertCurrent; } deniedSync(() => ledger.pulse(revokeCommitPulse), "EXPERIENCE_PULSE_NOT_FOUND");

  const workHost = H(20), colleague = H(21), room = H(120), roomManifest = H(220), consentHost = await attest("CONSENT", "RECORDING_CONSENT", workHost, room, roomManifest, "ROOM_RECORDING", "WORK"), consentPeer = await attest("CONSENT", "RECORDING_CONSENT", colleague, room, roomManifest, "ROOM_RECORDING", "WORK"), workParticipants = [{ profileCommitment: workHost, profileType: "WORK" as const, deviceCommitment: H(1020), recordingConsentReceipt: consentHost }, { profileCommitment: colleague, profileType: "WORK" as const, deviceCommitment: H(1021), recordingConsentReceipt: consentPeer }], workReceipts = [consentHost, consentPeer].sort();
  await ledger.append(await issue({ commandId: "CMD:WORK:MEETING", domain: "ROOM", action: "ROOM_CREATE", surface: "WORK", objectCommitment: room, actorProfileCommitment: workHost, nonce: 1, payloadCommitment: roomManifest, storyDuration: null, roomKind: "WORK_MEETING", participants: workParticipants, receiptCommitments: workReceipts, encryptionMode: "MANAGED_ENCRYPTED", recordingRequested: true, audience: "PARTICIPANTS" })); assert(ledger.room(room).recording, "Work meeting recording requires every participant signed consent");
  await denied(async () => ledger.append(await issue({ commandId: "CMD:WORK:NO-CONSENT", domain: "ROOM", action: "ROOM_CREATE", surface: "WORK", objectCommitment: H(121), actorProfileCommitment: H(22), nonce: 1, storyDuration: null, roomKind: "WORK_MEETING", participants: [{ profileCommitment: H(22), profileType: "WORK", deviceCommitment: H(1022), recordingConsentReceipt: null }, { profileCommitment: H(23), profileType: "WORK", deviceCommitment: H(1023), recordingConsentReceipt: null }], encryptionMode: "MANAGED_ENCRYPTED", recordingRequested: true, audience: "PARTICIPANTS" })), "EXPERIENCE_RECORDING_CONSENT_REQUIRED");
  await ledger.append(await issue({ commandId: "CMD:WORK:CLOSE", domain: "ROOM", action: "ROOM_CLOSE", surface: "WORK", objectCommitment: room, actorProfileCommitment: workHost, nonce: 2, payloadCommitment: room, priorPayloadCommitment: room, storyDuration: null, roomKind: "WORK_MEETING", participants: workParticipants, receiptCommitments: workReceipts, encryptionMode: "MANAGED_ENCRYPTED", recordingRequested: true, audience: "PARTICIPANTS" })); assert(ledger.room(room).state === "CLOSED", "meeting close is bound to original participant and receipt set");
  const raceSubject = H(24), raceBase: ReceiptInput = { receiptId: "RECEIPT:RACE:A", kind: "RECORDING_CONSENT", subjectCommitment: raceSubject, objectCommitment: H(124), bindingCommitment: H(224), surface: "WORK", generation: 1, jurisdiction: "GLOBAL", purpose: "ROOM_RECORDING", normalizedScoreBps: 0, qualifiedActors: 0, independentClusters: 0, trafficClean: true, mediaLifecycle: null, watermark: null, enforcement: null, nonce: 1, policyVersion: 1, expiresAt: AUTH_END }, raceResults = await Promise.allSettled([receipts.issue("CONSENT", raceBase), receipts.issue("CONSENT", { ...raceBase, receiptId: "RECEIPT:RACE:B" })]); assert(raceResults.filter(result => result.status === "fulfilled").length === 1 && raceResults.filter(result => result.status === "rejected").length === 1, "concurrent consent issuance consumes exactly one authority nonce");
  const datingPeer = H(30), datingRoom = H(130), datingManifest = H(230), datingSessionKey = H(1030), datingParticipants = [{ profileCommitment: datingOwner, profileType: "DATING" as const, deviceCommitment: H(2030), recordingConsentReceipt: null }, { profileCommitment: datingPeer, profileType: "DATING" as const, deviceCommitment: H(2031), recordingConsentReceipt: null }], datingBinding = await digest(JSON.stringify({ encryptionSuite: "X25519_AES256_GCM", participants: datingParticipants.map(value => ({ deviceCommitment: value.deviceCommitment, profileCommitment: value.profileCommitment })), sessionKeyCommitment: datingSessionKey })), e2eeReceipt = await attest("MEDIA", "E2EE_SESSION", datingOwner, datingRoom, datingBinding, "DATING_ROOM", "DATING");
  await ledger.append(await issue({ commandId: "CMD:DATING:CALL", domain: "ROOM", action: "ROOM_CREATE", surface: "DATING", objectCommitment: datingRoom, actorProfileCommitment: datingOwner, nonce: 2, payloadCommitment: datingManifest, storyDuration: null, roomKind: "VIDEO_1_TO_1", participants: datingParticipants, receiptCommitments: [e2eeReceipt], encryptionMode: "E2EE", encryptionSuite: "X25519_AES256_GCM", sessionKeyCommitment: datingSessionKey, audience: "PARTICIPANTS" })); assert(ledger.room(datingRoom).encryptionMode === "E2EE", "Dating call requires signed E2EE session bound to peers, devices, suite and session key");
  const substitutedPeerParticipants = [{ ...datingParticipants[0] }, { profileCommitment: H(33), profileType: "DATING" as const, deviceCommitment: H(2033), recordingConsentReceipt: null }]; await denied(async () => ledger.append(await issue({ commandId: "CMD:DATING:PEER-SUBSTITUTION", domain: "ROOM", action: "ROOM_CREATE", surface: "DATING", objectCommitment: H(133), actorProfileCommitment: datingOwner, nonce: 3, payloadCommitment: datingManifest, storyDuration: null, roomKind: "VIDEO_1_TO_1", participants: substitutedPeerParticipants, receiptCommitments: [e2eeReceipt], encryptionMode: "E2EE", encryptionSuite: "X25519_AES256_GCM", sessionKeyCommitment: datingSessionKey, audience: "PARTICIPANTS" })), "EXPERIENCE_RECEIPT_BINDING_MISMATCH");
  const managedActor = H(31), managedRoom = H(131), managedManifest = H(231), managedParticipants = [{ profileCommitment: managedActor, profileType: "DATING" as const, deviceCommitment: H(2034), recordingConsentReceipt: null }, { profileCommitment: H(32), profileType: "DATING" as const, deviceCommitment: H(2035), recordingConsentReceipt: null }], managedBinding = await digest(JSON.stringify({ encryptionSuite: "X25519_AES256_GCM", participants: managedParticipants.map(value => ({ deviceCommitment: value.deviceCommitment, profileCommitment: value.profileCommitment })), sessionKeyCommitment: H(1031) })), managedReceipt = await attest("MEDIA", "E2EE_SESSION", managedActor, managedRoom, managedBinding, "DATING_ROOM", "DATING"); await denied(async () => ledger.append(await issue({ commandId: "CMD:DATING:DOWNGRADE", domain: "ROOM", action: "ROOM_CREATE", surface: "DATING", objectCommitment: managedRoom, actorProfileCommitment: managedActor, nonce: 1, payloadCommitment: managedManifest, storyDuration: null, roomKind: "VIDEO_1_TO_1", participants: managedParticipants, receiptCommitments: [managedReceipt], encryptionMode: "MANAGED_ENCRYPTED", audience: "PARTICIPANTS" })), "EXPERIENCE_E2EE_SESSION_RECEIPT_REQUIRED");

  const accessorActor = H(40), accessorCommand = await issue({ commandId: "CMD:ACCESSOR:DENY", objectCommitment: H(140), actorProfileCommitment: accessorActor, nonce: 1 }), accessorInput = { ...accessorCommand } as Record<string, unknown>; let getterCalls = 0; Object.defineProperty(accessorInput, "signature", { enumerable: true, get: () => { getterCalls++; return accessorCommand.signature; } }); await denied(() => ledger.append(accessorInput), "EXPERIENCE_COMMAND_INVALID"); assert(getterCalls === 0, "getter-backed command is rejected before accessor execution");
  const proxyCommand = await issue({ commandId: "CMD:PROXY:DENY", objectCommitment: H(141), actorProfileCommitment: H(41), nonce: 1 }); await denied(() => ledger.append(new Proxy({ ...proxyCommand }, {})), "EXPERIENCE_COMMAND_INVALID");
  let release!: () => void; const wait = new Promise<void>(resolve => { release = resolve; }), slowVerifier: ExperienceCommandVerifier = { verify: async value => { await wait; return authority.verify(value); } }, slowLedger = new ExperienceLedger(slowVerifier, authority.keyId, clock, receipts), mutationActor = H(42), originalPayload = H(242), mutableCommand: any = structuredClone(await issue({ commandId: "CMD:ASYNC:CAPTURE", objectCommitment: H(142), actorProfileCommitment: mutationActor, nonce: 1, payloadCommitment: originalPayload })); const pending = slowLedger.append(mutableCommand); mutableCommand.payloadCommitment = H(9999); release(); await pending; assert(slowLedger.story(H(142)).mediaCommitment === originalPayload, "async caller mutation cannot change captured command");
  const queueClock = new LocalMonotonicExperienceClock("2026-01-01T10:00:00.000Z"), queueReceipts = new LocalSecurityReceiptRegistry(queueClock); registerAuthorities(queueReceipts); const queueAuthority = new LocalExperienceAuthority("AUTH:EXPERIENCE:QUEUE", "queue-expiry-fixture-key", queueClock), queueTemplate = await issue({ commandId: "CMD:QUEUE:EXPIRY", objectCommitment: H(143), actorProfileCommitment: H(43), nonce: 1 }), { occurredAt: _queueOccurredAt, authorityKeyId: _queueAuthorityKeyId, signature: _queueSignature, ...queueUnsigned } = queueTemplate, queuedCommand = await queueAuthority.issue({ ...queueUnsigned, authorizationExpiresAt: "2026-01-01T10:01:00.000Z" }); let releaseQueue!: () => void; const queueWait = new Promise<void>(resolve => { releaseQueue = resolve; }), queueVerifier: ExperienceCommandVerifier = { verify: async value => { await queueWait; return queueAuthority.verify(value); } }, queueLedger = new ExperienceLedger(queueVerifier, queueAuthority.keyId, queueClock, queueReceipts), queuePending = queueLedger.append(queuedCommand); queueClock.advanceTo("2026-01-01T10:02:00.000Z"); releaseQueue(); await denied(() => queuePending, "EXPERIENCE_AUTHORIZATION_EXPIRED");

  const snapshot = await ledger.exportSnapshot("CHECKPOINT:EXPERIENCE:1", 86_400_000, snapshotAuthority), durable = { checkpointId: snapshot.checkpointId, policyVersion: snapshot.policyVersion, eventCount: snapshot.eventCount, eventHeadHash: snapshot.eventHeadHash, eventsCommitment: snapshot.eventsCommitment, securityReceiptsCommitment: snapshot.securityReceiptsCommitment }, freshReceipts = new LocalSecurityReceiptRegistry(clock); registerAuthorities(freshReceipts); const restored = await ExperienceLedger.restore(snapshot, authority, authority.keyId, snapshotAuthority, durable, clock, freshReceipts); assert(restored.story(story).state === "HIGHLIGHT" && restored.pulse(pulse).state === "WITHDRAWN" && restored.room(room).state === "CLOSED", "fresh restore reconstructs receipt-bound projections and receipt registry");
  const atomicRegistry = new LocalSecurityReceiptRegistry(clock); registerAuthorities(atomicRegistry); const atomicBefore = JSON.stringify(atomicRegistry.exportBundle()), staleDurable = { ...durable, eventHeadHash: H(9090) }; await denied(() => ExperienceLedger.restore(snapshot, authority, authority.keyId, snapshotAuthority, staleDurable, clock, atomicRegistry), "EXPERIENCE_CHECKPOINT_STALE"); assert(JSON.stringify(atomicRegistry.exportBundle()) === atomicBefore && atomicRegistry.stateVersion() === 0, "failed restore leaves destination receipt registry byte-for-byte unchanged");
  const expiryClock = new LocalMonotonicExperienceClock("2026-01-01T10:00:00.000Z"), expiryRegistry = new LocalSecurityReceiptRegistry(expiryClock); registerAuthorities(expiryRegistry); const expiryAuthority = new LocalExperienceAuthority("AUTH:EXPERIENCE:EXPIRY", "expiry-restore-fixture-key", expiryClock), expiryLedger = new ExperienceLedger(expiryAuthority, expiryAuthority.keyId, expiryClock, expiryRegistry), expirySnapshotAuthority = new LocalExperienceSnapshotAuthority("AUTH:SNAPSHOT:EXPIRY", "expiry-snapshot-fixture-key"), expirySnapshot = await expiryLedger.exportSnapshot("CHECKPOINT:EXPIRY:1", 60_000, expirySnapshotAuthority), expiryDurable = { checkpointId: expirySnapshot.checkpointId, policyVersion: expirySnapshot.policyVersion, eventCount: expirySnapshot.eventCount, eventHeadHash: expirySnapshot.eventHeadHash, eventsCommitment: expirySnapshot.eventsCommitment, securityReceiptsCommitment: expirySnapshot.securityReceiptsCommitment }; let releaseSnapshot!: () => void; const snapshotWait = new Promise<void>(resolve => { releaseSnapshot = resolve; }), slowSnapshotAuthority = { keyId: expirySnapshotAuthority.keyId, sign: (value: any) => expirySnapshotAuthority.sign(value), verify: async (value: any) => { await snapshotWait; return expirySnapshotAuthority.verify(value); } }, expiryRestorePending = ExperienceLedger.restore(expirySnapshot, expiryAuthority, expiryAuthority.keyId, slowSnapshotAuthority, expiryDurable, expiryClock, expiryRegistry); expiryClock.advanceTo("2026-01-01T10:02:00.000Z"); releaseSnapshot(); await denied(() => expiryRestorePending, "EXPERIENCE_SNAPSHOT_INVALID"); assert(expiryRegistry.exportBundle().length === 0, "snapshot expiring during verifier await cannot mutate registry or restore");
  await denied(() => ExperienceLedger.restore({ ...snapshot, signature: H(77) }, authority, authority.keyId, snapshotAuthority, durable, clock, receipts), "EXPERIENCE_SNAPSHOT_INVALID"); const lateClock = new LocalMonotonicExperienceClock("2026-01-03T00:00:00.000Z"), lateReceipts = new LocalSecurityReceiptRegistry(lateClock); registerAuthorities(lateReceipts); await denied(() => ExperienceLedger.restore(snapshot, authority, authority.keyId, snapshotAuthority, durable, lateClock, lateReceipts), "EXPERIENCE_SNAPSHOT_INVALID");
  const tamperedReceiptBundle = snapshot.securityReceipts.map((entry, index) => index === 0 ? { ...entry, revoked: !entry.revoked } : entry), { signature: _oldSnapshotSignature, ...snapshotBase } = snapshot, tamperedSnapshotBase = { ...snapshotBase, securityReceipts: tamperedReceiptBundle }, tamperedSnapshot = { ...tamperedSnapshotBase, signature: await snapshotAuthority.sign(tamperedSnapshotBase) }; await denied(() => ExperienceLedger.restore(tamperedSnapshot, authority, authority.keyId, snapshotAuthority, durable, clock, freshReceipts), "EXPERIENCE_RECEIPT_BUNDLE_INVALID");

  const viewer = H(801), owner = H(802), device = H(803), content = H(804), audienceReceipt = await attest("PROFILE", "AUDIENCE_ACCESS", viewer, content, device, "VIEW_CONTENT", "SOCIAL"), saveRights = await attest("RIGHTS", "MEDIA_RIGHTS", viewer, content, owner, "SAVE_IN_NEXUS", "SOCIAL", { mediaLifecycle: MEDIA_LIFECYCLE }), offlineRights = await attest("RIGHTS", "MEDIA_RIGHTS", viewer, content, owner, "OFFLINE_CACHE", "SOCIAL", { mediaLifecycle: MEDIA_LIFECYCLE }), exportRights = await attest("RIGHTS", "MEDIA_RIGHTS", viewer, content, owner, "DOWNLOAD_TO_DEVICE", "SOCIAL", { mediaLifecycle: MEDIA_LIFECYCLE }), offlineGrant = await attest("MEDIA", "OFFLINE_GRANT", viewer, content, device, "OFFLINE_CACHE", "SOCIAL", { expiresAt: "2026-01-01T13:00:00.000Z", mediaLifecycle: MEDIA_LIFECYCLE }), authorPolicy = await attest("PROFILE", "AUTHOR_DOWNLOAD_POLICY", owner, content, viewer, "DOWNLOAD_ALLOWED", "SOCIAL"), watermark = await attest("MEDIA", "WATERMARK_GENERATED", owner, content, viewer, "NEXUS_CREATOR_CONTENT_CODE", "SOCIAL", { mediaLifecycle: MEDIA_LIFECYCLE, watermark: WATERMARK });
  const saved = await authorizeSaveDownload(baseDownload({ audienceReceiptCommitment: audienceReceipt, rightsReceiptCommitment: saveRights }), receipts); assert(saved.allowed && saved.profileScoped, "Save in Nexus uses signed audience and rights receipts");
  const offline = await authorizeSaveDownload(baseDownload({ operation: "OFFLINE_CACHE", audienceReceiptCommitment: audienceReceipt, rightsReceiptCommitment: offlineRights, offlineGrantReceiptCommitment: offlineGrant }), receipts); assert(offline.encryptedCache && offline.expiresAt === "2026-01-01T13:00:00.000Z" && offline.deviceCommitment === device, "offline cache returns a signed expiring device-bound grant");
  const exported = await authorizeSaveDownload(baseDownload({ operation: "DOWNLOAD_TO_DEVICE", watermark: WATERMARK, audienceReceiptCommitment: audienceReceipt, rightsReceiptCommitment: exportRights, authorPolicyReceiptCommitment: authorPolicy, watermarkReceiptCommitment: watermark }), receipts); assert(exported.watermarkRequired && exported.grantCommitment === watermark, "generated Nexus creator content code watermark receipt binds all four fields, device and export artifact");
  await denied(() => authorizeSaveDownload(baseDownload({ operation: "OFFLINE_CACHE", mediaLifecycle: { ...MEDIA_LIFECYCLE, keyEpoch: 8 }, audienceReceiptCommitment: audienceReceipt, rightsReceiptCommitment: offlineRights, offlineGrantReceiptCommitment: offlineGrant }), receipts), "EXPERIENCE_RECEIPT_BINDING_MISMATCH");
  await denied(() => authorizeSaveDownload(baseDownload({ operation: "OFFLINE_CACHE", mediaLifecycle: { ...MEDIA_LIFECYCLE, rightsState: "WITHDRAWN" }, audienceReceiptCommitment: audienceReceipt, rightsReceiptCommitment: offlineRights, offlineGrantReceiptCommitment: offlineGrant }), receipts), "EXPERIENCE_MEDIA_RIGHTS_INACTIVE");
  await denied(() => authorizeSaveDownload(baseDownload({ operation: "DOWNLOAD_TO_DEVICE", watermark: { ...WATERMARK, creatorHandle: "other.creator" }, audienceReceiptCommitment: audienceReceipt, rightsReceiptCommitment: exportRights, authorPolicyReceiptCommitment: authorPolicy, watermarkReceiptCommitment: watermark }), receipts), "EXPERIENCE_RECEIPT_BINDING_MISMATCH");
  const wrongOuterWatermark = { ...WATERMARK, contentCommitment: H(8991), deviceCommitment: H(8992) }, wrongOuterWatermarkReceipt = await attest("MEDIA", "WATERMARK_GENERATED", owner, content, viewer, "NEXUS_CREATOR_CONTENT_CODE", "SOCIAL", { mediaLifecycle: MEDIA_LIFECYCLE, watermark: wrongOuterWatermark }); await denied(() => authorizeSaveDownload(baseDownload({ operation: "DOWNLOAD_TO_DEVICE", watermark: wrongOuterWatermark, audienceReceiptCommitment: audienceReceipt, rightsReceiptCommitment: exportRights, authorPolicyReceiptCommitment: authorPolicy, watermarkReceiptCommitment: wrongOuterWatermarkReceipt }), receipts), "EXPERIENCE_WATERMARK_REQUEST_BINDING_MISMATCH");
  await denied(() => authorizeSaveDownload(baseDownload({ operation: "DOWNLOAD_TO_DEVICE", audienceReceiptCommitment: audienceReceipt, rightsReceiptCommitment: exportRights, authorPolicyReceiptCommitment: authorPolicy }), receipts), "EXPERIENCE_DOWNLOAD_RECEIPTS_REQUIRED");
  await denied(() => authorizeSaveDownload(baseDownload({ surface: "DATING", profileType: "DATING" }), receipts), "EXPERIENCE_PRIVATE_SURFACE_EXPORT_DENIED");
  receipts.revoke(offlineGrant); const revokedMediaRegistry = new LocalSecurityReceiptRegistry(clock); registerAuthorities(revokedMediaRegistry); await revokedMediaRegistry.importBundle(receipts.exportBundle([audienceReceipt, offlineRights, offlineGrant].sort())); await denied(() => authorizeSaveDownload(baseDownload({ operation: "OFFLINE_CACHE", audienceReceiptCommitment: audienceReceipt, rightsReceiptCommitment: offlineRights, offlineGrantReceiptCommitment: offlineGrant }), revokedMediaRegistry), "EXPERIENCE_RECEIPT_INVALID");

  const identityProfile = H(820), age29 = await attest("AGE", "AGE_PROOF", identityProfile, identityProfile, await digest("AGE:29"), "DATING_AGE", "DATING"), adult = await attest("AGE", "ADULT_PROOF", identityProfile, identityProfile, await digest("AGE:18_PLUS"), "ADULT_GATE", "ADULT"), wallet = await attest("WALLET", "WALLET_BINDING", identityProfile, identityProfile, await digest("HANDLE:nova.user"), "PAYMENT_USERNAME", null);
  assert((await presentIdentity(baseIdentity(), receipts)).ageLabel === null, "Social nickname does not reveal age or cross-profile link"); assert((await presentIdentity(baseIdentity({ profileType: "WORK", fullProfessionalName: "Nova Ionescu" }), receipts)).primaryName === "Nova Ionescu", "Work uses full professional name"); assert((await presentIdentity(baseIdentity({ profileType: "DATING", exactAge: 29, ageReceiptCommitment: age29 }), receipts)).verificationLabel === "AGE_VERIFIED", "Dating age requires signed age receipt"); assert((await presentIdentity(baseIdentity({ profileType: "ADULT", exactAge: 29, adultReceiptCommitment: adult }), receipts)).ageLabel === "18+", "Adult alias requires signed 18+ receipt"); assert((await presentIdentity(baseIdentity({ profileType: "PAYMENTS", walletReceiptCommitment: wallet }), receipts)).verificationLabel === "WALLET_BOUND", "payment username requires signed wallet binding"); await denied(() => presentIdentity(baseIdentity({ profileType: "DATING", exactAge: 29 }), receipts), "EXPERIENCE_DATING_AGE_REQUIRED");
  const getterIdentity = baseIdentity(), identityDescriptor = Object.getOwnPropertyDescriptor(getterIdentity, "handle")!, getterIdentityInput = { ...getterIdentity }; let identityGetterCalls = 0; Object.defineProperty(getterIdentityInput, "handle", { enumerable: true, get: () => { identityGetterCalls++; return identityDescriptor.value; } }); await denied(() => presentIdentity(getterIdentityInput, receipts), "EXPERIENCE_IDENTITY_INVALID"); assert(identityGetterCalls === 0, "identity accessor is rejected before execution");

  const followers: Record<string, unknown>[] = []; for (let index = 1; index <= 20; index++) followers.push({ followerCommitment: H(300 + index), clusterCommitment: H(400 + index), trafficClass: "HUMAN_ORGANIC", quarantined: false, incentivized: false }); followers.push({ followerCommitment: H(500), clusterCommitment: H(501), trafficClass: "PAID", quarantined: false, incentivized: false }, { followerCommitment: H(502), clusterCommitment: H(503), trafficClass: "SYSTEM_TEST", quarantined: false, incentivized: false }, { followerCommitment: H(504), clusterCommitment: H(505), trafficClass: "HUMAN_ORGANIC", quarantined: true, incentivized: false }); const audience = qualifyAudience(followers), reversedAudience = qualifyAudience([...followers].reverse()); assert(audience.qualifiedFollowers === 20 && audience.excludedFollowers === 3, "paid synthetic and quarantined followers do not qualify"); assert(JSON.stringify(audience) === JSON.stringify(reversedAudience), "qualified audience is order invariant"); assert(!audience.purchasedFollowerMarketplace && !audience.rawCountDirectReward, "Nexus neither sells followers nor rewards raw follower count");
  let followerProxyTraps = 0; const followerProxy = new Proxy({ followerCommitment: H(910), clusterCommitment: H(911), trafficClass: "HUMAN_ORGANIC", quarantined: false, incentivized: false }, { getPrototypeOf: target => { followerProxyTraps++; return Reflect.getPrototypeOf(target); }, ownKeys: target => { followerProxyTraps++; return Reflect.ownKeys(target); }, getOwnPropertyDescriptor: (target, key) => { followerProxyTraps++; return Reflect.getOwnPropertyDescriptor(target, key); } }); deniedSync(() => qualifyAudience([followerProxy]), "EXPERIENCE_FOLLOWER_INPUT_INVALID"); assert(followerProxyTraps === 0, "proxy-backed follower is denied before user-controlled traps execute");

  const discoveryProfile = H(850), locationReceipt = await attest("PROFILE", "LOCATION_CONSENT", discoveryProfile, await digest("REGION:RO-B"), await digest("LOCATION_MODE:CONSENTED_COARSE:sxfs12"), "NEAR_DISCOVERY", "SOCIAL", { jurisdiction: "RO-B" }), nearCandidates = [await candidate(601), await candidate(602, { language: "es" }), await candidate(603, { region: "RO-CJ", coarseGeohash: "u2xx11" }), await candidate(604, { profileType: "WORK" }), await candidate(605, { trafficClass: "SYSTEM_TEST", trafficClean: false })]; const near = await selectDiscovery(discoveryRequest({ lens: "NEAR", locationMode: "CONSENTED_COARSE", locationReceiptCommitment: locationReceipt }), nearCandidates, receipts); assert(near.selected.length === 1 && near.selected[0].candidateCommitment === H(601) && !near.preciseLocationPersisted, "Near uses signed profile-scoped coarse location and language"); await denied(() => selectDiscovery(discoveryRequest({ lens: "NEAR" }), nearCandidates, receipts), "EXPERIENCE_NEAR_CONSENT_REQUIRED");

  const globalA = H(610), globalB = H(611), regionalA1 = await attest("DISCOVERY", "REGIONAL_AGGREGATE", globalA, globalA, discoveryProfile, "GLOBAL_NORMALIZED", "SOCIAL", { jurisdiction: "DE", normalizedScoreBps: 8000, qualifiedActors: 100, independentClusters: 20 }), regionalA2 = await attest("DISCOVERY", "REGIONAL_AGGREGATE", globalA, globalA, discoveryProfile, "GLOBAL_NORMALIZED", "SOCIAL", { jurisdiction: "RO", normalizedScoreBps: 9000, qualifiedActors: 100, independentClusters: 20 }), regionalB1 = await attest("DISCOVERY", "REGIONAL_AGGREGATE", globalB, globalB, discoveryProfile, "GLOBAL_NORMALIZED", "SOCIAL", { jurisdiction: "DE", normalizedScoreBps: 5000, qualifiedActors: 100, independentClusters: 20 }); const globalCandidates = [await candidate(610, { interestScoreBps: 1000, regionalJurisdictions: ["DE", "RO"], regionalReceiptCommitments: [regionalA1, regionalA2] }), await candidate(611, { interestScoreBps: 10000, regionalJurisdictions: ["DE"], regionalReceiptCommitments: [regionalB1] }), await candidate(612, { paid: true, trafficClass: "PAID", trafficClean: false })], globalSelection = await selectDiscovery(discoveryRequest({ lens: "GLOBAL" }), globalCandidates, receipts), globalReordered = await selectDiscovery(discoveryRequest({ lens: "GLOBAL" }), [...globalCandidates].reverse(), receipts); assert(globalSelection.selected.length === 1 && globalSelection.selected[0].candidateCommitment === globalA, "Global requires signed aggregates from at least two independent regions"); assert(JSON.stringify(globalSelection) === JSON.stringify(globalReordered), "Global normalization is deterministic under candidate reordering");
  await denied(() => selectDiscovery(discoveryRequest({ lens: "GLOBAL", profileCommitment: H(851) }), globalCandidates, receipts), "EXPERIENCE_RECEIPT_BINDING_MISMATCH");

  const breakingId = H(620), breakTrust = await attest("TRUST", "TRUST_EVIDENCE", breakingId, breakingId, await digest("BREAKING:CRITICAL:2026-01-01T10:00:00.000Z:RO-B"), "BREAKING_EVIDENCE", "SOCIAL", { jurisdiction: "RO-B" }), sourceA = await attest("SOURCE", "SOURCE_CONTROL", breakingId, breakingId, await digest("SOURCE:agency.example"), "BREAKING_SOURCE", "SOCIAL", { jurisdiction: "RO-B" }, "AUTH:SOURCE:A"), sourceB = await attest("SOURCE", "SOURCE_CONTROL", breakingId, breakingId, await digest("SOURCE:public.example"), "BREAKING_SOURCE", "SOCIAL", { jurisdiction: "RO-B" }, "AUTH:SOURCE:B"), officialId = H(621), officialTrust = await attest("TRUST", "TRUST_EVIDENCE", officialId, officialId, await digest("BREAKING:MAJOR:2026-01-01T10:00:00.000Z:RO-B"), "BREAKING_EVIDENCE", "SOCIAL", { jurisdiction: "RO-B" }), official = await attest("OFFICIAL", "OFFICIAL_ALERT", officialId, officialId, await digest("ALERT:MAJOR:2026-01-01T10:00:00.000Z"), "PUBLIC_SAFETY_ALERT", "SOCIAL", { jurisdiction: "RO-B" }); const breakingCandidates = [await candidate(620, { breakingImpact: "CRITICAL", sourceDomains: ["agency.example", "public.example"], sourceReceiptCommitments: [sourceA, sourceB], trustReceiptCommitment: breakTrust }), await candidate(621, { breakingImpact: "MAJOR", officialAlertReceiptCommitment: official, trustReceiptCommitment: officialTrust }), await candidate(622, { breakingImpact: "CRITICAL" }), await candidate(623, { breakingImpact: "CRITICAL", paid: true, trafficClass: "PAID", trafficClean: false }), await candidate(624, { breakingImpact: "CRITICAL", politicalTargeting: true })], breaking = await selectDiscovery(discoveryRequest({ lens: "BREAKING" }), breakingCandidates, receipts); assert(breaking.selected.length === 2 && breaking.selected.some(item => item.candidateCommitment === breakingId) && breaking.selected.some(item => item.candidateCommitment === officialId), "Breaking requires signed Trust evidence and two independent roots or official authority"); assert(!breaking.paidBreakingSelected && !breaking.interruptsDatingCallsOrMessages, "Breaking cannot be bought and never interrupts private surfaces"); await denied(() => selectDiscovery(discoveryRequest({ lens: "BREAKING", profileType: "DATING" }), [], receipts), "EXPERIENCE_DATING_DISCOVERY_LENS_DENIED"); const duplicateA = await candidate(630), duplicateB = await candidate(630); await denied(() => selectDiscovery(discoveryRequest(), [duplicateA, duplicateB], receipts), "EXPERIENCE_DISCOVERY_DUPLICATE");
  const sameRootId = H(625), sameRootTrust = await attest("TRUST", "TRUST_EVIDENCE", sameRootId, sameRootId, await digest("BREAKING:CRITICAL:2026-01-01T10:00:00.000Z:RO-B"), "BREAKING_EVIDENCE", "SOCIAL", { jurisdiction: "RO-B" }), sameRootSourceA = await attest("SOURCE", "SOURCE_CONTROL", sameRootId, sameRootId, await digest("SOURCE:alpha.example"), "BREAKING_SOURCE", "SOCIAL", { jurisdiction: "RO-B" }, "AUTH:SOURCE:A"), sameRootSourceB = await attest("SOURCE", "SOURCE_CONTROL", sameRootId, sameRootId, await digest("SOURCE:beta.example"), "BREAKING_SOURCE", "SOCIAL", { jurisdiction: "RO-B" }, "AUTH:SOURCE:A"), sameRootCandidate = await candidate(625, { breakingImpact: "CRITICAL", sourceDomains: ["alpha.example", "beta.example"], sourceReceiptCommitments: [sameRootSourceA, sameRootSourceB], trustReceiptCommitment: sameRootTrust }), sameRootSelection = await selectDiscovery(discoveryRequest({ lens: "BREAKING" }), [sameRootCandidate], receipts); assert(sameRootSelection.selected.length === 0, "two labels controlled by one source root do not corroborate Breaking");
  const receiptPrefixOmitted = receipts.exportBundle().filter(entry => entry.commitment !== sameRootSourceA), prefixRegistry = new LocalSecurityReceiptRegistry(clock); registerAuthorities(prefixRegistry); await denied(() => prefixRegistry.importBundle(receiptPrefixOmitted), "EXPERIENCE_RECEIPT_BUNDLE_INVALID");
  let bundleProxyTraps = 0; const bundleProxy = new Proxy([sameRootSourceA] as string[], { get: (target, key, receiver) => { bundleProxyTraps++; return Reflect.get(target, key, receiver); }, getPrototypeOf: target => { bundleProxyTraps++; return Reflect.getPrototypeOf(target); }, ownKeys: target => { bundleProxyTraps++; return Reflect.ownKeys(target); } }); deniedSync(() => receipts.exportBundle(bundleProxy), "EXPERIENCE_RECEIPT_INVALID"); assert(bundleProxyTraps === 0, "exportBundle rejects proxy-backed commitment arrays before iterator traps execute");

  const kidsId = H(640), kidsTrust = await attest("TRUST", "TRUST_EVIDENCE", kidsId, kidsId, await digest("BREAKING:CRITICAL:2026-01-01T10:00:00.000Z:RO-B"), "BREAKING_EVIDENCE", "KIDS", { jurisdiction: "RO-B" }), kidsOfficial = await attest("OFFICIAL", "OFFICIAL_ALERT", kidsId, kidsId, await digest("ALERT:CRITICAL:2026-01-01T10:00:00.000Z"), "PUBLIC_SAFETY_ALERT", "KIDS", { jurisdiction: "RO-B" }), kidsGate = await attest("GUARDIAN", "KIDS_APPROPRIATE", kidsId, kidsId, await digest("KIDS:SAFETY_INFORMATION"), "KIDS_BREAKING", "KIDS", { jurisdiction: "RO-B" }), kidsCandidate = await candidate(640, { profileType: "KIDS", breakingImpact: "CRITICAL", officialAlertReceiptCommitment: kidsOfficial, trustReceiptCommitment: kidsTrust, kidsReceiptCommitment: kidsGate }), kidsBreaking = await selectDiscovery(discoveryRequest({ lens: "BREAKING", profileType: "KIDS" }), [kidsCandidate], receipts); assert(kidsBreaking.selected.length === 1, "Kids receives only guardian-attested verified safety information");
  const discoveryRaceCandidate = await candidate(650), discoveryRacePending = selectDiscovery(discoveryRequest(), [discoveryRaceCandidate], receipts); clock.advanceTo("2026-01-01T12:00:01.000Z"); await denied(() => discoveryRacePending, "EXPERIENCE_TIME_OVERRIDE_DENIED");
  const revokeRaceSubject = H(651), revokeRaceReceipt = await attest("TRUST", "TRUST_EVIDENCE", revokeRaceSubject, revokeRaceSubject, H(652), "REVOCATION_RACE", "SOCIAL"), revokeRacePending = receipts.verify(revokeRaceReceipt, { kind: "TRUST_EVIDENCE", subjectCommitment: revokeRaceSubject, objectCommitment: revokeRaceSubject, bindingCommitment: H(652), surface: "SOCIAL", generation: 1, jurisdiction: "GLOBAL", purpose: "REVOCATION_RACE", authorityRole: "TRUST" }); receipts.revoke(revokeRaceReceipt); await denied(() => revokeRacePending, "EXPERIENCE_RECEIPT_INVALID");

  clock.advanceTo("2026-01-01T14:00:00.000Z"); await denied(() => authorizeSaveDownload(baseDownload({ operation: "OFFLINE_CACHE", audienceReceiptCommitment: audienceReceipt, rightsReceiptCommitment: offlineRights, offlineGrantReceiptCommitment: offlineGrant }), receipts), "EXPERIENCE_RECEIPT_INVALID"); await denied(() => receipts.verify(offlineGrant, { kind: "OFFLINE_GRANT", subjectCommitment: viewer, objectCommitment: content, bindingCommitment: device, surface: "SOCIAL", generation: 1, jurisdiction: "GLOBAL", purpose: "OFFLINE_CACHE", authorityRole: "MEDIA", mediaLifecycle: MEDIA_LIFECYCLE }, "2026-01-01T12:30:00.000Z"), "EXPERIENCE_TIME_OVERRIDE_DENIED"); receipts.revoke(wallet); await denied(() => presentIdentity(baseIdentity({ profileType: "PAYMENTS", walletReceiptCommitment: wallet }), receipts), "EXPERIENCE_RECEIPT_INVALID"); const revokedBundle = receipts.exportBundle([wallet]), revokedRegistry = new LocalSecurityReceiptRegistry(clock); registerAuthorities(revokedRegistry); await revokedRegistry.importBundle(revokedBundle); await denied(() => revokedRegistry.verify(wallet, { kind: "WALLET_BINDING", subjectCommitment: identityProfile, objectCommitment: identityProfile, bindingCommitment: H(0), surface: null, generation: 1, jurisdiction: "GLOBAL", purpose: "PAYMENT_USERNAME", authorityRole: "WALLET" }), "EXPERIENCE_RECEIPT_INVALID");

  deniedSync(() => qualifyAudience([{ followerCommitment: H(900), clusterCommitment: H(901), trafficClass: "HUMAN_ORGANIC", quarantined: "false", incentivized: false }]), "EXPERIENCE_FOLLOWER_INPUT_INVALID");
  process.stdout.write(JSON.stringify({ schema_version: 1, task_id: "NX-EXPERIENCE-P01", status: "PASS", assertions, actor_class: "SYSTEM_TEST", input_boundary: { accessor_rejected_without_execution: true, proxy_rejected: true, public_helper_proxy_rejected_without_traps: true, async_mutation_captured: true, exact_shape: true }, time: { injected_monotonic_clock: true, caller_historical_override_denied: true, post_await_recheck: true, queued_authorization_expiry_denied: true, expired_story_promotion_denied: true, expired_snapshot_denied: true, breaking_uses_clock: true }, receipts: { role_separated: true, signed: true, scoped: true, expiring: true, revocable: true, revocation_race_denied: true, one_time_nonce: true, ordered_sha256: true, nonce_prefix_omission_denied: true, fresh_restore: true, fail_atomic_restore: true, durable_checkpoint: true }, stories: { user_selected_duration: true, until_removed_highlight: true, dating_private: true, safety_rights_purge: true, enforcement_metadata_bound: true }, pulse: { edit_generation: true, withdrawal_tombstone: true, signed_source_provenance: true, foreign_reply_erasure: false }, communication: { work_meetings: true, participant_signed_recording_consent: true, dating_e2ee: true, dating_e2ee_peer_device_suite_key_bound: true, dating_downgrade_denied: true, dating_contact_leakage: false }, save_download: { signed_audience_rights: true, encrypted_expiring_device_grant: true, lifecycle_key_license_rights_purge_bound: true, generated_watermark_receipt: true, watermark_fields_device_artifact_bound: true, dating_default_export: false, revocation_enforced: true, revocation_survives_restore: true }, identity: { per_profile: true, social_nickname: true, work_full_name: true, dating_age_receipt: true, adult_receipt: true, wallet_receipt: true, cross_profile_link_default: false }, discovery: { near_signed_coarse_consent: true, global_signed_cross_region_normalized: true, breaking_signed_trust: true, breaking_independent_source_roots_or_official: true, paid_breaking: false, political_targeting: false, interrupts_private_surfaces: false, duplicate_candidates_denied: true, async_time_version_conflict_denied: true, deterministic: true }, follower_integrity: { paid_synthetic_quarantined_excluded: true, order_invariant: true, follower_marketplace: false, raw_count_reward: false }, synthetic_isolation: { organic_events: 0, rewards_accrued: 0, reputation_delta: 0 }, network_operations: 0, provider_operations: 0, economic_operations: 0, real_fund_operations: 0, incremental_cost: { amount: 0, currency: "EUR" } }));
}
main().catch(error => { throw error; });
