import {CreatorBoundary,EmergencyEndCommand,LiveCheckpointBoundary,LiveEligibility,LivePolicyError,LiveSessionController,ManagedLiveProvider,ModeratorBoundary,ProviderOperation,ProviderReceipt,StartLiveCommand} from "./index";
declare const process:{stdout:{write(v:string):void}};let assertions=0;
function assert(v:unknown,m:string):asserts v{assertions++;if(!v)throw new Error(m)}
async function expect(fn:()=>Promise<unknown>,code:string){let actual="NO_ERROR";try{await fn()}catch(e){actual=e instanceof LivePolicyError?e.code:String(e)}assert(actual===code,`${code}/${actual}`)}
class Issuer<T extends object>{values=new Set<string>();issue(v:T){this.values.add(JSON.stringify(v));return v}verify(v:Readonly<T>){return this.values.has(JSON.stringify(v))}}
class Creators implements CreatorBoundary{state:{generation:number;policyVersion:number;active:boolean;liveEligible:boolean;strikeFree:boolean;trainingComplete:boolean;profileType:"SOCIAL"|"WORK"|"CHILD"}={generation:2,policyVersion:4,active:true,liveEligible:true,strikeFree:true,trainingComplete:true,profileType:"SOCIAL"};current(){return{...this.state}}}
class Moderators implements ModeratorBoundary{state={version:1,active:true,canEmergencyEnd:true};current(){return{...this.state}}}
class Checkpoints implements LiveCheckpointBoundary{state={checkpointId:"CHECKPOINT:LIVE:1",eventCount:1,eventHeadHash:"0".repeat(64),stateVersion:1,fencingToken:1};current(){return{...this.state}}}
const NOW="2026-08-09T22:00:00.000Z",EXP="2026-08-09T23:00:00.000Z",P="1".repeat(64),M="2".repeat(64),POL="3".repeat(64),EVIDENCE="4".repeat(64),MOD="5".repeat(64),H="a".repeat(128);
function fixtures(suffix="1"){const starts=new Issuer<StartLiveCommand>(),eligibilities=new Issuer<LiveEligibility>(),ends=new Issuer<EmergencyEndCommand>(),s:StartLiveCommand={schemaVersion:1,commandId:`COMMAND:START:${suffix}`,sessionId:`SESSION:LIVE:${suffix}`,creatorProfileCommitment:P,creatorGeneration:2,creatorPolicyVersion:4,eligibilityId:`ELIGIBILITY:${suffix}`,providerId:"FAKE_MANAGED",manifestCommitment:M,moderationPolicyCommitment:POL,audience:"ADULT_GENERAL",delaySeconds:15,issuedAt:NOW,expiresAt:EXP,signature:H},e:LiveEligibility={schemaVersion:1,eligibilityId:s.eligibilityId,creatorProfileCommitment:P,creatorGeneration:2,policyVersion:4,accountContinuity:true,strikeFree:true,trainingComplete:true,moderatorReady:true,providerId:"FAKE_MANAGED",manifestCommitment:M,moderationPolicyCommitment:POL,audience:"ADULT_GENERAL",delaySeconds:15,commandIssuedAt:NOW,commandExpiresAt:EXP,issuedAt:NOW,expiresAt:EXP,issuerKeyId:"KEY:LIVE:1",signature:H},end:EmergencyEndCommand={schemaVersion:1,commandId:`COMMAND:END:${suffix}`,sessionId:s.sessionId,moderatorCommitment:MOD,moderatorVersion:1,reason:"SAFETY",evidenceCommitment:EVIDENCE,issuedAt:NOW,expiresAt:EXP,signature:H};starts.issue(s);eligibilities.issue(e);ends.issue(end);return{starts,eligibilities,ends,e,s,end}}
class StatefulFakeProvider implements ManagedLiveProvider{
 state:"IDLE"|"LIVE"|"ENDED"="IDLE";highestFence=0;calls:string[]=[];issued=new Set<string>();receipts=new Map<string,ProviderReceipt>();holdStart=false;failStart=false;failEnd=false;hangEnd=false;corruptNextReceipt=false;afterStart:(()=>void)|null=null;afterEnd:(()=>void)|null=null;private held:{operation:ProviderOperation;resolve:(v:unknown)=>void;reject:(e:unknown)=>void}|null=null;
 verifyReceipt(r:Readonly<ProviderReceipt>){return this.issued.has(JSON.stringify(r))}
 private receipt(o:ProviderOperation,status:"LIVE"|"ENDED"){const cached=this.receipts.get(o.operationDigest);if(cached)return{...cached};let manifest=o.manifestCommitment;if(this.corruptNextReceipt){manifest=EVIDENCE;this.corruptNextReceipt=false}const r:ProviderReceipt={schemaVersion:1,authorityKeyId:"KEY:FAKE:PROVIDER",providerId:"FAKE_MANAGED",operationKind:o.operationKind,operationId:o.operationId,sessionId:o.sessionId,fencingToken:o.fencingToken,manifestCommitment:manifest,audience:o.audience,operationDigest:o.operationDigest,status,providerReceiptCommitment:o.operationDigest,issuedAt:NOW,signature:H};this.receipts.set(o.operationDigest,r);this.issued.add(JSON.stringify(r));return{...r}}
 private applyStart(o:ProviderOperation){if(o.fencingToken>this.highestFence){this.highestFence=o.fencingToken;this.state="LIVE"}const r=this.receipt(o,"LIVE");this.afterStart?.();return r}
 async start(o:Readonly<ProviderOperation>){const operation={...o};this.calls.push(o.operationId);if(this.failStart)throw new Error("start failed");if(this.holdStart)return await new Promise((resolve,reject)=>{this.held={operation,resolve,reject}});return this.applyStart(operation)}
 releaseLateStart(){const held=this.held;if(!held)throw new Error("no held start");this.held=null;held.resolve(this.applyStart(held.operation))}
 async emergencyEnd(o:Readonly<ProviderOperation>){const operation={...o};this.calls.push(o.operationId);if(this.failEnd)throw new Error("end failed");if(this.hangEnd)return await new Promise(()=>{});if(o.fencingToken>this.highestFence){this.highestFence=o.fencingToken;this.state="ENDED"}const r=this.receipt(operation,"ENDED");this.afterEnd?.();return r}
}
async function main(){
 const f=fixtures(),creators=new Creators(),moderators=new Moderators(),provider=new StatefulFakeProvider(),live=new LiveSessionController(creators,moderators,provider,25);
 await expect(()=>live.start({...f.s,extra:true},f.e,f.starts,f.eligibilities,NOW),"LIVE_START_INVALID");creators.state={...creators.state,profileType:"CHILD"};await expect(()=>live.start(f.s,f.e,f.starts,f.eligibilities,NOW),"LIVE_CREATOR_DENIED");creators.state={...creators.state,profileType:"SOCIAL"};
 const substituted={...f.s,manifestCommitment:EVIDENCE,commandId:"COMMAND:START:SUBSTITUTED"};f.starts.issue(substituted);await expect(()=>live.start(substituted,f.e,f.starts,f.eligibilities,NOW),"LIVE_ELIGIBILITY_BINDING_MISMATCH");assert(provider.calls.length===0&&live.get()===null,"coordinated eligibility substitution has zero effects");
 assert((await live.start(f.s,f.e,f.starts,f.eligibilities,NOW)).state==="LIVE"&&String(provider.state)==="LIVE","exact signed start reaches provider live");assert((await live.emergencyEnd(f.end,f.ends,NOW)).state==="ENDED"&&String(provider.state)==="ENDED","chain-independent emergency confirms provider ended");assert(provider.calls.join("|")==="START:COMMAND:START:1|END:COMMAND:END:1","provider called once per fenced operation");await expect(()=>live.emergencyEnd(f.end,f.ends,NOW),"LIVE_COMMAND_REPLAY");assert(live.get()?.chatEnabled===false&&live.get()?.replayState==="PENDING_VOD_MODERATION","chat off and replay requires VOD moderation");
 const subject=live.getCheckpointSubject(),snapshots=new Issuer<ReturnType<LiveSessionController["snapshot"]>>(),snapshot=snapshots.issue(live.snapshot({checkpointId:"CHECKPOINT:LIVE:1",...subject,issuedAt:NOW,expiresAt:EXP,issuerKeyId:"KEY:CHECKPOINT:1",signature:H})),checkpoints=new Checkpoints();checkpoints.state={checkpointId:snapshot.checkpointId,eventCount:snapshot.eventCount,eventHeadHash:snapshot.eventHeadHash,stateVersion:snapshot.projection.stateVersion,fencingToken:snapshot.projection.fencingToken};const restored=await LiveSessionController.restore(snapshot,snapshot.checkpointId,creators,moderators,provider,checkpoints,snapshots,f.starts,f.ends,NOW,25);assert(restored.get()?.state==="ENDED"&&restored.getCheckpointSubject().eventHeadHash===subject.eventHeadHash,"durable signed lineage restores exact terminal state");await expect(()=>restored.emergencyEnd(f.end,f.ends,NOW),"LIVE_COMMAND_REPLAY");await expect(()=>LiveSessionController.restore({...snapshot,extra:true},snapshot.checkpointId,creators,moderators,provider,checkpoints,snapshots,f.starts,f.ends,NOW,25),"LIVE_SNAPSHOT_INVALID");const prefix={...snapshot,eventCount:1,eventHeadHash:snapshot.events[0].eventHash,events:[snapshot.events[0]],projection:{...snapshot.projection,state:"LIVE",stateVersion:1,fencingToken:1,chatEnabled:true,replayState:"NONE",lastProviderReceiptCommitment:snapshot.events[0].providerReceipt?.providerReceiptCommitment??null,appealEvidenceCommitment:null}};await expect(()=>LiveSessionController.restore(prefix,snapshot.checkpointId,creators,moderators,provider,checkpoints,{verify:()=>true},f.starts,f.ends,NOW,25),"LIVE_CHECKPOINT_STALE");const fabricated={...snapshot,events:[snapshot.events[0],{...snapshot.events[1],evidenceCommitment:POL}]};await expect(()=>LiveSessionController.restore(fabricated,snapshot.checkpointId,creators,moderators,provider,checkpoints,{verify:()=>true},f.starts,f.ends,NOW,25),"LIVE_SNAPSHOT_INVALID");const projectionSubstitution={...snapshot,projection:{...snapshot.projection,manifestCommitment:EVIDENCE}};await expect(()=>LiveSessionController.restore(projectionSubstitution,snapshot.checkpointId,creators,moderators,provider,checkpoints,{verify:()=>true},f.starts,f.ends,NOW,25),"LIVE_SNAPSHOT_INVALID");

 const callback=fixtures("CALLBACK"),callbackProvider=new StatefulFakeProvider();callbackProvider.corruptNextReceipt=true;const callbackLive=new LiveSessionController(new Creators(),new Moderators(),callbackProvider,25);await expect(()=>callbackLive.start(callback.s,callback.e,callback.starts,callback.eligibilities,NOW),"PROVIDER_START_FAILED");assert(callbackLive.get()?.state==="FAILED_CLOSED"&&callbackProvider.state==="ENDED","receipt manifest substitution triggers higher-fence containment");
 const timeout=fixtures("TIMEOUT"),timeoutProvider=new StatefulFakeProvider();timeoutProvider.holdStart=true;const timeoutLive=new LiveSessionController(new Creators(),new Moderators(),timeoutProvider,5),timeoutResult=timeoutLive.start(timeout.s,timeout.e,timeout.starts,timeout.eligibilities,NOW);await expect(()=>timeoutResult,"PROVIDER_START_TIMEOUT");assert(timeoutLive.get()?.state==="FAILED_CLOSED"&&timeoutProvider.state==="ENDED"&&timeoutProvider.highestFence===2,"start timeout confirms compensating fence");timeoutProvider.releaseLateStart();await Promise.resolve();assert(timeoutProvider.state==="ENDED"&&timeoutProvider.highestFence===2,"late start callback cannot resurrect older fence");
 const race=fixtures("RACE"),raceProvider=new StatefulFakeProvider(),raceCreators=new Creators();raceProvider.afterStart=()=>{raceCreators.state={...raceCreators.state,liveEligible:false}};const raceLive=new LiveSessionController(raceCreators,new Moderators(),raceProvider,25);await expect(()=>raceLive.start(race.s,race.e,race.starts,race.eligibilities,NOW),"START_STATE_CONFLICT");assert(raceLive.get()?.state==="FAILED_CLOSED"&&raceProvider.state==="ENDED","post-provider creator conflict is compensating-contained");

 const pending=fixtures("PENDING"),pendingProvider=new StatefulFakeProvider(),pendingLive=new LiveSessionController(new Creators(),new Moderators(),pendingProvider,10);await pendingLive.start(pending.s,pending.e,pending.starts,pending.eligibilities,NOW);pendingProvider.failEnd=true;await expect(()=>pendingLive.emergencyEnd(pending.end,pending.ends,NOW),"CONTAINMENT_UNCONFIRMED");assert(pendingLive.get()?.state==="CONTAINMENT_PENDING"&&pendingLive.get()?.chatEnabled===false&&String(pendingProvider.state)==="LIVE","failed emergency never claims terminal containment");const pendingSubject=pendingLive.getCheckpointSubject(),pendingSnapshots=new Issuer<ReturnType<LiveSessionController["snapshot"]>>(),pendingSnapshot=pendingSnapshots.issue(pendingLive.snapshot({checkpointId:"CHECKPOINT:LIVE:PENDING",...pendingSubject,issuedAt:NOW,expiresAt:EXP,issuerKeyId:"KEY:CHECKPOINT:1",signature:H})),pendingCheckpoints=new Checkpoints();pendingCheckpoints.state={checkpointId:pendingSnapshot.checkpointId,eventCount:pendingSnapshot.eventCount,eventHeadHash:pendingSnapshot.eventHeadHash,stateVersion:pendingSnapshot.projection.stateVersion,fencingToken:pendingSnapshot.projection.fencingToken};const pendingRestored=await LiveSessionController.restore(pendingSnapshot,pendingSnapshot.checkpointId,new Creators(),new Moderators(),pendingProvider,pendingCheckpoints,pendingSnapshots,pending.starts,pending.ends,NOW,10);pendingProvider.failEnd=false;assert((await pendingRestored.retryContainment(NOW)).state==="FAILED_CLOSED"&&String(pendingProvider.state)==="ENDED"&&pendingProvider.highestFence===3,"restart retry confirms higher-fence provider containment");
 const endTimeout=fixtures("ENDTIMEOUT"),endTimeoutProvider=new StatefulFakeProvider(),endTimeoutLive=new LiveSessionController(new Creators(),new Moderators(),endTimeoutProvider,5);await endTimeoutLive.start(endTimeout.s,endTimeout.e,endTimeout.starts,endTimeout.eligibilities,NOW);endTimeoutProvider.hangEnd=true;await expect(()=>endTimeoutLive.emergencyEnd(endTimeout.end,endTimeout.ends,NOW),"CONTAINMENT_UNCONFIRMED");assert(endTimeoutLive.get()?.state==="CONTAINMENT_PENDING"&&String(endTimeoutProvider.state)==="LIVE","end timeout persists containment pending");endTimeoutProvider.hangEnd=false;assert((await endTimeoutLive.retryContainment(NOW)).state==="FAILED_CLOSED"&&String(endTimeoutProvider.state)==="ENDED","end timeout retry eventually confirms provider ended");
 const moderatorRace=fixtures("MODRACE"),moderatorRaceProvider=new StatefulFakeProvider(),raceModerators=new Moderators();moderatorRaceProvider.afterEnd=()=>{raceModerators.state={version:2,active:false,canEmergencyEnd:false}};const moderatorRaceLive=new LiveSessionController(new Creators(),raceModerators,moderatorRaceProvider,25);await moderatorRaceLive.start(moderatorRace.s,moderatorRace.e,moderatorRace.starts,moderatorRace.eligibilities,NOW);await expect(()=>moderatorRaceLive.emergencyEnd(moderatorRace.end,moderatorRace.ends,NOW),"CONTAINMENT_UNCONFIRMED");assert(moderatorRaceLive.get()?.state==="CONTAINMENT_PENDING"&&moderatorRaceProvider.state==="ENDED","moderator race remains conservatively pending despite provider end");
 process.stdout.write(JSON.stringify({schema_version:1,task_id:"NX-LIVE-P01",status:"PASS",assertions,state:{live:true,emergency_end:true,replay_pending_moderation:true,failed_closed:true,containment_pending:true},receipts:{full_operation_digest:true,provider_authority:true,ordered_hash_lineage:true,durable_checkpoint:true,appeal_evidence:true},negative:{exact_shape:true,kids_broadcast:true,eligibility_substitution:true,command_replay:true,provider_receipt_substitution:true,start_timeout_compensation:true,late_callback_fenced:true,creator_race_compensation:true,emergency_failure_pending:true,emergency_timeout_pending:true,restart_retry:true,moderator_race:true,snapshot_exact_shape:true,snapshot_prefix:true,snapshot_fabrication:true,projection_substitution:true,restore_replay:true},provider:"FAKE_MANAGED_LOCAL_ONLY",provider_terminal_state:"ENDED",network_operations:0,provider_operations:0,economic_operations:0,incremental_cost:{amount:0,currency:"EUR"}}))
}
void main();
