import { AdultLedger, AdultPaidRoomLedger, AdultPolicyError, AdultPolicyState, LocalAdultClock, LocalAdultCommandAuthority, LocalAdultEvidenceVault, LocalAdultRoomAuthority, LocalAdultSnapshotAuthority, adultRecordingConsentScopeCommitment, adultRoomTermsCommitment, adultSettlementTermsCommitment, allocateCreatorEconomics, scanAdultPublicLeakage, type AdultCommand, type AdultEvidenceReceipt, type AdultEvidenceRole, type AdultOperation, type AdultRoomCommand, type AdultRoomCommandVerifier, type AdultSnapshot, type AdultSnapshotAuthority } from "./index";
declare const process: { stdout: { write(value: string): void } };

let assertions = 0;
function assert(condition: unknown, message: string): asserts condition { assertions++; if (!condition) throw new Error(message); }
async function denied(operation: () => unknown | Promise<unknown>, code: string): Promise<void> { let actual = ""; try { await operation(); } catch (error) { actual = error instanceof AdultPolicyError ? error.code : String(error); } assert(actual === code, `expected ${code}, got ${actual}`); }
function H(value: number): string { return value.toString(16).padStart(64, "0"); }
const FUTURE = "2026-01-02T00:00:00.000Z", CREATOR = H(1), VIEWER = H(2), VIEWER_2 = H(3), PERFORMER = H(4), ASSET = H(10), MANIFEST = H(11), ENTITLEMENT = H(12), QUOTE = H(13), SETTLEMENT = H(14);

async function main(): Promise<void> {
  const clock = new LocalAdultClock("2026-01-01T10:00:00.000Z"), state: AdultPolicyState = { version: 1, country: "RO", countryEnabled: true, providerApproved: true, amlApproved: true, taxApproved: true, sanctionsClear: true, uploadsEnabled: true, playbackEnabled: true, settlementEnabled: true }, policy = { current: (country: string) => ({ ...state, country }) }, vault = new LocalAdultEvidenceVault(clock), commandAuthority = new LocalAdultCommandAuthority("AUTH:ADULT:COMMAND", "adult-command-fixture-key", clock);
  const authorities: readonly [AdultEvidenceRole, string, number][] = [["AGE_IDENTITY", "AUTH:AGE", 100], ["CONSENT", "AUTH:CONSENT", 101], ["RIGHTS", "AUTH:RIGHTS", 102], ["MODERATION", "AUTH:MODERATION", 103], ["COUNTRY", "AUTH:COUNTRY", 104], ["SETTLEMENT", "AUTH:SETTLEMENT", 105]];
  for (const [role, key, root] of authorities) vault.register(role, key, H(root), `fixture-secret-${role}-0001`);
  assert(new Set(authorities.map(([, , root]) => root)).size === authorities.length, "independent authority roots");

  const counters = new Map<string, number>();
  async function receipt(role: AdultEvidenceRole, subject: string, asset: string, binding: string, operation: AdultOperation, overrides: Partial<Omit<AdultEvidenceReceipt, "schemaVersion" | "issuedAt" | "authorityKeyId" | "authorityRootCommitment" | "signature">> = {}): Promise<string> { const key = `${role}:${subject}:${operation}`, nonce = (counters.get(key) ?? 0) + 1; counters.set(key, nonce); return vault.issue(role, { receiptId: `RECEIPT:${role}:${nonce}:${subject.slice(0, 6).toUpperCase()}`, role, subjectCommitment: subject, assetCommitment: asset, bindingCommitment: binding, country: "RO", operation, generation: 1, policyVersion: 1, nonce, ageVerified: true, identityVerified: true, livenessVerified: true, consentActive: true, rightsActive: true, automatedSafetyClear: true, immutableIllegalityClear: true, nciiClear: true, providerApproved: true, expiresAt: FUTURE, ...overrides }); }
  async function publishEvidence(asset = ASSET, manifest = MANIFEST): Promise<string[]> { return (await Promise.all([receipt("AGE_IDENTITY", CREATOR, asset, manifest, "PUBLISH"), receipt("AGE_IDENTITY", PERFORMER, asset, manifest, "PUBLISH"), receipt("CONSENT", PERFORMER, asset, manifest, "PUBLISH"), receipt("RIGHTS", CREATOR, asset, manifest, "PUBLISH"), receipt("MODERATION", asset, asset, manifest, "PUBLISH"), receipt("COUNTRY", CREATOR, asset, manifest, "PUBLISH")])).sort(); }
  let commandNonce = 0;
  async function issue(operation: AdultOperation, patch: Partial<Omit<AdultCommand, "authorizedAt" | "authorityKeyId" | "signature">> = {}): Promise<Readonly<AdultCommand>> { commandNonce++; return commandAuthority.issue({ schemaVersion: 1, commandId: `COMMAND:${operation}:${commandNonce}`, operation, offerType: "PPV", actorProfileCommitment: CREATOR, viewerProfileCommitment: null, assetCommitment: ASSET, encryptedManifestCommitment: MANIFEST, performerCommitments: [PERFORMER], quoteCommitment: null, settlementCommitment: null, entitlementCommitment: null, paymentTokenIdentifier: null, feeScheduleVersion: null, quoteExpiresAt: null, country: "RO", channel: "WEB_SEPARATE", policyVersion: 1, assetGeneration: 1, amountMicros: "0", creatorMicros: "0", platformMicros: "0", providerMicros: "0", reserveMicros: "0", evidenceCommitments: [], actorClass: "SYSTEM_TEST", nonce: commandNonce, expiresAt: FUTURE, ...patch }); }

  const ledger = new AdultLedger(policy), publicationEvidence = await publishEvidence(), publish = await issue("PUBLISH", { evidenceCommitments: publicationEvidence }), published = await ledger.execute(publish, commandAuthority, vault), asset = ledger.getAsset(ASSET);
  assert(published.resultingState === "PUBLISHED" && ledger.eventCount() === 1, "publication accepted");
  assert(asset?.state === "PUBLISHED" && asset.offerType === "PPV" && asset.discovery && asset.playback && asset.keysAvailable, "published paid asset active");
  assert(asset?.performerCommitments.length === 1 && asset.publicationEvidence.length === 6, "every performer and evidence retained as commitments");
  assert(scanAdultPublicLeakage(JSON.stringify(ledger.publicActions())).length === 0, "public action contains no sensitive graph or media metadata");
  assert(ledger.publicActions()[0].actionClass === "PRIVATE_ACTION", "public chain action is generic");

  const viewerEvidence = (await Promise.all([receipt("AGE_IDENTITY", VIEWER, ASSET, MANIFEST, "GRANT_ENTITLEMENT"), receipt("COUNTRY", VIEWER, ASSET, MANIFEST, "GRANT_ENTITLEMENT")])).sort(), grant = await issue("GRANT_ENTITLEMENT", { viewerProfileCommitment: VIEWER, entitlementCommitment: ENTITLEMENT, evidenceCommitments: viewerEvidence }), granted = await ledger.execute(grant, commandAuthority, vault);
  assert(granted.resultingState === "ENTITLED", "private entitlement granted");
  assert(ledger.getEntitlement(ENTITLEMENT)?.viewerProfileCommitment === VIEWER, "private viewer binding retained off public action");
  assert(scanAdultPublicLeakage(JSON.stringify(ledger.publicActions())).length === 0, "viewer graph absent from public actions");
  const playback = await ledger.authorizePlayback(ASSET, ENTITLEMENT, VIEWER, vault); assert(playback.keyReleaseAuthorized && playback.encryptedManifestCommitment === MANIFEST && playback.generation === 1, "playback key release binds current viewer entitlement asset manifest generation and country");
  await denied(() => ledger.authorizePlayback(ASSET, ENTITLEMENT, VIEWER_2, vault), "ADULT_PLAYBACK_DENIED");

  const settlementFields = { offerType: "PPV" as const, actorProfileCommitment: CREATOR, viewerProfileCommitment: VIEWER, assetCommitment: ASSET, encryptedManifestCommitment: MANIFEST, entitlementCommitment: ENTITLEMENT, quoteCommitment: QUOTE, settlementCommitment: SETTLEMENT, paymentTokenIdentifier: "USDC-abcdef", feeScheduleVersion: 1, quoteExpiresAt: FUTURE, country: "RO", policyVersion: 1, assetGeneration: 1, amountMicros: "100000", creatorMicros: "80000", platformMicros: "12000", providerMicros: "5000", reserveMicros: "3000", expiresAt: FUTURE }, settlementTerms = await adultSettlementTermsCommitment(settlementFields), settlementEvidence = (await Promise.all([receipt("SETTLEMENT", CREATOR, ASSET, settlementTerms, "SETTLE"), receipt("COUNTRY", CREATOR, ASSET, QUOTE, "SETTLE")])).sort(), settle = await issue("SETTLE", { ...settlementFields, evidenceCommitments: settlementEvidence }), settled = await ledger.execute(settle, commandAuthority, vault);
  assert(settled.resultingState === "SETTLED", "opaque settlement accepted");
  assert(ledger.publicActions()[2].actionClass === "PRIVATE_SETTLEMENT" && ledger.publicActions()[2].genericCommitment === SETTLEMENT, "only opaque settlement commitment reaches public action");
  await denied(() => ledger.execute(settle, commandAuthority, vault), "ADULT_COMMAND_REPLAY");
  const duplicateSettlementCommitment = H(99), duplicateFields = { ...settlementFields, settlementCommitment: duplicateSettlementCommitment }, duplicateTerms = await adultSettlementTermsCommitment(duplicateFields), duplicateSettlementEvidence = (await Promise.all([receipt("SETTLEMENT", CREATOR, ASSET, duplicateTerms, "SETTLE"), receipt("COUNTRY", CREATOR, ASSET, QUOTE, "SETTLE")])).sort(), duplicateSettlement = await issue("SETTLE", { ...duplicateFields, evidenceCommitments: duplicateSettlementEvidence }); await denied(() => ledger.execute(duplicateSettlement, commandAuthority, vault), "ADULT_SETTLEMENT_DENIED");
  const badQuote = H(15), badSettlement = H(16), badFields = { ...settlementFields, quoteCommitment: badQuote, settlementCommitment: badSettlement, creatorMicros: "90000" }, badTerms = await adultSettlementTermsCommitment(badFields), badEvidence = (await Promise.all([receipt("SETTLEMENT", CREATOR, ASSET, badTerms, "SETTLE"), receipt("COUNTRY", CREATOR, ASSET, badQuote, "SETTLE")])).sort(), badConservation = await issue("SETTLE", { ...badFields, evidenceCommitments: badEvidence }); await denied(() => ledger.execute(badConservation, commandAuthority, vault), "ADULT_SETTLEMENT_CONSERVATION_FAILED");
  const wrongSettlementViewerFields = { ...settlementFields, viewerProfileCommitment: VIEWER_2, quoteCommitment: H(17), settlementCommitment: H(18) }, wrongSettlementViewerTerms = await adultSettlementTermsCommitment(wrongSettlementViewerFields), wrongSettlementViewerEvidence = (await Promise.all([receipt("SETTLEMENT", CREATOR, ASSET, wrongSettlementViewerTerms, "SETTLE"), receipt("COUNTRY", CREATOR, ASSET, wrongSettlementViewerFields.quoteCommitment, "SETTLE")])).sort(), wrongSettlementViewer = await issue("SETTLE", { ...wrongSettlementViewerFields, evidenceCommitments: wrongSettlementViewerEvidence }); await denied(() => ledger.execute(wrongSettlementViewer, commandAuthority, vault), "ADULT_SETTLEMENT_DENIED");
  const lowShareFields = { ...settlementFields, quoteCommitment: H(19), settlementCommitment: H(23), creatorMicros: "70000", platformMicros: "22000" }, lowShareTerms = await adultSettlementTermsCommitment(lowShareFields), lowShareEvidence = (await Promise.all([receipt("SETTLEMENT", CREATOR, ASSET, lowShareTerms, "SETTLE"), receipt("COUNTRY", CREATOR, ASSET, lowShareFields.quoteCommitment, "SETTLE")])).sort(), lowShareSettlement = await issue("SETTLE", { ...lowShareFields, evidenceCommitments: lowShareEvidence }); await denied(() => ledger.execute(lowShareSettlement, commandAuthority, vault), "ADULT_CREATOR_SHARE_TOO_LOW");
  const settlementBindingVariants = await Promise.all([adultSettlementTermsCommitment({ ...settlementFields, assetGeneration: 2 }), adultSettlementTermsCommitment({ ...settlementFields, policyVersion: 2 }), adultSettlementTermsCommitment({ ...settlementFields, paymentTokenIdentifier: "EGLD" }), adultSettlementTermsCommitment({ ...settlementFields, feeScheduleVersion: 2 }), adultSettlementTermsCommitment({ ...settlementFields, quoteExpiresAt: "2026-01-01T10:30:00.000Z" }), adultSettlementTermsCommitment({ ...settlementFields, expiresAt: "2026-01-01T10:45:00.000Z" })]); assert(settlementBindingVariants.every(value => value !== settlementTerms) && new Set(settlementBindingVariants).size === settlementBindingVariants.length, "settlement terms bind generation policy token fee schedule quote expiry and command expiry independently");
  const generationQuote = H(24), generationSettlement = H(25), generationFields = { ...settlementFields, assetGeneration: 2, quoteCommitment: generationQuote, settlementCommitment: generationSettlement }, generationTerms = await adultSettlementTermsCommitment(generationFields), generationEvidence = (await Promise.all([receipt("SETTLEMENT", CREATOR, ASSET, generationTerms, "SETTLE", { generation: 2 }), receipt("COUNTRY", CREATOR, ASSET, generationQuote, "SETTLE", { generation: 2 })])).sort(), generationSubstitution = await issue("SETTLE", { ...generationFields, evidenceCommitments: generationEvidence }); await denied(() => ledger.execute(generationSubstitution, commandAuthority, vault), "ADULT_SETTLEMENT_DENIED");
  const expiredQuoteFields = { ...settlementFields, quoteCommitment: H(26), settlementCommitment: H(27), quoteExpiresAt: "2026-01-01T10:00:00.000Z" }, expiredQuoteTerms = await adultSettlementTermsCommitment(expiredQuoteFields), expiredQuoteEvidence = (await Promise.all([receipt("SETTLEMENT", CREATOR, ASSET, expiredQuoteTerms, "SETTLE"), receipt("COUNTRY", CREATOR, ASSET, expiredQuoteFields.quoteCommitment, "SETTLE")])).sort(), expiredQuoteSettlement = await issue("SETTLE", { ...expiredQuoteFields, evidenceCommitments: expiredQuoteEvidence }); await denied(() => ledger.execute(expiredQuoteSettlement, commandAuthority, vault), "ADULT_SETTLEMENT_QUOTE_EXPIRED");
  const raceFieldsA = { ...settlementFields, quoteCommitment: H(28), settlementCommitment: H(29) }, raceFieldsB = { ...settlementFields, quoteCommitment: H(30), settlementCommitment: H(31) }, raceTermsA = await adultSettlementTermsCommitment(raceFieldsA), raceTermsB = await adultSettlementTermsCommitment(raceFieldsB), raceEvidenceA = (await Promise.all([receipt("SETTLEMENT", CREATOR, ASSET, raceTermsA, "SETTLE"), receipt("COUNTRY", CREATOR, ASSET, raceFieldsA.quoteCommitment, "SETTLE")])).sort(), raceEvidenceB = (await Promise.all([receipt("SETTLEMENT", CREATOR, ASSET, raceTermsB, "SETTLE"), receipt("COUNTRY", CREATOR, ASSET, raceFieldsB.quoteCommitment, "SETTLE")])).sort(), raceCommandA = await issue("SETTLE", { ...raceFieldsA, evidenceCommitments: raceEvidenceA }), raceCommandB = await issue("SETTLE", { ...raceFieldsB, evidenceCommitments: raceEvidenceB }), eventsBeforeSettlementRace = ledger.eventCount(), settlementRace = await Promise.allSettled([ledger.execute(raceCommandA, commandAuthority, vault), ledger.execute(raceCommandB, commandAuthority, vault)]), settlementRaceFailure = settlementRace.find(result => result.status === "rejected") as PromiseRejectedResult | undefined; assert(settlementRace.filter(result => result.status === "fulfilled").length === 1 && settlementRaceFailure?.reason instanceof AdultPolicyError && settlementRaceFailure.reason.code === "ADULT_EXECUTION_STATE_CONFLICT" && ledger.eventCount() === eventsBeforeSettlementRace + 1, "concurrent settlements over the same current entitlement have exactly one CAS winner");

  const missingAge = await issue("PUBLISH", { assetCommitment: H(20), encryptedManifestCommitment: H(21), evidenceCommitments: [] }); await denied(() => ledger.execute(missingAge, commandAuthority, vault), "ADULT_REQUIRED_EVIDENCE_MISSING");
  const substituted = { ...publish, assetCommitment: H(22) }; await denied(() => ledger.execute(substituted, commandAuthority, vault), "ADULT_COMMAND_SIGNATURE_INVALID");
  const booleanString = { ...publish, actorClass: "SYSTEM_TEST", policyVersion: "1" }; await denied(() => ledger.execute(booleanString, commandAuthority, vault), "ADULT_COMMAND_INVALID");
  let getterCalls = 0; const getterCommand = { ...publish } as Record<string, unknown>; Object.defineProperty(getterCommand, "country", { enumerable: true, get: () => { getterCalls++; return "RO"; } }); await denied(() => ledger.execute(getterCommand, commandAuthority, vault), "ADULT_COMMAND_INVALID"); assert(getterCalls === 0, "accessor rejected without execution");
  let proxyCalls = 0; const proxy = new Proxy({ ...publish }, { getPrototypeOf: target => { proxyCalls++; return Reflect.getPrototypeOf(target); }, ownKeys: target => { proxyCalls++; return Reflect.ownKeys(target); } }); await denied(() => ledger.execute(proxy, commandAuthority, vault), "ADULT_COMMAND_INVALID"); assert(proxyCalls === 0, "proxy rejected before traps");

  state.countryEnabled = false; const countryDenied = await issue("GRANT_ENTITLEMENT", { viewerProfileCommitment: VIEWER_2, entitlementCommitment: H(30), evidenceCommitments: [] }); await denied(() => ledger.execute(countryDenied, commandAuthority, vault), "ADULT_COUNTRY_POLICY_DENIED"); state.countryEnabled = true;
  const wrongViewerEvidence = (await Promise.all([receipt("AGE_IDENTITY", VIEWER, ASSET, MANIFEST, "GRANT_ENTITLEMENT"), receipt("COUNTRY", VIEWER, ASSET, MANIFEST, "GRANT_ENTITLEMENT")])).sort(), wrongViewer = await issue("GRANT_ENTITLEMENT", { viewerProfileCommitment: VIEWER_2, entitlementCommitment: H(31), evidenceCommitments: wrongViewerEvidence }); await denied(() => ledger.execute(wrongViewer, commandAuthority, vault), "ADULT_REQUIRED_EVIDENCE_MISSING");

  clock.advance("2026-01-01T11:00:00.000Z"); const consentCommitment = publicationEvidence.find(value => vault.export().find(item => item.commitment === value)?.receipt.role === "CONSENT")!; vault.revoke(consentCommitment); await denied(() => ledger.authorizePlayback(ASSET, ENTITLEMENT, VIEWER, vault), "ADULT_PLAYBACK_DENIED"); assert(ledger.getAsset(ASSET)?.state === "SUSPENDED" && ledger.getEntitlement(ENTITLEMENT)?.state === "REVOKED", "revoked consent suspends asset and every existing entitlement before key release"); const freshViewerEvidence = (await Promise.all([receipt("AGE_IDENTITY", VIEWER_2, ASSET, MANIFEST, "GRANT_ENTITLEMENT"), receipt("COUNTRY", VIEWER_2, ASSET, MANIFEST, "GRANT_ENTITLEMENT")])).sort(), afterRevocation = await issue("GRANT_ENTITLEMENT", { viewerProfileCommitment: VIEWER_2, entitlementCommitment: H(32), evidenceCommitments: freshViewerEvidence }); await denied(() => ledger.execute(afterRevocation, commandAuthority, vault), "ADULT_EVIDENCE_INVALID"); assert(ledger.getEntitlement(H(32)) === null, "revoked consent cannot create entitlement");

  const purgeEvidence = [await receipt("MODERATION", ASSET, ASSET, MANIFEST, "PURGE")], purge = await issue("PURGE", { evidenceCommitments: purgeEvidence }), purged = await ledger.execute(purge, commandAuthority, vault);
  assert(purged.resultingState === "PURGED", "purge accepted after safety authority receipt");
  const purgedAsset = ledger.getAsset(ASSET); assert(purgedAsset?.state === "PURGED" && !purgedAsset.discovery && !purgedAsset.playback && !purgedAsset.keysAvailable, "purge revokes discovery playback and keys");
  assert(ledger.getEntitlement(ENTITLEMENT)?.state === "REVOKED", "purge revokes existing entitlement");
  const afterPurge = await issue("GRANT_ENTITLEMENT", { viewerProfileCommitment: VIEWER_2, entitlementCommitment: H(33), evidenceCommitments: freshViewerEvidence }); await denied(() => ledger.execute(afterPurge, commandAuthority, vault), "ADULT_EVIDENCE_INVALID");

  const concurrentAsset = H(40), concurrentManifest = H(41), concurrentEvidence = await publishEvidence(concurrentAsset, concurrentManifest), concurrentCommand = await issue("PUBLISH", { offerType: "FREE_DISCOVERY", assetCommitment: concurrentAsset, encryptedManifestCommitment: concurrentManifest, evidenceCommitments: concurrentEvidence }), concurrentLedger = new AdultLedger(policy), outcomes = await Promise.allSettled([concurrentLedger.execute(concurrentCommand, commandAuthority, vault), concurrentLedger.execute(concurrentCommand, commandAuthority, vault)]);
  assert(outcomes.filter(item => item.status === "fulfilled").length === 1, "concurrent command has one winner");
  assert(concurrentLedger.eventCount() === 1, "concurrent execution emits exactly one event");
  assert(concurrentLedger.getAsset(concurrentAsset)?.offerType === "FREE_DISCOVERY", "free discovery offer still required full age consent rights safety and country evidence");
  assert(JSON.stringify(concurrentLedger.publicActions()).includes("PRIVATE_ACTION"), "generic public action projection available");

  clock.advance("2026-01-01T12:00:00.000Z"); const snapshotAuthority = new LocalAdultSnapshotAuthority("AUTH:ADULT:SNAPSHOT", "adult-snapshot-fixture-key"), snapshot = await ledger.snapshot(vault, snapshotAuthority, "CHECKPOINT:ADULT:1", FUTURE), durable = { current: () => ({ checkpointId: snapshot.checkpointId, policyVersion: snapshot.policyVersion, eventCount: snapshot.eventCount, eventHeadHash: snapshot.eventHeadHash, eventsCommitment: snapshot.eventsCommitment, evidenceCommitment: snapshot.evidenceCommitment }) }, restored = await AdultLedger.restore(snapshot, snapshot.checkpointId, policy, commandAuthority, vault, snapshotAuthority, durable);
  assert(restored.eventCount() === ledger.eventCount(), "fresh restore reconstructs complete ordered history");
  assert(restored.getAsset(ASSET)?.state === "PURGED" && restored.getEntitlement(ENTITLEMENT)?.state === "REVOKED", "fresh restore preserves purge and entitlement revocation");
  assert(JSON.stringify(restored.publicActions()) === JSON.stringify(ledger.publicActions()), "public action projection is deterministic after restore");
  await denied(() => restored.execute(purge, commandAuthority, vault), "ADULT_COMMAND_REPLAY");
  const vaultVersionBeforeFailedRestore = vault.stateVersion(), truncatedUnsigned = { ...snapshot, events: snapshot.events.slice(0, -1), eventCount: snapshot.eventCount - 1, eventHeadHash: snapshot.events[snapshot.events.length - 2].eventHash }, { signature: _oldTruncatedSignature, ...truncatedBase } = truncatedUnsigned, truncated: AdultSnapshot = { ...truncatedBase, signature: await snapshotAuthority.sign(truncatedBase) }; await denied(() => AdultLedger.restore(truncated, snapshot.checkpointId, policy, commandAuthority, vault, snapshotAuthority, durable), "ADULT_SNAPSHOT_INVALID"); assert(vault.stateVersion() === vaultVersionBeforeFailedRestore, "failed restore leaves external evidence vault unchanged");
  const reordered = { ...snapshot, events: [snapshot.events[1], snapshot.events[0], ...snapshot.events.slice(2)] }; await denied(() => AdultLedger.restore(reordered, snapshot.checkpointId, policy, commandAuthority, vault, snapshotAuthority, durable), "ADULT_SNAPSHOT_INVALID");
  const extraField = { ...snapshot, unexpected: true }; await denied(() => AdultLedger.restore(extraField, snapshot.checkpointId, policy, commandAuthority, vault, snapshotAuthority, durable), "ADULT_SNAPSHOT_INVALID");
  const strippedEvidenceUnsigned = { ...snapshot, evidence: [], evidenceCommitment: H(0) }, { signature: _oldStrippedSignature, ...strippedBase } = strippedEvidenceUnsigned, strippedEvidence: AdultSnapshot = { ...strippedBase, signature: await snapshotAuthority.sign(strippedBase) }; await denied(() => AdultLedger.restore(strippedEvidence, snapshot.checkpointId, policy, commandAuthority, vault, snapshotAuthority, durable), "ADULT_SNAPSHOT_INVALID");
  const expiringSnapshot = await ledger.snapshot(vault, snapshotAuthority, "CHECKPOINT:ADULT:EXPIRING", "2026-01-01T12:00:01.000Z"), expiringDurable = { current: () => ({ checkpointId: expiringSnapshot.checkpointId, policyVersion: expiringSnapshot.policyVersion, eventCount: expiringSnapshot.eventCount, eventHeadHash: expiringSnapshot.eventHeadHash, eventsCommitment: expiringSnapshot.eventsCommitment, evidenceCommitment: expiringSnapshot.evidenceCommitment }) }, vaultBeforeExpiringRestore = vault.stateVersion(), slowSnapshotAuthority: AdultSnapshotAuthority = { keyId: snapshotAuthority.keyId, sign: value => snapshotAuthority.sign(value), verify: async value => { const valid = await snapshotAuthority.verify(value); clock.advance("2026-01-01T12:00:02.000Z"); return valid; } }; await denied(() => AdultLedger.restore(expiringSnapshot, expiringSnapshot.checkpointId, policy, commandAuthority, vault, slowSnapshotAuthority, expiringDurable), "ADULT_SNAPSHOT_INVALID"); assert(vault.stateVersion() === vaultBeforeExpiringRestore, "snapshot expiring during verification cannot mutate destination evidence state");

  const creatorAllocation = allocateCreatorEconomics({ offerType: "PPV", grossMicros: "100000", creatorMicros: "80000", nexusGrossMicros: "12000", providerMicros: "5000", reserveMicros: "3000", referralMicros: "2000", referralTrafficClass: "HUMAN_ORGANIC", qualifiedActivation: true, referralDepth: 1 });
  assert(creatorAllocation.creatorShareBps === 8000 && creatorAllocation.nexusNetMicros === "10000" && creatorAllocation.referralMicros === "2000", "creator gets dominant 80 percent and qualified referral is funded only from Nexus fee");
  const tipAllocation = allocateCreatorEconomics({ offerType: "TIP", grossMicros: "100000", creatorMicros: "90000", nexusGrossMicros: "5000", providerMicros: "2000", reserveMicros: "3000", referralMicros: "1000", referralTrafficClass: "HUMAN_ORGANIC", qualifiedActivation: true, referralDepth: 1 });
  assert(tipAllocation.creatorShareBps === 9000 && tipAllocation.nexusNetMicros === "4000", "tip model targets 90 percent creator share");
  await denied(() => allocateCreatorEconomics({ offerType: "TIP", grossMicros: "100000", creatorMicros: "70000", nexusGrossMicros: "25000", providerMicros: "2000", reserveMicros: "3000", referralMicros: "0", referralTrafficClass: "HUMAN_ORGANIC", qualifiedActivation: false, referralDepth: 0 }), "ADULT_CREATOR_SHARE_TOO_LOW");
  for (const referralTrafficClass of ["SYSTEM_TEST", "PAID", "AGENT"] as const) { const excluded = allocateCreatorEconomics({ offerType: "SUBSCRIPTION", grossMicros: "100000", creatorMicros: "80000", nexusGrossMicros: "12000", providerMicros: "5000", reserveMicros: "3000", referralMicros: "2000", referralTrafficClass, qualifiedActivation: true, referralDepth: 1 }); assert(excluded.referralMicros === "0" && excluded.nexusNetMicros === "12000", `${referralTrafficClass} referral receives zero`); }
  const unqualified = allocateCreatorEconomics({ offerType: "BUNDLE", grossMicros: "100000", creatorMicros: "80000", nexusGrossMicros: "12000", providerMicros: "5000", reserveMicros: "3000", referralMicros: "2000", referralTrafficClass: "HUMAN_ORGANIC", qualifiedActivation: false, referralDepth: 1 }), multiLevel = allocateCreatorEconomics({ offerType: "PAID_LIVE", grossMicros: "100000", creatorMicros: "80000", nexusGrossMicros: "12000", providerMicros: "5000", reserveMicros: "3000", referralMicros: "2000", referralTrafficClass: "HUMAN_ORGANIC", qualifiedActivation: true, referralDepth: 2 });
  assert(unqualified.referralMicros === "0" && multiLevel.referralMicros === "0", "unqualified and multi-level recruitment receive zero");
  await denied(() => allocateCreatorEconomics({ offerType: "FREE_DISCOVERY", grossMicros: "100000", creatorMicros: "80000", nexusGrossMicros: "12000", providerMicros: "5000", reserveMicros: "3000", referralMicros: "0", referralTrafficClass: "HUMAN_ORGANIC", qualifiedActivation: false, referralDepth: 0 }), "ADULT_ECONOMIC_CONSERVATION_FAILED");

  const roomAuthority = new LocalAdultRoomAuthority("AUTH:ADULT:ROOM", "adult-room-fixture-key", clock), roomLedger = new AdultPaidRoomLedger(policy, clock), ROOM = H(70), ESCROW = H(71), roomEscrowEvidence = new Map<string, string>(), roomConsentEvidence = new Map<string, string>(); let roomNonce = 0;
  async function issueRoom(action: "OPEN" | "METER" | "CLOSE", cumulativeSeconds: number, patch: Partial<Omit<AdultRoomCommand, "occurredAt" | "authorityKeyId" | "signature">> = {}): Promise<Readonly<AdultRoomCommand>> {
    roomNonce++;
    const draft = { schemaVersion: 1 as const, commandId: `ROOM:${action}:${roomNonce}`, action, roomKind: "PAID_1_TO_1_CALL" as const, sessionCommitment: ROOM, creatorProfileCommitment: CREATOR, viewerProfileCommitment: VIEWER, creatorDeviceCommitment: H(80), viewerDeviceCommitment: H(81), escrowCommitment: ESCROW, paymentTokenIdentifier: "EGLD", feeScheduleVersion: 1, escrowExpiresAt: FUTURE, rateMicrosPerMinute: "6000", authorizedMicros: "12000", cumulativeSeconds, timerVisible: true as const, recordingRequested: false, recordingPurpose: "NONE" as const, recordingConsentCommitments: [] as readonly string[], evidenceCommitments: [] as readonly string[], offPlatformServiceSolicitation: false as const, country: "RO", policyVersion: 1, actorClass: "SYSTEM_TEST" as const, nonce: roomNonce, expiresAt: FUTURE, ...patch }, terms = await adultRoomTermsCommitment(draft), escrowKey = `${draft.sessionCommitment}:${terms}`;
    let escrowAuthorization = roomEscrowEvidence.get(escrowKey); if (!escrowAuthorization) { escrowAuthorization = await receipt("SETTLEMENT", draft.creatorProfileCommitment, draft.sessionCommitment, terms, "SETTLE"); roomEscrowEvidence.set(escrowKey, escrowAuthorization); }
    const evidenceCommitments = patch.evidenceCommitments ?? (await Promise.all([receipt("AGE_IDENTITY", draft.creatorProfileCommitment, draft.sessionCommitment, draft.escrowCommitment, "SETTLE"), receipt("AGE_IDENTITY", draft.viewerProfileCommitment, draft.sessionCommitment, draft.escrowCommitment, "SETTLE"), receipt("COUNTRY", draft.creatorProfileCommitment, draft.sessionCommitment, draft.escrowCommitment, "SETTLE"), receipt("COUNTRY", draft.viewerProfileCommitment, draft.sessionCommitment, draft.escrowCommitment, "SETTLE")])).concat(escrowAuthorization).sort();
    let recordingConsentCommitments: readonly string[] = patch.recordingConsentCommitments ?? [];
    if (draft.recordingRequested && patch.recordingConsentCommitments === undefined) { const creatorScope = await adultRecordingConsentScopeCommitment(draft.creatorProfileCommitment, draft.creatorDeviceCommitment, draft), viewerScope = await adultRecordingConsentScopeCommitment(draft.viewerProfileCommitment, draft.viewerDeviceCommitment, draft), creatorKey = `${draft.creatorProfileCommitment}:${creatorScope}`, viewerKey = `${draft.viewerProfileCommitment}:${viewerScope}`; let creatorConsent = roomConsentEvidence.get(creatorKey), viewerConsent = roomConsentEvidence.get(viewerKey); if (!creatorConsent) { creatorConsent = await receipt("CONSENT", draft.creatorProfileCommitment, draft.sessionCommitment, creatorScope, "SETTLE"); roomConsentEvidence.set(creatorKey, creatorConsent); } if (!viewerConsent) { viewerConsent = await receipt("CONSENT", draft.viewerProfileCommitment, draft.sessionCommitment, viewerScope, "SETTLE"); roomConsentEvidence.set(viewerKey, viewerConsent); } recordingConsentCommitments = [creatorConsent, viewerConsent].sort(); }
    return roomAuthority.issue({ ...draft, evidenceCommitments, recordingConsentCommitments });
  }
  const openRoom = await issueRoom("OPEN", 0), openedRoom = await roomLedger.execute(openRoom, roomAuthority, vault); assert(openedRoom.state === "OPEN" && roomLedger.get(ROOM)?.timerVisible, "paid one-to-one call opens only with visible rate timer and preauthorized escrow cap");
  await denied(() => new AdultPaidRoomLedger(policy, clock).execute(openRoom, roomAuthority, vault), "ADULT_ROOM_EVIDENCE_MISSING");
  const openRoomTerms = await adultRoomTermsCommitment(openRoom), roomTermVariants = await Promise.all([adultRoomTermsCommitment({ ...openRoom, paymentTokenIdentifier: "USDC-abcdef" }), adultRoomTermsCommitment({ ...openRoom, escrowExpiresAt: "2026-01-01T23:00:00.000Z" }), adultRoomTermsCommitment({ ...openRoom, recordingPurpose: "SESSION_RECORDING" }), adultRoomTermsCommitment({ ...openRoom, feeScheduleVersion: 2 })]); assert(roomTermVariants.every(value => value !== openRoomTerms) && new Set(roomTermVariants).size === roomTermVariants.length, "room escrow terms bind token expiry recording purpose and fee schedule");
  const substitutedRoom = await issueRoom("METER", 60, { viewerProfileCommitment: VIEWER_2, escrowCommitment: H(78) }); await denied(() => roomLedger.execute(substitutedRoom, roomAuthority, vault), "ADULT_ROOM_STATE_INVALID");
  const tokenSubstitutedRoom = await issueRoom("METER", 60, { paymentTokenIdentifier: "USDC-abcdef" }); await denied(() => roomLedger.execute(tokenSubstitutedRoom, roomAuthority, vault), "ADULT_ROOM_STATE_INVALID");
  const expirySubstitutedRoom = await issueRoom("METER", 60, { escrowExpiresAt: "2026-01-01T23:00:00.000Z" }); await denied(() => roomLedger.execute(expirySubstitutedRoom, roomAuthority, vault), "ADULT_ROOM_STATE_INVALID");
  const firstMeter = await issueRoom("METER", 60), firstMeterReceipt = await roomLedger.execute(firstMeter, roomAuthority, vault); assert(firstMeterReceipt.billedMicros === "6000" && firstMeterReceipt.state === "OPEN", "signed per-minute metering bills only elapsed authorized time");
  const capMeter = await issueRoom("METER", 120), capReceipt = await roomLedger.execute(capMeter, roomAuthority, vault); assert(capReceipt.billedMicros === "12000" && capReceipt.state === "AUTO_CLOSED_LIMIT", "paid call automatically stops at authorized balance limit");
  const afterLimit = await issueRoom("METER", 121); await denied(() => roomLedger.execute(afterLimit, roomAuthority, vault), "ADULT_ROOM_STATE_INVALID");
  await denied(() => roomLedger.execute(capMeter, roomAuthority, vault), "ADULT_ROOM_REPLAY");
  assert(scanAdultPublicLeakage(JSON.stringify(roomLedger.publicReceipts())).length === 0, "public room metering receipts expose no participant or escrow graph");
  await denied(() => issueRoom("OPEN", 0, { sessionCommitment: H(72), recordingRequested: true, recordingPurpose: "SESSION_RECORDING", recordingConsentCommitments: [] }), "ADULT_ROOM_RECORDING_CONSENT_REQUIRED");
  const arbitraryRecordingConsent = await issueRoom("OPEN", 0, { sessionCommitment: H(76), recordingRequested: true, recordingPurpose: "SESSION_RECORDING", recordingConsentCommitments: [H(90), H(91)] }); await denied(() => roomLedger.execute(arbitraryRecordingConsent, roomAuthority, vault), "ADULT_ROOM_EVIDENCE_MISSING");
  await denied(() => issueRoom("OPEN", 0, { sessionCommitment: H(73), offPlatformServiceSolicitation: true as false }), "ADULT_ROOM_COMMAND_INVALID");
  const liveRoom = H(74), liveOpen = await issueRoom("OPEN", 0, { roomKind: "PAID_LIVE", sessionCommitment: liveRoom, escrowCommitment: H(75) }), liveLedger = new AdultPaidRoomLedger(policy, clock); await liveLedger.execute(liveOpen, roomAuthority, vault); assert(liveLedger.get(liveRoom)?.roomKind === "PAID_LIVE", "paid live room uses the same capped transparent metering boundary");
  const recordingRoom = H(82), recordingOpen = await issueRoom("OPEN", 0, { sessionCommitment: recordingRoom, escrowCommitment: H(83), recordingRequested: true, recordingPurpose: "SESSION_RECORDING" }), recordingLedger = new AdultPaidRoomLedger(policy, clock), recordingReceipt = await recordingLedger.execute(recordingOpen, roomAuthority, vault); assert(recordingReceipt.state === "OPEN" && recordingLedger.get(recordingRoom)?.recording, "recording opens only with both participant device-scoped consent receipts"); const creatorConsentScope = await adultRecordingConsentScopeCommitment(CREATOR, recordingOpen.creatorDeviceCommitment, recordingOpen), creatorConsentDeviceVariant = await adultRecordingConsentScopeCommitment(CREATOR, H(84), recordingOpen), creatorConsentPurposeVariant = await adultRecordingConsentScopeCommitment(CREATOR, recordingOpen.creatorDeviceCommitment, { ...recordingOpen, recordingPurpose: "NONE" }); assert(creatorConsentScope !== creatorConsentDeviceVariant && creatorConsentScope !== creatorConsentPurposeVariant, "recording consent scope binds participant device session purpose policy and generation");
  const recordingDeviceSubstitution = await issueRoom("METER", 60, { sessionCommitment: recordingRoom, escrowCommitment: H(83), recordingRequested: true, recordingPurpose: "SESSION_RECORDING", creatorDeviceCommitment: H(84) }); await denied(() => recordingLedger.execute(recordingDeviceSubstitution, roomAuthority, vault), "ADULT_ROOM_STATE_INVALID");
  const expiringRoom = await issueRoom("OPEN", 0, { sessionCommitment: H(77), escrowCommitment: H(79), expiresAt: "2026-01-01T12:00:03.000Z" }), slowRoomVerifier: AdultRoomCommandVerifier = { verify: async value => { const valid = await roomAuthority.verify(value); clock.advance("2026-01-01T12:00:04.000Z"); return valid; } }; await denied(() => new AdultPaidRoomLedger(policy, clock).execute(expiringRoom, slowRoomVerifier, vault), "ADULT_ROOM_COMMAND_EXPIRED");

  const external = { network_operations: 0, provider_operations: 0, economic_operations: 0, real_fund_operations: 0, real_identity_operations: 0, real_media_operations: 0 };
  assert(Object.values(external).every(value => value === 0), "zero external effects");
  process.stdout.write(JSON.stringify({ schema_version: 1, task_id: "NX-ADULT-P01", status: "PASS", assertions, actor_class: "SYSTEM_TEST", surface: { web_separate: true, mobile_store_catalog: false, public_ipfs: false, public_global_search: false, country_default_deny: true }, publication: { creator_age_identity_liveness: true, every_performer_age_identity_liveness_consent: true, rights: true, automated_safety: true, immutable_illegality_and_ncii: true, country_provider_gate: true, free_discovery_fully_gated: true }, entitlement: { private: true, current_evidence_recheck: true, viewer_graph_public: false }, paid_rooms: { live: true, one_to_one_call: true, visible_rate_timer: true, preauthorized_cap: true, signed_per_minute_metering: true, automatic_limit_stop: true, recording_all_party_consent: true, public_graph_leakage: 0 }, purge: { discovery: true, playback: true, keys: true, entitlements: true }, settlement: { opaque: true, quote_single_use: true, exact_conservation: true }, creator_economics: { content_creator_bps: 8000, tip_creator_bps: 9000, referral_from_nexus_fee_only: true, paid_agent_synthetic_referral_zero: true, multi_level_referral_zero: true, organic_ranking_contribution: 0 }, input_boundary: { exact_shape: true, boolean_string_denied: true, accessor_zero_execution: true, proxy_zero_traps: true }, concurrency: { one_winner: true, one_event: true }, restore: { signed_snapshot: true, durable_checkpoint: true, ordered_hash_chain: true, prefix_removal_denied: true, reorder_denied: true, evidence_strip_denied: true, replay_denied_after_restart: true, fail_atomic: true }, privacy: { public_leakage_findings: 0, perfect_anonymity_claim: false }, synthetic_isolation: external, incremental_cost: { amount: 0, currency: "EUR" } }));
}
main().catch(error => { throw error; });
