[CmdletBinding()]
param([string]$OutputDirectory)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$contractRoot = $PSScriptRoot
$api = Get-Content -LiteralPath (Join-Path $contractRoot 'api\openapi.v1.json') -Raw -Encoding UTF8 | ConvertFrom-Json
$event = Get-Content -LiteralPath (Join-Path $contractRoot 'events\action.chain.executed.v1.schema.json') -Raw -Encoding UTF8 | ConvertFrom-Json
$abi = Get-Content -LiteralPath (Join-Path $contractRoot 'abi\nexus-actions.abi.json') -Raw -Encoding UTF8 | ConvertFrom-Json
$catalog = Get-Content -LiteralPath (Join-Path $contractRoot 'data\catalog.v1.json') -Raw -Encoding UTF8 | ConvertFrom-Json
$repoRoot = Split-Path -Parent (Split-Path -Parent $contractRoot)
$generatedDir = if([string]::IsNullOrWhiteSpace($OutputDirectory)){Join-Path $contractRoot 'generated'}else{[IO.Path]::GetFullPath($OutputDirectory)}
$allowedRoots=@((Join-Path $contractRoot 'generated'),(Join-Path ([IO.Path]::GetTempPath()) 'Nexus\NX-CONTRACT-001'))
$contained=$false
foreach($allowedRoot in $allowedRoots){$rootFull=[IO.Path]::GetFullPath($allowedRoot).TrimEnd('\')+'\';if(($generatedDir.TrimEnd('\')+'\').StartsWith($rootFull,[StringComparison]::OrdinalIgnoreCase)){$contained=$true}}
if(-not $contained){throw 'Bindings output directory is outside approved generated/ephemeral roots.'}

function Convert-ToUnion {
    param([object[]]$Values)
    return (@($Values | ForEach-Object { "'" + ([string]$_).Replace("'", "\'") + "'" }) -join ' | ')
}

function Write-Utf8NoBom {
    param([string]$Path,[string]$Content)
    if (-not (Test-Path -LiteralPath (Split-Path -Parent $Path))) { New-Item -ItemType Directory -Path (Split-Path -Parent $Path) -Force | Out-Null }
    [IO.File]::WriteAllText($Path, $Content, [Text.UTF8Encoding]::new($false))
}

$actionTypes = Convert-ToUnion @($api.components.schemas.ActionType.enum)
$visibilityClasses = Convert-ToUnion @($api.components.schemas.VisibilityClass.enum)
$actionStates = Convert-ToUnion @($api.components.schemas.ActionState.enum)
$actorKinds = Convert-ToUnion @($event.properties.actorKind.enum)
$abiEndpoints = Convert-ToUnion @($abi.endpoints.name)
$catalogIds = Convert-ToUnion @($catalog.fields.catalog_id)
$eventType = [string]$event.properties.eventType.const

$index = @"
// GENERATED by packages/contracts/generate-bindings.ps1. Do not edit manually.
export type UuidV7 = string;
export type Hash32Hex = string;
export type ActionType = $actionTypes;
export type VisibilityClass = $visibilityClasses;
export type ActionState = $actionStates;
export type ActorKind = $actorKinds;
export type NexusActionsEndpoint = $abiEndpoints;
export type DataCatalogId = $catalogIds;

export interface CreateActionRequest {
  actionType: ActionType;
  objectCommitment: Hash32Hex;
  payloadHash: Hash32Hex;
  visibilityClass: VisibilityClass;
  actionNonce: string;
  expiresAt: string;
}

export interface ActionIntent {
  id: UuidV7;
  state: ActionState;
  txHash?: Hash32Hex | null;
  optimistic: boolean;
  aggregateVersion: number;
  createdAt: string;
  updatedAt: string;
}

export interface ChainActionExecutedV1 {
  eventId: UuidV7;
  eventType: '$eventType';
  occurredAt: string;
  producer: 'chain_integration';
  aggregateId: UuidV7;
  aggregateVersion: number;
  actorKind: ActorKind;
  traceId: string;
  privacyClass: 'INTERNAL';
  data: {
    network: 'localnet' | 'devnet' | 'testnet' | 'mainnet';
    contractAddress: string;
    originalTxHash: Hash32Hex;
    sourceTxHash: Hash32Hex;
    sourceKind: 'TRANSACTION' | 'SMART_CONTRACT_RESULT';
    eventIndex: number;
    shard: number;
    blockNonce: number;
    blockHash: Hash32Hex;
    hyperblockNonce: number;
    hyperblockHash: Hash32Hex;
    canonicality: 'FINALIZED_CANONICAL';
    finality: 'HYPERBLOCK_FINAL';
    status: 'EXECUTED_SUCCESS';
    actionType: 'PUBLIC_ACTION' | 'PRIVATE_ACTION';
    actorCommitment: Hash32Hex;
    objectCommitment: Hash32Hex;
  };
}

export interface NexusActionsClient {
  recordAction(envelope: Uint8Array, sessionSignature: Uint8Array): Promise<void>;
  recordPrivateAction(genericCommitment: Uint8Array, envelope: Uint8Array, sessionSignature: Uint8Array): Promise<void>;
}

export const CONTRACT_VERSIONS = {
  openapi: '$($api.info.version)',
  event: '$($event.'x-contract-version')',
  abi: '$($abi.contractVersion)',
  catalog: '$($catalog.catalog_version)'
} as const;
"@

$consumer = @"
import type { ActionIntent, ChainActionExecutedV1, CreateActionRequest, NexusActionsClient } from './index';

export function consumeActionContracts(
  request: CreateActionRequest,
  intent: ActionIntent,
  event: ChainActionExecutedV1,
  client: NexusActionsClient
): string {
  void request;
  void client;
  return intent.id + ':' + event.data.originalTxHash;
}
"@

Write-Utf8NoBom (Join-Path $generatedDir 'index.ts') ($index.Trim() + "`n")
Write-Utf8NoBom (Join-Path $generatedDir 'consumer-fixture.ts') ($consumer.Trim() + "`n")
[pscustomobject]@{
    status='PASS'
    openapi_version=$api.info.version
    event_version=$event.'x-contract-version'
    abi_version=$abi.contractVersion
    generated_files=2
} | ConvertTo-Json
