// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           17
// Async Callback (empty):               1
// Total number of exported functions:  20

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    nexus_actions
    (
        init => init
        upgrade => upgrade
        setRelayerAllowed => set_relayer_allowed
        setPauser => set_pauser
        pauseActionType => pause_action_type
        pauseRelayer => pause_relayer
        registerCapability => register_capability
        revokeCapability => revoke_capability
        rotateCapability => rotate_capability
        recordAction => record_action
        recordPrivateAction => record_private_action
        getSigningMessage => get_signing_message
        getCapability => get_capability
        getChainId => chain_id
        getDomainSeparator => domain_separator
        getPauser => pauser
        isRelayerAllowed => relayer_allowed
        isRelayerPaused => relayer_paused
        isActionPaused => action_paused
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
